#pmake: build flat cpu_386 os_nt dynamic
#
# plib3r -- 32-bit 3r MT PLIB, PLBX
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = dynamic
mthreaded  = 1
fs_registration = yes

!include $(cpplib_dir)/runtime/runtime.mif
