wasmtest_name = ideal

dis_objs = &
	   ideal.dis	&
	   simseg.dis	&
	   enum.dis	&
	   language.dis

asm_flags_ideal    = -zcm=tasm
asm_flags_simseg   = -zcm=tasm
asm_flags_enum     = -zcm=tasm
asm_flags_language = -zcm=tasm

!include ../test.mif
