#pmake: build flat cpu_386 os_os2 dynamic debug
#
# plib3r -- 32-bit 3r MT PLIB, PLBX
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = dynamic
mthreaded  = 1
fs_registration = yes
cpplib_release  = 0

!include $(cpplib_dir)/runtime/plib.mif
