#pmake: build serv remote os_linux cpu_386 tcp x86

host_os  = linux
host_cpu = 386

os    = linux
srv   = tcp
cpu   = x86
which = SERVER
type  = remote_link

!include $(trap_dir)/lcl/linux/trap.mif
!include $(trap_dir)/master.mif
