#pmake: build serv remote os_linux cpu_386 tcp x86

host_os  = linux
host_cpu = 386

target_cpu = x86

os    = linux
srv   = tcp
which = SERVER
remote_link = 1

!include $(trap_dir)/lcl/linux/trap.mif
!include $(trap_dir)/master.mif
