#pmake: build compact cpu_i86 os_win
processor  = 086
system     = windows
model      = mc
linkage    = static
subdir     = mc

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
