#pmake/150: build flat register 32bit inline winnt iX86 rtdll os_nt cpu_386 ntrtdll

component  = mathlib
processor  = 387
model      = mf
subdir     = mf_r
system     = winnt
convention = register

!include $(rtdll_dir)/master.mif
