#pmake: all build flat cpu_386 os_qnx
#
# plibmt3r -- 32-bit 3r PLIB multi-thread library
#
suffix = mt3r
target_system = qnx
target_lib = $(prefix)$(suffix).lib
production_lib = lib386
define_library_include = $(plusplus_runtime_dir)\plib.mif
define_target_include = $(plusplus_dir)\lib$(suffix).mif
!include $(plusplus_dir)\mklib.mif
