# application makefile test

objs = ap1.obj ap2.obj ap3.obj

.asm:       .;../asm
.asm.obj:
    as $[*

.c:         .;../c
.c.obj:
    cc -c -o $*.obj $[@

app : app.exe .symbolic
    @%null

app.exe : $(objs)
    cc -o app.exe $<
