#pmake: build large cpu_i86 os_win
#
# plibl -- 16-bit large memory-model PLIB for Windows
#
processor  = 086
system     = windows
model      = ml
linkage    = static

!include $(cpplib_dir)/runtime/runtime.mif
