#pmake: build huge cpu_i86 os_osi
#
# iosth.lib -- huge memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = mh
linkage    = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
