#pmake: build serv remote os_win cpu_i86 cpu_386 nmp x86
host_cpu = i86
host_os  = win

target_cpu = x86

os = win
srv = nmp
which = SERVER
gui = 1
remote_link = 1

extra_objs = nmpdos.obj

!include $(trap_dir)/master.mif
