#pmake: build flat cpu_386 os_os2
#
# plib3r -- 32-bit 3r MT PLIB, PLBX
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
mthreaded  = 1
fs_registration = yes
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
