wasmtest_name = diag

dis_objs = &
callimpl.dis &
float.dis &
foo.dis &
jmpext.dis &
jmpimpl.dis &
l2.dis &
l3.dis &
newmif.dis &
proccall.dis &
quote.dis &
sizebug2.dis &
struct1.dis

objs = &
b.dum &
diag01.dum &
diag02.dum &
diag03.dum &
diag04.dum &
diag05.dum &
diag06.dum &
diag07.dum &
diag08.dum &
error1.dum &
extern1.dum &
include.dum &
irp.dum &
cpureq.dum

asm_flags_diag01 = -4s
asm_flags_diag02 = -3
asm_flags_diag03 = -wx
asm_flags_diag05 = -e100

!include ../test.mif
