wasmtest_name = diag

dis_objs = &
callimpl.dis &
float.dis &
foo.dis &
jmpext.dis &
jmpimpl.dis &
l2.dis &
l3.dis &
newmif.dis &
proccall.dis &
quote.dis &
sizebug2.dis &
struct1.dis

objs = &
b.obj &
diag01.obj &
diag02.obj &
diag03.obj &
diag04.obj &
diag05.obj &
diag06.obj &
diag07.obj &
diag08.obj &
error1.obj &
extern1.obj &
include.obj &
irp.obj &
cpureq.obj

asm_flags_diag01 = -4s
asm_flags_diag02 = -3
asm_flags_diag03 = -wx
asm_flags_diag05 = -e100

!include ../test.mif
