name: artifacts-delete
description: 'Delete workflow run artifacs'

inputs:
  runid:
    description: 'Workflow run-id where delete'
    required: false
    default: ''
    type: string
  exclude:
    description: 'exclude files start mask'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    uses: ./.github/actions/curlcmd
  - name: Delete artifacts list
    id: artflist
    run: |
      $response = ${{ steps.curlcmd.outputs.gh }} -H "Authorization: Bearer ${{ github.token }}" `
      "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ inputs.runid }}/artifacts?per_page=100"
      if( '${{ env.OWDEBUG }}' -eq '1' ) { $response }
      $list_id = $response | jq -r .artifacts[].id
      $list_name = $response | jq -r .artifacts[].name
      for ($i = 0; $i -lt $list_id.Length; ++$i) {
        if( '${{ env.OWDEBUG }}' -eq '1' ) { "$($list_id[$i]),$($list_name[$i])" }
        if( '${{ inputs.exclude }}' -eq '' || "$($list_name[$i])" -ne "${{ inputs.exclude }}" ) {
          $response = ${{ steps.curlcmd.outputs.gh }} -H "Authorization: Bearer ${{ github.token }}" `
          -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$($list_id[$i])"
          if( '${{ env.OWDEBUG }}' -eq '1' ) { $response }
        }
      }
    shell: pwsh  
