name: artifacts-delete
description: 'Delete workflow run artifacs'
inputs:
  exclude:
    description: 'exclude files start mask'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    uses: "./.github/actions/curlcmd"
  - name: Delete artifacts list
    id: artflist
      $response = ${{ steps.curlcmd.outputs.gh }} `
      "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" `
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
      $list = $response | jq -r .artifacts
      $list | Foreach-Object {
        if( ! startsWith( $($_.name), ${{ inputs.exclude }} ) ) {
          $response = ${{ steps.curlcmd.outputs.gh }} -X DELETE `
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$($_.id)" `
          if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
        }
      }
    shell: pwsh  
