name: artifacts-delete
description: 'Delete workflow run artifacs'

inputs:
  runid:
    description: 'Workflow run-id where delete'
    required: false
    default: ''
    type: string
  exclude:
    description: 'exclude files start mask'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    uses: "./.github/actions/curlcmd"
  - name: Delete artifacts list
    id: artflist
    run: |
      $response = ${{ steps.curlcmd.outputs.gh }} -H "Authorization: Bearer ${{ github.token }}" `
      "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ inputs.runid }}/artifacts"
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
      $list = $response | jq -r .artifacts
      $list | Foreach-Object {
        if( "${{ inputs.exclude }}" -eq '' || "$($_.name)" -ne "${{ inputs.exclude }}" ) {
          $response = ${{ steps.curlcmd.outputs.gh }} -H "Authorization: Bearer ${{ github.token }}" `
          -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$($_.id)"
          if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
        }
      }
    shell: pwsh  
