#pmake: trap remote os_nt cpu_i86 cpu_386 nmp

tree_depth = 4

host_cpu = 386
host_os  = nt

target_cpu = x86

srv = nmp
which = TRAP
remote_link = 1

extra_objs = nmpnt.obj

!include $(trap_dir)/master.mif
