#pmake: build compact cpu_i86 os_dos os_os2 os_win os_qnx
#
# iostc.lib -- compact memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = mc
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
