#pmake: build compact cpu_i86 os_osi os_os2
#
# iostc.lib -- compact memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = mc
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
