#pmake: all build flat cpu_386 os_osi
#
# strg3r.lib -- register based 32-bit STRING library
#
suffix = 3r
target_system = generic
production_lib = lib386
define_library_include = $(plusplus_string_dir)\string.mif
define_deps_include = $(plusplus_string_dir)\deps.mif
define_target_include = $(plusplus_dir)\lib32$(suffix).mif
!include $(plusplus_dir)\mklib.mif
