#pmake: build os_nt cpu_x64
#
# WATCOM Debugger makefile for NT (character mode)
#

host_os=nt
host_cpu=x64

sysobjs =   &
    autoenv.obj &
    ntinit.obj &
    ntscrn.obj &
    ntfilio.obj &
    ntfinfo.obj &
    ntcmd.obj &
    winchk.obj &
    winlkup.obj

!include ../../master.mif
