#pmake: build flat cpu_386 os_linux
#
# cplx73s.lib -- stack based 32-bit COMPLEX library fpi
#
processor  = 387
system     = linux
model      = mf
convention = stack
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
