#pmake: build flat cpu_386 os_nt dynamic
#
# strgmt3r.lib -- register based multi-thread 32-bit STRING library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = dynamic
mthreaded  = 1
fs_registration = yes
cpplib_release = 0

!include $(cpplib_dir)/string/string.mif
