      PARAMETER (MAX_ELS=1000)

      STRUCTURE /OBJECT/
	  REAL	      SIZE
	  INTEGER     WEIGHT
	  CHARACTER*2 COLOUR
      END STRUCTURE

      RECORD /OBJECT/ ITEM(MAX_ELS)

      DO I = 1, MAX_ELS
	  ITEM(I).SIZE = I / .5
	  ITEM(I).WEIGHT = I
	  ITEM(I).COLOUR = 'BL'
      END DO
      OPEN(UNIT=3,FILE='ITEMS.DAT',FORM='UNFORMATTED')
      WRITE(UNIT=3) ITEM
      CLOSE(UNIT=3)
      END
