      CHARACTER*30 INTFIL(4)
      CHARACTER*20 NAME
      INTEGER AGE
      NAMELIST /PERSON/ NAME, AGE
      NAMELIST /ARRAY/ INTFIL

      READ PERSON
      PRINT PERSON
      WRITE( INTFIL, PERSON )
      PRINT ARRAY
      READ ARRAY
      PRINT ARRAY
      END
