      CHARACTER*20 NAME
      CHARACTER*20 STREET
      CHARACTER*15 CITY
      CHARACTER*20 STATE
      CHARACTER*20 COUNTRY
      CHARACTER*10 ZIP_CODE
      INTEGER AGE
      NAMELIST /PERSON/ NAME, STREET, CITY, STATE,
     +			COUNTRY, ZIP_CODE, AGE

      OPEN( UNIT=1, FILE='PEOPLE.DAT',
     +	   FORM='FORMATTED', ACCESS='SEQUENTIAL' )
      OPEN( UNIT=2, FILE='PEOPLE.REL',
     +	   FORM='FORMATTED', ACCESS='DIRECT', RECL=72 )
      I = 1
      LOOP
	  READ( UNIT=1, FMT=PERSON, END=98 )
*	  WRITE( UNIT=6, FMT=PERSON )
	  WRITE( UNIT=2, FMT=PERSON, ERR = 99, IOSTAT = K, REC = I )
	  I = I + 9
      ENDLOOP
98    CONTINUE
      I = 1
      LOOP
	  READ( UNIT=2, FMT=PERSON, ERR = 99, IOSTAT = K, REC = I )
	  WRITE( UNIT=6, FMT=PERSON )
	  I = I + 9
      ENDLOOP
99    CONTINUE
      CLOSE( UNIT=1 )
      CLOSE( UNIT=2 )
      END
