
      STRUCTURE /DATE/
	  INTEGER*1 DAY
	  INTEGER*1 MONTH
	  INTEGER*2 YEAR
      END STRUCTURE

      STRUCTURE /PERSON/
	  STRUCTURE
	      CHARACTER*20 LAST_NAME
	      CHARACTER*20 FIRST_NAME
	      CHARACTER*1  MIDDLE_INITIAL
	  END STRUCTURE
	  RECORD /DATE/ BIRTH_DATE
	  CHARACTER*1 SEX
      END STRUCTURE

      RECORD /PERSON/ PEOPLE

      PEOPLE.NAME.LAST_NAME = 'Schueler'
      PEOPLE.NAME.FIRST_NAME = 'Eva'
      PEOPLE.NAME.MIDDLE_INITIAL = 'M'
      PEOPLE.BIRTH_DATE.DAY = 21
      PEOPLE.BIRTH_DATE.MONTH = 11
      PEOPLE.BIRTH_DATE.YEAR = 1959
      PEOPLE.SEX = 'F'

      PRINT *, PEOPLE

      END
