#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# cont3s.lib -- stack based 32-bit CONTAINER library
#
processor  = 386
system     = generic
model      = ms
convention = stack
linkage    = static

!include $(cpplib_dir)/contain/contain.mif
