#pmake: build small cpu_i86 os_win
#
# plibs -- 16-bit small memory-model PLIB for Windows
#
processor  = 086
system     = windows
model      = ms
linkage    = static

!include $(cpplib_dir)/runtime/plib.mif
