#pmake: build medium cpu_i86 os_osi
#
# cplxm.lib -- medium memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mm
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
