#pmake: build medium cpu_i86 os_dos os_os2 os_win os_qnx
#
# cplxm.lib -- medium memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mm
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
