#pmake: build large cpu_i86 os_osi os_os2
#
# iostl.lib -- large memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = ml
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
