#pmake: build trap remote os_dos cpu_i86 cpu_386 nmp x86

tree_depth = 4

host_cpu = i86
host_os  = dos

target_cpu = x86

srv = nmp
which = TRAP
remote_link = 1

extra_objs = nmpdos.obj

!include $(trap_dir)/master.mif
