#pmake: os_nt cpu_axp axp
#
# WATCOM Debugger makefile for NT AXP (GUI mode)
#

host_CPU=axp
host_OS=nt

sys_windowed = 1

sysobjs =   &
    autoenv.obj &
    ntinit.obj &
    ntguiscn.obj &
    ntfilio.obj &
    ntfinfo.obj &
    ntcmd.obj &
    winchk.obj &
    winlkup.obj

!include ../../master.mif
