#pmake: build large cpu_i86 os_win
#
# contl.lib -- large memory-model CONTAINER library for Windows
#
processor  = 086
system     = windows
model      = ml
linkage    = static
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
