#pmake: nobuild nomodel cpu_axp os_nt
#
# iost -- 32-bit axp STRING library
#
processor    = axp
system       = winnt
linkage      = dynamic
mthreaded    = 1
export_only  = 1

!include $(cpplib_dir)/string/string.mif
