name: boot
description: 'Process boot build steps'
inputs:
  arch:
    description: ''
    required: false
    default: ''
    type: string
  pscript:
    description: ''
    required: false
    default: ''
    type: string
  tools:
    description: ''
    required: false
    default: ''
    type: string
  owdebug:
    description: ''
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: inputs.arch == 'lnx' && inputs.tools == 'gcc'
    name: Bootstrap
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'GCC'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.arch == 'lnx' && inputs.tools == 'clang'
    name: Bootstrap
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'CLANG'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.arch == 'nt'
    name: Bootstrap
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'VISUALC'
      OWIMAGE:       'windows-2019'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: cmd
  - if: inputs.arch == 'osx'
    name: Bootstrap
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'CLANG'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - uses: "./.github/actions/artfsave"
    with:
      arch: ${{ inputs.arch }}
      gitpath:   'bld watcom binbuild'
      artifname: bld watcom ${{ inputs.arch }}
      tools: ${{ inputs.tools }}
  - uses: "./.github/actions/artfsave"
    with:
      arch: ${{ inputs.arch }}
      gitpath:   'build binbuild'
      artifname: build ${{ inputs.arch }}
      tools: ${{ inputs.tools }}
