name: boot
description: 'Process OW bootstrap build'
inputs:
  suffix:
    description: 'artifact name suffix'
    required: true
    type: string
  args:
    description: 'build command arguments'
    required: false
    default: ''
    type: string
  owtools:
    description: 'OW build compiler toolchain'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: runner.os == 'Linux' || runner.os == 'macOS'
    name: Bootstrap
    run: |
      ci/buildx.sh ${{inputs.args}}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       ${{inputs.owtools}}
      OWROOT:        ${{github.workspace}}
      OWVERBOSE:     1
    shell: bash
  - if: runner.os == 'Windows'
    name: Bootstrap
    run: |
      ci\buildx.cmd ${{inputs.args}}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       ${{inputs.owtools}}
      OWROOT:        ${{github.workspace}}
      OWVERBOSE:     1
    shell: cmd
  - uses: ./.github/actions/artfsave
    with:
      gitpath:       'bld watcom binbuild'
      artifact:      bld watcom ${{inputs.suffix}}
  - uses: ./.github/actions/artfsave
    with:
      gitpath:       'build binbuild'
      artifact:      build ${{inputs.suffix}}
