name: boot
description: 'Process OW bootstrap build'
inputs:
  arch:
    description: 'run-time platform'
    required: false
    default: ''
    type: string
  bldscript:
    description: 'script to build action'
    required: false
    default: ''
    type: string
  tools:
    description: 'used compiler toolchain'
    required: false
    default: ''
    type: string
  owtools:
    description: 'OW build compiler toolchain'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: inputs.arch == 'lnx' || inputs.arch == 'osx'
    name: Bootstrap
    run: ${{ inputs.bldscript }} ${{ inputs.tools }}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       ${{ inputs.owtools }}
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.arch == 'nt'
    name: Bootstrap
    run: ${{ inputs.bldscript }} ${{ inputs.tools }}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       ${{ inputs.owtools }}
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: cmd
  - uses: "./.github/actions/artfsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'bld watcom binbuild'
      artifact: "bld watcom ${{ inputs.arch }}"
      tools:    ${{ inputs.tools }}
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'build binbuild'
      artifact: "build ${{ inputs.arch }}"
      tools:    ${{ inputs.tools }}
      owdebug:  ${{ inputs.owdebug }}
