#pmake: build flat cpu_386 os_nt dynamic
#
# contmt3r.lib -- register based multi-thread 32-bit CONTAINER library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = dynamic
mthreaded  = 1
fs_registration = yes
cpplib_release = 0
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
