#pmake: build serv remote os_nt cpu_386 nov x86
host_CPU = 386
host_OS = nt

gui = 1
os = nt
srv = nov
cpu = x86
which = SERVER
type  = remote_link

extra_objs = novnt.obj

!include $(trap_dir)/master.mif
