#pmake: build serv remote os_nt cpu_386 nov x86
host_cpu = 386
host_os  = nt

os = nt
srv = nov
cpu = x86
which = SERVER
gui = 1
remote_link = 1

extra_objs = novnt.obj

!include $(trap_dir)/master.mif
