#pmake: build compact cpu_i86 os_dos os_os2 os_win os_qnx
#
# strgc.lib -- compact memory-model STRING library
#
processor  = 086
system     = generic
model      = mc
linkage    = static

!include $(cpplib_dir)/string/string.mif
