#pmake: build compact cpu_i86 os_osi os_os2
#
# strgc.lib -- compact memory-model STRING library
#
processor  = 086
system     = generic
model      = mc
linkage    = static
define_library_include = $(cpplib_dir)/string/string.mif
!include $(cpplib_dir)/mklib.mif
