name: test-boot
description: ''
inputs:
  arch:
    description: ''
    required: false
    default: ''
    type: string
  pscript:
    description: ''
    required: false
    default: ''
    type: string
  tools:
    description: ''
    required: false
    default: ''
    type: string
  owdebug:
    description: ''
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Load Artifact
    uses: "./.github/actions/artfload"
    with:
      arch: ${{ inputs.arch }}
      gitpath:   'rel'
      artifname: rel ${{ inputs.arch }}
      tools: ${{ inputs.tools }}
  - if: inputs.arch == 'lnx'
    name: Test Bootstrap OW
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{ github.workspace }}
      WATCOM:        ${{ github.workspace }}/rel
      INCLUDE:       ${{ github.workspace }}/rel/lh
      WATCOM_PATH:   ${{ github.workspace }}/rel/binl
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.arch == 'nt'
    name: Test Bootstrap OW
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{ github.workspace }}
      WATCOM:        ${{ github.workspace }}\rel
      INCLUDE:       ${{ github.workspace }}\rel\h;${{ github.workspace }}\rel\h\nt
      WATCOM_PATH:   ${{ github.workspace }}\rel\binnt
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: cmd
