name: test-boot
description: 'Process test bootstrap build by OW (compatibility test)'
inputs:
  testnewow:
    description: 'use with new OW'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: runner.os == 'Linux'
    name: Test Bootstrap OW
    run: |
      if [ ! '${{env.OWTESTMODE}}' = '1' ]; then
        ci/buildx.sh
      fi
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{github.workspace}}
      OWVERBOSE:     1
      OWTESTBOOT:    ${{inputs.testnewow}}
    shell: bash
  - if: runner.os == 'Windows'
    name: Test Bootstrap OW
    run: |
      if not '${{env.OWTESTMODE}}' == '1' (
        ci\buildx.cmd
      )
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{github.workspace}}
      OWVERBOSE:     1
      OWTESTBOOT:    ${{inputs.testnewow}}
    shell: cmd
