#pmake: serv remote os_nt cpu_386 nov axp
host_cpu = axp
host_os  = nt

target_cpu = axp

os = nt
srv = nov
which = SERVER
gui = 1
remote_link = 1

extra_objs = novnt.obj

!include $(trap_dir)/master.mif
