name: set-ow-env
description: 'Set OW environment'
inputs:
  suffix:
    description: 'artifact name suffix'
    required: true
    type: string
  ow_version:
    description: 'OW version'
    required: false
    default: ''
    type: string
  ow_tag:
    description: 'OW version tag'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: inputs.ow_version != ''
    name: Open Watcom setup
    uses: open-watcom/setup-watcom@v0
    with:
      version: ${{ inputs.ow_version }}
      tag:     ${{ inputs.ow_tag }}
  - if: inputs.ow_version == ''
    name: Load Artifact
    uses: ./.github/actions/artfload
    with:
      gitpath:    'rel'
      artifact:   rel ${{ inputs.suffix }}
  - if: inputs.ow_version == '' && runner.os == 'Linux' && runner.arch == 'X64'
    name: Setup OW Linux x64
    run: |
      echo "${{github.workspace}}/rel/binl" >> "$GITHUB_PATH"
      echo "WATCOM=${{github.workspace}}/rel" >> "$GITHUB_ENV"
      echo "INCLUDE=${{github.workspace}}/rel/lh" >> "$GITHUB_ENV"
    shell: bash
  - if: inputs.ow_version == '' && runner.os == 'Linux' && runner.arch == 'ARM64'
    name: Setup OW Linux arm64
    run: |
      echo "${{github.workspace}}/rel/arm64" >> "$GITHUB_PATH"
      echo "WATCOM=${{github.workspace}}/rel" >> "$GITHUB_ENV"
      echo "INCLUDE=${{github.workspace}}/rel/lh" >> "$GITHUB_ENV"
    shell: bash
  - if: inputs.ow_version == '' && runner.os == 'Windows'
    name: Setup OW Windows
    run: |
      echo ${{github.workspace}}\rel\binnt>> "%GITHUB_PATH%"
      echo WATCOM=${{github.workspace}}\rel>> "%GITHUB_ENV%"
      echo INCLUDE=${{github.workspace}}\rel\h;${{github.workspace}}\rel\h\nt>> "%GITHUB_ENV%"
    shell: cmd
