#pmake: build trap remote os_win cpu_i86 cpu_386 par x86
host_cpu = i86
host_os  = win

target_cpu = x86

os = win
srv = par
which = TRAP
remote_link = 1

extra_objs = pardos.obj

!include $(trap_dir)/master.mif
