#pmake: build flat register 32bit calls winnt iX86 rtdll os_nt cpu_386
component  = wrtlib
processor  = 386
model      = mf
subdir     = mf_r
system     = winnt
convention = register

!include $(rtdll_dir)/master.mif
