clibtest_name = _dos

!ifdef __DOS__

srcfile = $(clib_dir)/_dos/c/_dostest.c
!include ../master.mif

!else ifdef __NT__

srcfile = $(clib_dir)/_dos/c/_dostest.c
!include ../master.mif

!else

all : .symbolic

!endif
