.im GR_ARC                         :cmt. _arc
.im GR_CLRSC                       :cmt. _clearscreen
.im GR_DISPC                       :cmt. _displaycursor
.im GR_ELLIP                       :cmt. _ellipse
.im GR_FLOOD                       :cmt. _floodfill
.im GR_GETAP                       :cmt. _getactivepage
.im GR_GETAI                       :cmt. _getarcinfo
.im GR_GETBC                       :cmt. _getbkcolor
.im GR_GETCR                       :cmt. _getcliprgn
.im GR_GETC                        :cmt. _getcolor
.im GR_GETCP                       :cmt. _getcurrentposition
.im GR_GETFM                       :cmt. _getfillmask
.im GR_GETFI                       :cmt. _getfontinfo
.im GR_GETGE                       :cmt. _getgtextextent
.im GR_GETTV                       :cmt. _getgtextvector
.im GR_GETIM                       :cmt. _getimage
.im GR_GETLS                       :cmt. _getlinestyle
.im GR_GETPC                       :cmt. _getphyscoord
.im GR_GETPX                       :cmt. _getpixel
.im GR_GETPA                       :cmt. _getplotaction
.im GR_GETTC                       :cmt. _gettextcolor
.im GR_GETTU                       :cmt. _gettextcursor
.im GR_GETTE                       :cmt. _gettextextent
.im GR_GETTP                       :cmt. _gettextposition
.im GR_GETTS                       :cmt. _gettextsettings
.im GR_GETTW                       :cmt. _gettextwindow
.im GR_GETVC                       :cmt. _getvideoconfig
.im GR_GETLC                       :cmt. _getviewcoord
.im GR_GETVP                       :cmt. _getvisualpage
.im GR_GETWC                       :cmt. _getwindowcoord
.im GR_STAT                        :cmt. _grstatus
.im GR_GRTXT                       :cmt. _grtext
.im GR_IMSIZ                       :cmt. _imagesize
.im GR_LINTO                       :cmt. _lineto
.im GR_MOVTO                       :cmt. _moveto
.im GR_OUTGT                       :cmt. _outgtext
.im GR_OUTM                        :cmt. _outmem
.im GR_OUTTX                       :cmt. _outtext
.im GR_PGAC                        :cmt. _pg_analyzechart
.im GR_PGAP                        :cmt. _pg_analyzepie
.im GR_PGAS                        :cmt. _pg_analyzescatter
.im GR_PGC                         :cmt. _pg_chart
.im GR_PGCP                        :cmt. _pg_chartpie
.im GR_PGCS                        :cmt. _pg_chartscatter
.im GR_PGDC                        :cmt. _pg_defaultchart
.im GR_PGGC                        :cmt. _pg_getchardef
.im GR_PGGP                        :cmt. _pg_getpalette
.im GR_PGGY                        :cmt. _pg_getstyleset
.im GR_PGHL                        :cmt. _pg_hlabelchart
.im GR_PGIC                        :cmt. _pg_initchart
.im GR_PGRP                        :cmt. _pg_resetpalette
.im GR_PGRY                        :cmt. _pg_resetstyleset
.im GR_PGSC                        :cmt. _pg_setchardef
.im GR_PGSP                        :cmt. _pg_setpalette
.im GR_PGSY                        :cmt. _pg_setstyleset
.im GR_PGVL                        :cmt. _pg_vlabelchart
.im GR_PIE                         :cmt. _pie
.im GR_POLYG                       :cmt. _polygon
.im GR_PUTIM                       :cmt. _putimage
.im GR_RECT                        :cmt. _rectangle
.im GR_REG                         :cmt. _registerfonts
.im GR_MAPPA                       :cmt. _remapallpalette
.im GR_MAPPC                       :cmt. _remappalette
.im GR_SCRTW                       :cmt. _scrolltextwindow
.im GR_SELP                        :cmt. _selectpalette
.im GR_SETAP                       :cmt. _setactivepage
.im GR_SETBC                       :cmt. _setbkcolor
.im GR_SETCS                       :cmt. _setcharsize
.im GR_SETCX                       :cmt. _setcharspacing
.im GR_SETCR                       :cmt. _setcliprgn
.im GR_SETC                        :cmt. _setcolor
.im GR_SETFM                       :cmt. _setfillmask
.im GR_SETF                        :cmt. _setfont
.im GR_SETTV                       :cmt. _setgtextvector
.im GR_SETLS                       :cmt. _setlinestyle
.im GR_SETPX                       :cmt. _setpixel
.im GR_SETPA                       :cmt. _setplotaction
.im GR_SETTA                       :cmt. _settextalign
.im GR_SETTC                       :cmt. _settextcolor
.im GR_SETTU                       :cmt. _settextcursor
.im GR_SETTO                       :cmt. _settextorient
.im GR_SETTT                       :cmt. _settextpath
.im GR_SETTP                       :cmt. _settextposition
.im GR_SETTR                       :cmt. _settextrows
.im GR_SETTW                       :cmt. _settextwindow
.im GR_SETVM                       :cmt. _setvideomode
.im GR_SETVR                       :cmt. _setvideomoderows
.im GR_SETLO                       :cmt. _setvieworg
.im GR_SETVW                       :cmt. _setviewport
.im GR_SETVP                       :cmt. _setvisualpage
.im GR_SETW                        :cmt. _setwindow
.im GR_UNREG                       :cmt. _unregisterfonts
.im GR_WRPON                       :cmt. _wrapon
