.if '&*1' eq 'eg_arc.c' .cp 11
.if '&*1' eq 'eg_arc.for' .cp  9
.if '&*1' eq 'eg_clear.c' .cp 14
.if '&*1' eq 'eg_clear.for' .cp 13
.if '&*1' eq 'eg_disp.c' .cp 19
.if '&*1' eq 'eg_disp.for' .cp 19
.if '&*1' eq 'eg_ellip.c' .cp 11
.if '&*1' eq 'eg_ellip.for' .cp  9
.if '&*1' eq 'eg_flood.c' .cp 14
.if '&*1' eq 'eg_flood.for' .cp 12
.if '&*1' eq 'eg_getai.c' .cp 16
.if '&*1' eq 'eg_getai.for' .cp 14
.if '&*1' eq 'eg_getbc.c' .cp 25
.if '&*1' eq 'eg_getbc.for' .cp 21
.if '&*1' eq 'eg_getc.c' .cp 18
.if '&*1' eq 'eg_getc.for' .cp 17
.if '&*1' eq 'eg_getcp.c' .cp 18
.if '&*1' eq 'eg_getcp.for' .cp 16
.if '&*1' eq 'eg_getfi.c' .cp 19
.if '&*1' eq 'eg_getfi.for' .cp 18
.if '&*1' eq 'eg_getfm.c' .cp 18
.if '&*1' eq 'eg_getfm.for' .cp 18
.if '&*1' eq 'eg_getim.c' .cp 27
.if '&*1' eq 'eg_getim.for' .cp 25
.if '&*1' eq 'eg_getlc.c' .cp 18
.if '&*1' eq 'eg_getlc.for' .cp 22
.if '&*1' eq 'eg_getls.c' .cp 18
.if '&*1' eq 'eg_getls.for' .cp 17
.if '&*1' eq 'eg_getpa.c' .cp 19
.if '&*1' eq 'eg_getpa.for' .cp 19
.if '&*1' eq 'eg_getpc.c' .cp 17
.if '&*1' eq 'eg_getpc.for' .cp 21
.if '&*1' eq 'eg_getpx.c' .cp 21
.if '&*1' eq 'eg_getpx.for' .cp 22
.if '&*1' eq 'eg_gettc.c' .cp 20
.if '&*1' eq 'eg_gettc.for' .cp 19
.if '&*1' eq 'eg_gette.c' .cp 17
.if '&*1' eq 'eg_gette.for' .cp 16
.if '&*1' eq 'eg_gettp.c' .cp 16
.if '&*1' eq 'eg_gettp.for' .cp 14
.if '&*1' eq 'eg_getts.c' .cp 17
.if '&*1' eq 'eg_getts.for' .cp 15
.if '&*1' eq 'eg_gettu.c' .cp 20
.if '&*1' eq 'eg_gettu.for' .cp 20
.if '&*1' eq 'eg_gettv.c' .cp 17
.if '&*1' eq 'eg_gettv.for' .cp 15
.if '&*1' eq 'eg_getvc.c' .cp 48
.if '&*1' eq 'eg_getvc.for' .cp 38
.if '&*1' eq 'eg_getwc.c' .cp 21
.if '&*1' eq 'eg_getwc.for' .cp 19
.if '&*1' eq 'eg_grtxt.c' .cp 12
.if '&*1' eq 'eg_grtxt.for' .cp 10
.if '&*1' eq 'eg_mappa.c' .cp 28
.if '&*1' eq 'eg_mappa.for' .cp 26
.if '&*1' eq 'eg_mappc.c' .cp 22
.if '&*1' eq 'eg_mappc.for' .cp 19
.if '&*1' eq 'eg_movto.c' .cp 14
.if '&*1' eq 'eg_movto.for' .cp 12
.if '&*1' eq 'eg_outm.c' .cp 18
.if '&*1' eq 'eg_outm.for' .cp 16
.if '&*1' eq 'eg_outtx.c' .cp 12
.if '&*1' eq 'eg_outtx.for' .cp 10
.if '&*1' eq 'eg_pal.c2' .cp 26
.if '&*1' eq 'eg_pgac.c' .cp 36
.if '&*1' eq 'eg_pgac.for' .cp 37
.if '&*1' eq 'eg_pgap.c' .cp 41
.if '&*1' eq 'eg_pgap.for' .cp 39
.if '&*1' eq 'eg_pgas.c' .cp 40
.if '&*1' eq 'eg_pgas.for' .cp 37
.if '&*1' eq 'eg_pgc.c' .cp 29
.if '&*1' eq 'eg_pgc.for' .cp 30
.if '&*1' eq 'eg_pgcp.c' .cp 34
.if '&*1' eq 'eg_pgcp.for' .cp 32
.if '&*1' eq 'eg_pgcs.c' .cp 35
.if '&*1' eq 'eg_pgcs.for' .cp 32
.if '&*1' eq 'eg_pggc.c' .cp 38
.if '&*1' eq 'eg_pggc.for' .cp 33
.if '&*1' eq 'eg_pggp.c' .cp 42
.if '&*1' eq 'eg_pggp.for' .cp 45
.if '&*1' eq 'eg_pggy.c' .cp 40
.if '&*1' eq 'eg_pggy.for' .cp 41
.if '&*1' eq 'eg_pghl.c' .cp 31
.if '&*1' eq 'eg_pghl.for' .cp 34
.if '&*1' eq 'eg_pic1.c2' .cp 32
.if '&*1' eq 'eg_pic2.c2' .cp 37
.if '&*1' eq 'eg_pie.c' .cp 12
.if '&*1' eq 'eg_pie.for' .cp 10
.if '&*1' eq 'eg_polyg.c' .cp 16
.if '&*1' eq 'eg_polyg.for' .cp 13
.if '&*1' eq 'eg_rect.c' .cp 11
.if '&*1' eq 'eg_rect.for' .cp  9
.if '&*1' eq 'eg_reg.c' .cp 23
.if '&*1' eq 'eg_reg.for' .cp 20
.if '&*1' eq 'eg_scrtw.c' .cp 23
.if '&*1' eq 'eg_scrtw.for' .cp 21
.if '&*1' eq 'eg_selpa.c' .cp 23
.if '&*1' eq 'eg_selpa.for' .cp 21
.if '&*1' eq 'eg_setap.c' .cp 27
.if '&*1' eq 'eg_setap.for' .cp 26
.if '&*1' eq 'eg_setcr.c' .cp 16
.if '&*1' eq 'eg_setcr.for' .cp 14
.if '&*1' eq 'eg_setcs.c' .cp 13
.if '&*1' eq 'eg_setcs.for' .cp 11
.if '&*1' eq 'eg_setlg.c' .cp 12
.if '&*1' eq 'eg_setlg.for' .cp 10
.if '&*1' eq 'eg_setta.c' .cp 15
.if '&*1' eq 'eg_setta.for' .cp 13
.if '&*1' eq 'eg_setto.c' .cp 13
.if '&*1' eq 'eg_setto.for' .cp 11
.if '&*1' eq 'eg_settr.c' .cp 28
.if '&*1' eq 'eg_settr.for' .cp 25
.if '&*1' eq 'eg_settw.c' .cp 22
.if '&*1' eq 'eg_settw.for' .cp 20
.if '&*1' eq 'eg_settx.c' .cp 13
.if '&*1' eq 'eg_settx.for' .cp 11
.if '&*1' eq 'eg_setvp.c' .cp 15
.if '&*1' eq 'eg_setvp.for' .cp 15
.if '&*1' eq 'eg_setvr.c' .cp 18
.if '&*1' eq 'eg_setvr.for' .cp 17
.if '&*1' eq 'eg_setw.c' .cp 27
.if '&*1' eq 'eg_setw.for' .cp 29
.if '&*1' eq 'eg_stat.c' .cp 18
.if '&*1' eq 'eg_stat.for' .cp 18
.if '&*1' eq 'eg_wrap.c' .cp 27
.if '&*1' eq 'eg_wrap.for' .cp 28
