#pmake: build flat cpu_386 os_rdos
#
# cont3smt.lib -- stack based 32-bit multi-threaded CONTAINER library
#
processor  = 386
system     = rdos
model      = mf
convention = stack
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/contain/contain.mif
