#pmake: build large cpu_i86 os_os2
#
# iostmt.lib -- large memory-model OS/2 multi-thread IOSTREAM library
#
processor  = 286
system     = os2
model      = ml
convention =
linkage    = static
mthreaded  = 1
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
