#pmake: trap remote os_os2 cpu_i86 tcp
host_CPU = i86
host_OS = os2

os  = os2
srv = tcp
cpu = x86
which = TRAP
type  = remote_link

extra_libs = $(watcom_dir)/lib/tcpipdll.lib
inc_dirs = -I"$(watcom_dir)/os220_h/tcpip"

!include $(trap_dir)/master.mif
