#pmake:all small stack 32bit inline winnt iX86 rtdll no_build os_nt cpu_386 dynamic
component=wrtlib
processor=387
model=ms
subdir=ms_sd
system=winnt
convention=stack
!include $(rtdll)\master.mif
!include ..\objs.mif
!include $(rtdll)\mkdll.mif
