#pmake: build flat cpu_386 os_osi
#
# strgmt3s.lib -- stack based multi-thread 32-bit STRING library
#
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static
mthreaded  = 1
define_library_include = $(cpplib_dir)/string/string.mif
!include $(cpplib_dir)/mklib.mif
