#pmake: build flat cpu_386 os_nt
#
# strgmt3r.lib -- register based multi-thread 32-bit STRING library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
mthreaded  = 1
fs_registration = yes

!include $(cpplib_dir)/string/string.mif
