#pmake: nobuild nomodel cpu_axp os_nt
#
# iost -- 32-bit axp IOSTREAM library
#
processor    = axp
system       = winnt
linkage      = dynamic
mthreaded    = 1

!include $(cpplib_dir)/iostream/iostream.mif
