#pmake: build serv remote os_nt cpu_i86 cpu_386 tcp x86

tree_depth = 4

host_cpu = 386
host_os  = nt

target_cpu = x86

srv = tcp
which = SERVER
gui = 1
remote_link = 1

extra_linker = lib wsock32.lib

!include $(trap_dir)/master.mif
