#pmake: build compact cpu_i86 os_win
#
# cplxc.lib -- compact memory-model COMPLEX library fpc for Windows
#
processor  = 086
system     = windows
model      = mc
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
