#pmake: build trap remote os_nt cpu_386 nov x86
host_cpu = 386
host_os  = nt

target_cpu = x86

os = nt
srv = nov
which = TRAP
remote_link = 1

extra_objs = novnt.obj

!include $(trap_dir)/master.mif
