type = win
os = ntaxp
build_target = nt
rc = wrc
rcopt = -bt=$(build_target) -D__AXP__
sys = ntaxp_win
compiler = compaxp
axp = 1

target : sample.exe .SYMBOLIC
    @%null

samp2 : samp2.exe  .SYMBOLIC
    @%null

!include ..\makefile
