// the following is the font used in the status bar of the window
pick(   WRE_STATUSFONT,
        "Helv.8",
        "Helv.8" )

// WREMSG.C
pick(   WRE_MSGBOXTITLE,
        "Open Watcom Resource Editor",
        "Open Watcom Resource Editor" )

// WRESTAT.C
pick(   WRE_NOCREATESTATUS,
        "Could not create status line.",
        "Could not create status line." )
pick(   WRE_READYMSG,
        "Ready",
        "Ready" )

// WREHINTS.C
pick(   WRE_HINT_NEW,
        "Create a new file.",
        "Create a new file." )
pick(   WRE_HINT_OPEN,
        "Open a file.",
        "Open a file." )
pick(   WRE_HINT_SAVE,
        "Save this file.",
        "Save this file." )
pick(   WRE_HINT_SAVEAS,
        "Save this file as a different file.",
        "Save this file as a different file." )
pick(   WRE_HINT_EXIT,
        "Exit the Open Watcom Resource Editor.",
        "Exit the Open Watcom Resource Editor." )
pick(   WRE_HINT_OPTIONS,
        "Set program options.",
        "Set program options." )
pick(   WRE_HINT_NEW_CURSOR,
        "Create a new cursor resource.",
        "Create a new cursor resource." )
pick(   WRE_HINT_NEW_BITMAP,
        "Create a new bitmap resource.",
        "Create a new bitmap resource." )
pick(   WRE_HINT_NEW_ICON,
        "Create a new icon resource.",
        "Create a new icon resource." )
pick(   WRE_HINT_NEW_MENU,
        "Create a new menu resource.",
        "Create a new menu resource." )
pick(   WRE_HINT_NEW_DIALOG,
        "Create a new dialog resource.",
        "Create a new dialog resource." )
pick(   WRE_HINT_NEW_STRING,
        "Create a new string table resource.",
        "Create a new string table resource." )
pick(   WRE_HINT_NEW_FONT,
        "Create a new font resource.",
        "Create a new font resource." )
pick(   WRE_HINT_NEW_ACCELERATOR,
        "Create a new accelerator table resource.",
        "Create a new accelerator table resource." )
pick(   WRE_HINT_NEW_RCDATA,
        "Create a new user data resource.",
        "Create a new user data resource." )
pick(   WRE_HINT_RES_SAVEAS,
        "Save the current resource to a file.",
        "Save the current resource to a file." )
pick(   WRE_HINT_RES_SAVE_INTO,
        "Copy the current resource INTO another file.",
        "Copy the current resource INTO another file." )
pick(   WRE_HINT_RES_EDIT,
        "Edit the current resource.",
        "Edit the current resource." )
pick(   WRE_HINT_RES_RENAME,
        "Rename the current resource.",
        "Rename the current resource." )
pick(   WRE_HINT_RES_MEM_FLAGS,
        "Change a resource's memory/load flags.",
        "Change a resource's memory/load flags." )
pick(   WRE_HINT_SHOW_RIBBON,
        "Show/hide the toolbar.",
        "Show/hide the toolbar." )
pick(   WRE_HINT_MDI_CASCADE,
        "Cascade resource windows.",
        "Cascade resource windows." )
pick(   WRE_HINT_MDI_TILEH,
        "Tile resource windows horizontally.",
        "Tile resource windows horizontally." )
pick(   WRE_HINT_MDI_TILEV,
        "Tile resource windows vertically.",
        "Tile resource windows vertically." )
pick(   WRE_HINT_MDI_ARRANGE,
        "Arrange resource icons.",
        "Arrange resource icons." )
pick(   WRE_HINT_ABOUT,
        "Display program information.",
        "Display program information." )
pick(   WRE_HINT_HELP,
        "List Open Watcom Resource Editor help topics.",
        "List Open Watcom Resource Editor help topics." )
pick(   WRE_HINT_HELP_SEARCH,
        "Search for help on a specific topic.",
        "Search for help on a specific topic." )
pick(   WRE_HINT_HELP_ON_HELP,
        "Display information on how to use help.",
        "Display information on how to use help." )
pick(   WRE_HINT_DELETE,
        "Delete selected object.",
        "Delete selected object." )
pick(   WRE_HINT_CUT,
        "Cut selected object to clipboard.",
        "Cut selected object to clipboard." )
pick(   WRE_HINT_PASTE,
        "Paste object from clipboard.",
        "Paste object from clipboard." )
pick(   WRE_HINT_COPY,
        "Copy selected object to clipboard.",
        "Copy selected object to clipboard." )
pick(   WRE_HINT_FILEMENU,
        "Create or open a new file.",
        "Create or open a new file." )
pick(   WRE_HINT_EDITMENU,
        "Edit selected resource.",
        "Edit selected resource." )
pick(   WRE_HINT_RESMENU,
        "Manipulate resources.",
        "Manipulate resources." )
pick(   WRE_HINT_NEWMENU,
        "Create new resources.",
        "Create new resources." )
pick(   WRE_HINT_WINDOWMENU,
        "Manipulate resource windows.",
        "Manipulate resource windows." )
pick(   WRE_HINT_HELPMENU,
        "Display help or program information.",
        "Display help or program information." )
pick(   WRE_HINT_MDIMSG,
        "Switch to Resource #%d.",
        "Switch to Resource #%d." )
pick(   WRE_HINT_EDITSYMMENU,
        "Load, edit, or write symbols.",
        "Load, edit, or write symbols." )
pick(   WRE_HINT_LOAD_SYMBOLS,
        "Load symbols from a file.",
        "Load symbols from a file." )
pick(   WRE_HINT_VIEW_SYMBOLS,
        "Edit symbols.",
        "Edit symbols." )
pick(   WRE_HINT_WRITE_SYMBOLS,
        "Write symbols to a file.",
        "Write symbols to a file." )

// WRETOOLB.C
pick(   WRE_SYSMENUMOVE,
        "Move",
        "Move" )
pick(   WRE_SYSMENUSIZE,
        "Size",
        "Size" )
pick(   WRE_SYSMENUHIDE,
        "Hide",
        "Hide" )

// WRERIBBN.C
pick(   WRE_SHOWTOOLBAR,
        "Show Tool&bar",
        "Show Tool&bar" )
pick(   WRE_HIDETOOLBAR,
        "Hide Tool&bar",
        "Hide Tool&bar" )

// all editors
pick(   WRE_EMPTYREMOVED,
        "Empty resource removed",
        "Empty resource removed" )
pick(   WRE_CANTFINDUNUSEDNAME,
        "Could not find an unused resource name.",
        "Could not find an unused resource name." )

// WREDLG.C
pick(   WRE_DEFDIALOGNAME,
        "DIALOG_%d",
        "DIALOG_%d" )
pick(   WRE_DLGSESSIONKILLED,
        "The Open Watcom Dialog Editor terminated the edit session.",
        "The Open Watcom Dialog Editor terminated the edit session." )
pick(   WRE_DLGEDITNOTSPAWNED,
        "Failed to spawn the Open Watcom Dialog Editor.",
        "Failed to spawn the Open Watcom Dialog Editor." )

// WREIMG.C
pick(   WRE_DEFBITMAPNAME,
        "BITMAP_%d",
        "BITMAP_%d" )
pick(   WRE_DEFCURSORNAME,
        "CURSOR_%d",
        "CURSOR_%d" )
pick(   WRE_DEFICONNAME,
        "ICON_%d",
        "ICON_%d" )
pick(   WRE_IMGSESSIONKILLED,
        "The Open Watcom Image Editor terminated the edit session.",
        "The Open Watcom Image Editor terminated the edit session." )
pick(   WRE_IMGEDITNOTSPAWNED,
        "Failed to spawn the Open Watcom Image Editor.",
        "Failed to spawn the Open Watcom Image Editor." )

// WREACCEL.C
pick(   WRE_DEFACCELNAME,
        "ACCELERATOR_%d",
        "ACCELERATOR_%d" )

// WREMENU.C
pick(   WRE_DEFMENUNAME,
        "MENU_%d",
        "MENU_%d" )

// WRESTR.C
pick(   WRE_STRINGTABLEEXISTS,
        "A string table already exists.",
        "A string table already exists." )

// WREGETFN.C
pick(   WRE_ERRORSELECTINGFILE,
        "An error occurred selecting the file.",
        "An error occurred selecting the file." )
pick(   WRE_GETFNCOMBOTITLE,
        "List Files of &Type",
        "List Files of &Type" )

// WREDEL.C
pick(   WRE_ALLSTRINGS,
        "All Strings",
        "All Strings" )

// WRECLIP.C
pick(   WRE_RESTOOLARGETOPASTE,
        "Resource is too large to paste.",
        "Resource is too large to paste." )

// WRERENAM.C
pick(   WRE_NORENAMESTRINGS,
        "You may not rename string resources.",
        "You may not rename string resources." )
pick(   WRE_DUPRESNAME,
        "There is already a resource with this name.",
        "There is already a resource with this name." )

// WRENAMES.C
pick(   WRE_EMPTYRESNAME,
        "Empty Resource",
        "Empty Resource" )
pick(   WRE_CURSORGROUPNAME,
        "Cursor Group Resources",
        "Cursor Group Resources" )
pick(   WRE_ICONGROUPNAME,
        "Icon Group Resources",
        "Icon Group Resources" )
pick(   WRE_BITMAPNAME,
        "Bitmap Resources",
        "Bitmap Resources" )
pick(   WRE_MENUNAME,
        "Menu Resources",
        "Menu Resources" )
pick(   WRE_DIALOGNAME,
        "Dialog Resources",
        "Dialog Resources" )
pick(   WRE_STRINGNAME,
        "String Resources",
        "String Resources" )
pick(   WRE_FONTNAME,
        "Font Resources",
        "Font Resources" )
pick(   WRE_ACCELNAME,
        "Accelerator Resources",
        "Accelerator Resources" )
pick(   WRE_USERDATANAME,
        "User-Defined Data",
        "User-Defined Data" )
pick(   WRE_CURSORNAME,
        "Cursor Resources",
        "Cursor Resources" )
pick(   WRE_ICONNAME,
        "Icon Resources",
        "Icon Resources" )
pick(   WRE_FONTDIRNAME,
        "Font Directory Resources",
        "Font Directory Resources" )
pick(   WRE_MESSAGETABLENAME,
        "Message Table Resources",
        "Message Table Resources" )
pick(   WRE_VERSIONNAME,
        "Version Information Resources",
        "Version Information Resources" )
pick(   WRE_DLGINCLUDENAME,
        "Dialog Include Resources",
        "Dialog Include Resources" )
pick(   WRE_TOTALTEXT_NONE,
        "No Resources",
        "No Resources" )
pick(   WRE_TOTALTEXT_ONE,
        "1 Resource",
        "1 Resource" )
pick(   WRE_TOTALTEXT,
        "%d Resources",
        "%d Resources" )

// WREMAIN.C
pick(   WRE_APPNAME,
        "Open Watcom Resource Editor",
        "Open Watcom Resource Editor" )
pick(   WRE_INITFAILED,
        "Initialization Failed!",
        "Initialization Failed!" )
pick(   WRE_DDEINITFAILED,
        "DDE Initialization Failed!",
        "DDE Initialization Failed!" )
pick(   WRE_NOREGISTERCLIPFORMATS,
        "Could not register clipboard formats!",
        "Could not register clipboard formats!" )
pick(   WRE_NOLOADACCELTABLE,
        "Could not load accelerator table!",
        "Could not load accelerator table!" )
pick(   WRE_NOCREATEAPPWINDOW,
        "Could not create application window!",
        "Could not create application window!" )
pick(   WRE_NOCREATETOOLRIBBON,
        "Could not create tool ribbon!",
        "Could not create tool ribbon!" )
pick(   WRE_NOCREATESTATUSLINE,
        "Could not create status line!",
        "Could not create status line!" )
pick(   WRE_NOINITHINTS,
        "Could not initalize hints!",
        "Could not initalize hints!" )
pick(   WRE_MOCREATEMDICLIENT,
        "Could not create MDI Client window!",
        "Could not create MDI Client window!" )
pick(   WRE_EDITSESSIONPENDING,
        "Edit session still pending",
        "Edit session still pending" )
pick(   WRE_INPUTFILESNOTLOADED,
        "Input file(s) not Loaded.",
        "Input file(s) not Loaded." )
pick(   WRE_INVALIDINPUTFILE,
        "Invalid input file.",
        "Invalid input file." )
pick(   WRE_ABOUT_NAME,
        "Open Watcom Resource Editor for Windows" STR_BITNEES,
        "Open Watcom Resource Editor for Windows" STR_BITNEES )
pick(   WRE_ABOUT_VERSION,
        banner1p2( _RESEDIT_VERSION_ ),
        banner1p2( _RESEDIT_VERSION_ ) )
pick(   WRE_ABOUT_COPYRIGHT_YEAR,
        "1984",
        "1984" )
pick(   WRE_ABOUT_TITLE,
        "About Open Watcom Resource Editor",
        "About Open Watcom Resource Editor" )

// WRERES.C
pick(   WRE_UNTITLED,
        "untitled",
        "untitled" )
pick(   WRE_OPENPROJECTTITLE,
        "Open File",
        "Open File" )
pick(   WRE_SAVEPROJECTTITLE,
        "Save File",
        "Save File" )
pick(   WRE_SAVEASPROJECTTITLE,
        "Save File As",
        "Save File As" )
pick(   WRE_COPYINTOPROJECTTITLE,
        "Copy Resource Into File",
        "Copy Resource Into File" )
pick(   WRE_PROJECTFILTER,
        "Bitmap Files (*.BMP)\t*.BMP\tCursor Files (*.CUR)\t*.CUR\t"
        "Icon Files (*.ICO)\t*.ICO\tResource Files (*.RES)\t*.RES\t"
        "Executable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t",
        "Bitmap Files (*.BMP)\t*.BMP\tCursor Files (*.CUR)\t*.CUR\t"
        "Icon Files (*.ICO)\t*.ICO\tResource Files (*.RES)\t*.RES\t"
        "Executable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t" )
pick(   WRE_PROJECTFILTERNOEXE,
        "Bitmap Files (*.BMP)\t*.BMP\tCursor Files (*.CUR)\t*.CUR\t"
        "Icon Files (*.ICO)\t*.ICO\tResource Files (*.RES)\t*.RES\t",
        "Bitmap Files (*.BMP)\t*.BMP\tCursor Files (*.CUR)\t*.CUR\t"
        "Icon Files (*.ICO)\t*.ICO\tResource Files (*.RES)\t*.RES\t" )
pick(   WRE_SAVEMLTFILTER,
        "Resource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\t"
        "DLL Libraries (*.DLL)\t*.DLL\t",
        "Resource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\t"
        "DLL Libraries (*.DLL)\t*.DLL\t" )
pick(   WRE_SAVEMLTFILTERNOEXE,
        "Resource Files (*.RES)\t*.RES\t",
        "Resource Files (*.RES)\t*.RES\t" )
pick(   WRE_ACCELFILTER,
        "Accelerator Files (*.ACC)\t*.ACC\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t",
        "Accelerator Files (*.ACC)\t*.ACC\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t" )
pick(   WRE_MENUFILTER,
        "Menu Files (*.MNU)\t*.MNU\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t",
        "Menu Files (*.MNU)\t*.MNU\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t" )
pick(   WRE_STRINGFILTER,
        "String Files (*.STR)\t*.STR\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t",
        "String Files (*.STR)\t*.STR\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t" )
pick(   WRE_OPENACCEL,
        "Open Accelerator",
        "Open Accelerator" )
pick(   WRE_OPENMENU,
        "Open Menu",
        "Open Menu" )
pick(   WRE_OPENSTRING,
        "Open String",
        "Open String" )
pick(   WRE_RESOURCESNOTLOADED,
        "Resources not loaded.",
        "Resources not loaded." )
pick(   WRE_QUERYMODIFIED,
        "This resource has been modified.\nSave resource?",
        "This resource has been modified.\nSave resource?" )
pick(   WRE_SAVEMODIFIEDSYM,
        "The symbols for this file have been modified.\nSave symbols?",
        "The symbols for this file have been modified.\nSave symbols?" )
pick(   WRE_UPDATEBEFORESAVE,
        "Please update all new resources first.",
        "Please update all new resources first." )
pick(   WRE_SAVEFAILED,
        "Save failed!",
        "Save failed!" )

// WRESVOBJ.C
pick(   WRE_UPDATEBEFORESAVE1,
        "Please update this resource first.",
        "Please update this resource first." )

// WRESVMLT.C
pick(   WRE_ERRORONDUPOBJS,
        "Error handling duplicate objects.",
        "Error handling duplicate objects." )

// WRESYM.C
pick(   WRE_SYMFILTER,
        "Header Files (*.h)\t*.h\tAll Files (*.*)\t*.*\t",
        "Header Files (*.h)\t*.h\tAll Files (*.*)\t*.*\t" )
pick(   WRE_LOADSYMTITLE,
        "Load Symbol Header File",
        "Load Symbol Header File" )
pick(   WRE_SAVESYMTITLE,
        "Save Symbol Header File",
        "Save Symbol Header File" )
pick(   WRE_LOADINGSYMBOLS,
        "Loading Symbols...",
        "Loading Symbols..." )
pick(   WRE_SYMOUTOFMEM,
        "Ran out of memory loading symbols.",
        "Ran out of memory loading symbols." )
pick(   WRE_NOLOADHEADERFILE,
        "Unable to open symbol file.",
        "Unable to open symbol file." )
pick(   WRE_SAVEINGSYMBOLS,
        "Saving Symbols...",
        "Saving Symbols..." )
pick(   WRE_ERRORCLOSINGSYMFILE,
        "Error closing symbol file!",
        "Error closing symbol file!" )
pick(   WRE_NOOPENSYMFILE,
        "Could not open symbol file.",
        "Could not open symbol file." )

// WRERIBBN.C
pick(   WRE_TIP_NEW,
        "New",
        "New" )
pick(   WRE_TIP_OPEN,
        "Open",
        "Open" )
pick(   WRE_TIP_SAVE,
        "Save",
        "Save" )
pick(   WRE_TIP_CUT,
        "Cut",
        "Cut" )
pick(   WRE_TIP_COPY,
        "Copy",
        "Copy" )
pick(   WRE_TIP_PASTE,
        "Paste",
        "Paste" )

