#pmake: build flat cpu_386 os_osi os_dos
#
# iost3r.lib -- register based 32-bit IOSTREAM library
#
processor  = 386
system     = generic
model      = ms
convention = register
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
