#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# iost3r.lib -- register based 32-bit IOSTREAM library
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
