// the following is the font used in the status bar of the window
pick(   W_STATUSFONT,
        "Helv.8",
        "Helv.8" )

// WSTAT.C
pick(   W_STATUSNOTCREATED,
        "Could not create status line.",
        "Could not create status line." )
pick(   W_READYMSG,
        "Ready.",
        "Ready." )

// WHINTS.C
pick(   W_ACC_CLEAR,
        "Clear the accelerator table.",
        "Clear the accelerator table." )
pick(   W_ACC_UPDATE,
        "Update the file with this accelerator table.",
        "Update the file with this accelerator table." )
pick(   W_ACC_SAVE,
        "Save this accelerator table.",
        "Save this accelerator table." )
pick(   W_ACC_SAVEAS,
        "Save this accelerator table to a different file.",
        "Save this accelerator table to a different file." )
pick(   W_ACC_SAVEINTO,
        "Copy this accelerator table into a different file.",
        "Copy this accelerator table into a different file." )
pick(   W_ACC_EXIT,
        "Exit the accelerator table editor.",
        "Exit the accelerator table editor." )
pick(   W_ACC_CUT,
        "Cut the accelerator table to the clipboard.",
        "Cut the accelerator table to the clipboard." )
pick(   W_ACC_COPY,
        "Copy the accelerator table to the clipboard.",
        "Copy the accelerator table to the clipboard." )
pick(   W_ACC_PASTE,
        "Paste the accelerator table from the clipboard.",
        "Paste the accelerator table from the clipboard." )
pick(   W_ACC_DELETE,
        "Delete an accelerator item from the accelerator.",
        "Delete an accelerator item from the accelerator." )
pick(   W_ACC_SHOWRIBBON,
        "Show/hide the toolbar.",
        "Show/hide the toolbar." )
pick(   W_ACC_SYMBOLS,
        "Edit Symbols.",
        "Edit Symbols." )
pick(   W_ACC_LOAD_SYMBOLS,
        "Load Symbols.",
        "Load Symbols." )
pick(   W_ACC_RENAME,
        "Rename the accelerator table.",
        "Rename the accelerator table." )
pick(   W_ACC_MEM_FLAGS,
        "Modify the accelerator table memory options.",
        "Modify the accelerator table memory options." )
pick(   W_ACC_NEWITEM,
        "Insert a new accelerator item.",
        "Insert a new accelerator item." )
pick(   W_ACC_KEYVALUE,
        "Set the accelerator item's key value with keyboard.",
        "Set the accelerator item's key value with keyboard." )
pick(   W_ACC_ABOUT,
        "Display program information.",
        "Display program information." )
pick(   W_ACC_HELP,
        "List Open Watcom Accelerator Editor help topics.",
        "List Open Watcom Accelerator Editor help topics." )
pick(   W_ACC_HELP_SEARCH,
        "Search for help on a specific topic.",
        "Search for help on a specific topic." )
pick(   W_ACC_HELP_ON_HELP,
        "Display information on how to use help.",
        "Display information on how to use help." )
pick(   W_ACC_FILEMENU,
        "Clear or update the accelerator table.",
        "Clear or update the accelerator table." )
pick(   W_ACC_EDITMENU,
        "Edit the accelerator table and its items.",
        "Edit the accelerator table and its items." )
pick(   W_ACC_RESMENU,
        "Manipulate accelerator table settings.",
        "Manipulate accelerator table settings." )
pick(   W_ACC_ACCMENU,
        "Create accelerator items.",
        "Create accelerator items." )
pick(   W_ACC_HELPMENU,
        "Display help or editor info.",
        "Display help or editor info." )

// WNEWITEM.C
pick(   W_INVALIDACCEL,
        "Invalid accelerator. Using default.",
        "Invalid accelerator. Using default." )

// WEDIT.C
pick(   W_CHANGEMODIFIEDMENUITEM,
        "This accelerator item has been modified.\nChange?",
        "This accelerator item has been modified.\nChange?" )
pick(   W_INVALIDACCELKEY,
        "Invalid accelerator key.",
        "Invalid accelerator key." )

// WKEY.C
pick(   W_SELECTKEY,
        "Use the keyboard to select a key.",
        "Use the keyboard to select a key." )

// WRIBBON.C
pick(   W_SHOWTOOLBAR,
        "Show Tool&bar",
        "Show Tool&bar" )
pick(   W_TOOLBARHIDDEN,
        "Toolbar Hidden",
        "Toolbar Hidden" )
pick(   W_HIDETOOLBAR,
        "Hide Tool&bar",
        "Hide Tool&bar" )
pick(   W_TOOLBARSHOWN,
        "Toolbar Shown",
        "Toolbar Shown" )

// WTOOLBAR.C
pick(   W_SYSMENUMOVE,
        "Move",
        "Move" )
pick(   W_SYSMENUSIZE,
        "Size",
        "Size" )
pick(   W_SYSMENUHIDE,
        "Hide",
        "Hide" )

// WSVOBJ.C
pick(   W_SAVERESINTO,
        "Save Accelerator Into Resource",
        "Save Accelerator Into Resource" )
pick(   W_SAVERESAS,
        "Save Accelerator Resource",
        "Save Accelerator Resource" )
pick(   W_SAVERESFILTER,
        "Accelerator Files (*.ACC)\t*.ACC\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t",
        "Accelerator Files (*.ACC)\t*.ACC\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t" )
pick(   W_RESHASNONAME,
        "This resource does not have a name.",
        "This resource does not have a name." )
pick(   W_RESDUPNAMEINFILE,
        "There is already a resource of that name in the file.",
        "There is already a resource of that name in the file." )
pick(   W_ACCELISEMPTY,
        "The accelerator table is empty.",
        "The accelerator table is empty." )

// WMAIN.C
pick(   W_ACCELAPPTITLE,
        "Open Watcom Accelerator Editor",
        "Open Watcom Accelerator Editor" )
pick(   W_GETTINGKEYS,
        "Getting Keys",
        "Getting Keys" )
pick(   W_CHANGEACCELMEMFLAGS,
        "Changing Memory Flags",
        "Changing Memory Flags" )
pick(   W_UPDATEMODIFIEDACCEL,
        "This accelerator resource has been modified.\nSave?",
        "This accelerator resource has been modified.\nSave?" )
pick(   W_RENAMINGACCEL,
        "Renaming Accelerator table",
        "Renaming Accelerator table" )
pick(   W_ACCELCLEARWARNING,
        "Clear will delete ALL accelerator items.\nClear?",
        "Clear will delete ALL accelerator items.\nClear?" )
pick(   W_ACCELCLEARTITLE,
        "Clear Accelerator Table",
        "Clear Accelerator Table" )
pick(   W_ACCELCLEARMSG,
        "Accelerator table cleared",
        "Accelerator table cleared" )
pick(   W_UPDATEMODIFIEDSYM,
        "The symbols have been modified.\nSave?",
        "The symbols have been modified.\nSave?" )
pick(   W_ABOUT_NAME,
        "Open Watcom Accelerator Editor for Windows" STR_BITNEES,
        "Open Watcom Accelerator Editor for Windows" STR_BITNEES )
pick(   W_ABOUT_COPYRIGHT_YEAR,
        "2002",
        "2002" )
pick(   W_ABOUT_TITLE,
        "About Open Watcom Accelerator Editor",
        "About Open Watcom Accelerator Editor" )

// WRIBBON.C
pick(   W_TIP_NEW,
        "New",
        "New" )
pick(   W_TIP_OPEN,
        "Open",
        "Open" )
pick(   W_TIP_SAVE,
        "Save",
        "Save" )
pick(   W_TIP_CLEAR,
        "Clear",
        "Clear" )
pick(   W_TIP_UPDATE,
        "Update",
        "Update" )
pick(   W_TIP_CUT,
        "Cut",
        "Cut" )
pick(   W_TIP_COPY,
        "Copy",
        "Copy" )
pick(   W_TIP_PASTE,
        "Paste",
        "Paste" )
pick(   W_TIP_NEWITEM,
        "Insert New Item",
        "Insert New Item" )
pick(   W_TIP_DELETE,
        "Delete",
        "Delete" )
pick(   W_TIP_KEYVALUE,
        "Select Key Value",
        "Select Key Value" )

#include "w.msg"
