#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# strg3s.lib -- stack based 32-bit STRING library
#
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static
define_library_include = $(cpplib_dir)/string/string.mif
!include $(cpplib_dir)/mklib.mif
