#pmake: build trap remote os_linux cpu_386 par
host_CPU = 386
host_OS = linux

os = linux
srv = par
cpu = x86
which = TRAP
type  = remote_link

extra_objs = parlinux.obj lnxnoth.obj

!include $(trap_dir)/master.mif
