#pmake: build trap remote os_linux cpu_386 par
host_cpu = 386
host_os  = linux

os = linux
srv = par
cpu = x86
which = TRAP
remote_link = 1

extra_objs = parlinux.obj

inc_dirs   = -I"$(trap_dir)/lcl/linux/h"

!include $(trap_dir)/master.mif
