copy btom.c p:\src\clibexam\japan
copy chkctype.c p:\src\clibexam\japan
copy hantozen.c p:\src\clibexam\japan
copy isalkana.c p:\src\clibexam\japan
copy isalnmkana.c p:\src\clibexam\japan
copy isgrkana.c p:\src\clibexam\japan
copy iskana.c p:\src\clibexam\japan
copy iskanji.c p:\src\clibexam\japan
copy iskanji2.c p:\src\clibexam\japan
copy iskmoji.c p:\src\clibexam\japan
copy iskpun.c p:\src\clibexam\japan
copy ispnkana.c p:\src\clibexam\japan
copy isprkana.c p:\src\clibexam\japan
copy jasctime.c p:\src\clibexam\japan
copy jctime.c p:\src\clibexam\japan
copy jgetmoji.c p:\src\clibexam\japan
copy jisalpha.c p:\src\clibexam\japan
copy jisdigit.c p:\src\clibexam\japan
copy jishira.c p:\src\clibexam\japan
copy jiskana.c p:\src\clibexam\japan
copy jiskigou.c p:\src\clibexam\japan
copy jisl0.c p:\src\clibexam\japan
copy jisl1.c p:\src\clibexam\japan
copy jisl2.c p:\src\clibexam\japan
copy jislower.c p:\src\clibexam\japan
copy jisprint.c p:\src\clibexam\japan
copy jisspace.c p:\src\clibexam\japan
copy jistojms.c p:\src\clibexam\japan
copy jisupper.c p:\src\clibexam\japan
copy jiszen.c p:\src\clibexam\japan
copy jmstojis.c p:\src\clibexam\japan
copy jperror.c p:\src\clibexam\japan
copy jputmoji.c p:\src\clibexam\japan
copy jstradv.c p:\src\clibexam\japan
copy jstrcat.c p:\src\clibexam\japan
copy jstrchr.c p:\src\clibexam\japan
copy jstrcmp.c p:\src\clibexam\japan
copy jstrcspn.c p:\src\clibexam\japan
copy jstrerror.c p:\src\clibexam\japan
copy jstricmp.c p:\src\clibexam\japan
copy jstrlen.c p:\src\clibexam\japan
copy jstrlwr.c p:\src\clibexam\japan
copy jstrmatch.c p:\src\clibexam\japan
copy jstrncat.c p:\src\clibexam\japan
copy jstrncmp.c p:\src\clibexam\japan
copy jstrncpy.c p:\src\clibexam\japan
copy jstrnicmp.c p:\src\clibexam\japan
copy jstrnset.c p:\src\clibexam\japan
copy jstrrchr.c p:\src\clibexam\japan
copy jstrrev.c p:\src\clibexam\japan
copy jstrset.c p:\src\clibexam\japan
copy jstrskip.c p:\src\clibexam\japan
copy jstrspn.c p:\src\clibexam\japan
copy jstrstr.c p:\src\clibexam\japan
copy jstrtok.c p:\src\clibexam\japan
copy jstrupr.c p:\src\clibexam\japan
copy jtohira.c p:\src\clibexam\japan
copy jtokata.c p:\src\clibexam\japan
copy jtolower.c p:\src\clibexam\japan
copy jtoupper.c p:\src\clibexam\japan
copy mtob.c p:\src\clibexam\japan
copy nthctype.c p:\src\clibexam\japan
copy zentohan.c p:\src\clibexam\japan
