#pmake: build serv remote os2 16 32 tcp x86

os = os2
srv = tcp
cpu = x86

extra_objs = $(remote_objs)
extra_libs = $(watcom_dir)\lib\tcpipdll.lib
extra_incs = $(watcom_dir)\os220_h\tcpip

!include $(trap_dir)\serv.mif
