#pmake: build flat cpu_386 os_nt dynamic
#
# iostmt3s.lib -- stack based multi-thread 32-bit IOSTREAM library
#
processor  = 386
system     = winnt
model      = mf
convention = stack
linkage    = dynamic
mthreaded  = 1
fs_registration = yes
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
