#pmake: build serv remote os_nt cpu_386 par

tree_depth = 4

host_cpu = 386
host_os  = nt

target_cpu = x86

srv = par
which = SERVER
gui = 1
remote_link = 1

extra_objs = parnt.obj

!include $(trap_dir)/master.mif
