#pmake: build lcl os_linux cpu_386 trap x86
#
# Create the Linux std.trp
#
host_cpu = 386
host_os  = linux

target_cpu = x86

os      = linux
srv     = lcl
which   = TRAP

!include $(trap_dir)/lcl/linux/trap.mif
!include $(trap_dir)/master.mif
