#pmake: build flat cpu_386 os_nt
#
# iostmt3s.lib -- stack based multi-thread 32-bit IOSTREAM library
#
processor  = 386
system     = winnt
model      = mf
convention = stack
linkage    = static
mthreaded  = 1
fs_registration = yes

!include $(cpplib_dir)/iostream/iostream.mif
