#pmake: build large cpu_i86 os_osi
#
# cplx7l.lib -- large memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = ml
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
