#pmake: build flat cpu_386 os_osi
#
# plibmt3s -- 32-bit 3s PLIB multi-thread
#
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/runtime/runtime.mif
