pick( ABT_COPYRIGHT,
        "Portions Copyright (c) %s Sybase, Inc.",
        "Portions Copyright (c) %s Sybase, Inc." )
pick( ABT_386_ENH,
        "386 Enhanced Mode",
        "386 エンハンスドモード" )
pick( ABT_STD_MODE,
        "Standard Mode",
        "スタンダードモード" )
pick( ABT_MEM_X_KB_FREE,
        "Memory:\t\t%s KB free",
        "メモリ:\t\t%s KB 使用可能" )
pick( ABT_SYS_RESOURCES_FREE,
        "System Resources:\t%d%% free",
        "システムリソース:\t%d%% 使用可能" )
pick( ABT_SYS_RESOURCES_N_A,
        "System Resources:\t\tNot available",
        "システムリソース:\t\t使用不可能" )
pick( ABT_RUNNING_ON_386,
        "Running on an i386",
        "i386 上で動作中" )
pick( ABT_RUNNING_ON_486,
        "Running on an i486",
        "i486 上で動作中" )
pick( ABT_RUNNING_ON_586,
        "Running on a Pentium or compatible",
        "Pentium 上で動作中" )
pick( ABT_VIRT_MEM,
        "Virtual Memory:\t\t%d KB",
        "仮想メモリ:\t\t%d KB" )
pick( ABT_MEM_LOAD,
        "Memory Load:\t\t%d%%",
        "メモリ ロード:\t\t%d%%" )
