#pmake: build flat cpu_386 os_rdos
#
# strg3rmt.lib -- register based 32-bit multi-threaded STRING library
#
processor  = 386
system     = rdos
model      = mf
convention = register
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/string/string.mif
