name: curl-command
description: 'handle curl command line common options'

outputs:
  cov:
    description: 'curl command for Coverity site'
    value: ${{steps.curlcmd.outputs.cov}}
  gh1:
    description: 'curl command for GitHub REST API'
    value: ${{steps.curlcmd.outputs.gh1}}
  gh2:
    description: 'api extension to curl command for GitHub REST API'
    value: ${{steps.curlcmd.outputs.gh2}}
  gh3:
    description: 'uploads extension to curl command for GitHub REST API'
    value: ${{steps.curlcmd.outputs.gh3}}
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    run: |
      $null = Remove-Item -ErrorAction Ignore alias:curl
      $curl_cov = "curl -s ${{env.OWCURLOPTS}}"
      $curl_gh1 = $curl_cov + ' -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{github.token}}"'
      "cov=$curl_cov" | Out-File -FilePath ${{github.output}} -Encoding utf8 -Append
      "gh1=$curl_gh1" | Out-File -FilePath ${{github.output}} -Encoding utf8 -Append
      "gh2=https://api.github.com/repos/${{github.repository}}" | Out-File -FilePath ${{github.output}} -Encoding utf8 -Append
      "gh3=https://uploads.github.com/repos/${{github.repository}}" | Out-File -FilePath ${{github.output}} -Encoding utf8 -Append
    shell: pwsh
