#pmake: build small cpu_i86 os_osi os_os2
#
# plibs -- 16-bit small memory-model PLIB
#
processor  = 086
system     = generic
model      = ms
linkage    = static

!include $(cpplib_dir)/runtime/plib.mif
