#pmake: build small cpu_i86 os_dos os_os2 os_win os_qnx
#
# plibs -- 16-bit small memory-model PLIB
#
processor  = 086
system     = generic
model      = ms
linkage    = static

!include $(cpplib_dir)/runtime/runtime.mif
