#pmake: build compact cpu_i86 os_dos os_os2 os_win os_qnx
#
# plibc -- 16-bit compact memory-model PLIB
#
processor  = 086
system     = generic
model      = mc
linkage    = static

!include $(cpplib_dir)/runtime/runtime.mif
