#pmake: trap lcl os_dos dsx cpu_386 x86
host_cpu = i86
host_os  = dos

target_cpu = x86
target_os  = dos

srv = ads
which = TRAP

extra_cpp_flags = -DACAD

!include $(trap_dir)/lcl/dos/dosx/dosx.mif
!include $(trap_dir)/master.mif
