#pmake: build trap remote os_linux cpu_386 tcp x86
host_cpu = 386
host_os  = linux

os = linux
srv = tcp
cpu = x86
which = TRAP
remote_link = 1

extra_objs = qtcpsupp.obj

!include $(trap_dir)/master.mif
