#pmake: build flat cpu_386 os_dos os_win os_rdos os_linux os_nt os_os2 os_qnx os_nov
#
# plib3s -- 32-bit 3s PLIB
#
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static

!include $(cpplib_dir)/runtime/runtime.mif
