#pmake: build os_nt cpu_386

host_os       = nt
host_cpu      = 386

root_dir      = ..
include_dir   = $(root_dir)/include
lib_dir       = $(root_dir)/lib
what_to_build = libs

!include ../master.mif
