#pmake: build serv remote os_nov cpu_386 nov x86
host_cpu = 386
host_os  = nov

target_cpu = x86

nlm_ver = 4
os    = nlm
srv   = nov
which = SERVER
remote_link = 1
builtin_trap = 1

extra_objs = novnlm.obj

!include $(trap_dir)/lcl/nlm/trap.mif
!include $(trap_dir)/master.mif
