#pmake: build flat cpu_386 os_rdos
#
# iost3smt.lib -- stack based 32-bit multi-threaded IOSTREAM library
#
processor  = 386
system     = rdos
model      = mf
convention = stack
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/iostream/iostream.mif
