#pmake: build medium cpu_i86 os_osi os_os2
#
# strgm.lib -- medium memory-model STRING library
#
processor  = 086
system     = generic
model      = mm
linkage    = static
define_library_include = $(cpplib_dir)/string/string.mif
!include $(cpplib_dir)/mklib.mif
