#pmake: build small cpu_i86 os_win
#
# strgs.lib -- small memory-model STRING library for Windows
#
processor  = 086
system     = windows
model      = ms
linkage    = static
define_library_include = $(cpplib_dir)/string/string.mif
!include $(cpplib_dir)/mklib.mif
