:FONTPAUSE
   type = 'pause00'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause00." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause01'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause01." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause02'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause02." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause03'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause03." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause04'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause04." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause05'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause05." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause06'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause06." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause07'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause07." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause08'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause08." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

:FONTPAUSE
   type = 'pause09'
   :value.
      %setsymbol("fontcount",%decimal(%add(%getnumsymbol("fontcount"),1)))
      %image( "*** FONTPAUSE pause09." )
      %image(" Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
   :evalue.
:eFONTPAUSE.

