:DEVICEFONT
   fontname     = 'tfon00'
   fontswitch   = 'switch00'
   fontpause    = 'pause00'
   resident     = no
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon01'
   fontswitch   = 'switch01'
   fontpause    = 'pause01'
   resident     = no
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon02'
   fontswitch   = 'switch02'
   fontpause    = 'pause02'
   resident     = no
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon03'
   fontswitch   = 'switch03'
   fontpause    = 'pause03'
   resident     = yes
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon04'
   fontswitch   = 'switch04'
   fontpause    = 'pause04'
   resident     = no
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon05'
   fontswitch   = 'switch05'
   fontpause    = 'pause05'
   resident     = no
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon06'
   fontswitch   = 'switch06'
   fontpause    = 'pause06'
   resident     = no
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon07'
   fontswitch   = 'switch07'
   fontpause    = 'pause07'
   resident     = no
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon08'
   fontswitch   = 'switch08'
   fontpause    = 'pause08'
   resident     = no
:eDEVICEFONT.

:DEVICEFONT
   fontname     = 'tfon09'
   fontswitch   = 'switch09'
   fontpause    = 'pause09'
   resident     = no
:eDEVICEFONT.

:DEFAULTFONT
   font         = 0
   fontname     = 'tfon00' 
   fontstyle    = plain
:eDEFAULTFONT.

:DEFAULTFONT
   font         = 1
   fontname     = 'tfon01' 
   fontstyle    = bold
:eDEFAULTFONT.

:DEFAULTFONT
   font         = 2
   fontname     = 'tfon02' 
   fontstyle    = uline
:eDEFAULTFONT.

:DEFAULTFONT
   font         = 3
   fontname     = 'tfon03' 
   fontstyle    = uscore
:eDEFAULTFONT.

:DEFAULTFONT
   font         = 4
   fontname     = 'tfon04' 
   fontstyle    = ulbold
:eDEFAULTFONT.

:DEFAULTFONT
   font         = 5
   fontname     = 'tfon05' 
   fontstyle    = usbold
:eDEFAULTFONT.

