:NEWPAGE
   :value
      %recordbreak()
      %image("*NEWPAGE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :evalue
:eNEWPAGE

:HTAB
   :value
      %image("*HTAB block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :evalue
:eHTAB

:FONTSWITCH
   type='switch00'
   :startvalue.
      %image("*FONTSWITCH 'switch00' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch00' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch01'
   :startvalue.
      %image("*FONTSWITCH 'switch01' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch01' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch02'
   :startvalue.
      %image("*FONTSWITCH 'switch02' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch02' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch03'
   :startvalue.
      %image("*FONTSWITCH 'switch03' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch03' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch04'
   :startvalue.
      %image("*FONTSWITCH 'switch04' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch04' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch05'
   :startvalue.
      %image("*FONTSWITCH 'switch05' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch05' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch06'
   :startvalue.
      %image("*FONTSWITCH 'switch06' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch06' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch07'
   :startvalue.
      %image("*FONTSWITCH 'switch07' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch07' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch08'
   :startvalue.
      %image("*FONTSWITCH 'switch08' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch08' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSWITCH
   type='switch09'
   :startvalue.
      %image("*FONTSWITCH 'switch09' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :endvalue.
      %image("*FONTSWITCH 'switch09' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSWITCH.

:FONTSTYLE
   type=plain
   :startvalue.
      %recordbreak()
      %image("*FONTSTYLE 'plain' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :lineproc
      pass=1
      :startvalue
         %image("*FONTSTYLE 'plain' Pass 1 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'plain' Pass 1 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'plain' Pass 1 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'plain' Pass 1 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'plain' Pass 1 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :endvalue.
      %image("*FONTSTYLE 'plain' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSTYLE.

:FONTSTYLE
   type=bold
   :startvalue.
      %image("*FONTSTYLE 'bold' STARTVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :lineproc
      pass=1
      :startvalue
         %image("*FONTSTYLE 'bold' Pass 1 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'bold' Pass 1 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'bold' Pass 1 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'bold' Pass 1 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'bold' Pass 1 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :lineproc
      pass=2
      :startvalue
         %image("*FONTSTYLE 'bold' Pass 2 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'bold' Pass 2 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'bold' Pass 2 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'bold' Pass 2 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'bold' Pass 2 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :endvalue.
      %image("*FONTSTYLE 'bold' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSTYLE.

:FONTSTYLE
   type=uline
   :startvalue.
      %image("*FONTSTYLE 'uline' STARTVALUE block*  ")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :lineproc
      pass=1
      :startvalue
         %image("*FONTSTYLE 'uline' Pass 1 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'uline' Pass 1 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'uline' Pass 1 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'uline' Pass 1 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'uline' Pass 1 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :lineproc
      pass=2
      :startvalue
         %image("*FONTSTYLE 'uline' Pass 2 LINEPROC STARTVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'uline' Pass 2 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %dotab()
         %ulineon()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'uline' Pass 2 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'uline' Pass 2 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'uline' Pass 2 LINEPROC ENDVALUE block*")
         %recordbreak()
         %ulineoff()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue.
   :elineproc.
   :endvalue.
      %image("*FONTSTYLE 'uline' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSTYLE.

:FONTSTYLE
   type=uscore
   :startvalue.
      %image("*FONTSTYLE 'uscore' STARTVALUE block* ")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :lineproc
      pass=1
      :startvalue
         %image("*FONTSTYLE 'uscore' Pass 1 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'uscore' Pass 1 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'uscore' Pass 1 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'uscore' Pass 1 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'uscore' Pass 1 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :lineproc
      pass=2
      :startvalue
         %image("*FONTSTYLE 'uscore' Pass 2 LINEPROC STARTVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :startword
         %image("*FONTSTYLE 'uscore' Pass 2 LINEPROC STARTWORD block*")
         %recordbreak()
         %dotab()
         %ulineon()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'uscore' Pass 2 LINEPROC ENDWORD block*")
         %recordbreak()
         %ulineoff()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword.
      :endvalue
         %image("*FONTSTYLE 'uscore' Pass 2 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :endvalue.
      %image("*FONTSTYLE 'uscore' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSTYLE.

:FONTSTYLE
   type=ulbold
   :startvalue.
      %image("*FONTSTYLE 'ulbold' STARTVALUE block* ")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :lineproc
      pass=1
      :startvalue
         %image("*FONTSTYLE 'ulbold' Pass 1 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'ulbold' Pass 1 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'ulbold' Pass 1 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'ulbold' Pass 1 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'ulbold' Pass 1 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :lineproc
      pass=2
      :startvalue
         %image("*FONTSTYLE 'ulbold' Pass 2 LINEPROC STARTVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'ulbold' Pass 2 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %dotab()
         %ulineon()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'ulbold' Pass 2 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'ulbold' Pass 2 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue.
         %image("*FONTSTYLE 'ulbold' Pass 2 LINEPROC ENDVALUE block*")
         %recordbreak()
         %dotab()
         %ulineoff()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue.
   :elineproc.
   :lineproc
      pass=3
      :startvalue
         %image("*FONTSTYLE 'ulbold' Pass 3 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'ulbold' Pass 3 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'ulbold' Pass 3 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'ulbold' Pass 3 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'ulbold' Pass 3 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :endvalue.
      %image("*FONTSTYLE 'ulbold' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSTYLE.

:FONTSTYLE
   type=usbold
   :startvalue.
      %image("*FONTSTYLE 'usbold' STARTVALUE block* ")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :estartvalue.
   :lineproc
      pass=1
      :startvalue
         %image("*FONTSTYLE 'usbold' Pass 1 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'usbold' Pass 1 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'usbold' Pass 1 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'usbold' Pass 1 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'usbold' Pass 1 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :lineproc
      pass=2
      :startvalue
         %image("*FONTSTYLE 'usbold' Pass 2 LINEPROC STARTVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :startword
         %image("*FONTSTYLE 'usbold' Pass 2 LINEPROC STARTWORD block*")
         %recordbreak()
         %dotab()
         %ulineon()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'usbold' Pass 2 LINEPROC ENDWORD block*")
         %recordbreak()
         %dotab()
         %ulineoff()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword.
      :endvalue
         %image("*FONTSTYLE 'usbold' Pass 2 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :lineproc
      pass=3
      :startvalue
         %image("*FONTSTYLE 'usbold' Pass 3 LINEPROC STARTVALUE block*")
         %recordbreak()
         %textpass()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartvalue
      :firstword
         %image("*FONTSTYLE 'usbold' Pass 3 LINEPROC FIRSTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :efirstword
      :startword
         %image("*FONTSTYLE 'usbold' Pass 3 LINEPROC STARTWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :estartword
      :endword
         %recordbreak()
         %image("*FONTSTYLE 'usbold' Pass 3 LINEPROC ENDWORD block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendword
      :endvalue
         %image("*FONTSTYLE 'usbold' Pass 3 LINEPROC ENDVALUE block*")
         %recordbreak()
         %image("Font Number: ") %image(%decimal(%font_number()))
         %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
         %recordbreak()
         %image("Pages: ") %image(%decimal(%pages())) 
         %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
         %recordbreak()
      :eendvalue
   :elineproc.
   :endvalue.
      %image("*FONTSTYLE 'usbold' ENDVALUE block*")
      %recordbreak()
      %image("Font Number: ") %image(%decimal(%font_number()))
      %image(" Instance: ") %image(%decimal(%getnumsymbol("fontcount")))
      %recordbreak()
      %image("Pages: ") %image(%decimal(%pages())) 
      %image(" Location: ") %image(%decimal(%x_address())) %image(",") %image(%decimal(%y_address())) 
      %recordbreak()
   :eendvalue.
:eFONTSTYLE.

