#pmake/150: build flat register 32bit winnt ix86 rtdll os_nt cpu_386 ntrtdll

component  = clib
processor  = 386
model      = mf
subdir     = mf_r
system     = winnt
convention = register

!include $(rtdll_dir)/master.mif
