#pmake/150: build flat register 32bit winnt ix86 rtdll os_nt cpu_386 ntrtdll
component  = clib
processor  = 386
model      = mf
system     = winnt
convention = register
mthreaded=1

!include $(rtdll_dir)/master.mif
