#pmake: trap remote os_os2 cpu_i86 par
host_cpu = i86
host_os  = os2

target_cpu = x86
target_os  = os2

srv = par
which = TRAP
remote_link = 1

extra_objs = paros2.obj portos2.obj

!include ../os2.mif
!include $(trap_dir)/master.mif
