#pmake: build os_linux cpu_386 386 intel
#
# Open Watcom Debugger makefile for Linux
#

host_OS  = linux
host_CPU = 386

syshdir =

sysobjs = &
    linuxcmd.obj &
    linuxio.obj &
    lnxinit.obj &
    lnxscrn.obj &
    lnxlkup.obj &
    lnxchk.obj

!include ../../master.mif
