/* UTF-8 encoding, ¥ */

pick( ERR_BAD_LIBRARY,      "'%s' is an invalid library",
                "'%s'は不適切なライブラリです" )
pick( ERR_BAD_OBJECT,       "'%s' is an invalid object file",
                "'%s'は不適切なオブジェクト・ファイルです" )
pick( ERR_BAD_DLL,      "'%s' is an invalid dll",
                "'%s'不適切なDLLです" )
pick( ERR_CANT_FIND,        "Cannot find file '%s'",
                "ファイル'%s'が見つかりません" )
pick( ERR_CREATING_LIBRARY, "Cannot open '%s' - library will be created",
                "'%s'をオープンできません - ライブラリを作成します" )
pick( ERR_DIR_NOT_EXIST,    "Directory '%s' does not exist",
                "ディレクトリ'%s'は存在しません" )
pick( ERR_DUPLICATE_OPTION, "Duplicate option near '%s'",
                "'%s'の付近のオプションは2度指定されています" )
pick( ERR_DUPLICATE_SYMBOL, "Duplicate symbol '%s' ignored.",
                "２重のシンボル'%s'を無視します" )
pick( ERR_CANT_READ,        "Error reading '%s'. %s.",
                "読み込みエラー '%s'. %s." )
pick( ERR_CANT_WRITE,       "Error writing '%s'. %s.",
                "書き込みエラー '%s'. %s." )
pick( ERR_DELETE_AND_CREATE,    "Files can not be extracted using the -n option",
                "-nオプションを指定するとファイルを取り出すことはできません" )
pick( ERR_BAD_CMDLINE,      "Invalid command line near '%s'",
                "'%s'の付近のコマンドラインの指定が不適切です" )
pick( ERR_BAD_OPTION,       "Invalid option '-%c'",
                "不適切なオプション '-%c'" )
pick( ERR_NO_LIBNAME,       "Library name required on command line",
                "コマンドラインでライブラリ名を指定してください" )
pick( ERR_TWO_LIBNAMES,     "Library name specified twice near '%s'",
                "ライブラリ名が'%s'の付近で２度指定されています" )
pick( ERR_NO_MEMORY,        "Out of memory",
                "メモリ不足です" )
pick( ERR_CANT_DELETE,      "Unable to find module '%s' for deletion",
                "削除するモジュール'%s'が見つかりません" )
pick( ERR_CANT_EXTRACT,     "Unable to find module '%s' for extraction",
                "取り出すモジュール'%s'が見つかりません" )
pick( ERR_CANT_OPEN,        "Unable to open file '%s'. %s.",
                "ファイルをオープンできません '%s'. %s." )
pick( ERR_CANT_REMOVE,      "Unable to remove file '%s'",
                "ファイル'%s'を削除できません" )
pick( ERR_CANT_REPLACE,     "Unable to replace contents of file '%s'. %s",
                "ファイルの内容を置き換えられません '%s'. %s" )
pick( ERR_NO_SYMBOLS,       "Library contains no external symbols",
                "ライブラリの中には外部シンボルが入っていません" )
pick( ERR_NOT_LIB,      "Cannot add %s object to %s library",
                "%s オブジェクトをLIBライブラリに追加できません" )
pick( ERR_CANT_DO_IMPORT,   "Unable to create %s import library from '%s'",
                "%sインポート・ライブラリを'%s'から作れません" )
pick( ERR_NO_PROCESSOR,     "No processor specified.  Using %s",
                "プロセッサが指定されていません。%sとして扱います" )
pick( ERR_NO_TYPE,      "No import type specified.  Using %s",
                "インポートの方が指定されていません。%sとして扱います" )
pick( ERR_NO_EXPORTS,       "No exports in '%s'",
                "'%s'にエクスポートはありません" )
pick( ERR_PAGE_RANGE,       "Page size out of range",
                "ページの大きさは範囲を超えています" )
pick( ERR_MIXED_OBJ,        "Can not put %s and %s objects in same library",
                "オブジェクト%sと%sを同じライブラリに入れられません" )
pick( ERR_LIB_TOO_LARGE,    "Library too large.  Recommend splitting the library into two or trying a page_bound larger than %s.",
                "ライブラリが大きすぎます。ライブラリを２つに分割するか、%sよりpage_boundをもっと大きくすることを推奨します。" )
