#pmake: build flat cpu_386 os_dos os_win os_rdos os_linux os_nt os_os2 os_qnx os_nov
#
# strg3r.lib -- register based 32-bit STRING library
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static

!include $(cpplib_dir)/string/string.mif
