#pmake: build large cpu_i86 os_dos os_os2 os_win os_qnx
#
# plibl -- 16-bit large memory-model PLIB
#
processor  = 086
system     = generic
model      = ml
linkage    = static

!include $(cpplib_dir)/runtime/runtime.mif
