#pmake: build large cpu_i86 os_osi os_os2
#
# plibl -- 16-bit large memory-model PLIB
#
processor  = 086
system     = generic
model      = ml
linkage    = static

!include $(cpplib_dir)/runtime/runtime.mif
