#pmake: build large cpu_i86 os_osi os_os2
#
# plibl -- 16-bit large memory-model PLIB
#
processor  = 086
system     = generic
model      = ml
linkage    = static
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
