#pmake: build os_linux cpu_x64
#
# Open Watcom Debugger makefile for Linux
#

host_os  = linux
host_cpu = x64

syshdir =

sysobjs = &
    linuxcmd.obj &
    linuxio.obj &
    lnxinit.obj &
    lnxscrn.obj &
    lnxlkup.obj &
    lnxchk.obj

!include ../../master.mif
