#pmake: build flat cpu_386 os_os2 dynamic
processor  = 386
system     = os2
model      = mf
convention = stack
linkage    = dynamic
mthreaded  = 1
subdir     = mf_smt.dll

additional_cleanup  = export*.def

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
