#pmake: build trap remote os_dos cpu_i86 cpu_386 ser x86
host_CPU = i86
host_OS = dos

os = dos
srv = ser
cpu = x86
which = TRAP
type  = remote_link

extra_objs = serint.obj serdos.obj busywait.obj dosnoth.obj

!include $(trap_dir)/master.mif
