#pmake: build trap remote os_dos cpu_i86 cpu_386 ser x86
host_cpu = i86
host_os = dos

os = dos
srv = ser
cpu = x86
which = TRAP
remote_link = 1
builtin_trap = 1

extra_objs = serint.obj serdos.obj busywait.obj

!include $(trap_dir)/master.mif
