#pmake: build flat cpu_386 os_osi os_dos os_linux
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static
subdir     = mf_s

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
