Project
    TargetGroup "RDOS Application"
      Target *.exe, rp2e_, "32-bit Executable"
      Target *.dll, rp2d_, "32-bit Dynamic Link Library"
      Target *.lib, rp2s_, "32-bit Library"
    TargetGroup "RDOS Kernel"
      Target *.rdv, rk6e_, "16-bit Device driver"
      Target *.rdv, rk2e_, "32-bit Device driver"
      Target *.bin, rb6e_, "16-bit Binary"
      Target *.bin, rb2e_, "32-bit Binary"
      Target *.bin, rm6e_, "Multiboot Stub"
      Target *.lib, r?6s_, "16-bit Library"
