#pmake/150: build debug flat register 32bit calls winnt iX86 rtdll os_nt cpu_386 cpplib

component  = cpplib
processor  = 386
model      = mf
subdir     = mf_rd
system     = winnt
convention = register

rtdll_release = 0

!include $(rtdll_dir)/master.mif
