#pmake: build flat cpu_386 os_nt dynamic
#
# plib3s -- 32-bit 3s MT PLIB, PLBX
#
processor  = 386
system     = winnt
model      = mf
convention = stack
linkage    = dynamic
mthreaded  = 1
fs_registration = yes

!include $(cpplib_dir)/runtime/plib.mif
