#pmake:all small stack 32bit calls winnt iX86 rtdll no_build os_nt cpu_386
component=wrtlib
processor=386
model=ms
subdir=ms_s
system=winnt
convention=stack
!include $(rtdll)\master.mif
!include ..\objs.mif
!include $(rtdll)\mkdll.mif
