#pmake: nobuild debug flat register 32bit inline winnt iX86 rtdll os_nt cpu_386

component  = wlib
processor  = 387
model      = mf
system     = winnt
convention = register

rtdll_release = 0

!include $(rtdll_dir)/master.mif
