#pmake: trap remote os_os2 cpu_i86 vdm

tree_depth = 3

host_cpu = i86
host_os  = os2

target_cpu = x86

srv = vdm
which = TRAP
remote_link = 1

extra_objs = vdmcli.obj

!include $(trap_dir)/master.mif
