#pmake: build trap remote os_nt cpu_386 par
host_CPU = 386
host_OS = nt

os = nt
srv = par
cpu = x86
which = TRAP
type  = remote_link

extra_objs = parnt.obj ntnoth.obj

!include $(trap_dir)/master.mif
