//wmsg.c
pick(   W_ERRMSG,
	"Error Message",
	"Error Message" )

//wclip.c
pick(   W_RESTOOBIGTOPASTE,
	"Resource is too large to paste.",
	"Resource is too large to paste." )
	
//wgetfn.c
pick(   W_ERRORSELFILE,
	"An error occurred selecting the file.",
	"An error occurred selecting the file." )
pick(	W_GETFNCOMBOTITLE,
	"List Files of &Type",
	"List Files of &Type" )
	
//weditsym.c
pick(	W_SYMFILTER,
	"Header Files (*.h)\t*.h\tAll Files (*.*)\t*.*\t",
	"Header Files (*.h)\t*.h\tAll Files (*.*)\t*.*\t" )
pick(	W_SAVESYMTITLE,
	"Save Symbol Header File",
	"Save Symbol Header File" )
pick(	W_LOADSYMTITLE,
	"Load Symbol Header File",
	"Load Symbol Header File" )
pick(	W_NOOPENSYMFILE,
	"Could not open symbol file.",
	"Could not open symbol file." )
pick(	W_SYMOUTOFMEM,
	"Ran out of memory loading symbols.",
	"Ran out of memory loading symbols." )

