#define __STL_95
#include <algo.h>
#include <bvector.h>
#include <defalloc.h>
#include <deque.h>
#include <function.h>
#include <iterator.h>
#include <list.h>
#include <map.h>
#include <multimap.h>
#include <multiset.h>
#include <stack.h>
#include <set.h>
#include <vector.h>
