#pmake: build small cpu_386 os_nov
#
# cplx73s.lib -- Netware stack based 32-bit COMPLEX library fpi
#
processor  = 387
system     = netware
model      = ms
convention = stack
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
