#pmake: trap remote os_qnx cpu_i86 cpu_386 par x86
host_cpu = 386
host_os  = qnx

target_cpu = x86
target_os  = qnx

srv = par
which = TRAP
remote_link = 1

extra_objs = parqnx.obj

!include $(trap_dir)/master.mif
