#pmake: trap remote os_qnx cpu_i86 cpu_386 par x86
host_CPU = 386
host_OS = qnx

os = qnx
srv = par
cpu = x86
which = TRAP
type  = remote_link

extra_objs = parqnx.obj

!include $(trap_dir)/master.mif
