#pmake/150: nobuild debug flat register 32bit os2 ix86 rtdll os_os2 cpu_386
component  = clib
processor  = 386
model      = mf
system     = os2
convention = register
mthreaded=1

lib_debug = 1

!include $(rtdll_dir)/master.mif
