#pmake: build flat cpu_386 os_osi
#
# contmt3r.lib -- register based multi-thread 32-bit CONTAINER library
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/contain/contain.mif
