.* QNX segment manipulation
.seelist qnx_segment_alloc qnx_segment_alloc_flags
.seelist qnx_segment_arm qnx_segment_flags
.seelist qnx_segment_free qnx_segment_get qnx_segment_huge
.seelist qnx_segment_index qnx_segment_info qnx_segment_overlay
.seelist qnx_segment_overlay_flags qnx_segment_put qnx_segment_realloc
