.begpoint $compact $setptnt 8
:DTHD.Error
:DDHD.Message
.point 0
"Error 0"
.point 1
"No such file or directory"
.point 2
"Argument list too big"
.point 3
"Exec format error"
.point 4
"Bad file number"
.point 5
"Not enough memory"
.point 6
"Permission denied"
.point 7
"File exists"
.point 8
"Cross-device link"
.point 9
"Invalid argument"
.point 10
"File table overflow"
.point 11
"Too many open files"
.point 12
"No space left on device"
.point 13
"Argument too large"
.point 14
"Result too large"
.point 15
"Resource deadlock would occur"
.endpoint
