

.extensions:
.extensions: .exe .cpp

exes = equal.exe    long.exe  short.exe  shtequal.exe lonequal.exe &
       notequal.exe add.exe   valid.exe  lshift.exe   rshift.exe

all : $(exes) .symbolic

.cpp.exe :
    wcl $[@
