#pmake:all small register 32bit inline winnt iX86 rtdll no_build os_nt cpu_386 dynamic
component=wrtlib
processor=387
model=ms
subdir=ms_rd
system=winnt
convention=register
!include $(rtdll)\master.mif
!include ..\objs.mif
!include $(rtdll)\mkdll.mif
