#pmake: lcl os_nt cpu_axp trap axp
#
# Create the NT STD.DLL for Alpha
#
host_os  = nt
host_cpu = axp

target_cpu = axp
target_os  = nt

srv     = lcl
which   = TRAP

extra_objs =

!include $(trap_dir)/lcl/nt/nt.mif

