#pmake: build small cpu_i86 os_dos os_os2 os_win os_qnx
#
# iosts.lib -- small memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = ms
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
