type = win
os = nt
build_target = nt
rc = wrc
rcopt = -bt=$(build_target)
sys = nt_win
compiler = comp386
model = f

target : sample.exe .SYMBOLIC
    @%null

samp2 : samp2.exe  .SYMBOLIC
    @%null

!include ..\makefile
