#pmake: lcl os_nto cpu_386 trap x86
#
# Create the QNX Neutrino std.trp
#
host_os  = nto
host_cpu = 386

os    = nto
srv   = lcl
cpu   = x86
which = TRAP

!include $(trap_dir)/lcl/nto/trap.mif
!include $(trap_dir)/master.mif
