#pmake: build trap lcl os_dos dsx cpu_386 x86
host_CPU = i86
host_OS = dos

os = dos
srv = pls
cpu = x86
which = TRAP

extra_c_flags = -dPHARLAP

!include $(trap_dir)/lcl/dos/dosx/dosx.mif
!include $(trap_dir)/master.mif
