name: release
description: 'Create new Release on GitHub'
inputs:
  isrelrel:
    description: 'is release release'
    required: false
    default: ''
    type: string
outputs:
  relid:
    description: 'release ID'
    value: ${{steps.newrel.outputs.relid}}
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    uses: ./.github/actions/curlcmd
##############################################
# create tag and timestamp
##############################################
  - name: 'Prepare build information'
    id: reldata
    run: |
      if [ ${{inputs.isrelrel}} = '1' ]; then
        echo "tag=Current-build" >> ${{github.output}}
        echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> ${{github.output}}
      else
        echo "tag=Last-CI-build" >> ${{github.output}}
        echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> ${{github.output}}
      fi
    shell: bash
##############################################
# delete existing release
##############################################
  - name: 'Remove Release if exists'
    uses: ./.github/actions/ghreldel
    with:
      tag:  ${{steps.reldata.outputs.tag}}
##############################################
# create new release
##############################################
  - name: Create new Release
    uses: ./.github/actions/ghrelcre
    id: newrel
    with:
      note:    "Last updated ${{steps.reldata.outputs.timestamp}} UTC"
      title:   ${{steps.reldata.outputs.tag}}
      tag:     ${{steps.reldata.outputs.tag}}
      tagmsg:  ${{steps.reldata.outputs.timestamp}}
