name: release
description: 'Create new day and month Release on GitHub'
inputs:
  arch:
    description: 'run-time platform'
    required: false
    default: ''
    type: string
  tools:
    description: 'used compiler toolchain'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
outputs:
  drelid:
    description: 'day release ID'
    value: ${{ steps.newdrel.outputs.id }}
  mrelid:
    description: 'month release ID'
    value: ${{ steps.newmrel.outputs.id }}
runs:
  using: composite
  steps:
  - id: curlcmd
    run: >
      if( "${{ inputs.owdebug }}" -eq '1' ) {
        'opts=-sv' | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
      } else {
        'opts=-s' | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
      }
    shell: pwsh      
##############################################
# create daily release, delete existing one
##############################################
  - name: 'Prepare build information for Release'
    id: dreldata
    run: |
      echo "tag=Current-build" >> ${{ github.output }}
      echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> ${{ github.output }}
    shell: bash
  - name: 'Remove daily Release if exists'
    uses: "./.github/actions/ghreldel"
    with:
      tag:     ${{ steps.dreldata.outputs.tag }}
      owdebug: ${{ inputs.owdebug }}
  - name: 'Create daily Release'
    id: newdrel
    uses: "./.github/actions/ghrelcre"
    with:
      note:    "Last updated ${{ steps.dreldata.outputs.timestamp }}"
      title:   ${{ steps.dreldata.outputs.tag }}
      tag:     ${{ steps.dreldata.outputs.tag }}
      tagmsg:  ${{ steps.dreldata.outputs.timestamp }}
      owdebug: ${{ inputs.owdebug }}
##############################################
# create monthly release, only if not exists
##############################################
  - name: 'Prepare information for monthly Release'
    id: mreldata
    run: |
      tagstamp=$(date +'%Y-%m-%d')
      echo "mtag=$(date +'%Y-%m-')" >> ${{ github.output }}
      echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> ${{ github.output }}
      echo "tag=$tagstamp-Build" >> ${{ github.output }}
      echo "tagmsg=$tagstamp $tagstamp-Build" >> ${{ github.output }}
      echo "title=$tagstamp Build" >> ${{ github.output }}
    shell: bash
  - name: 'Check monthly Release exists'
    id: oldmrel
    run: |
      $response = curl ${{ steps.curlcmd.outputs.opts }} -L `
      -H "Accept: application/vnd.github+json" `
      -H "Authorization: Bearer ${{ github.token }}" `
      -H "X-GitHub-Api-Version: 2022-11-28" `
      "https://api.github.com/repos/${{ github.repository }}/git/matching-refs/tags/${{ steps.mreldata.outputs.mtag }}"
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
      $sha = $response | jq -r .[].object.sha
      if( "$sha" -eq 'null' ) { $sha = '' }
      $sha | Join-String -OutputPrefix 'sha=' `
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - if: steps.oldmrel.outputs.sha == ''
    id: newmrel
    name: 'Create monthly Release'
    uses: "./.github/actions/ghrelcre"
    with:
      note:    "Created ${{ steps.mreldata.outputs.timestamp }}"
      title:   ${{ steps.mreldata.outputs.title }}
      tag:     ${{ steps.mreldata.outputs.tag }}
      tagmsg:  ${{ steps.mreldata.outputs.tagmsg }}
      owdebug: ${{ inputs.owdebug }}
  - if: steps.oldmrel.outputs.sha == ''
    id: mdata
    run: echo "tag=${{ steps.mreldata.outputs.tag }}" >> ${{ github.output }}
    shell: bash
