pick(   STR_WARNING,
        "Warning!",
        "警告!" )
pick(   STR_ERROR,
        "Error!",
        "エラ－!" )
pick(   STR_FATAL_ERROR,
        "Fatal Error!",
        "致命的エラ－!" )
pick(   STR_END_OF_FILE,
        "Unexpected end of file",
        "ファイルの終わりを検出しました" )
pick(   STR_APP_NAME,
        "Open Watcom Resource Compiler Version 1.0\n",
        "Open Watcom ウィンドウズ リソ－ス コンパイラ バ－ジョン 1.0\n" )
pick(   ERR_CANT_OPEN_FILE,
        "Unable to open file \"%s\": %s.",
        "ファイルをオ－プン出来ません \"%s\": %s." )
pick(   ERR_RENAMEING_TMP_FILE,
        "Error renaming temporary file \"%s\" to \"%s\": %s.",
        "テンポラリ ファイル \"%s\" の \"%s\"への変更エラ－です: %s." )
pick(   ERR_NOT_ICON_FILE,
        "\"%s\" is not a valid icon file.",
        "\"%s\" は無効なアイコンファイルです." )
pick(   ERR_NOT_CURSOR_FILE,
        "\"%s\" is not a valid cursor file.",
        "\"%s\" は無効なカ－ソルファイルです." )
pick(   ERR_NOT_BITMAP_FILE,
        "\"%s\" is not a valid bitmap file.",
        "\"%s\" は無効なビットマップファイルです." )
pick(   ERR_NONNT_RES_TO_NT_EXE,
        "Trying to add a Win16 or OS/2 RES file \"%s\" to a Win32 executable \"%s\".",
        "ウィンドウズ用 RESファイル \"%s\" をNT実行ファイル \"%s\" に追加しようとしています." )
pick(   ERR_NONWIN_RES_TO_WIN_EXE,
        "Trying to add a Win32 or OS/2 RES file \"%s\" to a Win16 executable \"%s\".",
        "Win32用 RESファイル \"%s\" をウィンドウズ実行ファイル \"%s\" に追加しようとしています." )
pick(   ERR_PE_HEADER_SIZE_CHANGE,
        "Object alignment increase required.  Relink with larger object alignment.",
        "より大きなオブジェクト アラインメントが必要です. より大きなオブジェクト アラインメントを指定して再リンクしてください." )
pick(   ERR_OLD_RESOURCE_OBJECT,
        "EXE contains old resources that cannot be removed.",
        "EXE に削除出来ない古いリソ－スが含まれています.")
pick(   ERR_READING_EXE,
        "Error reading EXE file \"%s\": %s.",
        "EXE ファイル \"%s\"の読み込みエラ－です: %s." )
pick(   ERR_UNEXPECTED_EOF,
        "Error reading file \"%s\": Unexpected end of file.",
        "ファイル \"%s\"の読み込みエラ－です: ファイルの終わりを検出しました." )
pick(   ERR_WRITTING_FILE,
        "Error writing to \"%s\": %s.",
        "\"%s\"への書き込みエラ－です: %s." )
pick(   ERR_READING_ICON,
        "Error reading icon file \"%s\": %s.",
        "アイコン ファイル \"%s\"の読み込みエラ－です: %s." )
pick(   ERR_READING_CURSOR,
        "Error reading cursor file \"%s\": %s.",
        "カ－ソル ファイル \"%s\"の読み込みエラ－です: %s." )
pick(   ERR_READING_BITMAP,
        "Error reading bitmap file \"%s\": %s.",
        "ビットマップ ファイル \"%s\"の読み込みエラ－です: %s." )
pick(   ERR_READING_FONT,
        "Error reading font file \"%s\": %s.",
        "フォント ファイル \"%s\"の読み込みエラ－です: %s." )
pick(   ERR_READING_DATA,
        "Error reading data file \"%s\": %s.",
        "デ－タ ファイル \"%s\"の読み込みエラ－です: %s." )
pick(   ERR_READING_RES,
        "Error reading RES file \"%s\": %s.",
        "RESファイル \"%s\"の読み込みエラ－です: %s." )
pick(   ERR_READING_TMP,
        "Error reading temporary file \"%s\": %s.",
        "テンポラリ ファイル \"%s\"の読み込みエラ－です: %s." )
pick(   ERR_WRITTING_TMP,
        "Error writing to temporary file \"%s\": %s.",
        "テンポラリ ファイル \"%s\"の書き込みエラ－です: %s." )
pick(   ERR_OPENING_TMP,
        "Unable to open temporary file \"%s\": %s.",
        "テンポラリ ファイル \"%s\"をオ－プン出来ません: %s." )
pick(   ERR_READING_FILE,
        "Error reading from file \"%s\": %s.",
        "ファイル \"%s\"からの読み込みエラ－です: %s." )
pick(   ERR_BAD_RES_VER,
        "Unable to read RES file \"%s\": wrong version.",
        "RES ファイル \"%s\"の読み込みエラ－です: バ－ジョンが異なります." )
pick(   ERR_INVALID_RES,
        "\"%s\" is not a valid RES file.",
        "\"%s\" は無効な RES ファイルです." )
pick(   ERR_INTERNAL,
        "Internal compiler error %d.",
        "コンパイラ内部エラ－ %d." )
pick(   ERR_WRITTING_RES_FILE,
        "Error writing resources to temporary file \"%s\": %s.",
        "テンポラリ ファイル \"%s\"へのリソ－スの書き込みエラ－です: %s." )
pick(   ERR_CLOSING_FILE,
        "Error while closing file \"%s\" or flushing buffers to it: %s.",
        "ファイル \"%s\" のクロ－ズ又は バッファフラッシュ時のエラ－です: %s." )
pick(   ERR_CLOSING_TMP,
        "Error while closing temporary file \"%s\" or flushing buffers to it: %s.",
        "テンポラリ ファイル \"%s\" のクロ－ズ又は バッファフラッシュ時のエラ－です: %s." )
pick(   ERR_NO_MSG,
        "",
        "" )
pick(   ERR_NO_RCINCLUDES,
        "RCINCLUDE keyword not currently supported. Use #include.",
        "RCINCLUDE キ－ワ－ドは現在サポ－トされていません. #includeを使用してください." )
pick(   ERR_UNKNOWN_CHAR,
        "'%c' is not valid at this point",
        "'%c' は現時点では無意味です" )
pick(   ERR_RUNAWAY_STRING,
        "String may not cross newline boundary",
        "文字列に改行を含む事は許されていません" )
pick(   ERR_EXPECTING_CHAR,
        "Expecting '%s' but found '%c'",
        "'%s' ではなく '%c'が見つかりました" )
pick(   ERR_TOO_MANY_ARGS,
        "Too many arguments: %s",
        "引数が多過ぎます: %s" )
pick(   ERR_FILENAME_NEEDED,
        "Filename required on command line.",
        "コマンド行でファイル名が必要です." )
pick(   ERR_UNKNOWN_OPTION,
        "Unknown option '%c'",
        "'%c' は無意味なオプションです" )
pick(   ERR_NO_OPT_SPECIFIED,
        "No options specified after options character.",
        "オプション文字の後にオプションが指定されていません." )
pick(   ERR_OUT_OF_MEMORY,
        "Out of memory",
        "メモリ範囲外です" )
pick(   ERR_ACCEL_NO_TYPE,
        "No type given for accelerator %ld",
        "アクセラレ－タ %ldの型がありません" )
pick(   ERR_ACCEL_KEYWORD_IGNORED,
        "Keyword %s ignored for type ASCII accelerator %ld",
        "ASCII型アクセラレ－タ %ld の %s キ－ワ－ドを無視します" )
pick(   ERR_DUPLICATE_RESOURCE,
        "Duplicate resource: %s",
        "リソ－スが重複しています: %s" )
pick(   ERR_PARSER_INTERNAL,
        "Internal parser error.",
        "内部解析エラ－." )
/* this message is unused */
pick(   ERR_SYNTAX_INT,
        "",
        "" )
pick(   ERR_SYNTAX_STR,
        "Syntax error near \"%s\"",
        "\"%s\"付近に文法エラ－があります" )
pick(   ERR_DUPLICATE_STRING_CONST,
        "%d is a duplicate string identifier.",
        "%d 文字列識別子が重複しています." )
pick(   ERR_RAW_DATA_TOO_BIG,
        "Raw data item %lu is too big. Max %u",
        "バイナリ デ－タ項目 %lu が最大値を越えています. 最大 %u" )
pick(   ERR_RAW_DATA_TOO_SMALL,
        "Raw data item %ld is too small. Min %d",
        "バイナリ デ－タ項目 %ld が小さ過ぎます. 最小 %d" )
pick(   ERR_FONT_NAME,
        "Font name must be a number.",
        "フォント名は番号でなければなりません." )
pick(   ERR_RCINCLUDE_TOO_DEEP,
        "Can't #include more than %d levels.",
        "#include のネストが %d レベル以上に達しています." )
pick(   ERR_INVALID_CPP,
        "Unknown preprocessor directive",
        "未知のプリプロセッサ疑似命令です" )
pick(   ERR_INVALID_CPP_LINE,
        "Invalid #line directive",
        "無効な#line 疑似命令です" )
pick(   ERR_UNKNOWN_MULT_OPTION,
        "Unknown option '%s'",
        "未知のオプション '%s'" )
pick(   ERR_NOT_VALID_EXE,
        "\"%s\" is not a valid EXE file.",
        "\"%s\" は有効な EXE ファイルではありません." )
pick(   ERR_NO_GANGLOAD,
        "Unable to produce fastload section.",
        "ファストロ－ド セクションが作成できません." )
pick(   ERR_CANT_FIND_FILE,
        "Can't find file \"%s\".",
        "ファイルが見つかりません \"%s\"." )
pick(   ERR_UNKNOWN_TARGET_OS,
        "Unknown target OS: '%s'.",
        "未知のタ－ゲット OS: '%s'." )
pick(   ERR_TEXT_FROM_CPP,
        "%s",
        "%s" )
pick(   ERR_NT_KEYWORD,
        "Keyword \"%s\" is only valid for Win32",
        "\"%s\" はWin32でのみ意味のあるキ－ワ－ドです" )
pick(   ERR_UNSUPPORTED,
        "Keyword \"%s\" not currently supported",
        " \"%s\" は現在サポ－トされていないキ－ワ－ドです" )
/* this is a place holder message, its text is embedded in the cannot be found */
pick(   ERR_RCSTR_NOT_FOUND,
        "",
        "" )
pick(   ERR_CANT_FIND_CHAR_FILE,
        "Error can't find character translation file \"%s\".",
        "文字変換ファイル \"%s\" が見つかりません." )
pick(   ERR_CANT_OPEN_CHAR_FILE,
        "Error opening character translation file \"%s\": %s.",
        "文字変換ファイル \"%s\"のオ－プンエラ－です: %s." )
pick(   ERR_READING_CHAR_FILE,
        "Error reading character translation file \"%s\": %s.",
        "文字変換ファイル \"%s\" の読み込みエラ－です: %s." )
pick(   ERR_BAD_CHAR_FILE,
        "\"%s\" is not a valid character translation file.",
        "\"%s\" は無効な文字変換ファイルです." )
pick(   ERR_WRONG_CHAR_FILE_VER,
        "Unable to read character translation file \"%s\": wrong version.",
        "\"%s\" 文字変換ファイルを読み込めません: バ－ジョンが異なります." )
pick(   ERR_OPT_NOT_VALID_FOR_NT,
        "Option '%s' not valid for a Win32 .res file.",
        "'%s' オプションは Win32用リソ－スファイルには無意味です." )
pick(   ERR_LSTRING_IGNORED_FOR_WINDOWS,
        "L\"...\" construct is not valid for Windows.",
        "L\"...\" 構成はWindowsでは無意味です." )
pick(   ERR_OPT_NOT_VALID_TOGETHER,
        "Options '%s' and '%s' may not be specified together.",
        "'%s' と '%s' オプションを同時に指定すべきではありません." )
pick(   ERR_ENV_VAR_NOT_FOUND,
        "Environment variable '%s' is not set.",
        "環境変数 '%s' が設定されていません." )
pick(   ERR_OPT_NOT_VALID_FOR_WINDOWS,
        "Option '%s' not valid for a Windows .res file.",
        "オプション '%s' はWindows用 .res ファイルには使用できません." )
pick(   ERR_MISSING_MENUITEM_ID,
       "MENUITEM must have ID value.",
       "MENUITEM must have ID value." )
pick(   ERR_MENUEX_POPUP_OPTIONS,
       "Id/Type/State/HelpId not allowed for MENU POPUP controls.",
       "Id/Type/State/HelpId not allowde for MENU POPUP controls." )
pick(   ERR_MENU_POPUP_OPTIONS,
       "MENUITEM options are not allowed for MENUEX POPUP controls.",
       "MENUITEM options are not allowed for MENUEX POPUP controls." )
pick(   ERR_MENUEX_NORMAL_OPTIONS,
       "Type/State not valid for MENU MENUITEM controls.",
       "Type/State not valid for MENU MENUITEM controls." )
pick(   ERR_MENU_NORMAL_OPTIONS,
       "MENUITEM options not valid for MENUEX MENUITEM controls.",
       "MENUITEM options not valid for MENUEX MENUITEM controls." )
pick(   ERR_DIALOG_HELPID,
       "HELPID not valid for DIALOG.",
       "HELPID not valid for DIALOG." )
pick(   ERR_FONT_ITALIC,
       "Font Italic setting not allowed for DIALOG.",
       "Font Italic setting not allowed for DIALOG." )
pick(   ERR_FONT_WEIGHT,
       "Font Weight setting not allowed for DIALOG.",
       "Font Weight setting not allowed for DIALOG." )
pick(   ERR_DIALOG_CONTROL_HELPID,
       "HELPID not valid for DIALOG controls.",
       "HELPID not valid for DIALOG controls." )
pick(   ERR_DATA_ELEMENTS,
       "Data Elements not valid for DIALOG controls.",
       "Data Elements not valid for DIALOG controls." )
pick(   ERR_BAD_RES_ID,
       "%ld is not a valid resource id.",
       "%ld は正しいリソースIDではありません." )
pick(   ERR_STOP_REQUESTED,
        "User interrupt detected.",
        "User interrupt detected." )
pick(   ERR_TYPE_GT_7FFF,
        "Resource type for resource \"%s\" is greater than 32767.",
        "Resource type for resource \"%s\" is greater than 32767." )
pick(   ERR_NAME_GT_7FFF,
        "Resource ID \"%s\" is greater than 32767.",
        "Resource ID \"%s\" is greater than 32767." )
pick(   ERR_UNMATCHED_QUOTE_ON_CMD_LINE,
        "Unmatched quotation mark on command line.",
        "Unmatched quotation mark on command line." )
pick(   ERR_DUPLICATE_RESOURCE_IN_FILE,
        "Duplicate resource \"%s\" found in files '%s' and '%s'.",
        "Duplicate resource \"%s\" found in files '%s' and '%s'." )
pick(   ERR_DUPLICATE_NUM_RESOURCE_IN_FILE,
        "Duplicate resource numbered %d found in files '%s' and '%s'.",
        "Duplicate resource numbered %d found in files '%s' and '%s'." )
pick(   ERR_FR_NOT_VALID_FOR_WIN,
        "'-fr' option cannot be used with Windows executables or .res files.",
        "'-fr' option cannot be used with Windows executables or .res files." )
pick(   ERR_RES_OS_MISMATCH,
        "Included RES file '%s' is compiled for a different platform.",
        "Included RES file '%s' is compiled for a different platform." )
pick(   ERR_DUPLICATE_RES,
        "Duplicate %s named '%s' found.",
        "Duplicate %s named '%s' found." )
pick(   ERR_DUPLICATE_RES_FILE,
        "Duplicate %s named '%s' found in files '%s' and '%s'.",
        "Duplicate %s named '%s' found in files '%s' and '%s'." )
pick(   ERR_DUPLICATE_STR_TABLE,
        "Duplicate string table block containing strings %d to %d found.",
        "Duplicate string table block containing strings %d to %d found." )
pick(   ERR_DUPLICATE_STR_TABLE_FILE,
        "Duplicate string table block containing strings %d to %d found in files '%s' and '%s'.",
        "Duplicate string table block containing strings %d to %d found in files '%s' and '%s'." )
pick(   ERR_RCVARIABLE_RECURSIVE,
        "Can't expand environment variable '%s' recursively.",
        "Can't expand environment variable '%s' recursively." )
pick(   ERR_NONOS2_RES_TO_OS2_EXE,
        "Trying to add a Win16 or Win32 RES file \"%s\" to an OS/2 executable \"%s\".",
        "Win32用 RESファイル \"%s\" をウィンドウズ実行ファイル \"%s\" に追加しようとしています." )
pick(   ERR_BAD_RES_TYPE,
       "%ld is not a valid type id.",
       "%ld は正しいリソースIDではありません." )
pick(   ERR_WIN16_TOO_MANY_CONTROLS,
        "Too many controls for Win16 resource '%d' > 255.",
        "Too many controls for Win16 resource '%d' > 255." )
pick(   ERR_SYMBOL_NOT_DEFINED,
        "Symbol '%s' is not defined.",
        "Can't expand environment variable '%s' recursively." )
#ifdef _STANDALONE_
pick(   USAGE_MSG_FIRST,
        "Usage: %s {options} input-filename {options} [output-filename] {options}",
        "Usage: %s {options} input-filename {options} [output-filename] {options}" )
pick(   USAGE_MSG_1,
        "Options: (/option is also accepted)",
        "Options: (/option is also accepted)" )
pick(   USAGE_MSG_2,
        "-?              - print this help message",
        "-?              - print this help message" )
pick(   USAGE_MSG_3,
        "-q              - operate quietly",
        "-q              - operate quietly" )
pick(   USAGE_MSG_4,
        "-30             - stamp file as requiring Windows 3.0",
        "-30             - stamp file as requiring Windows 3.0" )
pick(   USAGE_MSG_5,
        "-31             - stamp file as requiring Windows 3.1 (default)",
        "-31             - stamp file as requiring Windows 3.1 (default)" )
pick(   USAGE_MSG_6,
        "-DNAME=value    - behave as if #define NAME value was at top of file",
        "-DNAME=value    - behave as if #define NAME value was at top of file" )
pick(   USAGE_MSG_7,
        "-ad             - generate auto dependency information for use by wmake",
        "-ad             - generate auto dependency information for use by wmake" )
#if defined( RC_OSI ) || defined( RC_NT )
pick(   USAGE_MSG_8,
        "-bt=windows     - build a Win16 resource file",
        "-bt=windows     - build a Win16 resource file" )
#else
pick(   USAGE_MSG_8,
        "-bt=windows     - build a Win16 resource file (default)",
        "-bt=windows     - build a Win16 resource file (default)" )
#endif
#if defined( RC_NT )
pick(   USAGE_MSG_9,
        "-bt=nt          - build a Win32 resource file (default)",
        "-bt=nt          - build a Win32 resource file (default)" )
#else
pick(   USAGE_MSG_9,
        "-bt=nt          - build a Win32 resource file",
        "-bt=nt          - build a Win32 resource file" )
#endif
#if defined( RC_OS2 )
pick(   USAGE_MSG_10,
        "-bt=os2         - build an OS/2 resource file (default)",
        "-bt=os2         - build an OS/2 resource file (default)" )
#else
pick(   USAGE_MSG_10,
        "-bt=os2         - build an OS/2 resource file",
        "-bt=os2         - build an OS/2 resource file" )
#endif
pick(   USAGE_MSG_11,
        "-c=name         - set code page conversion file",
        "-c=name         - set code page conversion file" )
pick(   USAGE_MSG_12,
        "-e              - for a DLL, global memory above EMS line",
        "-e              - for a DLL, global memory above EMS line" )
pick(   USAGE_MSG_13,
        "-fo=name        - set the output resource file to name",
        "-fo=name        - set the output resource file to name" )
pick(   USAGE_MSG_14,
        "-fe=name        - set the output executable file to name",
        "-fe=name        - set the output executable file to name" )
pick(   USAGE_MSG_15,
        "-i=path         - look in path for include files",
        "-i=path         - look in path for include files" )
pick(   USAGE_MSG_16,
        "-k              - don't sort segments (same as -s0)",
        "-k              - don't sort segments (same as -s0)" )
pick(   USAGE_MSG_17,
        "-l              - program uses LIM 3.2 EMS directly",
        "-l              - program uses LIM 3.2 EMS directly" )
pick(   USAGE_MSG_18,
        "-m              - each instance of program has its own EMS bank",
        "-m              - each instance of program has its own EMS bank" )
pick(   USAGE_MSG_19,
        "-o              - preprocess only",
        "-o              - preprocess only" )
pick(   USAGE_MSG_20,
        "-p              - private DLL",
        "-p              - private DLL" )
pick(   USAGE_MSG_21,
        "-r              - only build the resource file",
        "-r              - only build the resource file" )
pick(   USAGE_MSG_22,
        "-s{0,1,2}       - segment and resource sorting method:",
        "-s{0,1,2}       - segment and resource sorting method:" )
pick(   USAGE_MSG_23,
        "                  0: no sorting, leave segments in the linker order",
        "                  0: no sorting, leave segments in the linker order" )
pick(   USAGE_MSG_24,
        "                  1: move preload segments to front and mark for fast load",
        "                  1: move preload segments to front and mark for fast load" )
pick(   USAGE_MSG_25,
        "                    if possible",
        "                    if possible" )
pick(   USAGE_MSG_26,
        "                  2: (default) move preload, data, and non-discardable segments",
        "                  2: (default) move preload, data, and non-discardable segments" )
pick(   USAGE_MSG_27,
        "                    to front and mark for fast load if possible",
        "                    to front and mark for fast load if possible" )
pick(   USAGE_MSG_28,
        "-t              - protected mode only",
        "-t              - protected mode only" )
#ifdef SCANDEBUG
pick(   USAGE_MSG_29,
        "-v              - verbose: print tokens as they are scanned",
        "-v              - verbose: print tokens as they are scanned" )
#endif
#ifdef YYDEBUG
pick(   USAGE_MSG_30,
        "-v1             - verbose: print grammar rules as they are reduced",
        "-v1             - verbose: print grammar rules as they are reduced" )
#endif
#if defined(YYDEBUG) || defined(SCANDEBUG)
pick(   USAGE_MSG_31,
        "-v2             - verbose: print both tokens and grammar rules",
        "-v2             - verbose: print both tokens and grammar rules" )
pick(   USAGE_MSG_32,
        "-v3             - verbose: print tokens as they are scanned",
        "-v3             - verbose: print tokens as they are scanned" )
#endif
pick(   USAGE_MSG_33,
        "-x              - ignore the INCLUDE environment variable",
        "-x              - ignore the INCLUDE environment variable" )
pick(   USAGE_MSG_34,
        "-zk{0,1,2,3,u8} - multi-byte characters support:",
        "-zk{0,1,2,3,u8} - multi-byte characters support:" )
pick(   USAGE_MSG_35,
        "                  0: (default) Japanese (Kanji, CP 932)",
        "                  0: (default) Japanese (Kanji, CP 932)" )
pick(   USAGE_MSG_36,
        "                  1: Chinese (Traditional, CP 950)",
        "                  1: Chinese (Traditional, CP 950)" )
pick(   USAGE_MSG_37,
        "                  2: Korean (Wansung, CP 949)",
        "                  2: Korean (Wansung, CP 949)" )
pick(   USAGE_MSG_38,
        "                  3: Chinese (Simplified, CP 936)",
        "                  3: Chinese (Simplified, CP 936)" )
pick(   USAGE_MSG_39,
        "                  u8: Unicode UTF-8",
        "                  u8: Unicode UTF-8" )
pick(   USAGE_MSG_40,
        "-zm             - output Microsoft/IBM format .res files",
        "-zm             - output Microsoft/IBM format .res files" )
pick(   USAGE_MSG_LAST,
        "-zn             - don't preprocess the file",
        "-zn             - don't preprocess the file" )
#endif
