#pmake: all build large cpu_i86 os_os2
host_CPU = i86
suffix = mtl
subdir = os2mt
production_lib = lib286\os2
define_library_include = $(plusplus_cpplib_dir)\plib.mif
!include $(plusplus_dir)\mrglib.mif
