#pmake: build flat cpu_386 os_osi os_win os_rdos os_linux os_nt os_os2
#
# cplx7r.lib -- register based 32-bit COMPLEX library -fpi
#
processor  = 387
system     = generic
model      = mf
convention = register
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
