#pmake: os_qnx cpu_386 386 intel
#
# Open Watcom Debugger makefile for QNX
#
host_os  = qnx
host_cpu = 386

sysobjs = &
        qnxinit.obj  &
        qnxlkup.obj  &
        qnxchk.obj   &
        qnxcmd.obj   &
        qnxfilio.obj &
        qnxscrn.obj

!include ../../master.mif
