#pmake: build serv remote os_rdos cpu_i86 cpu_386 tcp x86
host_cpu = 386
host_os  = rdos

target_cpu = x86
target_os  = rdos

srv = tcp
which = SERVER
remote_link = 1

!include $(trap_dir)/master.mif
