#pmake: build flat cpu_386 os_osi
processor  = 386
system     = generic
model      = ms
convention = stack
linkage    = static
mthreaded  = 1
subdir     = ms_smt

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
