#pmake: build compact cpu_i86 os_osi
#
# cplx7c.lib -- compact memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = mc
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
