#pmake: build compact cpu_i86 os_dos os_os2 os_win os_qnx
#
# cplx7c.lib -- compact memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = mc
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
