ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\ALPHA\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\ALPHA\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\ALPHA\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\BIOS\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\BIOS\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\BIOS\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\CGSUPP\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\CGSUPP\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\CGSUPP\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\CHAR\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\CHAR\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\CONIO\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\CONVERT\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\DEFWIN\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\DEFWIN\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\DEFWIN\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\DIRECT\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\ENVIRON\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\ENVIRON\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\ENVIRON\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\FILE\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\FILE\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\FPU\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\FPU\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\HANDLEIO\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\HEAP\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\HEAP\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\HEAP\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\INTEL\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\INTEL\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\KANJI\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\KANJI\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\LIBRARY\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\LIBWIN32\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MATH\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MATH\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MATH\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MBYTE\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MBYTE\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MEMORY\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MEMORY\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MISC\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MISC\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MTHREAD\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MTHREAD\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\MTHREAD\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\PPC\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\PPC\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\PROCESS\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\PROCESS\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\PROCESS\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\SEARCH\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STARTUP\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STARTUP\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STARTUP\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STREAMIO\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STREAMIO\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STREAMIO\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STRING\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STRING\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\STRING\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\TCHAR\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\TIME\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\TIME\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\TIME\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\WIN386\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\WIN386\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\WIN386\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\_DOS\a\*.asm
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\clib\_DOS\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\lib_misc\c\*.c
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\lib_misc\h\*.h
ctags -v -y -a -fe:\dev\clib\tags E:\DEV\lib_misc\h\*.inc
copy e:\dev\clib\tags e:\dev\lib_misc\tags
