// zero code is not included
pickdoserr( INVALID_FUNCTION,       "invalid function number" )
pickdoserr( FILE_NOT_FOUND,         "file not found" )
pickdoserr( PATH_NOT_FOUND,         "path not found" )
pickdoserr( TOO_MANY_OPEN_FILES,    "too many open files" )
pickdoserr( ACCESS_DENIED,          "access denied" )
pickdoserr( INVALID_HANDLE,         "invalid handle" )
pickdoserr( MEMORY_CONTROL_BLOCKS,  "memory control blocks destroyed" )
pickdoserr( INSUFFICIENT_MEMORY,    "insufficient memory" )
pickdoserr( INVALID_MEMORY_BLOCK,   "invalid memory block address" )
pickdoserr( INVALID_ENVIRONMENT,    "invalid environment" )
pickdoserr( INVALID_FORMAT,         "invalid format" )
pickdoserr( INVALID_ACCESS_CODE,    "invalid access code" )
pickdoserr( INVALID_DATA,           "invalid data" )
pickdoserr( RESERVED_ERROR_CODE,    "reserved error code" )
pickdoserr( INVALID_DRIVE,          "invalid drive was specified" )
pickdoserr( ATTEMPT_TO_REMOVE_CD,   "attempt to remove current directory" )
pickdoserr( NOT_SAME_DEVICE,        "not same device" )
pickdoserr( NO_MORE_FILES,          "no more files" )
