# makefile for os2tst01.c - test that DLL threading
# starts as expected.

clibtest_name = os2thrd

!ifdef __OS2__

srcfile = c/os2tst01.c
!include ../master.mif

!else

all : .symbolic
clean : .symbolic

!endif
