#pmake all 386 os2
host_CPU = 386
host_OS = nt
host_CG = nt
target_CPU = 386
comp386 = $(cc_dir)\nt386\wcc386d.exe
bootstrap = 1
o_dir = $(cg_dir)\intel\386\r1
i_dir = $(cg_dir)\intel\386\h;$(cg_dir)\intel\h;$(cg_dir)\h
!include ..\master.mif
