pick(   STR_ONLY_1_SPY_ALLOWED,
        "Only one spy allowed",
        "Only one spy allowed" )
pick(   STR_NO_CUR_SELECTION,
        "No Current Selection!",
        "No Current Selection!" )
pick(   STR_NONE,
        "<none>",
        "<none>" )
pick(   STR_CHILD_ID,
        ", Child ID = %d (0x%0*x)",
        ", Child ID = %d (0x%0*x)" )
pick(   STR_SPY_ON,
        "&Continue Spying",
        "&Continue Spying" )
pick(   STR_SPY_OFF,
        "Stop Spying &Temporarily",
        "Stop Spying &Temporarily" )
pick(   STR_APP_NAME,
        "Open Watcom Spy",
        "Open Watcom Spy" )
pick(   STR_HEADINGS_NT,
            "Message Name              hWnd     MsgID    wParam   lParam  ",
            "Message Name              hWnd     MsgID    wParam   lParam  " )
pick(   STR_HEADING_UNDERLINE_NT,
            "===========================================================",
            "===========================================================" )
pick(   STR_HEADINGS_WIN,
            "Message Name              hWnd MsgID wParam lParam",
            "Message Name              hWnd MsgID wParam lParam" )
pick(   STR_HEADING_UNDERLINE_WIN,
            "==================================================",
            "==================================================" )
pick(   STR_MULTIPLE_WIN_TITLE,
        "%s - Multiple Windows",
        "%s - Multiple Windows" )
pick(   STR_HEADING_1,
        "Message Name",
        "Message Name" )
pick(   STR_HEADING_2,
        "hWnd",
        "hWnd" )
pick(   STR_HEADING_3,
        "MsgID",
        "MsgID" )
pick(   STR_HEADING_4,
        "wParam",
        "wParam" )
pick(   STR_HEADING_5,
        "lParam",
        "lParam" )
pick(   STR_1_WIN_TITLE,
        "%s - hWnd %0*x",
        "%s - hWnd %0*x" )
pick(   STR_1_NAMED_WIN_TITLE,
        "%s - hWnd %0*x (%s)",
        "%s - hWnd %0*x (%s)" )
pick(   STR_ABOUT_NAME,
        "Open Watcom Spy for Windows" STR_BITNESS,
        "Open Watcom Spy for Windows" STR_BITNESS )
pick(   STR_ABOUT_VERSION,
        banner1p2( _SPY_VERSION_ ),
        banner1p2( _SPY_VERSION_ ) )
pick(   STR_ABOUT_TITLE,
        "About Open Watcom Spy",
        "About Open Watcom Spy" )
pick(   STR_ALL_WIN_TITLE,
        "%s - All Windows",
        "%s - All Windows" )

// used to format the coordinates and dimensions of a window
pick(   STR_DIM_COORD_FMT,
        "(%d,%d),(%d,%d): %d by %d",
        "(%d,%d),(%d,%d): %d by %d" )

pick(   STR_PEEK_AT_WIN,
        "Peek At Window",
        "Peek At Window" )
pick(   STR_SELECT_WIN,
        "Select Window",
        "Select Window" )
pick(   STR_WM_USER_PLUS,
        "WM_USER+%d",
        "WM_USER+%d" )
pick(   STR_UNKNOWN_MSG,
        "UNKNOWN MSG: %04x",
        "UNKNOWN MSG: %04x" )
pick(   STR_MSGS_TO_WATCH,
        "Messages To Watch",
        "Messages To Watch" )
pick(   STR_MSGS_TO_STOP,
        "Messages To Stop On",
        "Messages To Stop On" )
pick(   STR_DESTROYED,
        "%s (destroyed)",
        "%s (destroyed)" )
pick(   STR_WIN_DOESNT_EXIST,
        "This window no longer exists.",
        "This window no longer exists." )
pick(   STR_MSG_RANGE_STR,
        "Messages %s to %s",
        "Messages %s to %s" )
pick(   STR_SPYING_STOPPED,
        "Spying stopped because message %s was encountered",
        "Spying stopped because message %s was encountered" )

pick(   STR_EMPTY_STATUS,
        " ",
        " " )

pick(   STR_HINT_SAVE,
        "Save information in the event list to a file.",
        "Save information in the event list to a file." )

pick(   STR_HINT_SAVE_AS,
        "Save information in the event list to a file.",
        "Save information in the event list to a file." )

pick(   STR_HINT_LOG,
        "Start/Stop logging monitored events to a file.",
        "Start/Stop logging monitored events to a file." )

pick(   STR_HINT_PAUSE_LOG,
        "Pause/Resume logging monitored events to a file.",
        "Pause/Resume logging monitored events to a file." )

pick(   STR_HINT_CONFIG_LOG,
        "Configure the behavior of the logging function.",
        "Configure the behavior of the logging function." )

pick(   STR_HINT_SET_FONT,
        "Set the font for the Spy windows.",
        "Set the font for the Spy windows." )

pick(   STR_HINT_TOP,
        "Ensure Spy is never covered by other windows.",
        "Ensure Spy is never covered by other windows." )

pick(   STR_HINT_EXIT,
        "Exit Spy.",
        "Exit Spy." )

pick(   STR_HINT_CLEAR_MESSAGES,
        "Erase the information in the event list.",
        "Erase the information in the event list." )

pick(   STR_HINT_AUTO_SCROLL,
        "Scroll the display to show the newest events.",
        "Scroll the display to show the newest events." )

pick(   STR_HINT_MARK,
        "Put text in the event list.",
        "Put text in the event list." )

pick(   STR_HINT_WINDOW,
        "Select a single window to spy on.",
        "Select a single window to spy on." )

pick(   STR_HINT_ADD_WINDOW,
        "Select a window to spy on in addition to those already selected.",
        "Select a window to spy on in addition to those already selected." )

pick(   STR_HINT_ALL_WINDOWS,
        "Spy on all windows in the system.",
        "Spy on all windows in the system." )

pick(   STR_HINT_OFFON,
        "Pause/resume spying.",
        "Pause/resume spying." )

pick(   STR_HINT_STOP,
        "Stop spying.",
        "Stop spying." )

pick(   STR_HINT_PEEK_WINDOW,
        "Show style information about windows.",
        "Show style information about windows." )

pick(   STR_HINT_SHOW_SELECTED_WINDOWS,
        "Show a list of all windows in the system.",
        "Show a list of all windows in the system." )

pick(   STR_HINT_MESSAGES_WATCH,
        "Select messages to report on.",
        "Select messages to report on." )

pick(   STR_HINT_MESSAGES_STOP,
        "Select messages to stop on.",
        "Select messages to stop on." )

pick(   STR_HINT_MESSAGES_ASCFG,
        "Save the message confiratation on exit.",
        "Save the message confiratation on exit." )

pick(   STR_HINT_MESSAGES_SAVE,
        "Save the messages selected to watch and stop on.",
        "Save the messages selected to watch and stop on." )

pick(   STR_HINT_MESSAGES_LOAD,
        "Load a previously saved message configuration.",
        "Load a previously saved message configuration." )

pick(   STR_HINT_ABOUT,
        "Display program information.",
        "Display program information." )

pick(   STR_HINT_SHOW_TOOLBAR,
        "Display/hide the toolbar.",
        "Display/hide the toolbar." )

pick(   STR_HINT_SHOW_HELP,
        "Display/hide the hint bar.",
        "Display/hide the hint bar." )

pick(   STR_MESSAGE,
        "Message: %s",
        "Message: %s" )

pick(   STR_HINT_HELP_CONTENTS,
        "List Open Watcom Spy help topics.",
        "List Open Watcom Spy help topics." )

pick(   STR_HINT_HELP_SRCH,
        "Search for help on a specific topic.",
        "Search for help on a specific topic." )

pick(   STR_HINT_HELP_ON_HELP,
        "Display information on how to use help.",
        "Display information on how to use help." )

pick(   STR_TIP_ANOTHER_WINDOW,
        "Add Window",
        "Add Window" )
pick(   STR_TIP_STOP,
        "Done Spying",
        "Done Spying" )
pick(   STR_TIP_PEEK_WINDOW,
        "Peek At Window",
        "Peek At Window" )
pick(   STR_TIP_MARK,
        "Mark",
        "Mark" )
pick(   STR_TIP_CLEAR_MESSAGES,
        "Clear Message List",
        "Clear Message List" )
pick(   STR_TIP_SHOW_SELECTED_WINDOWS,
        "Show Selected Windows",
        "Show Selected Windows" )
pick(   STR_TIP_MESSAGES_WATCH,
        "Messages to Watch",
        "Messages to Watch" )
pick(   STR_TIP_MESSAGES_STOP,
        "Messages to Stop On",
        "Messages to Stop On" )
pick(   STR_TIP_OFFON,
        "Stop Spying Temporarily",
        "Stop Spying Temporarily" )

pick(   STR_IMC_TITLE,
        "Individual Message Control - Page %d of %d",
        "Individual Message Control - Page %d of %d" )
