#pmake: build trap remote os_win cpu_i86 cpu_386 nmp x86
host_CPU = i86
host_OS = win

os = win
srv = nmp
cpu = x86
which = TRAP
type  = remote_link

extra_objs = nmpdos.obj

!include $(trap_dir)/master.mif
