#pmake: build trap remote os_win cpu_i86 cpu_386 nmp x86
host_cpu = i86
host_os  = win

os = win
srv = nmp
cpu = x86
which = TRAP
remote_link = 1

extra_objs = nmpdos.obj

!include $(trap_dir)/master.mif
