#pmake: build os_win cpu_i86
#
# Open Watcom Debugger makefile for Windows
#

host_os=win
host_cpu=i86

sysobjs =   &
    autoenv.obj &
    wininit.obj &
    winchk.obj &
    wincmd.obj &
    winfilio.obj &
    winlkup.obj &
    winscrn.obj

!include ../../master.mif
