#pmake: build huge cpu_i86 os_osi
#
# cplx7h.lib -- huge memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = mh
linkage    = static
define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
