#pmake: build huge cpu_i86 os_dos os_os2 os_win os_qnx
#
# cplx7h.lib -- huge memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = mh
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
