#pmake: all build flat cpu_386 os_osi
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
suffix = 3r
target_system = generic
production_lib = lib386
define_library_include = $(plusplus_runtime_dir)\plib.mif
define_target_include = $(plusplus_dir)\lib32$(suffix).mif
!include $(plusplus_dir)\mklib.mif
