#pmake: build small cpu_i86 os_win
processor  = 086
system     = windows
model      = ms
linkage    = static
subdir     = ms

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
