#pmake: os_os2 cpu_i86
#
# Open Watcom Debugger makefile for OS/2
#

host_OS  = os2
host_CPU = i86

syshdir  =

#add '16' suffix to avoid conflicts
tail_char_os2 = 16

sysobjs =            &
        os2init.obj  &
        os2lkup.obj  &
        os2chk.obj   &
        os2cmd.obj   &
        os2filio.obj &
        os2scrn.obj

!include ../../master.mif
