#pmake: nobuild nomodel cpu_axp os_nt
#
# iost -- 32-bit axp CONTAINER library
#
processor    = axp
system       = winnt
linkage      = dynamic
mthreaded    = 1
export_only  = 1

!include $(cpplib_dir)/contain/contain.mif
