#pmake: all build small cpu_i86 os_osi
#
# plibs -- 16-bit small memory-model PLIB
#
suffix = s
target_system = generic
target_lib = $(prefix)$(suffix).lib
production_lib = lib286
define_library_include = $(plusplus_runtime_dir)\plib.mif
define_target_include = $(plusplus_dir)\lib16$(suffix).mif
!include $(plusplus_dir)\mklib.mif
