#pmake: build medium cpu_i86 os_win
#
# contm.lib -- medium memory-model CONTAINER library for Windows
#
processor  = 086
system     = windows
model      = mm
linkage    = static
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
