if exist %tag_dir%\tags del %tag_dir%\tags
ctags -aeqdstf %tag_dir%\tags %dev_dir%\owl\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\owl\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cc\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cc\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\plusplus\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\plusplus\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\intel\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\intel\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\intel\386\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\intel\386\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\intel\i86\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\intel\i86\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\risc\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\risc\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\risc\axp\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\risc\axp\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\risc\ppc\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\risc\ppc\c\*.c
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\risc\sparc\h\*.h
ctags -aeqdstf %tag_dir%\tags %dev_dir%\cg\risc\sparc\c\*.c
