#pmake: build flat cpu_386 os_os2
#
# strg3r.lib -- register based 32-bit STRING library
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
fs_registration = yes

!include $(cpplib_dir)/string/string.mif
