#pmake: build serv remote os_linux cpu_386 tcp x86

tree_depth = 4

host_os  = linux
host_cpu = 386

target_cpu = x86

srv   = tcp
which = SERVER
remote_link = 1

!include $(trap_dir)/lcl/linux/linux.mif
!include $(trap_dir)/lcl/lcl.mif
!include $(trap_dir)/master.mif
