#pmake: build large cpu_i86 os_osi
#
# cplxl.lib -- large memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = ml
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
