

.extensions:
.extensions: .exe .cpp

exes =flush.exe lshchar.exe  lshstr.exe   lshint.exe lshfloat.exe lshptr.exe &
      put.exe   seekppos.exe seekpoff.exe tellp.exe  write.exe    opfx.exe   &
      lshman.exe conostrm.exe  conbuf.exe destruct.exe eqostrm.exe           &
      lshstrbu.exe eqstrmbu.exe eqostrm.exe

all : $(exes) .symbolic

.cpp.exe :
    wcl $[@
