#pmake: build trap remote os_os2 cpu_i86 cpu_386 net x86
host_cpu = 386
host_OS = os2

os  = os2v2
srv = net
cpu = x86
which = TRAP
type  = remote_link

extra_libs = $(os2386)

!include $(trap_dir)/master.mif
