#pmake: build trap remote os_os2 cpu_i86 cpu_386 net x86

host_os  = os2
host_cpu = 386

target_cpu = x86
target_os  = os2v2

srv   = net
which = TRAP
remote_link = 1

!include $(trap_dir)/master.mif
