#pmake: nomodel cpu_axp os_nt
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static
subdir       = _s

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
