#pmake: build large cpu_i86 os_osi os_os2
#
# strgl.lib -- large memory-model STRING library
#
processor  = 086
system     = generic
model      = ml
linkage    = static

!include $(cpplib_dir)/string/string.mif
