type = ui
os = dos
build_target = dos
sys=dos
compiler = comp286
model=m
nodebug=
wreslib=wresm

target : sample.exe .SYMBOLIC
    @%null

samp2 : samp2.exe  .SYMBOLIC
    @%null

!include ..\makefile
