#pmake: build trap remote os_win cpu_i86 cpu_386 nov x86
host_cpu = i86
host_os = win

os = win
srv = nov
cpu = x86
which = TRAP
remote_link = 1

extra_objs = novdos.obj

!include $(trap_dir)/master.mif
