#pmake: build small cpu_i86 os_osi
#
# cplxs.lib -- small memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = ms
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
