#pmake: build small cpu_i86 os_dos os_os2 os_win os_qnx
#
# cplxs.lib -- small memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = ms
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
