#pmake: build large cpu_i86 os_win
#
# cplxl.lib -- large memory-model COMPLEX library fpc for Windows
#
processor  = 086
system     = windows
model      = ml
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
