#pmake: build flat cpu_386 os_nt
#
# cont3s.lib -- stack based 32-bit CONTAINER library
#
processor  = 386
system     = winnt
model      = mf
convention = stack
linkage    = static
fs_registration = yes
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
