#pmake/150: nobuild debug flat register 32bit calls os2 iX86 rtdll os_os2 cpu_386 cpplib

component  = plib
processor  = 386
model      = mf
system     = os2
convention = register

lib_debug = 1

!include $(rtdll_dir)/master.mif
