#pmake: build small cpu_i86 os_win
#
# plibs -- 16-bit small memory-model PLIB for Windows
#
processor  = 086
system     = windows
model      = ms
linkage    = static
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
