#pmake: nobuild debug flat cpu_386 os_nt dynamic
#
# plib3r -- 32-bit 3r MT PLIB, PLBX
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = dynamic
export_only=1
mthreaded  = 1
fs_registration = yes
lib_debug = 1

!include $(cpplib_dir)/runtime/runtime.mif
