#
# create NT version of ALARM
#
CFLAGS = -oaxt -d1 -w4 -bt=nt
CC = wcc386
NAME = shootgal

LNK = $(name).lnk

OBJS = $(name).obj

$(name).exe : $(OBJS) $(name).res $(LNK)
    wlink @$(LNK)
    wrc -bt=nt $(name).res

$(name).res : $(name).rc bolt.ico timer.ico gun.cur keyboard.ico mouse.ico &
                        scroll.ico $(name).ico target.bmp
    wrc -r -bt=nt $(name).rc

$(LNK) : makefile.nt
    %create $(LNK)
    @%append $(LNK) debug all
    @%append $(LNK) system nt_win
    @%append $(LNK) option stack=8k
    @%append $(LNK) name $(name)
    @for %i in ($(OBJS)) do @%append $(LNK) file %i

$(name).obj : $(name).c $(name).h
        $(CC) $(CFLAGS) $[*

clean: .symbolic
    @erase *.obj
    @erase *.err
    @erase *.exe
    @erase *.lnk
    @erase *.res
    @erase *.rex
