pick(    MSG_FILE_REC_NAME_0,   "file %s: " ,
                "ファイル %s: " )
pick(    MSG_FILE_REC_NAME_1,   "(%s): " ,
                "(%s): " )
pick(    MSG_FILE_REC_NAME_2,   "file %1(%2): " ,
                "ファイル %1(%2): " )
pick(    MSG_FILE_REC_NAME_3,   "record %d: " ,
                "レコード %d: " )
pick(    MSG_FILE_REC_NAME_4,   "file %s, record %d: " ,
                "ファイル %s, レコード %d: " )
pick(    MSG_FILE_REC_NAME_5,   "(%s), record %d: " ,
                "(%s), レコード %d: " )
pick(    MSG_FILE_REC_NAME_6,   "file %1(%2), record %d: " ,
                "ファイル %1(%2), レコード %d: " )
pick(    MSG_ERROR,     "Error! E%d: " ,
                "エラー(%d): " )
pick(    MSG_WARNING,       "Warning! W%d: " ,
                "警告(%d): " )
pick(    MSG_SYS_BLK,       "system block %s: " ,
                "システム・ブロック %s: " )
pick(    MSG_ENVIRON,       "environment %s: " ,
                "環境 %s: " )
pick(    MSG_LINE,      "line(%d): " ,
                "行(%d): " )
pick(    MSG_FORMAT_NOT_DECIDED, "format not decided" ,
                "フォーマットが決定していません" )
pick(    MSG_NO_LEADER_ON_PASS_2, "no leader found on pass 2" ,
                "パス２でリーダーが見つかりません" )
pick(    MSG_IOERRLIST_0,   "" ,
                "" )
pick(    MSG_IOERRLIST_1,   "" ,
                "" )
pick(    MSG_IOERRLIST_2,   "file not found" ,
                "ファイルが見つかりません" )
pick(    MSG_IOERRLIST_3,   "path not found" ,
                "パスが見つかりません" )
pick(    MSG_IOERRLIST_4,   "too many open files" ,
                "オープン・ファイルが多すぎます" )
pick(    MSG_IOERRLIST_5,   "access denied" ,
                "アクセスが拒否されました" )
pick(    MSG_IOERRLIST_6,   "invalid handle",
                "ハンドルが無効です" )
pick(    MSG_IOERRLIST_7,   "disk full" ,
                "ディスクが一杯です" )
pick(    MSG_PRESS_KEY,     "press any key to continue" ,
                "続行するために何かキーを押して下さい" )
pick(    MSG_FILE_TYPES_0,  "OS/2" ,
                "OS/2" )
pick(    MSG_FILE_TYPES_1,  "OS/2 linear" ,
                "OS/2 リニア" )
pick(    MSG_FILE_TYPES_2,  "OS/2 linear extended" ,
                "OS/2 リニア拡張" )
pick(    MSG_FILE_TYPES_3,  "Windows" ,
                "Windows" )
pick(    MSG_FILE_TYPES_4,  "PE" ,
                "PE" )
pick(    MSG_FILE_TYPES_5,  "DOS" ,
                "DOS" )
pick(    MSG_FILE_TYPES_6,  "DOS .COM" ,
                "DOS .COM" )
pick(    MSG_FILE_TYPES_7,  "DOS overlayed" ,
                "DOS オーバレイ" )
pick(    MSG_FILE_TYPES_8,  "Novell Netware" ,
                "Novell Netware" )
pick(    MSG_FILE_TYPES_9,  "QNX" ,
                "QNX" )
pick(    MSG_FILE_TYPES_10, "Phar Lap simple" ,
                "Phar Lap シンプル" )
pick(    MSG_FILE_TYPES_11, "Phar Lap extended" ,
                "Phar Lap 拡張" )
pick(    MSG_FILE_TYPES_12, "Phar Lap relocatable" ,
                "Phar Lap リロケータブル" )
pick(    MSG_FILE_TYPES_13, "Phar Lap segmented" ,
                "Phar Lap セグメント" )
pick(    MSG_FILE_TYPES_14, "QNX 386" ,
                "QNX 386" )
pick(    MSG_FILE_TYPES_15, "ELF" ,
                "ELF" )
pick(    MSG_FILE_TYPES_16, "Windows VxD" ,
                "Windows VxD" )
pick(    MSG_FILE_TYPES_17, "DOS/16M" ,
                "DOS/16M" )
pick(    MSG_CREATE_TYPE_DLL,   "dynamic link library" ,
                "ダイナミック・リンク・ライブラリ" )
pick(    MSG_CREATE_TYPE_EXE,   "executable" ,
                "実行可能" )
pick(    MSG_IS_A_EXE,      "This is %f" ,
                "これは %f です" )

pick(    MSG_MAP_BOX_GROUP, "|   Groups   |" ,
                "|  グループ  |" )
pick(    MSG_MAP_TITLE_GROUP_0, "Group                           Address              Size" ,
                "グループ                        アドレス             サイズ" )
pick(    MSG_MAP_TITLE_GROUP_1, "=====                           =======              ====" ,
                "=====                           =======              ====" )
pick(    MSG_MAP_BOX_ABS_SEG,   "|   Absolute Segments   |" ,
                "|     絶対セグメント    |" )
pick(    MSG_MAP_TITLE_ABS_SEG_0,   "Segment                 Class           Address              Size" ,
                    "セグメント              クラス          アドレス            サイズ" )
pick(    MSG_MAP_TITLE_ABS_SEG_1,       "=======                 =====           =======              ====" ,
                    "==========              ======          ========             ======" )
pick(    MSG_MAP_BOX_SEGMENTS,          "|   Segments   |" ,
                    "|  セグメント  |" )
pick(    MSG_MAP_TITLE_SEGMENTS_0,      "Segment                Class          Group          Address         Size" ,
                    "セグメント             クラス         グループ      アドレス        サイズ" )
pick(    MSG_MAP_TITLE_SEGMENTS_1,      "=======                =====          =====          =======         ====" ,
                    "=========              ======         =========      ========        ======" )
pick(    MSG_MAP_BOX_MEMORY_MAP,        "|   Memory Map   |" ,
                    "| メモリ・マップ |" )
pick(    MSG_MAP_UNREF_SYM,             "* = unreferenced symbol" ,
                    "* = 参照されないシンボル" )
pick(    MSG_MAP_REF_LOCAL_SYM,         "+ = symbol only referenced locally" ,
                    "+ = シンボルはローカルでの参照のみです" )
pick(    MSG_MAP_TITLE_MEMORY_MAP_0,    "Address        Symbol" ,
                    "アドレス       シンボル" )
pick(    MSG_MAP_TITLE_MEMORY_MAP_1,    "=======        ======" ,
                    "========       ========" )
pick(    MSG_MAP_BOX_OVERLAY_VECTOR,    "|   Overlay Vectors   |" ,
                    "| オーバレイ・ベクタ  |" )
pick(    MSG_MAP_BOX_COMMUNAL,          "|   Communal Symbols   |" ,
                    "|     共有シンボル     |" )
pick(    MSG_MAP_TITLE_COMMUNAL_0,      "Address        Symbol" ,
                    "アドレス       シンボル" )
pick(    MSG_MAP_TITLE_COMMUNAL_1,      "=======        ======" ,
                    "========       ========" )
pick(    MSG_MAP_BOX_MOD_SEG,           "|   Module Segments   |" ,
                    "|モジュール セグメント|" )
pick(    MSG_MAP_ABS_ADDR,              "* = absolute address" ,
                    "* = 絶対アドレス" )
pick(    MSG_MAP_32BIT_SEG,             "! = 32-bit segment" ,
                    "! = 32ビット・セグメント" )
pick(    MSG_MAP_TITLE_MOD_SEG_0,       "Module          Segment               Class           Address         Size" ,
                    "モジュール      セグメント            クラス         アドレス        サイズ" )
pick(    MSG_MAP_TITLE_MOD_SEG_1,       "======          =======               =====           =======         ====" ,
                    "==========      ==========            ======          ========        ======" )
pick(    MSG_MAP_BOX_TRACE_SYM,         "|   Traced Symbols   |" ,
                    "|  トレース シンボル |" )
pick(    MSG_MAP_BOX_IMP_SYM,           "|   Imported Symbols   |" ,
                    "|  インポート シンボル |" )
pick(    MSG_MAP_TITLE_IMP_SYM_0,       "Symbol" ,
                    "シンボル" )
pick(    MSG_MAP_TITLE_IMP_SYM_1,       "======" ,
                    "========" )
pick(    MSG_MAP_TITLE_IMP_SYM_2,       "Symbol                              Module" ,
                    "シンボル                            モジュール" )
pick(    MSG_MAP_TITLE_IMP_SYM_3,       "======                              ======" ,
                    "========                            ===========" )
pick(    MSG_MAP_BOX_UNRES_REF,         "|   Unresolved References   |" ,
                    "|        未解決な参照       |" )
pick(    MSG_MAP_TITLE_UNRES_REF_0, "Undefined Symbol                Referenced by" ,
                    "未定義シンボル                  参照モジュール" )
pick(    MSG_MAP_TITLE_UNRES_REF_1,     "================                =============" ,
                    "==============                  ===============" )
pick(    MSG_MAP_BOX_LIB_USED,          "|   Libraries Used   |" ,
                    "|   使用ライブラリ   |" )
pick(    MSG_MAP_BOX_LINKER_STAT,       "|   Linker Statistics   |" ,
                    "|     リンカー統計      |" )
pick(    MSG_MAP_STACK_SIZE,            "Stack size:" ,
                    "スタック サイズ:" )
pick(    MSG_MAP_MEM_SIZE,              "Memory size:" ,
                    "メモリ サイズ:" )
pick(    MSG_MAP_OVL_SIZE,              "Overlay area size:" ,
                    "オーバレイ サイズ:" )
pick(    MSG_MAP_ENTRY_PT_ADDR,     "Entry point address: %a" ,
                    "エントリアドレス: %a" )
pick(    MSG_MAP_LINK_TIME,             "Link time: %s" ,
                    "リンク時間: %s" )
pick(    MSG_MAP_COMDAT,                "c = initialized communal data" ,
                    "c = 初期化された共有データ" )
pick(    MSG_MAP_SYM_STATIC,        "s = symbol is static" ,
                    "s = シンボルはスタティックです" )
pick(    MSG_MAP_DEFINING_MODULE,   "Module: %s(%s)" ,
                    "モジュール: %s(%s)" )


/*
 *  General help screen: max 52 lines (from 0 to 51).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_GENERAL_HELP_0,    "usage: wlink {directive}" ,
                "使用方法: wlink {directive}" )
pick(    MSG_GENERAL_HELP_1,    "\ncommands valid for all executable formats:\n" ,
                "\n全ての実行可能フォーマットで有効なコマンド:\n" )
pick(    MSG_GENERAL_HELP_2,    "directive  ::= \"File\"        obj_spec{\",\"obj_spec}" ,
                "directive  ::= \"File\"        obj_spec{\",\"obj_spec}" )
pick(    MSG_GENERAL_HELP_3,    "            | \"Name\"         exe_file" ,
                "            | \"Name\"         EXEファイル" )
pick(    MSG_GENERAL_HELP_4,    "            | \"OPtion\"       option{\",\"option}" ,
                "            | \"OPtion\"       option{\",\"option}" )
pick(    MSG_GENERAL_HELP_5,    "            | \"Library\"      library_file{\",\"library_file}" ,
                "            | \"Library\"      ライブラリファイル{\",\"library_file}" )
pick(    MSG_GENERAL_HELP_6,    "            | \"OPTLIB\"       library_file{\",\"library_file}" ,
                "            | \"OPTLIB\"       ライブラリファイル{\",\"ライブラリファイル}" )
pick(    MSG_GENERAL_HELP_7,    "            | \"Path\"         path_name{\";\"path_name}" ,
                "            | \"Path\"         パス名{\";\"パス名}" )
pick(    MSG_GENERAL_HELP_8,    "            | \"LIBPath\"      path_name{\";\"path_name}" ,
                "            | \"LIBPath\"      パス名{\";\"パス名}" )
pick(    MSG_GENERAL_HELP_9,    "            | \"LIBFile\"      obj_file{\",\"obj_file}" ,
                "            | \"LIBFile\"      オブジェクトファイル{\",\"オブジェクトファイル}" )
pick(    MSG_GENERAL_HELP_10,   "            | \"Debug\"        dbtype [dblist] | dblist" ,
                "            | \"Debug\"        dbtype [dblist] | dblist" )
pick(    MSG_GENERAL_HELP_11,   "            | \"MODTrace\"     module_name{\",\"module_name}" ,
                "            | \"MODTrace\"     モジュール名{\",\"モジュール名}" )
pick(    MSG_GENERAL_HELP_12,   "            | \"SYMTrace\"     symbol_name{\",\"symbol_name}" ,
                "            | \"SYMTrace\"     シンボル名{\",\"シンボル名}" )
pick(    MSG_GENERAL_HELP_13,   "            | \"SYStem\"       system_name" ,
                "            | \"SYStem\"       システム名" )
pick(    MSG_GENERAL_HELP_14,   "            | \"SYStem Begin\" system_name directive {directive} \"End\"" ,
                "            | \"SYStem Begin\" システム名 directive {directive} \"End\"" )
pick(    MSG_GENERAL_HELP_15,   "            | \"FORMat\"       form" ,
                "            | \"FORMat\"       form" )
pick(    MSG_GENERAL_HELP_16,   "            | \"REFerence\"    symbol_name{\",\"symbol_name}" ,
                "            | \"REFerence\"    シンボル名{\",\"シンボル名}" )
pick(    MSG_GENERAL_HELP_17,   "            | \"@\"            directive_file" ,
                "            | \"@\"            directive_file" )
pick(    MSG_GENERAL_HELP_18,   "            | \"#\"            comment" ,
                "            | \"#\"            コメント" )

pick(    MSG_GENERAL_HELP_20,   "\ncommands valid for all executable formats (continued):\n" ,
                "\n全ての実行可能フォーマットで有効なコマンド(続き):\n" )
pick(    MSG_GENERAL_HELP_21,   "            | \"Alias\"        alias\"=\"symbol_name{\",\"alias\"=\"symbol_name}" ,
                "            | \"Alias\"        エイリアス\"=\"シンボル名{\",\"エイリアス\"=\"シンボル名}" )
pick(    MSG_GENERAL_HELP_22,   "            | \"DISAble\"      msg_num{\",\"msg_num}" ,
                                "            | \"DISAble\"      メッセージ番号{\",\"メッセージ番号}")
pick(    MSG_GENERAL_HELP_23,   "            | \"SOrt\"         [\"GLobal\"] [\"ALPhabetical\"]" ,
                                "            | \"SOrt\"         [\"GLobal\"] [\"ALPhabetical\"]")
pick(    MSG_GENERAL_HELP_24,   "            | \"LANGuage\"     (\"JApanese\" | \"CHinese\" | \"KOrean\")",
                "            | \"LANGuage\"     (\"JApanese\" | \"CHinese\" | \"KOrean\")")
pick(    MSG_GENERAL_HELP_25,   "            | \"STARTLINK\"",
                "            | \"STARTLINK\"")
pick(    MSG_GENERAL_HELP_26,   "            | \"ENDLINK\"",
                "            | \"ENDLINK\"")
pick(    MSG_GENERAL_HELP_27,   "            | \"MODFile\"      obj_file{\",\"obj_file}" ,
                "            | \"MODFile\"      オブジェクトファイル{\",\"オブジェクトファイル}" )
pick(    MSG_GENERAL_HELP_28,   "obj_spec  ::= obj_file[\"(\"obj_member\")\"] | library_file[\"(\"lib_member\")\"]" ,
                                "obj_spec  ::= オブジェクトファイル[\"(\"オブジェクトメンバー\")\"] | ライブラリファイル[\"(\"ライブラリメンバー\")\"]")
pick(    MSG_GENERAL_HELP_29,   "dbtype    ::= \"Watcom\" | \"Dwarf\" | \"Codeview\"",
                                "dbtype    ::= \"Watcom\" | \"Dwarf\" | \"Codeview\"")
pick(    MSG_GENERAL_HELP_30,   "dblist    ::= dboption{\",\"dboption}" ,
                                "dblist    ::= dboption{\",\"dboption}")
pick(    MSG_GENERAL_HELP_31,   "dboption  ::= \"LInes\" | \"Types\" | \"LOcals\" | \"All\"" ,
                                "dboption  ::= \"LInes\" | \"Types\" | \"LOcals\" | \"All\"")
pick(    MSG_GENERAL_HELP_32,   "option    ::= \"ARTificial\" | \"[NO]CAChe\" | \"[NO]Caseexact\" | \"CVPack\"",
                "option    ::= \"ARTificial\" | \"[NO]CAChe\" | \"[NO]Caseexact\" | \"CVPack\"" )
pick(    MSG_GENERAL_HELP_33,   "            | \"Dosseg\" | \"ELiminate\" | \"[NO]FARcalls\"",
                "            | \"Dosseg\" | \"ELiminate\" | \"[NO]FARcalls\"")
pick(    MSG_GENERAL_HELP_34,   "            | \"INCremental[=file_name]\" | \"MANGlednames\"",
                "            | \"INCremental[=ファイル名]\" | \"MANGlednames\"")
pick(    MSG_GENERAL_HELP_35,   "            | \"Map\"[\"=\"map_file] | \"MAXErrors=\"n | \"NAMELen=\"n",
                "            | \"Map\"[\"=\"マップファイル] | \"MAXErrors=\"n | \"NAMELen=\"n" )
pick(    MSG_GENERAL_HELP_36,   "            | \"NODefaultlibs\" | \"NOEXTension\" | \"OSName=\"string | \"Quiet\"",
                "            | \"NODefaultlibs\" | \"NOEXTension\" | \"OSName=\"文字列 | \"Quiet\"" )
pick(    MSG_GENERAL_HELP_37,   "            | \"[NO]REDefsok\" | \"STack\"=n | \"START=\"symbol_name | \"STATics\"",
                "            | \"[NO]REDefsok\" | \"STack\"=n | \"START=\"シンボル名 | \"STATics\"" )
pick(    MSG_GENERAL_HELP_38,   "            | \"SYMFile\"[\"=\"symbol_file], | \"[NO]Undefsok\" | \"Verbose\"",
                "            | \"SYMFile\"[\"=\"シンボルファイル], | \"[NO]Undefsok\" | \"Verbose\"" )
pick(    MSG_GENERAL_HELP_39,   "            | \"VFRemoval\"" ,
                "            | \"VFRemoval\"" )
                
/*
 *  Dos help screen: max 16 lines (from 0 to 15).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_DOS_HELP_0,    "\ncommands valid for the MS-DOS executable format only:\n" ,
                "\nMS-DOS 実行可能形式に対してのみ有効なコマンド:\n" )
pick(    MSG_DOS_HELP_1,    "form      ::= \"Dos\" [\"COM\"]" ,
                "form      ::= \"Dos\" [\"COM\"]" )
pick(    MSG_DOS_HELP_2,    "directive ::= \"NEWsegment\"" ,
                "directive ::+ \"NEWsegment\"" )                
pick(    MSG_DOS_HELP_3,    "option    ::= \"FULLHeader\" | \"PACKCode=\"n | \"PACKData=\"n" ,
                "option    ::= \"FULLHeader\" | \"PACKCode=\"n | \"PACKData=\"n" )

/*
 *  OS2 help screen: max 32 lines (from 0 to 31).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_OS2_HELP_0,    "\ncommands valid for the OS/2 and DOS/4G executable formats only:\n" ,
                "\nOS/2実行可能形式に対してのみ有効なコマンド:\n" )
pick(    MSG_OS2_HELP_1,    "form      ::= \"OS2\" [\"FLat\"|\"LE\"|\"LX\"] [\"PHYSdevice\" | \"VIRTdevice\"" ,
                "form      ::= \"OS2\" [\"FLat\"|\"LE\"|\"LX\"] [\"PHYSdevice\" | \"VIRTdevice\"" )
pick(    MSG_OS2_HELP_2,    "            | [\"DLl\"[\"INITGlobal\"|\"INITInstance\" [\"TERMInstance\"|\"TERMGlobal\"]]" ,
                "            | [\"DLl\"[\"INITGlobal\"|\"INITInstance\" [\"TERMInstance\"|\"TERMGlobal\"]]" )
pick(    MSG_OS2_HELP_3,    "            | \"PM\" | \"PMCompatible\" | \"FULLscreen\"] " ,
                "            | \"PM\" | \"PMCompatible\" | \"FULLscreen\"] " )
pick(    MSG_OS2_HELP_4,    "directive ::= \"NEWsegment\"" ,
                "directive ::= \"NEWsegment\"" )                
pick(    MSG_OS2_HELP_5,    "            | \"SEGment\"     segdesc{\",\"segdesc}" ,
                "            | \"SEgment\"     segdesc{\",\"segdesc}" )
pick(    MSG_OS2_HELP_6,    "            | \"IMPort\"      import{\",\"import}" ,
                "            | \"IMPort\"      import{\",\"import}" )
pick(    MSG_OS2_HELP_7,    "            | \"EXPort\"      export{\",\"export}" ,
                "            | \"EXPort\"      export{\",\"export}" )
pick(    MSG_OS2_HELP_8,    "            | \"EXPort\"      \"=\"wlib_directive_file" ,
                "            | \"EXPort\"      \"=\"wlib疑似命令ﾌｧｲﾙ" )
pick(    MSG_OS2_HELP_9,    "segdesc   ::= segspec segmodel {segmodel}" ,
                "segdesc   ::= segspec segmodel {segmodel}" )
pick(    MSG_OS2_HELP_10,   "segspec   ::= seg_name | \"Class\" class_name | \"TYpe\" (\"CODE\" | \"DATA\")" ,
                "segspec   ::= セグメント名 | \"Class\" クラス名 | \"TYpe\" (\"CODE\" | \"DATA\")" )
pick(    MSG_OS2_HELP_11,   "import    ::= entryname module[\".\"(extname | ordinal)]" ,
                "import    ::= エントリ名 モジュール[\".\"(外部名 | 序数)]" )
pick(    MSG_OS2_HELP_12,   "option    ::= \"Alignment=\"n | \"DEscription\" description | \"Heapsize=\"n" ,
                "option    ::= \"Alignment=\"n | \"DEscription\" ﾃﾞｨｽｸﾘﾌﾟｼｮﾝ | \"Heapsize=\"n" )
pick(    MSG_OS2_HELP_13,   "            | \"IMPFile\"[=file_name] | \"IMPLib\"[=file_name]" ,
                "            | \"IMPFile\"[=ファイル名] | \"IMPLib\"[=ファイル名]" )
pick(    MSG_OS2_HELP_14,   "            | (\"MANYautodata\" | \"NOautodata\" | \"ONEAutodata\")" ,
                "            | (\"MANYautodata\" | \"NOautodata\" | \"ONEAutodata\")" )
pick(    MSG_OS2_HELP_15,   "            | \"MODName=\"module_name | \"MIXed1632\" | \"NEWFiles\" | \"OFFset=\"n" ,
                "            | \"MODName=\"モジュール名 | \"MIXed1632\" | \"NEWFiles\" | \"OFFset=\"n" )
pick(    MSG_OS2_HELP_16,   "            | \"OLDlibrary=\"dll_name | \"PACKCode=\"n | \"PACKData=\"n | \"PROTmode\"" ,
                                "            | \"OLDlibrary=\"DLL名 | \"PACKCode=\"n | \"PACKData=\"n | \"PROTmode\"")
pick(    MSG_OS2_HELP_17,   "            | \"RESource=\"res_file_name | \"STUB=\"stub_name | \"NOSTUB\"" ,
                                "            | \"RESource=\"リソースファイル名 | \"STUB=\"スタブ名 | \"NOSTUB\"")
pick(    MSG_OS2_HELP_18,   "            | \"VERSion=\"major.[minor]" ,
                                "            | \"VERSion=\"ﾒｼﾞｬｰﾊﾞｰｼﾞｮﾝ.[ﾏｲﾅｰﾊﾞｰｼﾞｮﾝ]")
pick(    MSG_OS2_HELP_19,   "export    ::= entryname[\".\"ordinal][\"=\"internal][\"RESident\"][\"PRIVATE\"][iopl]" ,
                                "export    ::= エントリ名[\".\"序数][\"=\"\/内部名][\"RESident\"][\"PRIVATE\"][I/O特権レベル]")
pick(    MSG_OS2_HELP_20,   "segmodel  ::= (\"PReload\" | \"LOadoncall\") | (\"SHared\" | \"NONShared\")" ,
                "segmodel  ::= (\"PReload\" | \"LOadoncall\") | {\"SHared\" | \"NONShared\")" )
pick(    MSG_OS2_HELP_21,   "            | (\"EXECUTEOnly\" | \"EXECUTERead\" | \"READOnly\" | \"READWrite\")" ,
                "            | (\"EXECUTEOnly\" | \"EXECUTERead\" | \"READOnly\" | \"READWrite\")" )
pick(    MSG_OS2_HELP_22,   "            | (\"Iopl\" | \"NOIopl\") | (\"CONforming\" | \"NONConforming\")" ,
                "            | (\"Iopl\" | \"NOIopl\") | (\"CONforming\" | \"NONConforming\")" )
pick(    MSG_OS2_HELP_23,   "            | (\"PERManent\" | \"NONPERManent\") | \"INValid\" | \"RESident\"" ,
                "            | (\"PERManent\" | \"NONPERManent\") | \"INValid\" | \"RESident\"" )
pick(    MSG_OS2_HELP_24,   "            | \"CONTiguous\" | \"DYNamic\"\n" ,
                "            | \"CONTiguous\" | \"DYNamic\"\n" )

/*
 *  Windows help screen: max 32 lines (from 0 to 31).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_WINDOWS_HELP_0,    "\ncommands valid for the Microsoft Windows executable formats only:\n" ,
                "\nMicrosoft Windows実行可能形式に対してのみ有効なオプション:\n" )
pick(    MSG_WINDOWS_HELP_1,    "form      ::= \"WIndows\" [\"DLl\"[\"INITGlobal\" | \"INITInstance\"]] [MEMory] [FOnt]" ,
                "form      ::= \"WIndows\" [\"DLl\"[\"INITGlobal\" | \"INITInstance\"]] [MEMory] [FOnt]" )
pick(    MSG_WINDOWS_HELP_2,    "directive ::= \"NEWsegment\"" ,
                "directive ::= \"NEWsegment\"" )
pick(    MSG_WINDOWS_HELP_3,    "            | \"SEGment\"     segdesc{\",\"segdesc}" ,
                "            | \"SEgment\"     segdesc{\",\"segdesc}" )
pick(    MSG_WINDOWS_HELP_4,    "            | \"IMPort\"      import{\",\"import}" ,
                "            | \"IMPort\"      import{\",\"import}" )
pick(    MSG_WINDOWS_HELP_5,    "            | \"EXPort\"      export{\",\"export}" ,
                "            | \"EXPort\"      export{\",\"export}" )
pick(    MSG_WINDOWS_HELP_6,    "            | \"EXPort\"      \"=\"wlib_directive_file" ,
                "            | \"EXPort\"      \"=\"wlib疑似命令ﾌｧｲﾙ" )
pick(    MSG_WINDOWS_HELP_7,    "segdesc   ::= segspec segmodel {segmodel}" ,
                "segdesc   ::= segspec segmodel {segmodel}" )
pick(    MSG_WINDOWS_HELP_8,    "segspec   ::= seg_name | \"Class\" class_name | \"TYpe\" (\"CODE\" | \"DATA\")" ,
                "segspec   ::= セグメント名 | \"Class\" クラス名 | \"TYpe\" (\"CODE\" | \"DATA\")" )
pick(    MSG_WINDOWS_HELP_9,    "import    ::= entryname module[\".\"(extname | ordinal)]" ,
                "import    ::= エントリ名 モジュール[\".\"(外部名 | 序数)]" )
pick(    MSG_WINDOWS_HELP_10,   "option    ::= \"Alignment=\"n | \"DEscription\" description | \"Heapsize=\"n" ,
                "option    ::= \"Alignment=\"n | \"DEscription\" ﾃﾞｨｽｸﾘﾌﾟｼｮﾝ | \"Heapsize=\"n" )
pick(    MSG_WINDOWS_HELP_11,   "            | \"IMPFile\"[=file_name] | \"IMPLib\"[=file_name]" ,
                "            | \"IMPFile\"[=ファイル名] | \"IMPLib\"[=ファイル名]" )
pick(    MSG_WINDOWS_HELP_12,   "            | (\"MANYautodata\" | \"NOautodata\" | \"ONEAutodata\")" ,
                "            | (\"MANYautodata\" | \"NOautodata\" | \"ONEAutodata\")" )
pick(    MSG_WINDOWS_HELP_13,   "            | \"MODName=\"module_name | \"OLDlibrary=\"dll_name | \"PACKCode=\"n" ,
                "            | \"MODName=\"モジュール名 | \"OLDlibrary=\"DLL名 | \"PACKCode=\"n" )
pick(    MSG_WINDOWS_HELP_14,   "            | \"PACKData=\"n | \"RESource=\"res_file_name | \"RWReloccheck\"" ,
                                "            | \"PACKData=\"n | \"RESource=\"リソースファイル名 | \"RWReloccheck\"")
pick(    MSG_WINDOWS_HELP_15,   "            | \"STUB=\"stub_name | \"NOSTUB\" | \"VERSion=\"major.[minor]" ,
                                "            | \"STUB=\"スタブ名 | \"NOSTUB\" | \"VERSion=\"ﾒｼﾞｬｰﾊﾞｰｼﾞｮﾝ.[ﾏｲﾅｰﾊﾞｰｼﾞｮﾝ]")
pick(    MSG_WINDOWS_HELP_16,   "export    ::= entryname[\".\"ordinal][\"=\"internal][\"RESident\"][\"PRIVATE\"]" ,
                                "export    ::= エントリ名[\".\"序数][\"=\"内部名][\"RESident\"][\"PRIVATE\"]" )
pick(    MSG_WINDOWS_HELP_17,   "segmodel  ::= (\"PReload\" | \"LOadoncall\") | (\"SHared\" | \"NONShared\")" ,
                                "segmodel  ::= (\"PReload\" | \"LOadoncall\") | (\"SHared\" | \"NONShared\")" )
pick(    MSG_WINDOWS_HELP_18,   "            | (\"EXECUTEOnly\" | \"EXECUTERead\" | \"READOnly\" | \"READWrite\")" ,
                                "            | (\"EXECUTEOnly\" | \"EXECUTERead\" | \"READOnly\" | \"READWrite\")" )
pick(    MSG_WINDOWS_HELP_19,   "            | (\"MOVeable\" | \"FIXed\") | \"DIScardable\"\n" ,
                                "            | (\"MOVeable\" | \"FIXed\") | \"DIScardable\"\n" )

/*
 *  NT help screen: max 32 lines (from 0 to 31).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_NT_HELP_0,     "\ncommands valid for the Microsoft Windows NT executable formats only:\n" ,
                "Microsoft Windows NT実行可能形式に対してのみ有効なオプション:\n" )
pick(    MSG_NT_HELP_1,     "form      ::= \"WIndows NT\" [\"TNT\" | \"RDOS\"]" ,
                "form      ::= \"WIndows NT\" [\"TNT\" | \"RDOS\"]" )
pick(    MSG_NT_HELP_2,     "              [\"DLl\"[\"INITGlobal\"|\"INITInstance\" [\"TERMInstance\"|\"TERMGlobal\"]]" ,
                "              [\"DLl\"[\"INITGlobal\"|\"INITInstance\" [\"TERMInstance\"|\"TERMGlobal\"]]" )
pick(    MSG_NT_HELP_3,     "directive ::= \"RUntime\"     runoption[\"=\"major[\".\"minor]]" ,
                "directive ::= \"RUntime\"     runoption[\"=\"ﾒｼﾞｬｰﾊﾞｰｼﾞｮﾝ[\".\"ﾏｲﾅｰﾊﾞｰｼﾞｮﾝ]]")             
pick(    MSG_NT_HELP_4,     "            | \"SEGment\"     segdesc{\",\"segdesc}" ,
                                "            | \"SEgment\"     segdesc{\",\"segdesc}" )
pick(    MSG_NT_HELP_5,     "            | \"IMPort\"      import{\",\"import}" ,
                                "            | \"IMPort\"      import{\",\"import}" )
pick(    MSG_NT_HELP_6,     "            | \"EXPort\"      export{\",\"export}" ,
                                "            | \"EXPort\"      export{\",\"export}" )
pick(    MSG_NT_HELP_7,     "            | \"EXPort\"      \"=\"wlib_directive_file" ,
                                "            | \"EXPort\"      \"=\"wlib疑似命令ﾌｧｲﾙ" )
pick(    MSG_NT_HELP_8,     "            | \"COMmit\"       commitopt{\",\"commitopt}" ,
                                "            | \"COMmit\"       commitopt{\",\"commitopt}" )
pick(    MSG_NT_HELP_9,     "segdesc   ::= segspec segmodel {segmodel}" ,
                "segdesc   ::= segspec segmodel {segmodel}" )
pick(    MSG_NT_HELP_10,    "segspec   ::= seg_name | \"Class\" class_name | \"TYpe\" (\"CODE\" | \"DATA\")" ,
                "segspec   ::= セグメント名 | \"Class\" クラス名 | \"TYpe\" (\"CODE\" | \"DATA\")" )
pick(    MSG_NT_HELP_11,    "import    ::= entryname module[\".\"(extname | ordinal)]" ,
                "import    ::= エントリ名 モジュール[\".\"(外部名 | 序数)]" )
pick(    MSG_NT_HELP_12,    "option    ::= \"Alignment=\"n | \"DEscription\" description | \"Heapsize=\"n" ,
                "option    ::= \"Alignment=\"n | \"DEscription\" ﾃﾞｨｽｸﾘﾌﾟｼｮﾝ | \"Heapsize=\"n" )
pick(    MSG_NT_HELP_13,    "            | \"IMPFile\"[=file_name] | \"IMPLib\"[=file_name]" ,
                "            | \"IMPFile\"[=ファイル名] | \"IMPLib\"[=ファイル名]" )
pick(    MSG_NT_HELP_14,    "            | \"MODName=\"module_name | \"NOSTDCall\" | \"OBJAlign=\"n | \"OFFset=\"n" ,
                "            | \"MODName=\"モジュール名 | \"NOSTDCall\" | \"OBJAlign=\"n | \"OFFset=\"n" )
pick(    MSG_NT_HELP_15,    "            | \"OLDlibrary=\"dll_name | \"RESource=\"res_file_name" ,
                                "            | \"OLDlibrary=\"DLL名 | \"RESource=\"リソースファイル名")
pick(    MSG_NT_HELP_16,    "            | \"STUB=\"stub_name | \"NOSTUB\" | \"VERSion=\"major.[minor]" ,
                                "            | \"STUB=\"スタブ名 | \"NOSTUB\" | \"VERSion=\"ﾒｼﾞｬｰﾊﾞｰｼﾞｮﾝ.[ﾏｲﾅｰﾊﾞｰｼﾞｮﾝ]")
pick(    MSG_NT_HELP_17,    "export    ::= entryname[\".\"ordinal][\"=\"internal][\"PRIVATE\"]" ,
                "export    ::= エントリ名[\".\"序数][\"=\"内部名][\"PRIVATE\"]" )
pick(    MSG_NT_HELP_18,    "segmodel  ::= (\"SHared\" | \"NONShared\") | (\"PAGEable\" | \"NONPageable\")" ,
                "segmodel  ::= (\"SHared\" | \"NONShared\") | (\"PAGEable\" | \"NONPageable\")" )
pick(    MSG_NT_HELP_19,    "runoption ::= (\"NATive\" | \"WINdows\" | \"CONsole\" | \"POSix\" | \"OS2\" | \"DOSstyle\")" ,
                "runoption ::= (\"NATive\" | \"WINdows\" | \"CONsole\" | \"POSix\" | \"OS2\" | \"DOSstyle\")" )
pick(    MSG_NT_HELP_20,    "commitopt ::= \"STack=\"n | \"Heap=\"n\n" ,
                "commitopt ::= \"STack=\"n | \"Heap=\"n\n" )

/*
 *  Phar Lap help screen: max 16 lines (from 0 to 15).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_PHAR_HELP_0,   " " ,
                " " )               
pick(    MSG_PHAR_HELP_1,   "commands valid for the Phar Lap executable formats only:" ,
                "Phar Lap実行可能形式に対してのみ有効なオプション:" )
pick(    MSG_PHAR_HELP_2,   " " ,
                " " )               
pick(    MSG_PHAR_HELP_3,   "form      ::= \"PHARlap\" [\"EXTended\" | \"REX\" | \"SEGmented\"]" ,
                "form      ::= \"PHARlap\" [\"EXTended\" | \"REX\"]" )
pick(    MSG_PHAR_HELP_4,   "directive ::= \"RUntime\"     runoption{\",\"runoption}" ,
                "directive ::= \"RUntime\"     runoption{\",\"runoption}" )
pick(    MSG_PHAR_HELP_5,   "option    ::= \"MAXData=\"n | \"MINData=\"n | \"OFFset=\"n | \"STUB=\"stub_name" ,
                "option    ::= \"MAXData=\"n | \"MINData=\"n | \"OFFset=\"n | \"STUB=\"スタブ名" )
pick(    MSG_PHAR_HELP_6,   "runoption ::= \"MINReal=\"n | \"MAXReal=\"n | \"CALLBufs=\"n | \"MINIBuf=\"n" ,
                "runoption ::= \"MINReal=\"n | \"MAXReal=\"n | \"CALLBufs=\"n | \"MINIBuf=\"n" )
pick(    MSG_PHAR_HELP_7,   "            | \"MAXIBuf=\"n | \"NISTack=\"n | \"ISTKsize=\"n | \"PRIVileged\"" ,
                "            | \"MAXIBuf=\"n | \"NISTack=\"n | \"ISTKsize=\"n | \"PRIVileged\"" )
pick(    MSG_PHAR_HELP_8,   "            | \"REALBreak=\"(n | symbol_name ) | \"UNPRIVileged\"" ,
                "            | \"REALBreak=\"(n | シンボル名)  | \"UNPRIVileged\"" )
pick(    MSG_PHAR_HELP_9,   " " ,
                " " )

/*
 *  Novell help screen: max 32 lines (from 0 to 31).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_NOVELL_HELP_0, " " ,
                " " )
pick(    MSG_NOVELL_HELP_1, "commands valid for the Novell Netware executable format only:" ,
                "Novell Netware実行可能形式に対してのみ有効なコマンド:" )
pick(    MSG_NOVELL_HELP_2, " " ,
                " " )
pick(    MSG_NOVELL_HELP_3, "form      ::= \"NOVell\" [\"NLM\" | \"LAN\" | \"DSK\" | \"NAM\" | 'number'] 'description'" ,
                "form      ::= \"NOVell\" [\"NLM\" | \"LAN\" | \"DSK\" | \"NAM\" | 'number'] ﾃﾞｨｽｸﾘﾌﾟｼｮﾝ" )
pick(    MSG_NOVELL_HELP_4, "directive ::= \"MODUle\"      module_name{\",\"module_name}" ,
                                "directive ::= \"MODUle\"      モジュール名{\",\"モジュール名}" )
pick(    MSG_NOVELL_HELP_5, "            | \"IMPort\"      import{\",\"import}" ,
                                "            | \"IMPort\"      import{\",\"import}" )
pick(    MSG_NOVELL_HELP_6, "            | \"EXPort\"      export{\",\"export}" ,
                                "            | \"EXPort\"      export{\",\"export}" )
pick(    MSG_NOVELL_HELP_7, "            | \"Debug\"       \"Novell\" [\"ONLyexports\"] [\"REFerenced\"]" ,
                                "            | \"Debug\"       \"Novell\" [\"ONLyexports\"] [\"REFerenced\"]" )
pick(    MSG_NOVELL_HELP_8, "option    ::= \"CHeck=\"symbol_name | \"COPYRight\" [string] | \"CUSTom=\"file_name" ,
                "option    ::= \"CHeck=\"シンボル名 | \"COPYRight\" [文字列] | \"CUSTom=\"ファイル名" )
pick(    MSG_NOVELL_HELP_9, "            | \"EXit=\"symbol_name | \"HElp=\"file_name | \"IMPFile=\"file_name" ,
                                "            | \"EXit=\"シンボル名 | \"HElp=\"ファイル名 | \"IMPFile=\"ファイル名" )
pick(    MSG_NOVELL_HELP_10,    "            | \"IMPLib\"[=file_name] | \"MESsages\"[=file_name] | \"MULTILoad\"" ,
                "            | \"IMPLib\"[=ファイル名] | \"MESsages\"[=ファイル名] | \"MULTILoad\"" )
pick(    MSG_NOVELL_HELP_11,    "            | \"NLMFlags=\"value | \"PSeudopreemption\" | \"REentrant\"" ,
                                "            | \"NLMFlags=\"value | \"PSeudopreemption\" | \"REentrant\"" )
pick(    MSG_NOVELL_HELP_12,    "            | \"SCReenname\" description | \"SHArelib=\"file_name | \"SYnchronize\"" ,
                                "            | \"SCReenname\" ﾃﾞｨｽｸﾘﾌﾟｼｮﾝ | \"SHArelib=\"ファイル名 | \"SYnchronize\"" )
pick(    MSG_NOVELL_HELP_13,    "            | \"THReadname\" name | \"VERSion=\"major[.minor[.revision]]" ,
                "            | \"THReadname\" name | \"VERSion=\"ﾒｼﾞｬｰﾊﾞｰｼﾞｮﾝ[.ﾏｲﾅｰﾊﾞｰｼﾞｮﾝ[.ﾘﾋﾞｼﾞｮﾝ]]" )
pick(    MSG_NOVELL_HELP_14,    "            | \"XDCdata=\"file_name | \"AUTOUNload\"" ,
                "            | \"XDCdata=\"ファイル名 | \"AUTOUNload\"" )
pick(    MSG_NOVELL_HELP_15,    "import    ::= entryname" ,
                "import    ::= エントリ名" )                
pick(    MSG_NOVELL_HELP_16,    "export    ::= entryname" ,
                "export    ::= エントリ名" )                
pick(    MSG_NOVELL_HELP_17,    " " ,
                " " )

/*
 *  Dos/16M help screen: max 16 lines (from 0 to 15).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_DOS16_HELP_0,  " " ,
                " " )               
pick(    MSG_DOS16_HELP_1,  "commands valid for the DOS/16M executable format only:" ,
                "DOS/16M実行可能形式に対してのみ有効なコマンド:" )
pick(    MSG_DOS16_HELP_2,  " " ,
                " " )
pick(    MSG_DOS16_HELP_3,  "form      ::= \"DOS16M\"" ,
                "form      ::= \"DOS16m\"" )
pick(    MSG_DOS16_HELP_4,  "directive ::= \"MEMory\"      strategy" ,
                "directive ::= \"MEMory\"      strategy" )              
pick(    MSG_DOS16_HELP_5,  "            | \"TRansparent\" seg_type" ,
                "            | \"TRansparent\" seg_type" )              
pick(    MSG_DOS16_HELP_6,  "            | \"RUntime\"     runoption{\",\"runoption}" ,
                "            | \"RUntime\"     runoption{\",\"runoption}" )
pick(    MSG_DOS16_HELP_7,  "option    ::= \"BUFfer=\"n | \"GDTsize=\"n | (\"RELocs\" | \"NORelocs\") | \"SELstart=\"n" ,
                "option    ::= \"BUFfer=\"n | \"GDTsize=\"n | (\"RELocs\" | \"NORelocs\") | \"SELstart=\"n" )
pick(    MSG_DOS16_HELP_8,  "            | \"DATASize=\"n | \"EXTended=\"n" ,
                "            | \"DATASize=\"n | \"EXTended=\"n" )
pick(    MSG_DOS16_HELP_9,   "            | \"STUB=\"stub_name" ,
                                "            | \"STUB=\"スタブ名")
pick(    MSG_DOS16_HELP_10, "runoption ::= \"KEYboard\" | \"OVERload\" | \"INIT00\" | \"INITFF\" | \"ROTate\" | \"AUTO\"" ,
                "runoption ::=  \"KEYbord\" | \"OVERload\" | \"INIT00\" | \"INITFF\" | \"ROTate\" | \"AUTO\"" )
pick(    MSG_DOS16_HELP_11, "            | \"SELectors\" | \"INT10\"" ,
                "            | \"SELectors\" | \"INT10\"" )
pick(    MSG_DOS16_HELP_12, "strategy  ::= \"TRYExtended\" | \"TRYLow\" | \"FORCEExtended\" | \"FORCELow\"" ,
                "strategy  ::= \"TRYExtended\" | \"TRYLow\" | \"FORCEExtended\" | \"FORCELow\"" )
pick(    MSG_DOS16_HELP_13, "seg_type  ::= \"STack\" | \"DAta\"" ,
                "seg_type  ::= \"STack\" | \"DAta\"" )              
pick(    MSG_DOS16_HELP_14, " " ,
                " " )

/*
 *  QNX help screen: max 16 lines (from 0 to 15).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_QNX_HELP_0,    " " ,
                " " )               
pick(    MSG_QNX_HELP_1,    "commands valid for the QNX executable format only:" ,
                "QNX実行可能形式に対してのみ有効なコマンド:" )              
pick(    MSG_QNX_HELP_2,    " " ,
                " " )               
pick(    MSG_QNX_HELP_3,    "form      ::= \"QNX\" [\"FLat\"]" ,
                "form      ::= \"QNX\" [\"FLat\"]" )                
pick(    MSG_QNX_HELP_4,    "directive ::= \"SEGment\"     segdesc{\",\"segdesc}" ,
                "directive ::= \"SEgment\"     segdesc{\",\"segdesc}" )
pick(    MSG_QNX_HELP_5,    "            | \"NEWsegment\"" ,
                "            | \"NEWsegment\"" )
pick(    MSG_QNX_HELP_6,    "option    ::= \"Heapsize=\"n | \"LInearrelocs\" | \"LOnglived\" | \"NORelocs\" " ,
                "option    ::= \"Heapsize=\"n | \"LInearrelocs\" | \"LOnglived\" | \"NORelocs\" " )
pick(    MSG_QNX_HELP_7,    "            | \"OFFset=\"n | \"PACKCode=\"n | \"PACKData=\"n | \"PRIVilege\"=n" ,
                "            | \"OFFset=\"n | \"PACKCode=\"n | \"PACKData=\"n | \"PRIVilege\"=n" )
pick(    MSG_QNX_HELP_8,    "            | \"RESource\"(\"=\"res_file_name | string)" ,
                "            | \"RESource\"(\"=\"リソースファイル名 | 文字列)" )
pick(    MSG_QNX_HELP_9,    "segdesc   ::= segspec segmodel {segmodel}" ,
                "segdesc   ::= segspec segmodel {segmodel}" )
pick(    MSG_QNX_HELP_10,   "segspec   ::= seg_name | \"Class\" class_name | \"TYpe\" (\"CODE\" | \"DATA\")" ,
                "segspec   ::= セグメント名 | \"Class\" クラス名 | \"TYpe\" (\"CODE\" | \"DATA\")" )
pick(    MSG_QNX_HELP_11,   "segmodel  ::= \"EXECUTEOnly\" | \"EXECUTERead\" | \"READOnly\" | \"READWrite\"" ,
                "segmodel  ::= \"EXECUTEOnly\" | \"EXECUTERead\" | \"READOnly\" | \"READWrite\"" )
pick(    MSG_QNX_HELP_12,   " " ,
                " " )

/*
 *  ELF help screen: max 16 lines (from 0 to 15).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_ELF_HELP_0,    " " ,
                " " )
pick(    MSG_ELF_HELP_1,    "commands valid for the ELF executable format only:" ,
                "ELF実行可能フォーマットに対してのみのコマンドです:" )
pick(    MSG_ELF_HELP_2,    " " ,
                " " )
pick(    MSG_ELF_HELP_3,    "form      ::= \"ELF\" [\"DLl\"]" ,
                "form      ::= \"ELF\" [\"DLl\"]" )
pick(    MSG_ELF_HELP_4,    "directive ::= \"MODUle\"      module_name{\",\"module_name}" ,
                "directive ::= \"MODUle\"      モジュール名{\",\"モジュール名}" )
pick(    MSG_ELF_HELP_5,    "            | \"IMPort\"      import{\",\"import}" ,
                "            | \"IMPort\"      import{\",\"import}" )
pick(    MSG_ELF_HELP_6,    "            | \"EXPort\"      export{\",\"export}" ,
                "            | \"EXPort\"      export{\",\"export}" )
pick(    MSG_ELF_HELP_7,    "            | \"RUntime\"     runoption{\",\"runoption}" ,
                "            | \"RUntime\"     runoption{\",\"runoption}" )
pick(    MSG_ELF_HELP_8,    "option    ::= \"Alignment=\"n | \"EXPORTAll\" | \"EXTRASections=\"n | \"OBJAlign=\"n" ,
                "option    ::= \"Alignment=\"n | \"EXPORTAll\" | \"EXTRASections=\"n | \"OBJAlign=\"n" )
pick(    MSG_ELF_HELP_9,    "            | \"OFFSet=\"n" ,
                "            | \"OFFSet=\"n" )
pick(    MSG_ELF_HELP_10,   "import    ::= entryname" ,
                "import    ::= エントリ名" )
pick(    MSG_ELF_HELP_11,   "export    ::= entryname" ,
                "export    ::= エントリ名" )
pick(    MSG_ELF_HELP_12,   "runoption ::= (\"SVR4\" | \"LINux\" | \"FREebsd\" | \"NETbsd\" | \"SOLaris\" | \"ABIver\" )" ,
                "runoption ::= (\"SVR4\" | \"LINux\" | \"FREebsd\" | \"NETbsd\" | \"SOLaris\" | \"ABIver\" )" )
pick(    MSG_ELF_HELP_13,   " " ,
                " " )


/*
 *  Windows help screen: max 32 lines (from 0 to 31).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_WIN_VXD_HELP_0,    "\ncommands valid for the Microsoft Windows VxD formats only:\n" ,
                "\nMicrosoft Windows VxD実行可能形式に対してのみ有効なオプション:\n" )
pick(    MSG_WIN_VXD_HELP_1,    "form      ::= \"WIndows VXD\" [\"DYNamic\"]" ,
                "form      ::= \"WIndows VXD\" [\"DYNamic\"]" )
/*
pick(    MSG_WIN_VXD_HELP_2,    "directive ::= \"NEWsegment\"" ,
                "directive ::= \"NEWsegment\"" )
pick(    MSG_WIN_VXD_HELP_3,    "            | \"SEGment\"     segdesc{\",\"segdesc}" ,
                "            | \"SEgment\"     segdesc{\",\"segdesc}" )
pick(    MSG_WIN_VXD_HELP_4,    "            | \"IMPort\"      import{\",\"import}" ,
                "            | \"IMPort\"      import{\",\"import}" )
pick(    MSG_WIN_VXD_HELP_5,    "            | \"EXPort\"      export{\",\"export}" ,
                "            | \"EXPort\"      export{\",\"export}" )
pick(    MSG_WIN_VXD_HELP_6,    "            | \"EXPort\"      \"=\"wlib_directive_file" ,
                "            | \"EXPort\"      \"=\"wlib疑似命令ﾌｧｲﾙ" )
pick(    MSG_WIN_VXD_HELP_7,    "segdesc   ::= segspec segmodel {segmodel}" ,
                "segdesc   ::= segspec segmodel {segmodel}" )
pick(    MSG_WIN_VXD_HELP_8,    "segspec   ::= seg_name | \"Class\" class_name | \"TYpe\" (\"CODE\" | \"DATA\")" ,
                "segspec   ::= セグメント名 | \"Class\" クラス名 | \"TYpe\" (\"CODE\" | \"DATA\")" )
pick(    MSG_WIN_VXD_HELP_9,    "import    ::= entryname module[\".\"(extname | ordinal)]" ,
                "import    ::= エントリ名 モジュール[\".\"(外部名 | 序数)]" )
pick(    MSG_WIN_VXD_HELP_10,   "option    ::= \"Alignment=\"n | \"DEscription\" description | \"Heapsize=\"n" ,
                "option    ::= \"Alignment=\"n | \"DEscription\" ﾃﾞｨｽｸﾘﾌﾟｼｮﾝ | \"Heapsize=\"n" )
pick(    MSG_WIN_VXD_HELP_11,   "            | \"IMPFile\"[=file_name] | \"IMPLib\"[=file_name]" ,
                "            | \"IMPFile\"[=ファイル名] | \"IMPLib\"[=ファイル名]" )
pick(    MSG_WIN_VXD_HELP_12,   "            | (\"MANYautodata\" | \"NOautodata\" | \"ONEAutodata\")" ,
                "            | (\"MANYautodata\" | \"NOautodata\" | \"ONEAutodata\")" )
pick(    MSG_WIN_VXD_HELP_13,   "            | \"MODName=\"module_name | \"OLDlibrary=\"dll_name | \"PACKCode=\"n" ,
                "            | \"MODName=\"モジュール名 | \"OLDlibrary=\"DLL名 | \"PACKCode=\"n" )
pick(    MSG_WIN_VXD_HELP_14,   "            | \"PACKData=\"n | \"RESource=\"res_file_name | \"RWReloccheck\"" ,
                                "            | \"PACKData=\"n | \"RESource=\"リソースファイル名 | \"RWReloccheck\"")
pick(    MSG_WIN_VXD_HELP_15,   "            | \"STUB=\"stub_name | \"NOSTUB\" | \"VERSion=\"major.[minor]" ,
                                "            | \"STUB=\"スタブ名 | \"NOSTUB\" | \"VERSion=\"ﾒｼﾞｬｰﾊﾞｰｼﾞｮﾝ.[ﾏｲﾅｰﾊﾞｰｼﾞｮﾝ]")
pick(    MSG_WIN_VXD_HELP_16,   "export    ::= entryname[\".\"ordinal][\"=\"internal][\"RESident\"][\"PRIVATE\"]" ,
                                "export    ::= エントリ名[\".\"序数][\"=\"内部名][\"RESident\"][\"PRIVATE\"]" )
pick(    MSG_WIN_VXD_HELP_17,   "segmodel  ::= (\"PReload\" | \"LOadoncall\") | (\"SHared\" | \"NONShared\")" ,
                                "segmodel  ::= (\"PReload\" | \"LOadoncall\") | (\"SHared\" | \"NONShared\")" )
pick(    MSG_WIN_VXD_HELP_18,   "            | (\"EXECUTEOnly\" | \"EXECUTERead\" | \"READOnly\" | \"READWrite\")" ,
                                "            | (\"EXECUTEOnly\" | \"EXECUTERead\" | \"READOnly\" | \"READWrite\")" )
pick(    MSG_WIN_VXD_HELP_19,   "            | (\"MOVeable\" | \"FIXed\") | \"DIScardable\"\n" ,
                                "            | (\"MOVeable\" | \"FIXed\") | \"DIScardable\"\n" )
*/

/*
 *  Zdos help screen: max 16 lines (from 0 to 15).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_ZDOS_HELP_0,       " " ,
                                " " )
pick(    MSG_ZDOS_HELP_1,       "commands valid for the ZDOS executable formats only:" ,
                                "ZDOS 実行可能形式に対してのみ有効なオプション:" )
pick(    MSG_ZDOS_HELP_2,       " " ,
                                " " )
pick(    MSG_ZDOS_HELP_3,       "form      ::= \"ZDos\" [\"SYS\" | \"HWD\" | \"FSD\"]" ,
                                "form      ::= \"ZDos\" [\"SYS\" | \"HWD\" | \"FSD\"]" )
pick(    MSG_ZDOS_HELP_4,       " " ,
                                " " )
/*
 *  Raw help screen: max 16 lines (from 0 to 15).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_RAW_HELP_0,        " " ,
                                " " )
pick(    MSG_RAW_HELP_1,        "commands valid for the RAW executable formats only:" ,
                                "RAW 実行可能形式に対してのみ有効なオプション:" )
pick(    MSG_RAW_HELP_2,        " " ,
                                " " )
pick(    MSG_RAW_HELP_3,        "form      ::= \"Raw\" (\"BIN\" | \"HEX\")" ,
                                "form      ::= \"Raw\" (\"SYS\" | \"HEX\")" )
pick(    MSG_RAW_HELP_4,        "option    ::= \"OFFset=\"n" ,
                                "option    ::= \"OFFset=\"n" )
pick(    MSG_RAW_HELP_5,        " " ,
                                " " )
                                
/*
 *  Zdos help screen: max 16 lines (from 0 to 15).
 *  To start a new page, leave a line undefined or define an empty line.
 */
pick(    MSG_RDOS_HELP_0,       " " ,
                                " " )
pick(    MSG_RDOS_HELP_1,       "commands valid for the RDOS executable formats only:" ,
                                "RDOS 実行可能形式に対してのみ有効なオプション:" )
pick(    MSG_RDOS_HELP_2,       " " ,
                                " " )
pick(    MSG_RDOS_HELP_3,       "form      ::= \"RDos\" [\"DEV\"]" ,
                                "form      ::= \"RDos\" [\"DEV\"]" )
pick(    MSG_RDOS_HELP_4,       " " ,
                                " " )

