#pmake: build flat cpu_386 os_osi
#
# plibmt3r -- 32-bit 3r PLIB multi-thread library
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/runtime/runtime.mif
