#pmake: build flat cpu_386 os_nt dynamic profile
#
# contmt3r.lib -- register based multi-thread 32-bit CONTAINER library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
mthreaded  = 1
fs_registration = yes
profile    = 1

!include $(cpplib_dir)/contain/contain.mif
