#pmake: build flat cpu_386 os_os2
processor  = 386
system     = os2
model      = mf
convention = stack
linkage    = static
mthreaded  = 1
subdir     = mf_smt
define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
