#pmake: serv remote os_os2 cpu_i86 par
host_CPU = i86
host_OS = os2

os  = os2
srv = par
cpu = x86
which = SERVER
type  = remote_link

extra_objs = paros2.obj portos2.obj

!include ../os2.mif
!include $(trap_dir)/master.mif
