#pmake: nobuild debug flat cpu_386 os_nt
#
# cont3r.lib -- register based 32-bit CONTAINER library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
fs_registration = yes

lib_debug = 1

!include $(cpplib_dir)/contain/contain.mif
