#pmake/150: nobuild debug flat register 32bit winnt ix86 rtdll os_nt cpu_386

component  = clib
processor  = 386
model      = mf
system     = winnt
convention = register

rtdll_release = 0

!include $(rtdll_dir)/master.mif
