#pmake/150: nobuild debug flat register 32bit winnt ix86 rtdll os_nt cpu_386
component  = clib
processor  = 386
model      = mf
system     = winnt
convention = register
mthreaded=1

lib_debug = 1

!include $(rtdll_dir)/master.mif
