type = win
os = win
build_target = windows
sys = windows
compiler = comp286
model = l
xflags=-zW

target : sample.exe .SYMBOLIC
    @%null

samp2 : samp2.exe  .SYMBOLIC
    @%null

!include ..\makefile
