#pmake/50:all small stack 32bit inline winnt iX86 rtdll build os_nt cpu_386 dynamic
component=mathlib
processor=387
model=ms
subdir=ms_sd
system=winnt
convention=stack
!include $(rtdll_dir)\master.mif
!include ..\objs.mif
!include $(rtdll_dir)\mkdll.mif
