#pmake: build small cpu_i86 os_osi os_os2
#
# conts.lib -- small memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = ms
linkage    = static
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
