#pmake: build flat cpu_386 os_rdos
#
# strg3smt.lib -- stack based 32-bit multi-threaded STRING library
#
processor  = 386
system     = rdos
model      = mf
convention = stack
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/string/string.mif
