#pmake: build flat cpu_386 os_nt dynamic profile
#
# plib3r -- 32-bit 3r MT PLIB, PLBX
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
mthreaded  = 1
fs_registration = yes
profile = 1

!include $(cpplib_dir)/runtime/plib.mif
