#pmake: build trap lcl os_dos dsx cpu_386 x86

tree_depth = 7

host_os  = dos
host_cpu = i86

target_cpu = x86

srv = cw
which = TRAP

!include $(trap_dir)/lcl/dos/dosx/dosx.mif
!include $(trap_dir)/master.mif
