#pmake: build flat cpu_386 os_os2
#
# cont3s.lib -- stack based 32-bit CONTAINER library
#
processor  = 386
system     = os2
model      = mf
convention = stack
linkage    = static
fs_registration = yes

!include $(cpplib_dir)/contain/contain.mif
