#pmake: build flat cpu_386 os_os2 dynamic
#
# contmt3s.lib -- stack based multi-thread 32-bit CONTAINER library
#
processor  = 386
system     = os2
model      = mf
convention = stack
linkage    = dynamic
mthreaded  = 1
fs_registration = yes
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
