#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp IOSTREAM library
#
suffix = mt
target_system = ntaxp
production_lib = libaxp
define_library_include = $(plusplus_iostream_dir)\iostream.mif
define_deps_include = $(plusplus_iostream_dir)\deps.mif
define_target_include = $(plusplus_dir)\libaxp$(suffix).mif
!include $(plusplus_dir)\mklib.mif
