#pmake: serv remote os_qnx cpu_386 tcp x86

host_os  = nto
host_cpu = 386

os    = nto
srv   = tcp
cpu   = x86
which = SERVER
type  = remote_link

#extra_libs = $(watcom_dir)/lib/qnx/socket3r.lib
#inc_dirs   = -I"$(watcom_dir)/qnx_h"

!include $(trap_dir)/lcl/nto/trap.mif
!include $(trap_dir)/master.mif
