Project
    TargetGroup "MFC ALPHA - 32-bit (4.1)"
      Target *.exe, nmae_, "Executable"
      Target *.exe, naae_, "Executable (AFXDLL)"
      Target *.exe, nuae_, "Unicode Executable"
      Target *.exe, noae_, "Unicode Executable (AFXDLL)"
      Target *.dll, nmad_, "DLL (USRDLL)"
      Target *.dll, naad_, "DLL (AFXEXT)"
      Target *.dll, nuad_, "Unicode DLL (USRDLL)"
      Target *.dll, noad_, "Unicode DLL (AFXEXT)"
