#pmake: serv remote os_qnx cpu_i86 cpu_386 ser x86
host_CPU = 386
host_OS = qnx

os = qnx
srv = ser
cpu = x86
which = SERVER
type  = remote_link

extra_objs = serqnx.obj

!include $(trap_dir)/master.mif
