#pmake: serv remote os_qnx cpu_i86 cpu_386 ser x86
host_cpu = 386
host_os  = qnx

os = qnx
srv = ser
cpu = x86
which = SERVER
remote_link = 1

extra_objs = serqnx.obj

!include $(trap_dir)/master.mif
