.ti 3b bb
.tr bb 3b
:set symbol="pc" value="\".
:set symbol="ps" value="~;".
:set symbol="dr1" value="a:".
:set symbol="dr2" value="b:".
:set symbol="dr3" value="c:".
:set symbol="dr4" value="d:".
:set symbol="obj" value="obj".
:set symbol="setcmd" value="set".
