.*
.*
.option NOEXTENSION
.*
.np
The "NOEXTENSION" option suppresses automatic addition of an extension to
the name of the executable file generated by &lnkname.. This affects both
names specified explicitly through the "NAME" directive as well as default
names chosen in the absence of a "NAME" directive.
.np
The format of the "NOEXTENSION" option (short form "NOEXT") is as
follows.
.mbigbox
    OPTION NOEXTENSION
.embigbox
