#pmake: build trap remote os_os2 cpu_i86 cpu_386 nmp x86
host_CPU = 386
host_OS = os2

os  = os2v2
srv = nmp
cpu = x86
which = TRAP
type  = remote_link

extra_objs = nmpos22.obj

!include $(trap_dir)/master.mif
