#pmake: build trap remote os_os2 cpu_i86 cpu_386 nmp x86
host_cpu = 386
host_os  = os2

target_cpu = x86

os    = os2v2
srv   = nmp
which = TRAP
remote_link = 1

extra_objs = nmpos22.obj

!include $(trap_dir)/master.mif
