#pmake: trap remote os_nt cpu_386 nov axp

tree_depth = 4

host_cpu = axp
host_os  = nt

target_cpu = axp

srv = nov
which = TRAP
remote_link = 1

extra_objs = novnt.obj

extra_linker = lib wsock32.lib

!include $(trap_dir)/master.mif
