pick(   UNINS_TITLE,
        "Open Watcom",
        "Open Watcom" )
pick(   UNINS_NO_OW_INST,
        "The uninstaller could not locate a valid Open Watcom installation to remove.",
        "The uninstaller could not locate a valid Open Watcom installation to remove." )
pick(   UNINS_CONFIRM,
        "You are about to uninstall Open Watcom from your computer.  Would you like to continue?",
        "You are about to uninstall Open Watcom from your computer.  Would you like to continue?" )
pick(   UNINS_COMPLETED,
        "Open Watcom has been removed from your computer.",
        "Open Watcom has been removed from your computer." )
