#pmake: build flat cpu_386 os_os2
#
# strgmt3s.lib -- stack based multi-thread 32-bit STRING library
#
processor  = 386
system     = os2
model      = mf
convention = stack
linkage    = static
mthreaded  = 1
fs_registration = yes

!include $(cpplib_dir)/string/string.mif
