#pmake: build large cpu_i86 os_win
#
# cplx7l.lib -- large memory-model COMPLEX library fpi for Windows
#
processor  = 087
system     = windows
model      = ml
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
