#pmake: nobuild debug flat cpu_386 os_nt
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
fs_registration = yes

lib_debug = 1

!include $(cpplib_dir)/runtime/runtime.mif
