#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# cont3r.lib -- register based 32-bit CONTAINER library
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static

!include $(cpplib_dir)/contain/contain.mif
