#include "fail.h"

void check_add( float result, unsigned line )
{
    if( result != 21 ) fail(line);
}

void check_subtract( double result, unsigned line )
{
    if( result != 13 ) fail(line);
}

void check_multiply( unsigned long int result, unsigned line )
{
    if( result != 68 ) fail(line);
}

void check_divide( char result, unsigned line )
{
    if( result != 4 ) fail(line);
}


signed char sc1;
unsigned char uc1;
char c1;
signed short ss1;
unsigned short us1;
short s1;
signed int si1;
unsigned int ui1;
int i1;
signed long int sli1;
unsigned long int uli1;
long int li1;
float f1;
double d1;
long double ld1;

signed char sc2;
unsigned char uc2;
char c2;
signed short ss2;
unsigned short us2;
short s2;
signed int si2;
unsigned int ui2;
int i2;
signed long int sli2;
unsigned long int uli2;
long int li2;
float f2;
double d2;
long double ld2;

int main( void )
{
    sc1 = 17;
    sc2 = 4;
    check_add( sc1 + sc2, __LINE__ );
    check_subtract( sc1 - sc2, __LINE__ );
    check_multiply( sc1 * sc2, __LINE__ );
    check_divide( sc1 / sc2, __LINE__ );
    sc1 = 17;
    uc2 = 4;
    check_add( sc1 + uc2, __LINE__ );
    check_subtract( sc1 - uc2, __LINE__ );
    check_multiply( sc1 * uc2, __LINE__ );
    check_divide( sc1 / uc2, __LINE__ );
    sc1 = 17;
    c2 = 4;
    check_add( sc1 + c2, __LINE__ );
    check_subtract( sc1 - c2, __LINE__ );
    check_multiply( sc1 * c2, __LINE__ );
    check_divide( sc1 / c2, __LINE__ );
    sc1 = 17;
    ss2 = 4;
    check_add( sc1 + ss2, __LINE__ );
    check_subtract( sc1 - ss2, __LINE__ );
    check_multiply( sc1 * ss2, __LINE__ );
    check_divide( sc1 / ss2, __LINE__ );
    sc1 = 17;
    us2 = 4;
    check_add( sc1 + us2, __LINE__ );
    check_subtract( sc1 - us2, __LINE__ );
    check_multiply( sc1 * us2, __LINE__ );
    check_divide( sc1 / us2, __LINE__ );
    sc1 = 17;
    s2 = 4;
    check_add( sc1 + s2, __LINE__ );
    check_subtract( sc1 - s2, __LINE__ );
    check_multiply( sc1 * s2, __LINE__ );
    check_divide( sc1 / s2, __LINE__ );
    sc1 = 17;
    si2 = 4;
    check_add( sc1 + si2, __LINE__ );
    check_subtract( sc1 - si2, __LINE__ );
    check_multiply( sc1 * si2, __LINE__ );
    check_divide( sc1 / si2, __LINE__ );
    sc1 = 17;
    ui2 = 4;
    check_add( sc1 + ui2, __LINE__ );
    check_subtract( sc1 - ui2, __LINE__ );
    check_multiply( sc1 * ui2, __LINE__ );
    check_divide( sc1 / ui2, __LINE__ );
    sc1 = 17;
    i2 = 4;
    check_add( sc1 + i2, __LINE__ );
    check_subtract( sc1 - i2, __LINE__ );
    check_multiply( sc1 * i2, __LINE__ );
    check_divide( sc1 / i2, __LINE__ );
    sc1 = 17;
    sli2 = 4;
    check_add( sc1 + sli2, __LINE__ );
    check_subtract( sc1 - sli2, __LINE__ );
    check_multiply( sc1 * sli2, __LINE__ );
    check_divide( sc1 / sli2, __LINE__ );
    sc1 = 17;
    uli2 = 4;
    check_add( sc1 + uli2, __LINE__ );
    check_subtract( sc1 - uli2, __LINE__ );
    check_multiply( sc1 * uli2, __LINE__ );
    check_divide( sc1 / uli2, __LINE__ );
    sc1 = 17;
    li2 = 4;
    check_add( sc1 + li2, __LINE__ );
    check_subtract( sc1 - li2, __LINE__ );
    check_multiply( sc1 * li2, __LINE__ );
    check_divide( sc1 / li2, __LINE__ );
    sc1 = 17;
    f2 = 4;
    check_add( sc1 + f2, __LINE__ );
    check_subtract( sc1 - f2, __LINE__ );
    check_multiply( sc1 * f2, __LINE__ );
    check_divide( sc1 / f2, __LINE__ );
    sc1 = 17;
    d2 = 4;
    check_add( sc1 + d2, __LINE__ );
    check_subtract( sc1 - d2, __LINE__ );
    check_multiply( sc1 * d2, __LINE__ );
    check_divide( sc1 / d2, __LINE__ );
    sc1 = 17;
    ld2 = 4;
    check_add( sc1 + ld2, __LINE__ );
    check_subtract( sc1 - ld2, __LINE__ );
    check_multiply( sc1 * ld2, __LINE__ );
    check_divide( sc1 / ld2, __LINE__ );
    uc1 = 17;
    sc2 = 4;
    check_add( uc1 + sc2, __LINE__ );
    check_subtract( uc1 - sc2, __LINE__ );
    check_multiply( uc1 * sc2, __LINE__ );
    check_divide( uc1 / sc2, __LINE__ );
    uc1 = 17;
    uc2 = 4;
    check_add( uc1 + uc2, __LINE__ );
    check_subtract( uc1 - uc2, __LINE__ );
    check_multiply( uc1 * uc2, __LINE__ );
    check_divide( uc1 / uc2, __LINE__ );
    uc1 = 17;
    c2 = 4;
    check_add( uc1 + c2, __LINE__ );
    check_subtract( uc1 - c2, __LINE__ );
    check_multiply( uc1 * c2, __LINE__ );
    check_divide( uc1 / c2, __LINE__ );
    uc1 = 17;
    ss2 = 4;
    check_add( uc1 + ss2, __LINE__ );
    check_subtract( uc1 - ss2, __LINE__ );
    check_multiply( uc1 * ss2, __LINE__ );
    check_divide( uc1 / ss2, __LINE__ );
    uc1 = 17;
    us2 = 4;
    check_add( uc1 + us2, __LINE__ );
    check_subtract( uc1 - us2, __LINE__ );
    check_multiply( uc1 * us2, __LINE__ );
    check_divide( uc1 / us2, __LINE__ );
    uc1 = 17;
    s2 = 4;
    check_add( uc1 + s2, __LINE__ );
    check_subtract( uc1 - s2, __LINE__ );
    check_multiply( uc1 * s2, __LINE__ );
    check_divide( uc1 / s2, __LINE__ );
    uc1 = 17;
    si2 = 4;
    check_add( uc1 + si2, __LINE__ );
    check_subtract( uc1 - si2, __LINE__ );
    check_multiply( uc1 * si2, __LINE__ );
    check_divide( uc1 / si2, __LINE__ );
    uc1 = 17;
    ui2 = 4;
    check_add( uc1 + ui2, __LINE__ );
    check_subtract( uc1 - ui2, __LINE__ );
    check_multiply( uc1 * ui2, __LINE__ );
    check_divide( uc1 / ui2, __LINE__ );
    uc1 = 17;
    i2 = 4;
    check_add( uc1 + i2, __LINE__ );
    check_subtract( uc1 - i2, __LINE__ );
    check_multiply( uc1 * i2, __LINE__ );
    check_divide( uc1 / i2, __LINE__ );
    uc1 = 17;
    sli2 = 4;
    check_add( uc1 + sli2, __LINE__ );
    check_subtract( uc1 - sli2, __LINE__ );
    check_multiply( uc1 * sli2, __LINE__ );
    check_divide( uc1 / sli2, __LINE__ );
    uc1 = 17;
    uli2 = 4;
    check_add( uc1 + uli2, __LINE__ );
    check_subtract( uc1 - uli2, __LINE__ );
    check_multiply( uc1 * uli2, __LINE__ );
    check_divide( uc1 / uli2, __LINE__ );
    uc1 = 17;
    li2 = 4;
    check_add( uc1 + li2, __LINE__ );
    check_subtract( uc1 - li2, __LINE__ );
    check_multiply( uc1 * li2, __LINE__ );
    check_divide( uc1 / li2, __LINE__ );
    uc1 = 17;
    f2 = 4;
    check_add( uc1 + f2, __LINE__ );
    check_subtract( uc1 - f2, __LINE__ );
    check_multiply( uc1 * f2, __LINE__ );
    check_divide( uc1 / f2, __LINE__ );
    uc1 = 17;
    d2 = 4;
    check_add( uc1 + d2, __LINE__ );
    check_subtract( uc1 - d2, __LINE__ );
    check_multiply( uc1 * d2, __LINE__ );
    check_divide( uc1 / d2, __LINE__ );
    uc1 = 17;
    ld2 = 4;
    check_add( uc1 + ld2, __LINE__ );
    check_subtract( uc1 - ld2, __LINE__ );
    check_multiply( uc1 * ld2, __LINE__ );
    check_divide( uc1 / ld2, __LINE__ );
    c1 = 17;
    sc2 = 4;
    check_add( c1 + sc2, __LINE__ );
    check_subtract( c1 - sc2, __LINE__ );
    check_multiply( c1 * sc2, __LINE__ );
    check_divide( c1 / sc2, __LINE__ );
    c1 = 17;
    uc2 = 4;
    check_add( c1 + uc2, __LINE__ );
    check_subtract( c1 - uc2, __LINE__ );
    check_multiply( c1 * uc2, __LINE__ );
    check_divide( c1 / uc2, __LINE__ );
    c1 = 17;
    c2 = 4;
    check_add( c1 + c2, __LINE__ );
    check_subtract( c1 - c2, __LINE__ );
    check_multiply( c1 * c2, __LINE__ );
    check_divide( c1 / c2, __LINE__ );
    c1 = 17;
    ss2 = 4;
    check_add( c1 + ss2, __LINE__ );
    check_subtract( c1 - ss2, __LINE__ );
    check_multiply( c1 * ss2, __LINE__ );
    check_divide( c1 / ss2, __LINE__ );
    c1 = 17;
    us2 = 4;
    check_add( c1 + us2, __LINE__ );
    check_subtract( c1 - us2, __LINE__ );
    check_multiply( c1 * us2, __LINE__ );
    check_divide( c1 / us2, __LINE__ );
    c1 = 17;
    s2 = 4;
    check_add( c1 + s2, __LINE__ );
    check_subtract( c1 - s2, __LINE__ );
    check_multiply( c1 * s2, __LINE__ );
    check_divide( c1 / s2, __LINE__ );
    c1 = 17;
    si2 = 4;
    check_add( c1 + si2, __LINE__ );
    check_subtract( c1 - si2, __LINE__ );
    check_multiply( c1 * si2, __LINE__ );
    check_divide( c1 / si2, __LINE__ );
    c1 = 17;
    ui2 = 4;
    check_add( c1 + ui2, __LINE__ );
    check_subtract( c1 - ui2, __LINE__ );
    check_multiply( c1 * ui2, __LINE__ );
    check_divide( c1 / ui2, __LINE__ );
    c1 = 17;
    i2 = 4;
    check_add( c1 + i2, __LINE__ );
    check_subtract( c1 - i2, __LINE__ );
    check_multiply( c1 * i2, __LINE__ );
    check_divide( c1 / i2, __LINE__ );
    c1 = 17;
    sli2 = 4;
    check_add( c1 + sli2, __LINE__ );
    check_subtract( c1 - sli2, __LINE__ );
    check_multiply( c1 * sli2, __LINE__ );
    check_divide( c1 / sli2, __LINE__ );
    c1 = 17;
    uli2 = 4;
    check_add( c1 + uli2, __LINE__ );
    check_subtract( c1 - uli2, __LINE__ );
    check_multiply( c1 * uli2, __LINE__ );
    check_divide( c1 / uli2, __LINE__ );
    c1 = 17;
    li2 = 4;
    check_add( c1 + li2, __LINE__ );
    check_subtract( c1 - li2, __LINE__ );
    check_multiply( c1 * li2, __LINE__ );
    check_divide( c1 / li2, __LINE__ );
    c1 = 17;
    f2 = 4;
    check_add( c1 + f2, __LINE__ );
    check_subtract( c1 - f2, __LINE__ );
    check_multiply( c1 * f2, __LINE__ );
    check_divide( c1 / f2, __LINE__ );
    c1 = 17;
    d2 = 4;
    check_add( c1 + d2, __LINE__ );
    check_subtract( c1 - d2, __LINE__ );
    check_multiply( c1 * d2, __LINE__ );
    check_divide( c1 / d2, __LINE__ );
    c1 = 17;
    ld2 = 4;
    check_add( c1 + ld2, __LINE__ );
    check_subtract( c1 - ld2, __LINE__ );
    check_multiply( c1 * ld2, __LINE__ );
    check_divide( c1 / ld2, __LINE__ );
    ss1 = 17;
    sc2 = 4;
    check_add( ss1 + sc2, __LINE__ );
    check_subtract( ss1 - sc2, __LINE__ );
    check_multiply( ss1 * sc2, __LINE__ );
    check_divide( ss1 / sc2, __LINE__ );
    ss1 = 17;
    uc2 = 4;
    check_add( ss1 + uc2, __LINE__ );
    check_subtract( ss1 - uc2, __LINE__ );
    check_multiply( ss1 * uc2, __LINE__ );
    check_divide( ss1 / uc2, __LINE__ );
    ss1 = 17;
    c2 = 4;
    check_add( ss1 + c2, __LINE__ );
    check_subtract( ss1 - c2, __LINE__ );
    check_multiply( ss1 * c2, __LINE__ );
    check_divide( ss1 / c2, __LINE__ );
    ss1 = 17;
    ss2 = 4;
    check_add( ss1 + ss2, __LINE__ );
    check_subtract( ss1 - ss2, __LINE__ );
    check_multiply( ss1 * ss2, __LINE__ );
    check_divide( ss1 / ss2, __LINE__ );
    ss1 = 17;
    us2 = 4;
    check_add( ss1 + us2, __LINE__ );
    check_subtract( ss1 - us2, __LINE__ );
    check_multiply( ss1 * us2, __LINE__ );
    check_divide( ss1 / us2, __LINE__ );
    ss1 = 17;
    s2 = 4;
    check_add( ss1 + s2, __LINE__ );
    check_subtract( ss1 - s2, __LINE__ );
    check_multiply( ss1 * s2, __LINE__ );
    check_divide( ss1 / s2, __LINE__ );
    ss1 = 17;
    si2 = 4;
    check_add( ss1 + si2, __LINE__ );
    check_subtract( ss1 - si2, __LINE__ );
    check_multiply( ss1 * si2, __LINE__ );
    check_divide( ss1 / si2, __LINE__ );
    ss1 = 17;
    ui2 = 4;
    check_add( ss1 + ui2, __LINE__ );
    check_subtract( ss1 - ui2, __LINE__ );
    check_multiply( ss1 * ui2, __LINE__ );
    check_divide( ss1 / ui2, __LINE__ );
    ss1 = 17;
    i2 = 4;
    check_add( ss1 + i2, __LINE__ );
    check_subtract( ss1 - i2, __LINE__ );
    check_multiply( ss1 * i2, __LINE__ );
    check_divide( ss1 / i2, __LINE__ );
    ss1 = 17;
    sli2 = 4;
    check_add( ss1 + sli2, __LINE__ );
    check_subtract( ss1 - sli2, __LINE__ );
    check_multiply( ss1 * sli2, __LINE__ );
    check_divide( ss1 / sli2, __LINE__ );
    ss1 = 17;
    uli2 = 4;
    check_add( ss1 + uli2, __LINE__ );
    check_subtract( ss1 - uli2, __LINE__ );
    check_multiply( ss1 * uli2, __LINE__ );
    check_divide( ss1 / uli2, __LINE__ );
    ss1 = 17;
    li2 = 4;
    check_add( ss1 + li2, __LINE__ );
    check_subtract( ss1 - li2, __LINE__ );
    check_multiply( ss1 * li2, __LINE__ );
    check_divide( ss1 / li2, __LINE__ );
    ss1 = 17;
    f2 = 4;
    check_add( ss1 + f2, __LINE__ );
    check_subtract( ss1 - f2, __LINE__ );
    check_multiply( ss1 * f2, __LINE__ );
    check_divide( ss1 / f2, __LINE__ );
    ss1 = 17;
    d2 = 4;
    check_add( ss1 + d2, __LINE__ );
    check_subtract( ss1 - d2, __LINE__ );
    check_multiply( ss1 * d2, __LINE__ );
    check_divide( ss1 / d2, __LINE__ );
    ss1 = 17;
    ld2 = 4;
    check_add( ss1 + ld2, __LINE__ );
    check_subtract( ss1 - ld2, __LINE__ );
    check_multiply( ss1 * ld2, __LINE__ );
    check_divide( ss1 / ld2, __LINE__ );
    us1 = 17;
    sc2 = 4;
    check_add( us1 + sc2, __LINE__ );
    check_subtract( us1 - sc2, __LINE__ );
    check_multiply( us1 * sc2, __LINE__ );
    check_divide( us1 / sc2, __LINE__ );
    us1 = 17;
    uc2 = 4;
    check_add( us1 + uc2, __LINE__ );
    check_subtract( us1 - uc2, __LINE__ );
    check_multiply( us1 * uc2, __LINE__ );
    check_divide( us1 / uc2, __LINE__ );
    us1 = 17;
    c2 = 4;
    check_add( us1 + c2, __LINE__ );
    check_subtract( us1 - c2, __LINE__ );
    check_multiply( us1 * c2, __LINE__ );
    check_divide( us1 / c2, __LINE__ );
    us1 = 17;
    ss2 = 4;
    check_add( us1 + ss2, __LINE__ );
    check_subtract( us1 - ss2, __LINE__ );
    check_multiply( us1 * ss2, __LINE__ );
    check_divide( us1 / ss2, __LINE__ );
    us1 = 17;
    us2 = 4;
    check_add( us1 + us2, __LINE__ );
    check_subtract( us1 - us2, __LINE__ );
    check_multiply( us1 * us2, __LINE__ );
    check_divide( us1 / us2, __LINE__ );
    us1 = 17;
    s2 = 4;
    check_add( us1 + s2, __LINE__ );
    check_subtract( us1 - s2, __LINE__ );
    check_multiply( us1 * s2, __LINE__ );
    check_divide( us1 / s2, __LINE__ );
    us1 = 17;
    si2 = 4;
    check_add( us1 + si2, __LINE__ );
    check_subtract( us1 - si2, __LINE__ );
    check_multiply( us1 * si2, __LINE__ );
    check_divide( us1 / si2, __LINE__ );
    us1 = 17;
    ui2 = 4;
    check_add( us1 + ui2, __LINE__ );
    check_subtract( us1 - ui2, __LINE__ );
    check_multiply( us1 * ui2, __LINE__ );
    check_divide( us1 / ui2, __LINE__ );
    us1 = 17;
    i2 = 4;
    check_add( us1 + i2, __LINE__ );
    check_subtract( us1 - i2, __LINE__ );
    check_multiply( us1 * i2, __LINE__ );
    check_divide( us1 / i2, __LINE__ );
    us1 = 17;
    sli2 = 4;
    check_add( us1 + sli2, __LINE__ );
    check_subtract( us1 - sli2, __LINE__ );
    check_multiply( us1 * sli2, __LINE__ );
    check_divide( us1 / sli2, __LINE__ );
    us1 = 17;
    uli2 = 4;
    check_add( us1 + uli2, __LINE__ );
    check_subtract( us1 - uli2, __LINE__ );
    check_multiply( us1 * uli2, __LINE__ );
    check_divide( us1 / uli2, __LINE__ );
    us1 = 17;
    li2 = 4;
    check_add( us1 + li2, __LINE__ );
    check_subtract( us1 - li2, __LINE__ );
    check_multiply( us1 * li2, __LINE__ );
    check_divide( us1 / li2, __LINE__ );
    us1 = 17;
    f2 = 4;
    check_add( us1 + f2, __LINE__ );
    check_subtract( us1 - f2, __LINE__ );
    check_multiply( us1 * f2, __LINE__ );
    check_divide( us1 / f2, __LINE__ );
    us1 = 17;
    d2 = 4;
    check_add( us1 + d2, __LINE__ );
    check_subtract( us1 - d2, __LINE__ );
    check_multiply( us1 * d2, __LINE__ );
    check_divide( us1 / d2, __LINE__ );
    us1 = 17;
    ld2 = 4;
    check_add( us1 + ld2, __LINE__ );
    check_subtract( us1 - ld2, __LINE__ );
    check_multiply( us1 * ld2, __LINE__ );
    check_divide( us1 / ld2, __LINE__ );
    s1 = 17;
    sc2 = 4;
    check_add( s1 + sc2, __LINE__ );
    check_subtract( s1 - sc2, __LINE__ );
    check_multiply( s1 * sc2, __LINE__ );
    check_divide( s1 / sc2, __LINE__ );
    s1 = 17;
    uc2 = 4;
    check_add( s1 + uc2, __LINE__ );
    check_subtract( s1 - uc2, __LINE__ );
    check_multiply( s1 * uc2, __LINE__ );
    check_divide( s1 / uc2, __LINE__ );
    s1 = 17;
    c2 = 4;
    check_add( s1 + c2, __LINE__ );
    check_subtract( s1 - c2, __LINE__ );
    check_multiply( s1 * c2, __LINE__ );
    check_divide( s1 / c2, __LINE__ );
    s1 = 17;
    ss2 = 4;
    check_add( s1 + ss2, __LINE__ );
    check_subtract( s1 - ss2, __LINE__ );
    check_multiply( s1 * ss2, __LINE__ );
    check_divide( s1 / ss2, __LINE__ );
    s1 = 17;
    us2 = 4;
    check_add( s1 + us2, __LINE__ );
    check_subtract( s1 - us2, __LINE__ );
    check_multiply( s1 * us2, __LINE__ );
    check_divide( s1 / us2, __LINE__ );
    s1 = 17;
    s2 = 4;
    check_add( s1 + s2, __LINE__ );
    check_subtract( s1 - s2, __LINE__ );
    check_multiply( s1 * s2, __LINE__ );
    check_divide( s1 / s2, __LINE__ );
    s1 = 17;
    si2 = 4;
    check_add( s1 + si2, __LINE__ );
    check_subtract( s1 - si2, __LINE__ );
    check_multiply( s1 * si2, __LINE__ );
    check_divide( s1 / si2, __LINE__ );
    s1 = 17;
    ui2 = 4;
    check_add( s1 + ui2, __LINE__ );
    check_subtract( s1 - ui2, __LINE__ );
    check_multiply( s1 * ui2, __LINE__ );
    check_divide( s1 / ui2, __LINE__ );
    s1 = 17;
    i2 = 4;
    check_add( s1 + i2, __LINE__ );
    check_subtract( s1 - i2, __LINE__ );
    check_multiply( s1 * i2, __LINE__ );
    check_divide( s1 / i2, __LINE__ );
    s1 = 17;
    sli2 = 4;
    check_add( s1 + sli2, __LINE__ );
    check_subtract( s1 - sli2, __LINE__ );
    check_multiply( s1 * sli2, __LINE__ );
    check_divide( s1 / sli2, __LINE__ );
    s1 = 17;
    uli2 = 4;
    check_add( s1 + uli2, __LINE__ );
    check_subtract( s1 - uli2, __LINE__ );
    check_multiply( s1 * uli2, __LINE__ );
    check_divide( s1 / uli2, __LINE__ );
    s1 = 17;
    li2 = 4;
    check_add( s1 + li2, __LINE__ );
    check_subtract( s1 - li2, __LINE__ );
    check_multiply( s1 * li2, __LINE__ );
    check_divide( s1 / li2, __LINE__ );
    s1 = 17;
    f2 = 4;
    check_add( s1 + f2, __LINE__ );
    check_subtract( s1 - f2, __LINE__ );
    check_multiply( s1 * f2, __LINE__ );
    check_divide( s1 / f2, __LINE__ );
    s1 = 17;
    d2 = 4;
    check_add( s1 + d2, __LINE__ );
    check_subtract( s1 - d2, __LINE__ );
    check_multiply( s1 * d2, __LINE__ );
    check_divide( s1 / d2, __LINE__ );
    s1 = 17;
    ld2 = 4;
    check_add( s1 + ld2, __LINE__ );
    check_subtract( s1 - ld2, __LINE__ );
    check_multiply( s1 * ld2, __LINE__ );
    check_divide( s1 / ld2, __LINE__ );
    si1 = 17;
    sc2 = 4;
    check_add( si1 + sc2, __LINE__ );
    check_subtract( si1 - sc2, __LINE__ );
    check_multiply( si1 * sc2, __LINE__ );
    check_divide( si1 / sc2, __LINE__ );
    si1 = 17;
    uc2 = 4;
    check_add( si1 + uc2, __LINE__ );
    check_subtract( si1 - uc2, __LINE__ );
    check_multiply( si1 * uc2, __LINE__ );
    check_divide( si1 / uc2, __LINE__ );
    si1 = 17;
    c2 = 4;
    check_add( si1 + c2, __LINE__ );
    check_subtract( si1 - c2, __LINE__ );
    check_multiply( si1 * c2, __LINE__ );
    check_divide( si1 / c2, __LINE__ );
    si1 = 17;
    ss2 = 4;
    check_add( si1 + ss2, __LINE__ );
    check_subtract( si1 - ss2, __LINE__ );
    check_multiply( si1 * ss2, __LINE__ );
    check_divide( si1 / ss2, __LINE__ );
    si1 = 17;
    us2 = 4;
    check_add( si1 + us2, __LINE__ );
    check_subtract( si1 - us2, __LINE__ );
    check_multiply( si1 * us2, __LINE__ );
    check_divide( si1 / us2, __LINE__ );
    si1 = 17;
    s2 = 4;
    check_add( si1 + s2, __LINE__ );
    check_subtract( si1 - s2, __LINE__ );
    check_multiply( si1 * s2, __LINE__ );
    check_divide( si1 / s2, __LINE__ );
    si1 = 17;
    si2 = 4;
    check_add( si1 + si2, __LINE__ );
    check_subtract( si1 - si2, __LINE__ );
    check_multiply( si1 * si2, __LINE__ );
    check_divide( si1 / si2, __LINE__ );
    si1 = 17;
    ui2 = 4;
    check_add( si1 + ui2, __LINE__ );
    check_subtract( si1 - ui2, __LINE__ );
    check_multiply( si1 * ui2, __LINE__ );
    check_divide( si1 / ui2, __LINE__ );
    si1 = 17;
    i2 = 4;
    check_add( si1 + i2, __LINE__ );
    check_subtract( si1 - i2, __LINE__ );
    check_multiply( si1 * i2, __LINE__ );
    check_divide( si1 / i2, __LINE__ );
    si1 = 17;
    sli2 = 4;
    check_add( si1 + sli2, __LINE__ );
    check_subtract( si1 - sli2, __LINE__ );
    check_multiply( si1 * sli2, __LINE__ );
    check_divide( si1 / sli2, __LINE__ );
    _PASS;
}
