#pmake: build medium cpu_i86 os_win
#
# plibm -- 16-bit medium memory-model PLIB for Windows
#
processor  = 086
system     = windows
model      = mm
linkage    = static

!include $(cpplib_dir)/runtime/plib.mif
