type = ui
os = dos
build_target = dos
sys=pharlap
compiler = comp386
model=f
extra_option = op offset=64k
wreslib=$(wres_dir)\lib\wresf

ext = exp

target : sample.$(ext) .SYMBOLIC

samp2 : samp2.$(ext)  .SYMBOLIC

!include ../makefile
