name: artifacts-delete-call
description: 'Call to delete workflow run artifacs'
inputs:
  exclude:
    description: 'exclude files start mask'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    uses: ./.github/actions/curlcmd
  - name: Call to delete Artifacts
    run: |
      $response = ${{steps.curlcmd.outputs.gh1}} `
      -X POST "${{steps.curlcmd.outputs.gh2}}/dispatches" `
      -d '{"event_type":"delete_artifacts","client_payload":{"runid":"${{github.run_id}}","exclude":"${{inputs.exclude}}"}}'
      if( '${{env.OWDEBUG}}' -eq '1' ) { $response }
    shell: pwsh
