name: artifacts-delete-call
description: 'Call to delete workflow run artifacs'
inputs:
  exclude:
    description: 'exclude files start mask'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
    needs: wikiupdate
    name: Delete Artifacs
    runs-on: ubuntu-latest
    steps:
    - name: Setup curl options
      id: curlcmd
      uses: "./.github/actions/curlcmd"
    - name: Delete Artifacts
      run: |
        $response = ${{ steps.curlcmd.outputs.gh }} -H "Authorization: Bearer ${{ github.token }}" `
        -X POST "https://api.github.com/repos/${{ github.repository }}/dispatches" `
        --data-raw "{\"event_type\": \"delete_artifacts\", \"client_payload\": {\"runid\": \"${{ github.run-id }}\"}}"
        if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
      shell: pwsh
