#pmake: build huge cpu_i86 os_dos os_os2 os_win os_qnx
#
# strgh.lib -- huge memory-model STRING library
#
processor  = 086
system     = generic
model      = mh
linkage    = static

!include $(cpplib_dir)/string/string.mif
