#pmake: build huge cpu_i86 os_osi
#
# strgh.lib -- huge memory-model STRING library
#
processor  = 086
system     = generic
model      = mh
linkage    = static

!include $(cpplib_dir)/string/string.mif
