wasmtest_name = test3

dis_objs = &
3dnow.dis &
absjumps.dis &
addrmode.dis &
allign.dis &
callcnv1.dis &
callcnv2.dis &
callcnv3.dis &
callcnv4.dis &
callcnv5.dis &
commdef.dis &
datamix1.dis &
datamix2.dis &
dgroup.dis &
dsxfork.dis &
dsxhdlr.dis &
expr01.dis &
extern1.dis &
extern2.dis &
extern3.dis &
extprocf.dis &
extprocn.dis &
fpu1.dib &
fpu2.dib &
fpu3.dib &
fpu4.dib &
fpu5.dib &
fpu6.dib &
fpu7.dib &
indirect.dis &
jmpshrt.dis &
lsxxx.dis &
mmx.dis &
movx.dis &
mseg.dis &
opi8u.dis &
plsintr.dis &
push.dis &
retiret.dis &
seg16.dis &
segatrep.dis &
segregs.dis &
shift.dis &
#sse.dis &
sse2.dis &
sse3.dis &
structdd.dis &
support.dis &
tbyte.dis &
testequ.dis &
tst1.dis

asm_flags_callcnv1 = -zcm
asm_flags_callcnv3 = -3r
asm_flags_callcnv4 = -3s
asm_flags_callcnv5 = -zcm
asm_flags_jmpshrt = -zcm
asm_flags_retiret = -zcm
asm_flags_support = -zcm -Dmemodel=large
asm_flags_fpu1 = -fpi87
asm_flags_fpu2 = -fpi87
asm_flags_fpu3 = -fpi87
asm_flags_fpu4 = -fpi87
asm_flags_fpu5 = -fpi
asm_flags_fpu6 = -fpi
asm_flags_fpu7 = -fpi

!include ../test.mif
