trappick( TRP_ERR_BAD_TRAP_FILE,
	"Invalid trap file",
	"jInvalid trap file" )
trappick( TRP_ERR_CANT_LOAD_TRAP,
	"Unable to load trap file",
	"jUnable to load trap file" )
trappick( TRP_ERR_OUT_OF_MEMORY,
	"Out of memory",
	"jOut of memory" )
trappick( TRP_ERR_OUT_OF_DOS_MEMORY,
	"Out of DOS memory",
	"jOut of DOS memory" )
trappick( TRP_ERR_WRONG_TRAP_VERSION,
	"Incorrect version of trap file",
	"jIncorrect version of trap file" )
trappick( TRP_ERR_CANT_REGISTER_SERVER,
	"Unable to register server",
	"jUnable to register server" )
trappick( TRP_ERR_CANT_FIND_SERVER,
	"Unable to register server",
	"jUnable to register server" )
trappick( TRP_ERR_CANT_CONNECT,
	"Unable to connect to server",
	"jUnable to connect to server" )
trappick( TRP_ERR_WRONG_SERVER_VERSION,
	"Incorrect version of debug server",
	"jIncorrect version of debug server" )
trappick( TRP_EXC_divide_overflow,
	"divide overflow",
	"jdivide overflow" )
trappick( TRP_EXC_non_maskable_interrupt,
	"non-maskable interrupt",
	"jnon-maskable interrupt" )
trappick( TRP_EXC_integer_overflow,
	"integer overflow",
	"jinteger overflow" )
trappick( TRP_EXC_bounds_check,
	"bounds check",
	"jbounds check" )
trappick( TRP_EXC_invalid_opcode,
	"invalid opcode",
	"jinvalid opcode" )
trappick( TRP_EXC_coprocessor_not_available,
	"coprocessor not available",
	"jcoprocessor not available" )
trappick( TRP_EXC_double_fault,
	"double fault",
	"jdouble fault" )
trappick( TRP_EXC_coprocessor_segment_overrun,
	"coprocessor segment overrun",
	"jcoprocessor segment overrun" )
trappick( TRP_EXC_invalid_TSS,
	"invalid TSS",
	"jinvalid TSS" )
trappick( TRP_EXC_segment_not_present,
	"segment not present",
	"jsegment not present" )
trappick( TRP_EXC_stack_exception,
	"stack exception",
	"jstack exception" )
trappick( TRP_EXC_general_protection_fault,
	"general protection fault",
	"jgeneral protection fault" )
trappick( TRP_EXC_page_fault,
	"page fault",
	"jpage fault" )
trappick( TRP_EXC_coprocessor_error,
	"coprocessor error",
	"jcoprocessor error" )
trappick( TRP_EXC_unknown,
	"unknown exception",
	"junknown exception" )
trappick( TRP_EXC_data_type_misalignment,
	"data type misalignment",
	"jdata type misalignment" )
trappick( TRP_EXC_illegal_instruction,
	"illegal instruction",
	"jillegal instruction" )
trappick( TRP_EXC_integer_divide_by_zero,
	"integer divide by zero",
	"jinteger divide by zero" )
trappick( TRP_EXC_privileged_instruction,
	"privileged instruction",
	"jprivileged instruction" )
trappick( TRP_EXC_floating_point_denormal_operand,
	"floating point denormal operand",
	"jfloating point denormal operand" )
trappick( TRP_EXC_floating_point_divide_by_zero,
	"floating point divide by zero",
	"jfloating point divide by zero" )
trappick( TRP_EXC_floating_point_inexact_result,
	"floating point inexact result",
	"jfloating point inexact result" )
trappick( TRP_EXC_floating_point_invalid_operation,
	"floating point invalid operation",
	"jfloating point invalid operation" )
trappick( TRP_EXC_floating_point_overflow,
	"floating point overflow",
	"jfloating point overflow" )
trappick( TRP_EXC_floating_point_stack_check,
	"floating point stack check",
	"jfloating point stack check" )
trappick( TRP_EXC_floating_point_underflow,
	"floating point underflow",
	"jfloating point underflow" )
trappick( TRP_EXC_access_violation,
	"access violation",
	"jaccess violation" )
trappick( TRP_ERR_invalid_function_number,
	"invalid function number",
	"jinvalid function number" )
trappick( TRP_ERR_file_not_found,
	"file not found",
	"jfile not found" )
trappick( TRP_ERR_path_not_found,
	"path not found",
	"jpath not found" )
trappick( TRP_ERR_too_many_open_files,
	"too many open files",
	"jtoo many open files" )
trappick( TRP_ERR_access_denied,
	"access denied",
	"jaccess denied" )
trappick( TRP_ERR_invalid_handle,
	"invalid handle",
	"jinvalid handle" )
trappick( TRP_ERR_memory_control_blocks_destroyed,
	"memory control blocks destroyed",
	"jmemory control blocks destroyed" )
trappick( TRP_ERR_insufficient_memory,
	"insufficient memory",
	"jinsufficient memory" )
trappick( TRP_ERR_invalid_memory_block_address,
	"invalid memory block address",
	"jinvalid memory block address" )
trappick( TRP_ERR_invalid_environment,
	"invalid environment",
	"jinvalid environment" )
trappick( TRP_ERR_invalid_format,
	"invalid format",
	"jinvalid format" )
trappick( TRP_ERR_invalid_access_code,
	"invalid access code",
	"jinvalid access code" )
trappick( TRP_ERR_invalid_data,
	"invalid data",
	"jinvalid data" )
trappick( TRP_ERR_reserved_error_code,
	"reserved error code",
	"jreserved error code" )
trappick( TRP_ERR_invalid_drive_was_specified,
	"invalid drive was specified",
	"jinvalid drive was specified" )
trappick( TRP_ERR_attempt_to_remove_current_directory,
	"attempt to remove current directory",
	"jattempt to remove current directory" )
trappick( TRP_ERR_not_same_device,
	"not same device",
	"jnot same device" )
trappick( TRP_ERR_no_more_files,
	"no more files",
	"jno more files" )
trappick( TRP_ERR_must_use_rsi,
	"must use the '/tr=rsi' command line option to debug a rational application",
	"jmust use the '/tr=rsi' command line option to debug a rational application" )
trappick( TRP_ERR_must_use_pls,
	"must use the '/tr=pls' command line option to debug a pharlap application",
	"jmust use the '/tr=pls' command line option to debug a pharlap application" )
trappick( TRP_ERR_unknown_system_error,
	"unknown system error",
	"junknown system error" )
trappick( TRP_ERR_not_from_command,
	"Cannot be executed from the command line",
	"jCannot be executed from the command line" )
trappick( TRP_ERR_no_extender,
	"Unable to locate DOS extender. Probable cause: incorrectly set PATH",
	"jUnable to locate DOS extender. Probable cause: incorrectly set PATH" )
trappick( TRP_ERR_cant_start_extender,
	"Could not start DOS extender. Probable cause: insufficent DOS memory",
	"jCould not start DOS extender. Probable cause: insufficent DOS memory" )
trappick( TRP_ERR_bad_dpmi,
	"Cannot debug a DOS extender application under DPMI 0.9.  Use remote debugging.",
	"jCannot debug a DOS extender application under DPMI 0.9.  Use remote debugging." )
trappick( TRP_QNX_hangup,
	"hangup",
	"jhangup" )
trappick( TRP_QNX_user_interrupt,
	"user interrupt",
	"juser interrupt" )
trappick( TRP_QNX_quit,
	"quit",
	"jquit" )
trappick( TRP_QNX_trap,
	"trap",
	"jtrap" )
trappick( TRP_QNX_abort,
	"abort",
	"jabort" )
trappick( TRP_QNX_emt,
	"emt",
	"jemt" )
trappick( TRP_QNX_floating_point_error,
	"floating point error",
	"jfloating point error" )
trappick( TRP_QNX_process_killed,
	"process killed",
	"jprocess killed" )
trappick( TRP_QNX_bus_error,
	"bus error",
	"jbus error" )
trappick( TRP_QNX_sys,
	"sys",
	"jsys" )
trappick( TRP_QNX_broken_pipe,
	"broken pipe",
	"jbroken pipe" )
trappick( TRP_QNX_alarm,
	"alarm",
	"jalarm" )
trappick( TRP_QNX_process_termination,
	"process termination",
	"jprocess termination" )
trappick( TRP_QNX_user_signal_1,
	"user signal 1",
	"juser signal 1" )
trappick( TRP_QNX_user_signal_2,
	"user signal 2",
	"juser signal 2" )
trappick( TRP_QNX_child_stopped,
	"child stopped",
	"jchild stopped" )
trappick( TRP_QNX_power_fail,
	"power fail",
	"jpower fail" )
trappick( TRP_QNX_winch,
	"winch",
	"jwinch" )
trappick( TRP_QNX_urgent,
	"urgent",
	"jurgent" )
trappick( TRP_QNX_poll,
	"poll",
	"jpoll" )
trappick( TRP_QNX_process_stopped,
	"process stopped",
	"jprocess stopped" )
trappick( TRP_QNX_process_continued,
	"process continued",
	"jprocess continued" )
trappick( TRP_QNX_device_ready,
	"device ready",
	"jdevice ready" )
trappick( TRP_QNX_no_proxy,
	"can not create proxy",
	"jcan not create proxy" )
trappick( TRP_QNX_invalid_node_number,
	"invalid node number",
	"jinvalid node number" )
trappick( TRP_NT_status_user_apc,
	"user apc",
	"juser apc" );
trappick( TRP_NT_status_guard_page_violation,
	"guard page violation",
	"jguard page violation" );
trappick( TRP_NT_status_in_page_error,
	"in page error",
	"jin page error" );
trappick( TRP_NT_status_no_memory,
	"no memory",
	"jno memory" );
trappick( TRP_NT_status_invalid_disposition,
	"invalid disposition",
	"jinvalid disposition" );
trappick( TRP_NT_status_stack_overflow,
	"stack overflow",
	"jstack overflow" );
trappick( TRP_NT_invalid_handle,
	"Invalid handle passed to system API",
	"jInvalid handle passed to system API" )
trappick( TRP_NT_wait_0,
	"wait 0",
	"jwait 0" )
trappick( TRP_NT_abandoned_Wait_0,
	"abandoned Wait 0",
	"jabandoned Wait 0" )
trappick( TRP_NT_timeout,
	"timeout",
	"jtimeout" )
trappick( TRP_NT_pending,
	"pending",
	"jpending" )
trappick( TRP_NT_noncontinuable_exception,
	"non-continuable exception",
	"jnon-continuable exception" )
trappick( TRP_NT_control_C_exit,
	"control C exit",
	"jcontrol C exit" )
trappick( TRP_NT_wow_warning,
	"cannot debug application since NTVDM is already running.  Killing NTVDM will allow debugging to continue but will stop any running 16-bit applications. Kill NTVDM?",
	"jcannot debug application since NTVDM is already running.  Killing NTVDM will allow debugging to continue but will stop any running 16-bit applications. Kill NTVDM?" )
trappick( TRP_The_WATCOM_Debugger,
	"The WATCOM Debugger",
	"jThe WATCOM Debugger" )
trappick( TRP_WIN_Failed_to_get_interrupt_hook,
	"Failed to get interrupt hook",
	"jFailed to get interrupt hook" )
trappick( TRP_WIN_Failed_to_get_notify_hook,
	"Failed to get notify hook",
	"jFailed to get notify hook" )
trappick( TRP_WIN_no_can_do,
	"The debugger cannot be used while the application is running.",
	"jThe debugger cannot be used while the application is running." )
trappick( TRP_WIN_LOADERR,
	"Internal Error - LOADERR",
	"jInternal Error - LOADERR" )
trappick( TRP_WIN_WDEBUG386,
	"WDEBUG.386 must be installed in the [386Enh] section of SYSTEM.INI in order to debug a 32-bit application",
	"jWDEBUG.386 must be installed in the [386Enh] section of SYSTEM.INI in order to debug a 32-bit application" )
trappick( TRP_WIN_NOINT1,
	"Internal Error - expecting INT 1",
	"jInternal Error - expecting INT 1" )
trappick( TRP_WIN_NOINT3,
	"Internal Error - expecting INT 3",
	"jInternal Error - expecting INT 3" )
trappick( TRP_WIN_LoadModule_failed,
	"LoadModule() failed",
	"jLoadModule() failed" )
trappick( TRP_WIN_NOSTART,
	"Internal Error - unable to find application start address",
	"jInternal Error - unable to find application start address" )
trappick( TRP_WIN_NOWINDEBUG,
	"NOWINDEBUG",
	"jNOWINDEBUG" )
trappick( TRP_WIN_Unexpected_notification,
	"Internal error: Unexpected notification - expecting break point",
	"jInternal error: Unexpected notification - expecting break point" )
trappick( TRP_OS2_Wrong_Version,
	"Not running OS/2 2.x",
	"jNot running OS/2 2.x" )
trappick( TRP_OS2_no_info,
	"Internal error - Can not access info segments",
	"jInternal error - Can not access info segments" )
trappick( TRP_OS2_not_1p2,
	"Not running OS/2 1.2",
	"jNot running OS/2 1.2" )
trappick( TRP_OS2_no_dll,
	"Internal error - Could not find DLL directory",
	"jInternal error - Could not find DLL directory" )
trappick( TRP_OS2_no_pipe,
	"Internal error - Could not create pipe",
	"jInternal error - Could not create pipe" )
trappick( TRP_OS2_no_help,
	"Internal error - Could not start OS2V2HLP.EXE",
	"jInternal error - Could not start OS2V2HLP.EXE" )
trappick( TRP_OS2_no_pm_from_vio,
	"Cannot debug a PM application from an OS/2 Windowed session",
	"jCannot debug a PM application from an OS/2 Windowed session" )
trappick( TRP_OS2_cannot_set_thread_priority,
	"Internal error - cannot set thread priority",
	"jInternal error - cannot set thread priority" )
trappick( TRP_OS2_cannot_create_helper_thread,
	"cannot create helper thread",
	"jcannot create helper thread" )
trappick( TRP_ERR_cannot_access_parallel_ports,
	"Unable to access parallel ports",
	"jUnable to access parallel ports" )
trappick( TRP_ERR_invalid_parallel_port_number,
	"invalid parallel port number",
	"jinvalid parallel port number" )
trappick( TRP_ERR_parallel_port_not_present,
	"parallel port not present",
	"jparallel port not present" )
trappick( TRP_ERR_invalid_serial_port_number,
	"invalid serial port number",
	"jinvalid serial port number" )
trappick( TRP_ERR_serial_port_does_not_exist,
	"serial port does not exist",
	"jserial port does not exist" )
trappick( TRP_ERR_serial_port_not_available,
	"serial port not available",
	"jserial port not available" )
trappick( TRP_ERR_could_not_set_serial_port_characteristics,
	"could not set serial port characteristics",
	"jcould not set serial port characteristics" )
trappick( TRP_ERR_invalid_maximum_baud_rate,
	"invalid maximum baud rate",
	"jinvalid maximum baud rate" )
trappick( TRP_ERR_invalid_baud_rate,
	"invalid baud rate",
	"jinvalid baud rate" )
trappick( TRP_ERR_ambiguous_baud_rate,
	"ambiguous baud rate",
	"jambiguous baud rate" )
trappick( TRP_ERR_invalid_modem_string,
	"invalid modem string",
	"jinvalid modem string" )
trappick( TRP_ERR_timeout_on_modem_string,
	"timeout on modem string",
	"jtimeout on modem string" )
trappick( TRP_ERR_modem_failed_connection,
	"modem failed connection",
	"jmodem failed connection" )
trappick( TRP_ERR_NetBIOS_is_not_running,
	"NetBIOS is not running",
	"jNetBIOS is not running" )
trappick( TRP_ERR_can_not_start_server,
	"can not start server",
	"jcan not start server" )
trappick( TRP_ERR_IPX_SPX_not_present,
	"IPX/SPX not present",
	"jIPX/SPX not present" )
trappick( TRP_ERR_Netware_API_not_present,
	"Netware API not present",
	"jNetware API not present" )
trappick( TRP_ERR_NETWAREDRV_not_present,
	"NETWARE.DRV not present",
	"jNETWARE.DRV not present" )
trappick( TRP_ERR_IPX_not_initialized,
	"IPX not initialized",
	"jIPX not initialized" )
trappick( TRP_ERR_SPX_not_present,
	"SPX not present",
	"jSPX not present" )
trappick( TRP_ERR_can_not_obtain_socket,
	"can not obtain socket",
	"jcan not obtain socket" )
trappick( TRP_ERR_server_name_already_in_use,
	"server name already in use",
	"jserver name already in use" )
trappick( TRP_ERR_can_not_initialize_server,
	"can not initialize server",
	"jcan not initialize server" )
trappick( TRP_ERR_no_such_server,
	"no such server",
	"jno such server" )
trappick( TRP_ERR_invalid_server_name,
	"invalid server name",
	"jinvalid server name" )
trappick( TRP_ERR_unable_to_access_server,
	"unable to access server",
	"junable to access server" )
trappick( TRP_NMPBIND_running,
	"NMPBIND is already running",
	"jNMPBIND is already running" )
trappick( TRP_ERR_NMPBIND_not_found,
	"NMPBIND not found",
	"jNMPBIND not found" )
trappick( TRP_ERR_invalid_server_name_format_is,
	"invalid server name - format is name@machine",
	"jinvalid server name - format is name@machine" )
trappick( TRP_ERR_server_not_found,
	"server not found",
	"jserver not found" )
trappick( TRP_ERR_unable_to_initialize_TCPIP,
	"unable to initialize TCPIP",
	"junable to initialize TCPIP" )
trappick( TRP_ERR_unable_to_open_stream_socket,
	"unable to open stream socket",
	"junable to open stream socket" )
trappick( TRP_ERR_unable_to_bind_stream_socket,
	"unable to bind stream socket",
	"junable to bind stream socket" )
trappick( TRP_ERR_unable_to_get_socket_name,
	"unable to get socket name",
	"junable to get socket name" )
trappick( TRP_ERR_unable_to_parse_port_number,
	"unable to parse port number",
	"junable to parse port number" )
trappick( TRP_ERR_unknown_host,
	"unknown host",
	"junknown host" )
trappick( TRP_NLM_cant_debug_os,
	"Cannot Debug OS code. Entering system debugger.",
	"jCannot Debug OS code. Entering system debugger." )
trappick( TRP_NLM_no_unload,
	"This NLM may not be unloaded!",
	"jThis NLM may not be unloaded!" )
trappick( TRP_NLM_no_screen,
	"Could not create a screen",
	"jCould not create a screen" )
trappick( TRP_NLM_not_version_3,
	"Must be running on NetWare version 3",
	"jMust be running on NetWare version 3" )
trappick( TRP_MSG_loading_program,
	"Loading program:",
	"jLoading program:" );
trappick( TRP_ERR_expect_brace,
	"Invalid parameter: expecting '}'",
	"jInvalid parameter: expecting '}'" )
trappick( TRP_MSG_usage,
	"Usage: ",
	"jUsage: " )
trappick( TRP_ERR_expect_option,
	"Invalid command line: expecting an option",
	"jInvalid command line: expecting an option" )
trappick( TRP_ERR_expect_equal,
	"Invalid command line: expecting equals sign",
	"jInvalid command line: expecting equals sign" )
trappick( TRP_MSG_connection_established,
	"Initial connection established",
	"jInitial connection established" )
trappick( TRP_MSG_session_started,
	"Session started",
	"jSession started" )
trappick( TRP_MSG_session_ended,
	"Session ended",
	"jSession ended" )
trappick( TRP_MSG_press_q,
	"Press 'q' to exit",
	"jPress 'q' to exit" )
trappick( TRP_MSG_select_exit,
	"Enter new specifications; or select 'Exit' to quit",
	"jEnter new specifications; or select 'Exit' to quit" )
trappick( TRP_TCP_socket_number,
	 "Socket port number: ",
	 "jSocket port number: " )
trappick( TRP_PARSERV_Usage,
	"PARSERV [-Trap=trap_file[;trap_parm]] [-Once] [printer_number]",
	"jPARSERV [-Trap=trap_file[;trap_parm]] [-Once] [printer_number]" )
trappick( TRP_SERSERV_Usage,
	"SERSERV [-Trap=trap_file[;trap_parm]] [-Once] [serial_port][.max_baud_rate]",
	"jSERSERV [-Trap=trap_file[;trap_parm]] [-Once] [serial_port][.max_baud_rate]" )
trappick( TRP_NETSERV_Usage,
	"NETSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]",
	"jNETSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]" )
trappick( TRP_NOVSERV_Usage,
	"NOVSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]",
	"jNOVSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]" )
trappick( TRP_VDMSERV_Usage,
	"VDMSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]",
	"jVDMSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]" )
trappick( TRP_NMPSERV_Usage,
	"NMPSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]",
	"jNMPSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]" )
trappick( TRP_TCPSERV_Usage,
	"TCPSERV [-Trap=trap_file[;trap_parm]] [-Once] [service_or_port]",
	"jTCPSERV [-Trap=trap_file[;trap_parm]] [-Once] [service_or_port]" )
trappick( TRP_WINSERV_Usage,
	"WINSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]",
	"jWINSERV [-Trap=trap_file[;trap_parm]] [-Once] [server_name]" )
trappick( TRP_Parallel_Name,
	"WATCOM Parallel Debug Server",
	"jWATCOM Parallel Debug Server" )
trappick( TRP_Serial_Name,
	"WATCOM Serial Debug Server",
	"jWATCOM Serial Debug Server" )
trappick( TRP_NetBIOS_Name,
	"WATCOM NetBIOS Debug Server",
	"jWATCOM NetBIOS Debug Server" )
trappick( TRP_Novell_Name,
	"WATCOM Novell Debug Server",
	"jWATCOM Novell Debug Server" )
trappick( TRP_Virtual_Name,
	"WATCOM Virtual DOS Machine Debug Server",
	"jWATCOM Virtual DOS Machine Debug Server" )
trappick( TRP_Named_Name,
	"WATCOM Named Pipe Debug Server",
	"jWATCOM Named Pipe Debug Server" )
trappick( TRP_TCP_Name,
	"WATCOM TCP/IP Debug Server",
	"jWATCOM TCP/IP Debug Server" )
trappick( TRP_Windows_Name,
	"WATCOM Windows DOS box Debug Server",
	"jWATCOM Windows DOS box Debug Server" )
trappick( TRP_ERR_one_allowed,
	"Only One Server Allowed",
	"jOnly One Server Allowed" )
trappick( TRP_WIN_not_protect_mode,
	"Must Run In Protect Mode",
	"jMust Run In Protect Mode" )
trappick( TRP_WIN_server_name,
	"Server Name:",
	"jServer Name:" )
trappick( TRP_WIN_register_name,
	"Try To Register Above Server Name",
	"jTry To Register Above Server Name" )
trappick( TRP_ERR_null_name,
	"Null name not allowed",
	"jNull name not allowed" )
trappick( TRP_WIN_setting_name,
	"Setting server name to %s",
	"jSetting server name to %s" )
trappick( TRP_WIN_parallel_port,
	"Parallel Port %d",
	"jParallel Port %d" )
trappick( TRP_WIN_port_set,
	"Port set to LPT%d",
	"jPort set to LPT%d" )
trappick( TRP_QNX_PROC_FORK,
	"Process forked",
	"jProcess forked" )
trappick( TRP_WIN_wanna_interrupt,
	"The debugger cannot be used while the application is running. Do you want to interrupt the application?",
	"jThe debugger cannot be used while the application is running. Do you want to interrupt the application?" )
trappick( TRP_WIN_wanna_kill,
	"The debugger could not sucessfully interrupt your application.  Do you want to terminate the application?",
	"jThe debugger could not sucessfully interrupt your application.  Do you want to terminate the application?" )
