# makefile for nttstrt1.c - test that DLL threading
# starts as expected.

clibtest_name = ntthrd

!ifdef __NT__

srcfile = c/nttstrt1.c
!include ../master.mif

!else

all : .symbolic
clean : .symbolic

!endif
