#pmake:all small stack 32bit inline os2 iX86 rtdll no_build os_os2 cpu_386
component=wrtlib
processor=387
model=ms
subdir=ms_s
system=os2
convention=stack
!include $(rtdll)\master.mif
!include ..\objs.mif
!include $(rtdll)\mkdll.mif
