name: artifact-load
description: 'Download Artifact (tar file) and restore it to git subdirectory'
inputs:
  arch:
    description: 'run-time platform'
    required: false
    default: ''
    type: string
  gitpath:
    description: 'git subdirectory'
    required: false
    default: ''
    type: string
  artifact:
    description: 'artifact name, worlds separated by space, spaces are replased by dash characters (-)'
    required: false
    default: ''
    type: string
  tools:
    description: 'used compiler toolchain'
    required: false
    default: ''
    type: string
  noarchive:
    description: 'not use tar archive for artifacts'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Get Artifact name
    id: artifact_name
    run: >
      -Split "${{ inputs.artifact }} ${{ inputs.tools }}"
      | Join-String -Separator '-' -OutputPrefix 'id='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - name: Get destination folder
    id: dstpath
    run: |
      if( '${{ inputs.noarchive }}' -eq '' ) {
        "${{ github.workspace }}" | Join-String -OutputPrefix 'path=' | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
      } else {
        Join-Path ${{ github.workspace }} ${{ inputs.gitpath }} | Join-String -OutputPrefix 'path=' | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
      }
    shell: pwsh
  - name: Restore Artifact ${{ steps.artifact_name.outputs.id }}
    uses: actions/download-artifact@v4
    with:
      name: ${{ steps.artifact_name.outputs.id }}
      path: ${{ steps.dstpath.outputs.path }}
  - if: inputs.noarchive == ''
    name: Get tar file name
    id: tarname
    run: >
      Join-Path ${{ github.workspace }} owartifact.tar.xz
      | Join-String -OutputPrefix 'fullname='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - if: inputs.noarchive == ''
    name: Restore Artifact
    uses: "./.github/actions/tarload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  ${{ inputs.gitpath }}
      fullname: ${{ steps.tarname.outputs.fullname }}
      owdebug:  ${{ inputs.owdebug }}
  - if: inputs.noarchive == ''
    name: Delete Temporary Artifact tar file
    run: rm -f ${{ steps.tarname.outputs.fullname }}
    shell: bash
