name: artifact-load
description: 'Download Artifact (tar file) and restore it to git subdirectory'
inputs:
  arch:
    description: 'run-time platform'
    required: false
    default: ''
    type: string
  gitpath:
    description: 'git subdirectory'
    required: false
    default: ''
    type: string
  artifact:
    description: 'artifact name, worlds separated by space, spaces are replased by dash characters (-)'
    required: false
    default: ''
    type: string
  tools:
    description: 'used compiler toolchain'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Get Artifact name
    id: artifact_name
    run: >
      -Split "${{ inputs.artifact }} ${{ inputs.tools }}"
      | Join-String -Separator '-' -OutputPrefix 'id='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - name: Download Artifact ${{ steps.artifact_name.outputs.id }}
    uses: actions/download-artifact@v3
    with:
      name: ${{ steps.artifact_name.outputs.id }}
      path: ${{ runner.temp }}
  - name: Get tar file name
    id: tarname
    run: >
      Join-Path ${{ runner.temp }} owartifact.tar.xz
      | Join-String -OutputPrefix 'fullname='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - name: Restore Artifact
    uses: "./.github/actions/tarload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  ${{ inputs.gitpath }}
      fullname: ${{ steps.tarname.outputs.fullname }}
      owdebug:  ${{ inputs.owdebug }}
  - name: Delete Temporary Artifact tar file
    run: rm -f ${{ steps.tarname.outputs.fullname }}
    shell: bash
