#pmake: build large cpu_i86 os_osi os_os2
processor  = 086
system     = generic
model      = ml
linkage    = static
subdir     = ml

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
