#pmake/75:all small stack 32bit calls winnt iX86 rtdll build os_nt cpu_386 cpplib
component=cpplib
processor=386
model=ms
subdir=ms_s
system=winnt
convention=stack
!include $(rtdll_dir)\master.mif
!include ..\objs.mif
!include $(rtdll_dir)\mkdll.mif
