#pmake: nomodel cpu_axp os_nt
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static
mthreaded    = 1
subdir       = _smt

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
