#pmake/75:all small register 32bit calls winnt iX86 rtdll build os_nt cpu_386 cpplib profile dynamic
component=cpplib
processor=386
model=ms
subdir=ms_rpd
system=winnt
convention=register
profile=1
!include $(rtdll_dir)\master.mif
!include ..\objs.mif
!include $(rtdll_dir)\mkdll.mif
