# makefile for GRAPH3R.LIB

libname =       graph3r
model =         /ms /3r /d_NEC_PC
module =        $[&r
cdecl =
fard =
_386 =          386
_qnx =
asm_cmd =       386asm
asm_flags =     -NOL -EL $[&.err -O $[&.obj -I ..\inc\ -d _MODEL=_SMALL -d _386 -NO87 -TWOC
_NEC_PC =       1

!include ..\graphics.mif
