#pmake: build large cpu_i86 os_win
#
# iostl.lib -- large memory-model IOSTREAM library for Windows
#
processor  = 086
system     = windows
model      = ml
linkage    = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
