#pmake: build debug flat cpu_386 os_os2
#
# iostmt3r.lib -- register based multi-thread 32-bit IOSTREAM library
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
mthreaded  = 1
fs_registration = yes

cpplib_release = 0

!include $(cpplib_dir)/iostream/iostream.mif
