#pmake: os_qnx cpu_386 flat
processor  = 386
system     = qnx
model      = ms
convention = stack
linkage    = static
mthreaded  = 1
subdir     = ms_smt

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
