#pmake: all build flat cpu_386 os_nt dynamic profile
host_CPU = 386
fs_prefix = nt
suffix = mt3r
subdir = 3rmtp.dll
linkage = dynamic
profile = 1
target_lib = $(prefix)$(suffix).lib
production_lib = lib386
define_library_include = $(plusplus_cpplib_dir)\plib.mif
!include $(plusplus_dir)\mrglib.mif
