#pmake: build huge cpu_i86 os_dos os_os2 os_win os_qnx
#
# iosth.lib -- huge memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = mh
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
