#pmake: build serv remote os_dos cpu_i86 cpu_386 winl x86
host_CPU = i86
host_OS = dos

os = dos
srv = win
cpu = x86
which = SERVER
type  = remote_link

extra_c_flags_i86 = -3

!include $(trap_dir)/master.mif
