#pmake: build serv remote os_rdos cpu_i86 cpu_386 ser x86

tree_depth = 4

host_cpu = 386
host_os  = rdos

target_cpu = x86

srv = ser
which = SERVER
remote_link = 1

extra_objs = serrdos.obj

!include $(trap_dir)/master.mif
