#pmake: build serv remote os_rdos cpu_i86 cpu_386 ser x86
host_CPU = 386
host_OS = rdos

os = rdos
srv = ser
cpu = x86
which = SERVER
type  = remote_link

extra_objs = serrdos.obj

!include $(trap_dir)/master.mif
