#pmake/25:all small register 32bit winnt iX86 rtdll build os_nt cpu_386 dynamic
component=clib
processor=386
model=ms
subdir=ms_rd
system=winnt
convention=register
!include $(rtdll_dir)\master.mif
!include ..\objs.mif
!include $(rtdll_dir)\mkdll.mif
