#pmake: all build compact cpu_i86 os_win
host_CPU = i86
suffix = c
subdir = wscbd
production_lib = lib286\win
define_library_include = $(plusplus_cpplib_dir)\plib.mif
!include $(plusplus_dir)\mrglib.mif
