#pmake: build serv remote os_linux cpu_386 par

tree_depth = 4

host_cpu = 386
host_os  = linux

target_cpu = x86

srv = par
which = SERVER
remote_link = 1

extra_objs = parlinux.obj

!include $(trap_dir)/lcl/linux/linux.mif
!include $(trap_dir)/master.mif
