#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# cplx3s.lib -- stack based 32-bit COMPLEX library fpc
#
processor  = 386
system     = generic
model      = ms
convention = stack
linkage    = static
define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
