.* commands
.setid <
.setid >
.setid !
.setid abbrev
.setid alias
.setid append
.setid cascade
.setid cd
.setid change
.setid compile
.setid compress
.setid copy
.setid date
.setid delete
.setid echo
.setid edit
.setid egrep
.setid eval
.setid execute
.setid exitall
.setid expand
.setid fgrep
.setid files
.setid floatmenu
.setid genconfig
.setid global
.setid help
.setid insert
.setid join
.setid keyadd
.setid list
.setid load
.setid map
.setid mapbase
.setid mark
.setid match
.setid maximize
.setid minimize
.setid move
.setid movewin
.setid next
.setid open
.setid pop
.setid prev
.setid push
.setid put
.setid quit
.setid quitall
.setid read
.setid resize
.setid set
.setid setcolor
.setid shell
.setid size
.setid source
.setid substitute
.setid tag
.setid tile
.setid unabbrev
.setid unalias
.setid 'undo (command)'
.setid unmap
.setid version
.setid view
.setid visual
.setid write
.setid wq
.setid yank
.setid xit
.* windows
.setid border
.setid dimension
.setid endwindow
.setid hilight
.setid text
.setid commandwindow
.setid countwindow
.setid defaultwindow
.setid dirwindow
.setid editwindow
.setid extrainfowindow
.setid filewindow
.setid filecwindow
.setid linenumberwindow
.setid menuwindow
.setid menubarwindow
.setid messagewindow
.setid setwindow
.setid setvalwindow
.setid statuswindow
.setid addmenuitem
.setid deletemenu
.setid deletemenuitem
.setid endmenu
.setid menu
.setid menuitem
.* settings
.setid autoindent
.setid automessageclear
.setid beepflag
.setid caseignore
.setid changelikevi
.setid cmode
.setid columninfilestatus
.setid currentstatus
.setid drawtildes
.setid eightbits
.setid escapemessage
.setid extendedmemory
.setid ignorectrlz
.setid ignoretagcase
.setid magic
.setid pauseonspawnerr
.setid quiet
.setid quitmovesforward
.setid readentirefile
.setid readonlycheck
.setid realtabs
.setid regsubmagic
.setid samefilecheck
.setid saveconfig
.setid saveposition
.setid searchwrap
.setid showmatch
.setid tagprompt
.setid undo
.setid verbose
.setid wordwrap
.setid wrapbackspace
.setid writecrlf
.setid lefthandmouse
.setid usemouse
.setid clock
.setid linenumbers
.setid linenumsonright
.setid marklonglines
.setid menus
.setid repeatinfo
.setid spinning
.setid statusinfo
.setid toolbar
.setid windowgadgets
.setid autosaveinterval
.setid commandcursortype
.setid endoflinechar
.setid exitattr
.setid fileendstring
.setid grepdefault
.setid hardtab
.setid historyfile
.setid insertcursortype
.setid magicstring
.setid maxclhistory
.setid maxemsk
.setid maxfilterhistory
.setid maxfindhistory
.setid maxlinelen
.setid maxpush
.setid maxswapk
.setid maxxmsk
.setid pagelinesexposed
.setid overstrikecursortype
.setid radix
.setid shiftwidth
.setid stackk
.setid statussections
.setid statusstring
.setid shellprompt
.setid tabamount
.setid tagfilename
.setid tmpdir
.setid word
.setid wrapmargin
.setid mousedclickspeed
.setid mouserepeatdelay
.setid mousespeed
.setid wordalt
.setid buttonheight
.setid buttonwidth
.setid clockx
.setid clocky
.setid currentstatuscolumn
.setid cursorblinkrate
.setid gadgetstring
.setid inactivewindowcolor
.setid maxtilecolors
.setid maxwindowtilex
.setid maxwindowtiley
.setid movecolor
.setid resizecolor
.setid spinx
.setid spiny
.setid tilecolor
.* scripts
.setid atomic
.setid assign
.setid break
.setid continue
.setid endif
.setid endloop
.setid endwhile
.setid elseif
.setid else
.setid expr
.setid fclose
.setid fopen
.setid fread
.setid fwrite
.setid get
.setid goto
.setid if
.setid input
.setid label
.setid loop
.setid nextword
.setid quif
.setid return
.setid until
.setid while

