#pmake: build flat cpu_386 os_os2
#
# plib3s -- 32-bit 3s PLIB, PLBX
#
processor  = 386
system     = os2
model      = mf
convention = stack
linkage    = static
fs_registration = yes

!include $(cpplib_dir)/runtime/runtime.mif
