#pmake: all build flat cpu_386 os_nt dynamic
host_CPU = 386
fs_prefix = nt
suffix = mt3s
subdir = 3smt.dll
linkage = dynamic
target_lib = $(prefix)$(suffix).lib
production_lib = lib386
define_library_include = $(plusplus_cpplib_dir)\plib.mif
!include $(plusplus_dir)\mrglib.mif
