#pmake: build compact cpu_i86 os_osi os_os2
#
# contc.lib -- compact memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = mc
linkage    = static
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
