#pmake: nobuild debug flat register 32bit inline os2 iX86 rtdll os_os2 cpu_386

component  = wlib
processor  = 387
model      = mf
system     = os2
convention = register

lib_debug = 1

!include ../../../rtdll.mif
