#pmake: build serv remote os_win cpu_i86 cpu_386 net x86
host_cpu = i86
host_os  = win

target_cpu = x86
target_os  = win

srv = net
which = SERVER
gui = 1
remote_link = 1

!include $(trap_dir)/master.mif
