#pmake: build serv remote os_win cpu_i86 cpu_386 net x86

tree_depth = 4

host_cpu = i86
host_os  = win

target_cpu = x86

srv = net
which = SERVER
gui = 1
remote_link = 1

!include $(trap_dir)/lcl/win/win.mif
!include $(trap_dir)/master.mif
