wasmtest_name = test1

dis_objs = &
387.dis &
a.dis &
alias.dis &
alignorg.dis &
anon.dis &
anthony.dis &
atseg.dis &
backquot.dis &
bar.dis &
beep.dis &
bigext.dis &
bug.dis &
c.dis &
cmps.dis &
comm.dis &
current.dis &
data.dis &
dos16m.dis &
dosinite.dis &
dosstart.dis &
do_ax.dis &
dup.dis &
empty.dis &
f.dis &
farjmp.dis &
fcom.dis &
five.dis &
float.dis &
fubar.dis &
g.dis &
getenv.dis &
hello.dis &
ifs.dis &
ins.dis &
jmpfword.dis &
jmpsize.dis &
jmptst.dis &
labelbug.dis &
loader2.dis &
lods.dis &
maaak.dis &
macro.dis &
macroloc.dis &
macrotst.dis &
main.dis &
mainnew.dis &
mangle.dis &
masmsuks.dis &
masmtest.dis &
movs.dis &
new.dis &
newbug.dis &
newproc.dis &
notcomm.dis &
offset.dis &
org.dis &
orgage.dis &
outs.dis &
passtest.dis &
proc.dis &
proc3.dis &
pub.dis &
pub2.dis &
pubdef.dis &
q.dis &
qnxstrt.dis &
scas.dis &
segoff.dis &
shell.dis &
size.dis &
sizebug.dis &
sizlen.dis &
stos.dis &
strmang.dis &
struct.dis &
t2.dis &
test.dis &
tmp2.dis &
tn.dis &
wincall.dis &
word.dis &
x.dis &
xx.dis

asm_flags_x = -c
asm_flags_loader2 = -c
asm_flags_getenv = -I"$(watcom_dir)/h"

!include ../test.mif
