#pmake: build os_rdos cpu_386
#
# WATCOM Debugger makefile for NT (character mode)
#

host_os=rdos
host_cpu=386

sysobjs =   &
    autoenv.obj &
    rdosinit.obj &
    rdosscrn.obj &
    rdosio.obj &
    rdoscmd.obj &
    rdoschk.obj &
    rdoslkup.obj

!include ../../master.mif
