1
                     NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
                    FORTRAN COMPILER VALIDATION SYSTEM
                      VERSION 2.1  93/10/21*21.02.00
 
 *FM373BEGIN*            TEST RESULTS - FM373

         TEST DATE*TIME= *NO DATE*TIME      -  COMPILER= *NONE SPECIFIED*    
 
 XCOS - (189) INTRINSIC FUNCTIONS

  COS (COSINE)

  SUBSET REF. - 15.3
 
 
  TEST   PASS/FAIL       DISPLAYED RESULTS       REMARKS
 -------------------------------------------------------------------------------
                                                 THIS PROGRAM HAS  18 TESTS

     1     PASS  
     2     PASS  
     3     PASS  
     4     PASS  
     5     PASS  
     6     PASS  
     7     PASS  
     8     PASS  
     9     PASS  
    10     PASS  
    11     PASS  
    12     PASS  
    13     PASS  
    14     PASS  
    15     PASS  
    16     PASS  
    17     PASS  
    18     PASS  
 
 -------------------------------------------------------------------------------
 
                         18 TESTS PASSED
                          0 TESTS FAILED
                          0 TESTS DELETED
                          0 TESTS REQUIRE INSPECTION
                         18 OF  18 TESTS EXECUTED
 
 *FM373END*              END OF TEST - FM373

 *NO PROJECT*              *NO COMPANY NAME*      *   *NO TAPE* /*NO TAPE DATE
 FOR OFFICIAL USE ONLY                                        COPYRIGHT  1982
