1
                     NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
                    FORTRAN COMPILER VALIDATION SYSTEM
                      VERSION 2.1  93/10/21*21.02.00
 
 *FM405BEGIN*            TEST RESULTS - FM405

         TEST DATE*TIME= *NO DATE*TIME      -  COMPILER= *NONE SPECIFIED*    

   INTER1 - (390) INTERNAL FILES -- USING READ

 SUBSET REF. - 12.2.5
 
 
  TEST   PASS/FAIL       DISPLAYED RESULTS       REMARKS
 -------------------------------------------------------------------------------
                                                 THIS PROGRAM HAS  15 TESTS

     1     PASS  
     2     PASS  
     3     PASS  
     4     PASS  
     5     PASS  
     6     PASS  
     7     PASS  
     8     PASS  
     9     PASS  
    10     PASS  
    11     PASS  
    12     PASS  
    13     PASS  
    14     PASS  
    15     PASS  
 
 -------------------------------------------------------------------------------
 
                         15 TESTS PASSED
                          0 TESTS FAILED
                          0 TESTS DELETED
                          0 TESTS REQUIRE INSPECTION
                         15 OF  15 TESTS EXECUTED
 
 *FM405END*              END OF TEST - FM405

 *NO PROJECT*              *NO COMPANY NAME*      *   *NO TAPE* /*NO TAPE DATE
 FOR OFFICIAL USE ONLY                                        COPYRIGHT  1982
