1
                     NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
                    FORTRAN COMPILER VALIDATION SYSTEM
                      VERSION 2.1  93/10/21*21.02.00
 
 *FM514BEGIN*            TEST RESULTS - FM514

         TEST DATE*TIME= *NO DATE*TIME      -  COMPILER= *NONE SPECIFIED*    
 
 
  TEST   PASS/FAIL       DISPLAYED RESULTS       REMARKS
 -------------------------------------------------------------------------------
                                                 THIS PROGRAM HAS   2 TESTS

     1     PASS  
     2     PASS  
 
 -------------------------------------------------------------------------------
 
                          2 TESTS PASSED
                          0 TESTS FAILED
                          0 TESTS DELETED
                          0 TESTS REQUIRE INSPECTION
                          2 OF   2 TESTS EXECUTED
 
 *FM514END*              END OF TEST - FM514

 *NO PROJECT*              *NO COMPANY NAME*      *   *NO TAPE* /*NO TAPE DATE
 FOR OFFICIAL USE ONLY                                        COPYRIGHT  1982
