1
                     NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
                    FORTRAN COMPILER VALIDATION SYSTEM
                      VERSION 2.1  93/10/21*21.02.00
 
 *FM800BEGIN*            TEST RESULTS - FM800

         TEST DATE*TIME= *NO DATE*TIME      -  COMPILER= *NONE SPECIFIED*    
 

 YIDINT - (151) INTRINSIC FUNCTION--

                 IDINT (TYPE CONVERSION)

  ANS REF. - 15.3
 
 
  TEST   PASS/FAIL       DISPLAYED RESULTS       REMARKS
 -------------------------------------------------------------------------------
                                                 THIS PROGRAM HAS  12 TESTS

     1     PASS  
     2     PASS  
     3     PASS  
     4     PASS  
     5     PASS  
     6     PASS  
     7     PASS  
     8     PASS  
     9     PASS  
    10     PASS  
    11     PASS  
    12     PASS  
 
 -------------------------------------------------------------------------------
 
                         12 TESTS PASSED
                          0 TESTS FAILED
                          0 TESTS DELETED
                          0 TESTS REQUIRE INSPECTION
                         12 OF  12 TESTS EXECUTED
 
 *FM800END*              END OF TEST - FM800

 *NO PROJECT*              *NO COMPANY NAME*      *   *NO TAPE* /*NO TAPE DATE
 FOR OFFICIAL USE ONLY                                        COPYRIGHT  1982
