1
                     NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
                    FORTRAN COMPILER VALIDATION SYSTEM
                      VERSION 2.1  93/10/21*21.02.00
 
 *FM804BEGIN*            TEST RESULTS - FM804

         TEST DATE*TIME= *NO DATE*TIME      -  COMPILER= *NONE SPECIFIED*    
 

 YDMOD - (160) INTRINSIC FUNCTION--

                DMOD (REMAINDERING)

  ANS REF. - 15.3  
 
 
  TEST   PASS/FAIL       DISPLAYED RESULTS       REMARKS
 -------------------------------------------------------------------------------
                                                 THIS PROGRAM HAS  11 TESTS

     1     PASS  
     2     PASS  
     3     PASS  
     4     PASS  
     5     PASS  
     6     PASS  
     7     PASS  
     8     PASS  
     9     PASS  
    10     PASS  
    11     PASS  
 
 -------------------------------------------------------------------------------
 
                         11 TESTS PASSED
                          0 TESTS FAILED
                          0 TESTS DELETED
                          0 TESTS REQUIRE INSPECTION
                         11 OF  11 TESTS EXECUTED
 
 *FM804END*              END OF TEST - FM804

 *NO PROJECT*              *NO COMPANY NAME*      *   *NO TAPE* /*NO TAPE DATE
 FOR OFFICIAL USE ONLY                                        COPYRIGHT  1982
