1
                     NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
                    FORTRAN COMPILER VALIDATION SYSTEM
                      VERSION 2.1  93/10/21*21.02.00
 
 *FM920BEGIN*            TEST RESULTS - FM920

         TEST DATE*TIME= *NO DATE*TIME      -  COMPILER= *NONE SPECIFIED*    
 
 INQF2 - (439) INQUIRE BY FILE

 SEQUENTIAL UNFORMATTED FILE, CONNECTED BY OPEN

 ANS REF. - 12.10.3
 
 
  TEST   PASS/FAIL       DISPLAYED RESULTS       REMARKS
 -------------------------------------------------------------------------------
                                                 THIS PROGRAM HAS   3 TESTS

     1     PASS  
     2     PASS  
     3     PASS  
 
 -------------------------------------------------------------------------------
 
                          3 TESTS PASSED
                          0 TESTS FAILED
                          0 TESTS DELETED
                          0 TESTS REQUIRE INSPECTION
                          3 OF   3 TESTS EXECUTED
 
 *FM920END*              END OF TEST - FM920

 *NO PROJECT*              *NO COMPANY NAME*      *   *NO TAPE* /*NO TAPE DATE
 FOR OFFICIAL USE ONLY                                        COPYRIGHT  1982
