#pmake: build medium cpu_i86 os_osi os_os2
#
# contm.lib -- medium memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = mm
linkage    = static

!include $(cpplib_dir)/contain/contain.mif
