#pmake: build medium cpu_i86 os_dos os_os2 os_win os_qnx
#
# contm.lib -- medium memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = mm
linkage    = static

!include $(cpplib_dir)/contain/contain.mif
