echo %1 inline assembler test

set outfile=%1.out
echo "" > %outfile%
call do 486 %1 %outfile%
call do adc %1 %outfile%
call do add %1 %outfile%
call do admodes %1 %outfile%
call do admodes1 %1 %outfile%
call do admodes2 %1 %outfile%
call do admodes3 %1 %outfile%
call do admodes4 %1 %outfile%
call do admodes5 %1 %outfile%
call do admodes6 %1 %outfile%
call do amodes %1 %outfile%
call do amodes1 %1 %outfile%
call do amodes2 %1 %outfile%
call do amodes3 %1 %outfile%
call do amodes4 %1 %outfile%
call do amodes5 %1 %outfile%
call do amodes6 %1 %outfile%
call do and %1 %outfile%
call do bt %1 %outfile%
call do bug %1 %outfile%
call do cc2 %1 %outfile%
call do cmp %1 %outfile%
call do cmpx %1 %outfile%
call do dec %1 %outfile%
call do div %1 %outfile%
call do dmodes1 %1 %outfile%
call do dmodes2 %1 %outfile%
call do dmodes3 %1 %outfile%
call do dmodes4 %1 %outfile%
call do dmodes5 %1 %outfile%
call do dmodes6 %1 %outfile%
call do enter %1 %outfile%
call do fadd %1 %outfile%
call do fcom %1 %outfile%
call do fdiv %1 %outfile%
call do fld %1 %outfile%
call do fmul %1 %outfile%
call do fp %1 %outfile%
call do fpmisc %1 %outfile%
call do fpmisc2 %1 %outfile%
call do fsub %1 %outfile%
call do fubar %1 %outfile%
call do fucom %1 %outfile%
call do idiv %1 %outfile%
call do imul %1 %outfile%
call do in %1 %outfile%
call do inc %1 %outfile%
call do lea %1 %outfile%
call do lod %1 %outfile%
call do lxs %1 %outfile%
call do misc %1 %outfile%
call do misc2 %1 %outfile%
call do modes %1 %outfile%
call do modes1 %1 %outfile%
call do modes2 %1 %outfile%
call do modes3 %1 %outfile%
call do modes4 %1 %outfile%
call do modes5 %1 %outfile%
call do modes6 %1 %outfile%
call do mov %1 %outfile%
call do mov2 %1 %outfile%
call do movs %1 %outfile%
call do movx %1 %outfile%
call do mul %1 %outfile%
call do neg %1 %outfile%
call do not %1 %outfile%
call do or %1 %outfile%
call do out %1 %outfile%
call do outs %1 %outfile%
call do pop %1 %outfile%
call do rcl %1 %outfile%
call do sal %1 %outfile%
call do sbb %1 %outfile%
call do scas %1 %outfile%
call do setcc %1 %outfile%
call do shld %1 %outfile%
call do sub %1 %outfile%
call do test %1 %outfile%
call do try %1 %outfile%
call do xadd %1 %outfile%
call do xchg %1 %outfile%
call do xor %1 %outfile%

%1 kernel.c /i=c:\lang\qh
wdisasm kernel /l
cat kernel.lst >> %outfile%
