echo %1 inline assembler test
set outfile=dif
if not [%2]==[] set outfile=%2
if not [%1]==[] set da_cmplr=%1
if [%1]==[] set da_cmplr=c386p
call create 486 %da_cmplr% clean %outfile%
call create adc %da_cmplr% clean %outfile%
call create add %da_cmplr% clean %outfile%
call create admodes %da_cmplr% clean %outfile%
call create admodes1 %da_cmplr% clean %outfile%
call create admodes2 %da_cmplr% clean %outfile%
call create admodes3 %da_cmplr% clean %outfile%
call create admodes4 %da_cmplr% clean %outfile%
call create admodes5 %da_cmplr% clean %outfile%
call create admodes6 %da_cmplr% clean %outfile%
call create amodes %da_cmplr% clean %outfile%
call create amodes1 %da_cmplr% clean %outfile%
call create amodes2 %da_cmplr% clean %outfile%
call create amodes3 %da_cmplr% clean %outfile%
call create amodes4 %da_cmplr% clean %outfile%
call create amodes5 %da_cmplr% clean %outfile%
call create amodes6 %da_cmplr% clean %outfile%
call create and %da_cmplr% clean %outfile%
call create bt %da_cmplr% clean %outfile%
call create bug %da_cmplr% clean %outfile%
call create cmp %da_cmplr% clean %outfile%
call create cmpx %da_cmplr% clean %outfile%
call create dec %da_cmplr% clean %outfile%
call create disasm %da_cmplr% clean %outfile%
call create div %da_cmplr% clean %outfile%
call create dmodes1 %da_cmplr% clean %outfile%
call create dmodes2 %da_cmplr% clean %outfile%
call create dmodes3 %da_cmplr% clean %outfile%
call create dmodes4 %da_cmplr% clean %outfile%
call create dmodes5 %da_cmplr% clean %outfile%
call create dmodes6 %da_cmplr% clean %outfile%
call create enter %da_cmplr% clean %outfile%
call create fadd %da_cmplr% clean %outfile%
call create fcom %da_cmplr% clean %outfile%
call create fdiv %da_cmplr% clean %outfile%
call create fld %da_cmplr% clean %outfile%
call create fmul %da_cmplr% clean %outfile%
call create fp %da_cmplr% clean %outfile%
call create fpmisc %da_cmplr% clean %outfile%
call create fpmisc2 %da_cmplr% clean %outfile%
call create fsub %da_cmplr% clean %outfile%
call create fucom %da_cmplr% clean %outfile%
call create idiv %da_cmplr% clean %outfile%
call create imul %da_cmplr% clean %outfile%
call create in %da_cmplr% clean %outfile%
call create inc %da_cmplr% clean %outfile%
call create lea %da_cmplr% clean %outfile%
call create lod %da_cmplr% clean %outfile%
call create lxs %da_cmplr% clean %outfile%
call create misc %da_cmplr% clean %outfile%
call create misc2 %da_cmplr% clean %outfile%
call create modes %da_cmplr% clean %outfile%
call create modes1 %da_cmplr% clean %outfile%
call create modes2 %da_cmplr% clean %outfile%
call create modes3 %da_cmplr% clean %outfile%
call create modes4 %da_cmplr% clean %outfile%
call create modes5 %da_cmplr% clean %outfile%
call create modes6 %da_cmplr% clean %outfile%
call create mov %da_cmplr% clean %outfile%
call create mov2 %da_cmplr% clean %outfile%
call create movs %da_cmplr% clean %outfile%
call create movx %da_cmplr% clean %outfile%
call create mul %da_cmplr% clean %outfile%
call create neg %da_cmplr% clean %outfile%
call create not %da_cmplr% clean %outfile%
call create or %da_cmplr% clean %outfile%
call create out %da_cmplr% clean %outfile%
call create outs %da_cmplr% clean %outfile%
call create pop %da_cmplr% clean %outfile%
call create rcl %da_cmplr% clean %outfile%
call create sal %da_cmplr% clean %outfile%
call create sbb %da_cmplr% clean %outfile%
call create scas %da_cmplr% clean %outfile%
call create setcc %da_cmplr% clean %outfile%
call create shld %da_cmplr% clean %outfile%
call create sub %da_cmplr% clean %outfile%
call create test %da_cmplr% clean %outfile%
call create xadd %da_cmplr% clean %outfile%
call create xchg %da_cmplr% clean %outfile%
call create xor %da_cmplr% clean %outfile%
%da_cmplr% kernel.c /i=c:\dlang\qh
