echo %1 inline assembler test
set outfile=dif
if not [%2]==[] set outfile=%2
if not [%1]==[] set da_cmplr=%1
if [%1]==[] set da_cmplr=c386p
call do 486 %da_cmplr% 
call do adc %da_cmplr% 
call do add %da_cmplr% 
call do admodes %da_cmplr% 
call do admodes1 %da_cmplr% 
call do admodes2 %da_cmplr% 
call do admodes3 %da_cmplr% 
call do admodes4 %da_cmplr% 
call do admodes5 %da_cmplr% 
call do admodes6 %da_cmplr% 
call do amodes %da_cmplr% 
call do amodes1 %da_cmplr% 
call do amodes2 %da_cmplr% 
call do amodes3 %da_cmplr% 
call do amodes4 %da_cmplr% 
call do amodes5 %da_cmplr% 
call do amodes6 %da_cmplr% 
call do and %da_cmplr% 
call do bt %da_cmplr% 
call do bug %da_cmplr% 
call do cmp %da_cmplr% 
call do cmpx %da_cmplr% 
call do dec %da_cmplr% 
call do disasm %da_cmplr% 
call do div %da_cmplr% 
call do dmodes1 %da_cmplr% 
call do dmodes2 %da_cmplr% 
call do dmodes3 %da_cmplr% 
call do dmodes4 %da_cmplr% 
call do dmodes5 %da_cmplr% 
call do dmodes6 %da_cmplr% 
call do enter %da_cmplr% 
call do fadd %da_cmplr% 
call do fcom %da_cmplr% 
call do fdiv %da_cmplr% 
call do fld %da_cmplr% 
call do fmul %da_cmplr% 
call do fp %da_cmplr% 
call do fpmisc %da_cmplr% 
call do fpmisc2 %da_cmplr% 
call do fsub %da_cmplr% 
call do fucom %da_cmplr% 
call do idiv %da_cmplr% 
call do imul %da_cmplr% 
call do in %da_cmplr% 
call do inc %da_cmplr% 
call do lea %da_cmplr% 
call do lod %da_cmplr% 
call do lxs %da_cmplr% 
call do misc %da_cmplr% 
call do misc2 %da_cmplr% 
call do modes %da_cmplr% 
call do modes1 %da_cmplr% 
call do modes2 %da_cmplr% 
call do modes3 %da_cmplr% 
call do modes4 %da_cmplr% 
call do modes5 %da_cmplr% 
call do modes6 %da_cmplr% 
call do mov %da_cmplr% 
call do mov2 %da_cmplr% 
call do movs %da_cmplr% 
call do movx %da_cmplr% 
call do mul %da_cmplr% 
call do neg %da_cmplr% 
call do not %da_cmplr% 
call do or %da_cmplr% 
call do out %da_cmplr% 
call do outs %da_cmplr% 
call do pop %da_cmplr% 
call do rcl %da_cmplr% 
call do sal %da_cmplr% 
call do sbb %da_cmplr% 
call do scas %da_cmplr% 
call do setcc %da_cmplr% 
call do shld %da_cmplr% 
call do sub %da_cmplr% 
call do test %da_cmplr% 
call do xadd %da_cmplr% 
call do xchg %da_cmplr% 
call do xor %da_cmplr% 
%da_cmplr% kernel.c /i=c:\dlang\qh
