#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# cplx3s.lib -- stack based 32-bit COMPLEX library fpc
#
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
