#pmake: build serv remote os_os2 cpu_i86 cpu_386 nmp x86

tree_depth = 4

host_cpu = 386
host_os  = os2

target_cpu = x86

srv = nmp
which = SERVER
remote_link = 1

extra_objs = nmpos22.obj

!include $(trap_dir)/master.mif
