#pmake: debug flat cpu_386 os_os2
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
subdir     = mf_rd

cpplib_release = 0

define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
