#pmake/50:all small register 32bit inline os2 iX86 rtdll build os_os2 cpu_386
component=mathlib
processor=387
model=ms
subdir=ms_r
system=os2
convention=register
!include $(rtdll_dir)\master.mif
!include ..\objs.mif
!include $(rtdll_dir)\mkdll.mif
