#pmake: build trap remote os_dos cpu_i86 cpu_386 nov x86
host_cpu = i86
host_os  = dos

target_cpu = x86
target_os  = dos

srv = nov
which = TRAP
remote_link = 1

extra_objs = novdos.obj spx.obj ipx.obj

!include $(trap_dir)/master.mif
