#include "fail.h"

void check_add( float result, unsigned line )
{
    if( result != 21 ) fail(line);
}

void check_subtract( double result, unsigned line )
{
    if( result != 13 ) fail(line);
}

void check_multiply( unsigned long int result, unsigned line )
{
    if( result != 68 ) fail(line);
}

void check_divide( char result, unsigned line )
{
    if( result != 4 ) fail(line);
}


signed char sc1;
unsigned char uc1;
char c1;
signed short ss1;
unsigned short us1;
short s1;
signed int si1;
unsigned int ui1;
int i1;
signed long int sli1;
unsigned long int uli1;
long int li1;
float f1;
double d1;
long double ld1;

signed char sc2;
unsigned char uc2;
char c2;
signed short ss2;
unsigned short us2;
short s2;
signed int si2;
unsigned int ui2;
int i2;
signed long int sli2;
unsigned long int uli2;
long int li2;
float f2;
double d2;
long double ld2;

int main( void )
{
#if 0
    sc1 = 17;
    sc2 = 4;
    check_add( sc1 + sc2, __LINE__ );
    check_subtract( sc1 - sc2, __LINE__ );
    check_multiply( sc1 * sc2, __LINE__ );
    check_divide( sc1 / sc2, __LINE__ );
    sc1 = 17;
    uc2 = 4;
    check_add( sc1 + uc2, __LINE__ );
    check_subtract( sc1 - uc2, __LINE__ );
    check_multiply( sc1 * uc2, __LINE__ );
    check_divide( sc1 / uc2, __LINE__ );
    sc1 = 17;
    c2 = 4;
    check_add( sc1 + c2, __LINE__ );
    check_subtract( sc1 - c2, __LINE__ );
    check_multiply( sc1 * c2, __LINE__ );
    check_divide( sc1 / c2, __LINE__ );
    sc1 = 17;
    ss2 = 4;
    check_add( sc1 + ss2, __LINE__ );
    check_subtract( sc1 - ss2, __LINE__ );
    check_multiply( sc1 * ss2, __LINE__ );
    check_divide( sc1 / ss2, __LINE__ );
    sc1 = 17;
    us2 = 4;
    check_add( sc1 + us2, __LINE__ );
    check_subtract( sc1 - us2, __LINE__ );
    check_multiply( sc1 * us2, __LINE__ );
    check_divide( sc1 / us2, __LINE__ );
    sc1 = 17;
    s2 = 4;
    check_add( sc1 + s2, __LINE__ );
    check_subtract( sc1 - s2, __LINE__ );
    check_multiply( sc1 * s2, __LINE__ );
    check_divide( sc1 / s2, __LINE__ );
    sc1 = 17;
    si2 = 4;
    check_add( sc1 + si2, __LINE__ );
    check_subtract( sc1 - si2, __LINE__ );
    check_multiply( sc1 * si2, __LINE__ );
    check_divide( sc1 / si2, __LINE__ );
    sc1 = 17;
    ui2 = 4;
    check_add( sc1 + ui2, __LINE__ );
    check_subtract( sc1 - ui2, __LINE__ );
    check_multiply( sc1 * ui2, __LINE__ );
    check_divide( sc1 / ui2, __LINE__ );
    sc1 = 17;
    i2 = 4;
    check_add( sc1 + i2, __LINE__ );
    check_subtract( sc1 - i2, __LINE__ );
    check_multiply( sc1 * i2, __LINE__ );
    check_divide( sc1 / i2, __LINE__ );
    sc1 = 17;
    sli2 = 4;
    check_add( sc1 + sli2, __LINE__ );
    check_subtract( sc1 - sli2, __LINE__ );
    check_multiply( sc1 * sli2, __LINE__ );
    check_divide( sc1 / sli2, __LINE__ );
    sc1 = 17;
    uli2 = 4;
    check_add( sc1 + uli2, __LINE__ );
    check_subtract( sc1 - uli2, __LINE__ );
    check_multiply( sc1 * uli2, __LINE__ );
    check_divide( sc1 / uli2, __LINE__ );
    sc1 = 17;
    li2 = 4;
    check_add( sc1 + li2, __LINE__ );
    check_subtract( sc1 - li2, __LINE__ );
    check_multiply( sc1 * li2, __LINE__ );
    check_divide( sc1 / li2, __LINE__ );
    sc1 = 17;
    f2 = 4;
    check_add( sc1 + f2, __LINE__ );
    check_subtract( sc1 - f2, __LINE__ );
    check_multiply( sc1 * f2, __LINE__ );
    check_divide( sc1 / f2, __LINE__ );
    sc1 = 17;
    d2 = 4;
    check_add( sc1 + d2, __LINE__ );
    check_subtract( sc1 - d2, __LINE__ );
    check_multiply( sc1 * d2, __LINE__ );
    check_divide( sc1 / d2, __LINE__ );
    sc1 = 17;
    ld2 = 4;
    check_add( sc1 + ld2, __LINE__ );
    check_subtract( sc1 - ld2, __LINE__ );
    check_multiply( sc1 * ld2, __LINE__ );
    check_divide( sc1 / ld2, __LINE__ );
    uc1 = 17;
    sc2 = 4;
    check_add( uc1 + sc2, __LINE__ );
    check_subtract( uc1 - sc2, __LINE__ );
    check_multiply( uc1 * sc2, __LINE__ );
    check_divide( uc1 / sc2, __LINE__ );
    uc1 = 17;
    uc2 = 4;
    check_add( uc1 + uc2, __LINE__ );
    check_subtract( uc1 - uc2, __LINE__ );
    check_multiply( uc1 * uc2, __LINE__ );
    check_divide( uc1 / uc2, __LINE__ );
    uc1 = 17;
    c2 = 4;
    check_add( uc1 + c2, __LINE__ );
    check_subtract( uc1 - c2, __LINE__ );
    check_multiply( uc1 * c2, __LINE__ );
    check_divide( uc1 / c2, __LINE__ );
    uc1 = 17;
    ss2 = 4;
    check_add( uc1 + ss2, __LINE__ );
    check_subtract( uc1 - ss2, __LINE__ );
    check_multiply( uc1 * ss2, __LINE__ );
    check_divide( uc1 / ss2, __LINE__ );
    uc1 = 17;
    us2 = 4;
    check_add( uc1 + us2, __LINE__ );
    check_subtract( uc1 - us2, __LINE__ );
    check_multiply( uc1 * us2, __LINE__ );
    check_divide( uc1 / us2, __LINE__ );
    uc1 = 17;
    s2 = 4;
    check_add( uc1 + s2, __LINE__ );
    check_subtract( uc1 - s2, __LINE__ );
    check_multiply( uc1 * s2, __LINE__ );
    check_divide( uc1 / s2, __LINE__ );
    uc1 = 17;
    si2 = 4;
    check_add( uc1 + si2, __LINE__ );
    check_subtract( uc1 - si2, __LINE__ );
    check_multiply( uc1 * si2, __LINE__ );
    check_divide( uc1 / si2, __LINE__ );
    uc1 = 17;
    ui2 = 4;
    check_add( uc1 + ui2, __LINE__ );
    check_subtract( uc1 - ui2, __LINE__ );
    check_multiply( uc1 * ui2, __LINE__ );
    check_divide( uc1 / ui2, __LINE__ );
    uc1 = 17;
    i2 = 4;
    check_add( uc1 + i2, __LINE__ );
    check_subtract( uc1 - i2, __LINE__ );
    check_multiply( uc1 * i2, __LINE__ );
    check_divide( uc1 / i2, __LINE__ );
    uc1 = 17;
    sli2 = 4;
    check_add( uc1 + sli2, __LINE__ );
    check_subtract( uc1 - sli2, __LINE__ );
    check_multiply( uc1 * sli2, __LINE__ );
    check_divide( uc1 / sli2, __LINE__ );
    uc1 = 17;
    uli2 = 4;
    check_add( uc1 + uli2, __LINE__ );
    check_subtract( uc1 - uli2, __LINE__ );
    check_multiply( uc1 * uli2, __LINE__ );
    check_divide( uc1 / uli2, __LINE__ );
    uc1 = 17;
    li2 = 4;
    check_add( uc1 + li2, __LINE__ );
    check_subtract( uc1 - li2, __LINE__ );
    check_multiply( uc1 * li2, __LINE__ );
    check_divide( uc1 / li2, __LINE__ );
    uc1 = 17;
    f2 = 4;
    check_add( uc1 + f2, __LINE__ );
    check_subtract( uc1 - f2, __LINE__ );
    check_multiply( uc1 * f2, __LINE__ );
    check_divide( uc1 / f2, __LINE__ );
    uc1 = 17;
    d2 = 4;
    check_add( uc1 + d2, __LINE__ );
    check_subtract( uc1 - d2, __LINE__ );
    check_multiply( uc1 * d2, __LINE__ );
    check_divide( uc1 / d2, __LINE__ );
    uc1 = 17;
    ld2 = 4;
    check_add( uc1 + ld2, __LINE__ );
    check_subtract( uc1 - ld2, __LINE__ );
    check_multiply( uc1 * ld2, __LINE__ );
    check_divide( uc1 / ld2, __LINE__ );
    c1 = 17;
    sc2 = 4;
    check_add( c1 + sc2, __LINE__ );
    check_subtract( c1 - sc2, __LINE__ );
    check_multiply( c1 * sc2, __LINE__ );
    check_divide( c1 / sc2, __LINE__ );
    c1 = 17;
    uc2 = 4;
    check_add( c1 + uc2, __LINE__ );
    check_subtract( c1 - uc2, __LINE__ );
    check_multiply( c1 * uc2, __LINE__ );
    check_divide( c1 / uc2, __LINE__ );
    c1 = 17;
    c2 = 4;
    check_add( c1 + c2, __LINE__ );
    check_subtract( c1 - c2, __LINE__ );
    check_multiply( c1 * c2, __LINE__ );
    check_divide( c1 / c2, __LINE__ );
    c1 = 17;
    ss2 = 4;
    check_add( c1 + ss2, __LINE__ );
    check_subtract( c1 - ss2, __LINE__ );
    check_multiply( c1 * ss2, __LINE__ );
    check_divide( c1 / ss2, __LINE__ );
    c1 = 17;
    us2 = 4;
    check_add( c1 + us2, __LINE__ );
    check_subtract( c1 - us2, __LINE__ );
    check_multiply( c1 * us2, __LINE__ );
    check_divide( c1 / us2, __LINE__ );
    c1 = 17;
    s2 = 4;
    check_add( c1 + s2, __LINE__ );
    check_subtract( c1 - s2, __LINE__ );
    check_multiply( c1 * s2, __LINE__ );
    check_divide( c1 / s2, __LINE__ );
    c1 = 17;
    si2 = 4;
    check_add( c1 + si2, __LINE__ );
    check_subtract( c1 - si2, __LINE__ );
    check_multiply( c1 * si2, __LINE__ );
    check_divide( c1 / si2, __LINE__ );
    c1 = 17;
    ui2 = 4;
    check_add( c1 + ui2, __LINE__ );
    check_subtract( c1 - ui2, __LINE__ );
    check_multiply( c1 * ui2, __LINE__ );
    check_divide( c1 / ui2, __LINE__ );
    c1 = 17;
    i2 = 4;
    check_add( c1 + i2, __LINE__ );
    check_subtract( c1 - i2, __LINE__ );
    check_multiply( c1 * i2, __LINE__ );
    check_divide( c1 / i2, __LINE__ );
    c1 = 17;
    sli2 = 4;
    check_add( c1 + sli2, __LINE__ );
    check_subtract( c1 - sli2, __LINE__ );
    check_multiply( c1 * sli2, __LINE__ );
    check_divide( c1 / sli2, __LINE__ );
    c1 = 17;
    uli2 = 4;
    check_add( c1 + uli2, __LINE__ );
    check_subtract( c1 - uli2, __LINE__ );
    check_multiply( c1 * uli2, __LINE__ );
    check_divide( c1 / uli2, __LINE__ );
    c1 = 17;
    li2 = 4;
    check_add( c1 + li2, __LINE__ );
    check_subtract( c1 - li2, __LINE__ );
    check_multiply( c1 * li2, __LINE__ );
    check_divide( c1 / li2, __LINE__ );
    c1 = 17;
    f2 = 4;
    check_add( c1 + f2, __LINE__ );
    check_subtract( c1 - f2, __LINE__ );
    check_multiply( c1 * f2, __LINE__ );
    check_divide( c1 / f2, __LINE__ );
    c1 = 17;
    d2 = 4;
    check_add( c1 + d2, __LINE__ );
    check_subtract( c1 - d2, __LINE__ );
    check_multiply( c1 * d2, __LINE__ );
    check_divide( c1 / d2, __LINE__ );
    c1 = 17;
    ld2 = 4;
    check_add( c1 + ld2, __LINE__ );
    check_subtract( c1 - ld2, __LINE__ );
    check_multiply( c1 * ld2, __LINE__ );
    check_divide( c1 / ld2, __LINE__ );
    ss1 = 17;
    sc2 = 4;
    check_add( ss1 + sc2, __LINE__ );
    check_subtract( ss1 - sc2, __LINE__ );
    check_multiply( ss1 * sc2, __LINE__ );
    check_divide( ss1 / sc2, __LINE__ );
    ss1 = 17;
    uc2 = 4;
    check_add( ss1 + uc2, __LINE__ );
    check_subtract( ss1 - uc2, __LINE__ );
    check_multiply( ss1 * uc2, __LINE__ );
    check_divide( ss1 / uc2, __LINE__ );
    ss1 = 17;
    c2 = 4;
    check_add( ss1 + c2, __LINE__ );
    check_subtract( ss1 - c2, __LINE__ );
    check_multiply( ss1 * c2, __LINE__ );
    check_divide( ss1 / c2, __LINE__ );
    ss1 = 17;
    ss2 = 4;
    check_add( ss1 + ss2, __LINE__ );
    check_subtract( ss1 - ss2, __LINE__ );
    check_multiply( ss1 * ss2, __LINE__ );
    check_divide( ss1 / ss2, __LINE__ );
    ss1 = 17;
    us2 = 4;
    check_add( ss1 + us2, __LINE__ );
    check_subtract( ss1 - us2, __LINE__ );
    check_multiply( ss1 * us2, __LINE__ );
    check_divide( ss1 / us2, __LINE__ );
    ss1 = 17;
    s2 = 4;
    check_add( ss1 + s2, __LINE__ );
    check_subtract( ss1 - s2, __LINE__ );
    check_multiply( ss1 * s2, __LINE__ );
    check_divide( ss1 / s2, __LINE__ );
    ss1 = 17;
    si2 = 4;
    check_add( ss1 + si2, __LINE__ );
    check_subtract( ss1 - si2, __LINE__ );
    check_multiply( ss1 * si2, __LINE__ );
    check_divide( ss1 / si2, __LINE__ );
    ss1 = 17;
    ui2 = 4;
    check_add( ss1 + ui2, __LINE__ );
    check_subtract( ss1 - ui2, __LINE__ );
    check_multiply( ss1 * ui2, __LINE__ );
    check_divide( ss1 / ui2, __LINE__ );
    ss1 = 17;
    i2 = 4;
    check_add( ss1 + i2, __LINE__ );
    check_subtract( ss1 - i2, __LINE__ );
    check_multiply( ss1 * i2, __LINE__ );
    check_divide( ss1 / i2, __LINE__ );
    ss1 = 17;
    sli2 = 4;
    check_add( ss1 + sli2, __LINE__ );
    check_subtract( ss1 - sli2, __LINE__ );
    check_multiply( ss1 * sli2, __LINE__ );
    check_divide( ss1 / sli2, __LINE__ );
    ss1 = 17;
    uli2 = 4;
    check_add( ss1 + uli2, __LINE__ );
    check_subtract( ss1 - uli2, __LINE__ );
    check_multiply( ss1 * uli2, __LINE__ );
    check_divide( ss1 / uli2, __LINE__ );
    ss1 = 17;
    li2 = 4;
    check_add( ss1 + li2, __LINE__ );
    check_subtract( ss1 - li2, __LINE__ );
    check_multiply( ss1 * li2, __LINE__ );
    check_divide( ss1 / li2, __LINE__ );
    ss1 = 17;
    f2 = 4;
    check_add( ss1 + f2, __LINE__ );
    check_subtract( ss1 - f2, __LINE__ );
    check_multiply( ss1 * f2, __LINE__ );
    check_divide( ss1 / f2, __LINE__ );
    ss1 = 17;
    d2 = 4;
    check_add( ss1 + d2, __LINE__ );
    check_subtract( ss1 - d2, __LINE__ );
    check_multiply( ss1 * d2, __LINE__ );
    check_divide( ss1 / d2, __LINE__ );
    ss1 = 17;
    ld2 = 4;
    check_add( ss1 + ld2, __LINE__ );
    check_subtract( ss1 - ld2, __LINE__ );
    check_multiply( ss1 * ld2, __LINE__ );
    check_divide( ss1 / ld2, __LINE__ );
    us1 = 17;
    sc2 = 4;
    check_add( us1 + sc2, __LINE__ );
    check_subtract( us1 - sc2, __LINE__ );
    check_multiply( us1 * sc2, __LINE__ );
    check_divide( us1 / sc2, __LINE__ );
    us1 = 17;
    uc2 = 4;
    check_add( us1 + uc2, __LINE__ );
    check_subtract( us1 - uc2, __LINE__ );
    check_multiply( us1 * uc2, __LINE__ );
    check_divide( us1 / uc2, __LINE__ );
    us1 = 17;
    c2 = 4;
    check_add( us1 + c2, __LINE__ );
    check_subtract( us1 - c2, __LINE__ );
    check_multiply( us1 * c2, __LINE__ );
    check_divide( us1 / c2, __LINE__ );
    us1 = 17;
    ss2 = 4;
    check_add( us1 + ss2, __LINE__ );
    check_subtract( us1 - ss2, __LINE__ );
    check_multiply( us1 * ss2, __LINE__ );
    check_divide( us1 / ss2, __LINE__ );
    us1 = 17;
    us2 = 4;
    check_add( us1 + us2, __LINE__ );
    check_subtract( us1 - us2, __LINE__ );
    check_multiply( us1 * us2, __LINE__ );
    check_divide( us1 / us2, __LINE__ );
    us1 = 17;
    s2 = 4;
    check_add( us1 + s2, __LINE__ );
    check_subtract( us1 - s2, __LINE__ );
    check_multiply( us1 * s2, __LINE__ );
    check_divide( us1 / s2, __LINE__ );
    us1 = 17;
    si2 = 4;
    check_add( us1 + si2, __LINE__ );
    check_subtract( us1 - si2, __LINE__ );
    check_multiply( us1 * si2, __LINE__ );
    check_divide( us1 / si2, __LINE__ );
    us1 = 17;
    ui2 = 4;
    check_add( us1 + ui2, __LINE__ );
    check_subtract( us1 - ui2, __LINE__ );
    check_multiply( us1 * ui2, __LINE__ );
    check_divide( us1 / ui2, __LINE__ );
    us1 = 17;
    i2 = 4;
    check_add( us1 + i2, __LINE__ );
    check_subtract( us1 - i2, __LINE__ );
    check_multiply( us1 * i2, __LINE__ );
    check_divide( us1 / i2, __LINE__ );
    us1 = 17;
    sli2 = 4;
    check_add( us1 + sli2, __LINE__ );
    check_subtract( us1 - sli2, __LINE__ );
    check_multiply( us1 * sli2, __LINE__ );
    check_divide( us1 / sli2, __LINE__ );
    us1 = 17;
    uli2 = 4;
    check_add( us1 + uli2, __LINE__ );
    check_subtract( us1 - uli2, __LINE__ );
    check_multiply( us1 * uli2, __LINE__ );
    check_divide( us1 / uli2, __LINE__ );
    us1 = 17;
    li2 = 4;
    check_add( us1 + li2, __LINE__ );
    check_subtract( us1 - li2, __LINE__ );
    check_multiply( us1 * li2, __LINE__ );
    check_divide( us1 / li2, __LINE__ );
    us1 = 17;
    f2 = 4;
    check_add( us1 + f2, __LINE__ );
    check_subtract( us1 - f2, __LINE__ );
    check_multiply( us1 * f2, __LINE__ );
    check_divide( us1 / f2, __LINE__ );
    us1 = 17;
    d2 = 4;
    check_add( us1 + d2, __LINE__ );
    check_subtract( us1 - d2, __LINE__ );
    check_multiply( us1 * d2, __LINE__ );
    check_divide( us1 / d2, __LINE__ );
    us1 = 17;
    ld2 = 4;
    check_add( us1 + ld2, __LINE__ );
    check_subtract( us1 - ld2, __LINE__ );
    check_multiply( us1 * ld2, __LINE__ );
    check_divide( us1 / ld2, __LINE__ );
    s1 = 17;
    sc2 = 4;
    check_add( s1 + sc2, __LINE__ );
    check_subtract( s1 - sc2, __LINE__ );
    check_multiply( s1 * sc2, __LINE__ );
    check_divide( s1 / sc2, __LINE__ );
    s1 = 17;
    uc2 = 4;
    check_add( s1 + uc2, __LINE__ );
    check_subtract( s1 - uc2, __LINE__ );
    check_multiply( s1 * uc2, __LINE__ );
    check_divide( s1 / uc2, __LINE__ );
    s1 = 17;
    c2 = 4;
    check_add( s1 + c2, __LINE__ );
    check_subtract( s1 - c2, __LINE__ );
    check_multiply( s1 * c2, __LINE__ );
    check_divide( s1 / c2, __LINE__ );
    s1 = 17;
    ss2 = 4;
    check_add( s1 + ss2, __LINE__ );
    check_subtract( s1 - ss2, __LINE__ );
    check_multiply( s1 * ss2, __LINE__ );
    check_divide( s1 / ss2, __LINE__ );
    s1 = 17;
    us2 = 4;
    check_add( s1 + us2, __LINE__ );
    check_subtract( s1 - us2, __LINE__ );
    check_multiply( s1 * us2, __LINE__ );
    check_divide( s1 / us2, __LINE__ );
    s1 = 17;
    s2 = 4;
    check_add( s1 + s2, __LINE__ );
    check_subtract( s1 - s2, __LINE__ );
    check_multiply( s1 * s2, __LINE__ );
    check_divide( s1 / s2, __LINE__ );
    s1 = 17;
    si2 = 4;
    check_add( s1 + si2, __LINE__ );
    check_subtract( s1 - si2, __LINE__ );
    check_multiply( s1 * si2, __LINE__ );
    check_divide( s1 / si2, __LINE__ );
    s1 = 17;
    ui2 = 4;
    check_add( s1 + ui2, __LINE__ );
    check_subtract( s1 - ui2, __LINE__ );
    check_multiply( s1 * ui2, __LINE__ );
    check_divide( s1 / ui2, __LINE__ );
    s1 = 17;
    i2 = 4;
    check_add( s1 + i2, __LINE__ );
    check_subtract( s1 - i2, __LINE__ );
    check_multiply( s1 * i2, __LINE__ );
    check_divide( s1 / i2, __LINE__ );
    s1 = 17;
    sli2 = 4;
    check_add( s1 + sli2, __LINE__ );
    check_subtract( s1 - sli2, __LINE__ );
    check_multiply( s1 * sli2, __LINE__ );
    check_divide( s1 / sli2, __LINE__ );
    s1 = 17;
    uli2 = 4;
    check_add( s1 + uli2, __LINE__ );
    check_subtract( s1 - uli2, __LINE__ );
    check_multiply( s1 * uli2, __LINE__ );
    check_divide( s1 / uli2, __LINE__ );
    s1 = 17;
    li2 = 4;
    check_add( s1 + li2, __LINE__ );
    check_subtract( s1 - li2, __LINE__ );
    check_multiply( s1 * li2, __LINE__ );
    check_divide( s1 / li2, __LINE__ );
    s1 = 17;
    f2 = 4;
    check_add( s1 + f2, __LINE__ );
    check_subtract( s1 - f2, __LINE__ );
    check_multiply( s1 * f2, __LINE__ );
    check_divide( s1 / f2, __LINE__ );
    s1 = 17;
    d2 = 4;
    check_add( s1 + d2, __LINE__ );
    check_subtract( s1 - d2, __LINE__ );
    check_multiply( s1 * d2, __LINE__ );
    check_divide( s1 / d2, __LINE__ );
    s1 = 17;
    ld2 = 4;
    check_add( s1 + ld2, __LINE__ );
    check_subtract( s1 - ld2, __LINE__ );
    check_multiply( s1 * ld2, __LINE__ );
    check_divide( s1 / ld2, __LINE__ );
    si1 = 17;
    sc2 = 4;
    check_add( si1 + sc2, __LINE__ );
    check_subtract( si1 - sc2, __LINE__ );
    check_multiply( si1 * sc2, __LINE__ );
    check_divide( si1 / sc2, __LINE__ );
    si1 = 17;
    uc2 = 4;
    check_add( si1 + uc2, __LINE__ );
    check_subtract( si1 - uc2, __LINE__ );
    check_multiply( si1 * uc2, __LINE__ );
    check_divide( si1 / uc2, __LINE__ );
    si1 = 17;
    c2 = 4;
    check_add( si1 + c2, __LINE__ );
    check_subtract( si1 - c2, __LINE__ );
    check_multiply( si1 * c2, __LINE__ );
    check_divide( si1 / c2, __LINE__ );
    si1 = 17;
    ss2 = 4;
    check_add( si1 + ss2, __LINE__ );
    check_subtract( si1 - ss2, __LINE__ );
    check_multiply( si1 * ss2, __LINE__ );
    check_divide( si1 / ss2, __LINE__ );
    si1 = 17;
    us2 = 4;
    check_add( si1 + us2, __LINE__ );
    check_subtract( si1 - us2, __LINE__ );
    check_multiply( si1 * us2, __LINE__ );
    check_divide( si1 / us2, __LINE__ );
    si1 = 17;
    s2 = 4;
    check_add( si1 + s2, __LINE__ );
    check_subtract( si1 - s2, __LINE__ );
    check_multiply( si1 * s2, __LINE__ );
    check_divide( si1 / s2, __LINE__ );
    si1 = 17;
    si2 = 4;
    check_add( si1 + si2, __LINE__ );
    check_subtract( si1 - si2, __LINE__ );
    check_multiply( si1 * si2, __LINE__ );
    check_divide( si1 / si2, __LINE__ );
    si1 = 17;
    ui2 = 4;
    check_add( si1 + ui2, __LINE__ );
    check_subtract( si1 - ui2, __LINE__ );
    check_multiply( si1 * ui2, __LINE__ );
    check_divide( si1 / ui2, __LINE__ );
    si1 = 17;
    i2 = 4;
    check_add( si1 + i2, __LINE__ );
    check_subtract( si1 - i2, __LINE__ );
    check_multiply( si1 * i2, __LINE__ );
    check_divide( si1 / i2, __LINE__ );
    si1 = 17;
    sli2 = 4;
    check_add( si1 + sli2, __LINE__ );
    check_subtract( si1 - sli2, __LINE__ );
    check_multiply( si1 * sli2, __LINE__ );
    check_divide( si1 / sli2, __LINE__ );
#else
#if 0
    si1 = 17;
    uli2 = 4;
    check_add( si1 + uli2, __LINE__ );
    check_subtract( si1 - uli2, __LINE__ );
    check_multiply( si1 * uli2, __LINE__ );
    check_divide( si1 / uli2, __LINE__ );
    si1 = 17;
    li2 = 4;
    check_add( si1 + li2, __LINE__ );
    check_subtract( si1 - li2, __LINE__ );
    check_multiply( si1 * li2, __LINE__ );
    check_divide( si1 / li2, __LINE__ );
    si1 = 17;
    f2 = 4;
    check_add( si1 + f2, __LINE__ );
    check_subtract( si1 - f2, __LINE__ );
    check_multiply( si1 * f2, __LINE__ );
    check_divide( si1 / f2, __LINE__ );
    si1 = 17;
    d2 = 4;
    check_add( si1 + d2, __LINE__ );
    check_subtract( si1 - d2, __LINE__ );
    check_multiply( si1 * d2, __LINE__ );
    check_divide( si1 / d2, __LINE__ );
    si1 = 17;
    ld2 = 4;
    check_add( si1 + ld2, __LINE__ );
    check_subtract( si1 - ld2, __LINE__ );
    check_multiply( si1 * ld2, __LINE__ );
    check_divide( si1 / ld2, __LINE__ );
    ui1 = 17;
    sc2 = 4;
    check_add( ui1 + sc2, __LINE__ );
    check_subtract( ui1 - sc2, __LINE__ );
    check_multiply( ui1 * sc2, __LINE__ );
    check_divide( ui1 / sc2, __LINE__ );
    ui1 = 17;
    uc2 = 4;
    check_add( ui1 + uc2, __LINE__ );
    check_subtract( ui1 - uc2, __LINE__ );
    check_multiply( ui1 * uc2, __LINE__ );
    check_divide( ui1 / uc2, __LINE__ );
    ui1 = 17;
    c2 = 4;
    check_add( ui1 + c2, __LINE__ );
    check_subtract( ui1 - c2, __LINE__ );
    check_multiply( ui1 * c2, __LINE__ );
    check_divide( ui1 / c2, __LINE__ );
    ui1 = 17;
    ss2 = 4;
    check_add( ui1 + ss2, __LINE__ );
    check_subtract( ui1 - ss2, __LINE__ );
    check_multiply( ui1 * ss2, __LINE__ );
    check_divide( ui1 / ss2, __LINE__ );
    ui1 = 17;
    us2 = 4;
    check_add( ui1 + us2, __LINE__ );
    check_subtract( ui1 - us2, __LINE__ );
    check_multiply( ui1 * us2, __LINE__ );
    check_divide( ui1 / us2, __LINE__ );
    ui1 = 17;
    s2 = 4;
    check_add( ui1 + s2, __LINE__ );
    check_subtract( ui1 - s2, __LINE__ );
    check_multiply( ui1 * s2, __LINE__ );
    check_divide( ui1 / s2, __LINE__ );
    ui1 = 17;
    si2 = 4;
    check_add( ui1 + si2, __LINE__ );
    check_subtract( ui1 - si2, __LINE__ );
    check_multiply( ui1 * si2, __LINE__ );
    check_divide( ui1 / si2, __LINE__ );
    ui1 = 17;
    ui2 = 4;
    check_add( ui1 + ui2, __LINE__ );
    check_subtract( ui1 - ui2, __LINE__ );
    check_multiply( ui1 * ui2, __LINE__ );
    check_divide( ui1 / ui2, __LINE__ );
    ui1 = 17;
    i2 = 4;
    check_add( ui1 + i2, __LINE__ );
    check_subtract( ui1 - i2, __LINE__ );
    check_multiply( ui1 * i2, __LINE__ );
    check_divide( ui1 / i2, __LINE__ );
    ui1 = 17;
    sli2 = 4;
    check_add( ui1 + sli2, __LINE__ );
    check_subtract( ui1 - sli2, __LINE__ );
    check_multiply( ui1 * sli2, __LINE__ );
    check_divide( ui1 / sli2, __LINE__ );
    ui1 = 17;
    uli2 = 4;
    check_add( ui1 + uli2, __LINE__ );
    check_subtract( ui1 - uli2, __LINE__ );
    check_multiply( ui1 * uli2, __LINE__ );
    check_divide( ui1 / uli2, __LINE__ );
    ui1 = 17;
    li2 = 4;
    check_add( ui1 + li2, __LINE__ );
    check_subtract( ui1 - li2, __LINE__ );
    check_multiply( ui1 * li2, __LINE__ );
    check_divide( ui1 / li2, __LINE__ );
    ui1 = 17;
    f2 = 4;
    check_add( ui1 + f2, __LINE__ );
    check_subtract( ui1 - f2, __LINE__ );
    check_multiply( ui1 * f2, __LINE__ );
    check_divide( ui1 / f2, __LINE__ );
    ui1 = 17;
    d2 = 4;
    check_add( ui1 + d2, __LINE__ );
    check_subtract( ui1 - d2, __LINE__ );
    check_multiply( ui1 * d2, __LINE__ );
    check_divide( ui1 / d2, __LINE__ );
    ui1 = 17;
    ld2 = 4;
    check_add( ui1 + ld2, __LINE__ );
    check_subtract( ui1 - ld2, __LINE__ );
    check_multiply( ui1 * ld2, __LINE__ );
    check_divide( ui1 / ld2, __LINE__ );
    i1 = 17;
    sc2 = 4;
    check_add( i1 + sc2, __LINE__ );
    check_subtract( i1 - sc2, __LINE__ );
    check_multiply( i1 * sc2, __LINE__ );
    check_divide( i1 / sc2, __LINE__ );
    i1 = 17;
    uc2 = 4;
    check_add( i1 + uc2, __LINE__ );
    check_subtract( i1 - uc2, __LINE__ );
    check_multiply( i1 * uc2, __LINE__ );
    check_divide( i1 / uc2, __LINE__ );
    i1 = 17;
    c2 = 4;
    check_add( i1 + c2, __LINE__ );
    check_subtract( i1 - c2, __LINE__ );
    check_multiply( i1 * c2, __LINE__ );
    check_divide( i1 / c2, __LINE__ );
    i1 = 17;
    ss2 = 4;
    check_add( i1 + ss2, __LINE__ );
    check_subtract( i1 - ss2, __LINE__ );
    check_multiply( i1 * ss2, __LINE__ );
    check_divide( i1 / ss2, __LINE__ );
    i1 = 17;
    us2 = 4;
    check_add( i1 + us2, __LINE__ );
    check_subtract( i1 - us2, __LINE__ );
    check_multiply( i1 * us2, __LINE__ );
    check_divide( i1 / us2, __LINE__ );
    i1 = 17;
    s2 = 4;
    check_add( i1 + s2, __LINE__ );
    check_subtract( i1 - s2, __LINE__ );
    check_multiply( i1 * s2, __LINE__ );
    check_divide( i1 / s2, __LINE__ );
    i1 = 17;
    si2 = 4;
    check_add( i1 + si2, __LINE__ );
    check_subtract( i1 - si2, __LINE__ );
    check_multiply( i1 * si2, __LINE__ );
    check_divide( i1 / si2, __LINE__ );
    i1 = 17;
    ui2 = 4;
    check_add( i1 + ui2, __LINE__ );
    check_subtract( i1 - ui2, __LINE__ );
    check_multiply( i1 * ui2, __LINE__ );
    check_divide( i1 / ui2, __LINE__ );
    i1 = 17;
    i2 = 4;
    check_add( i1 + i2, __LINE__ );
    check_subtract( i1 - i2, __LINE__ );
    check_multiply( i1 * i2, __LINE__ );
    check_divide( i1 / i2, __LINE__ );
    i1 = 17;
    sli2 = 4;
    check_add( i1 + sli2, __LINE__ );
    check_subtract( i1 - sli2, __LINE__ );
    check_multiply( i1 * sli2, __LINE__ );
    check_divide( i1 / sli2, __LINE__ );
    i1 = 17;
    uli2 = 4;
    check_add( i1 + uli2, __LINE__ );
    check_subtract( i1 - uli2, __LINE__ );
    check_multiply( i1 * uli2, __LINE__ );
    check_divide( i1 / uli2, __LINE__ );
    i1 = 17;
    li2 = 4;
    check_add( i1 + li2, __LINE__ );
    check_subtract( i1 - li2, __LINE__ );
    check_multiply( i1 * li2, __LINE__ );
    check_divide( i1 / li2, __LINE__ );
    i1 = 17;
    f2 = 4;
    check_add( i1 + f2, __LINE__ );
    check_subtract( i1 - f2, __LINE__ );
    check_multiply( i1 * f2, __LINE__ );
    check_divide( i1 / f2, __LINE__ );
    i1 = 17;
    d2 = 4;
    check_add( i1 + d2, __LINE__ );
    check_subtract( i1 - d2, __LINE__ );
    check_multiply( i1 * d2, __LINE__ );
    check_divide( i1 / d2, __LINE__ );
    i1 = 17;
    ld2 = 4;
    check_add( i1 + ld2, __LINE__ );
    check_subtract( i1 - ld2, __LINE__ );
    check_multiply( i1 * ld2, __LINE__ );
    check_divide( i1 / ld2, __LINE__ );
    sli1 = 17;
    sc2 = 4;
    check_add( sli1 + sc2, __LINE__ );
    check_subtract( sli1 - sc2, __LINE__ );
    check_multiply( sli1 * sc2, __LINE__ );
    check_divide( sli1 / sc2, __LINE__ );
    sli1 = 17;
    uc2 = 4;
    check_add( sli1 + uc2, __LINE__ );
    check_subtract( sli1 - uc2, __LINE__ );
    check_multiply( sli1 * uc2, __LINE__ );
    check_divide( sli1 / uc2, __LINE__ );
    sli1 = 17;
    c2 = 4;
    check_add( sli1 + c2, __LINE__ );
    check_subtract( sli1 - c2, __LINE__ );
    check_multiply( sli1 * c2, __LINE__ );
    check_divide( sli1 / c2, __LINE__ );
    sli1 = 17;
    ss2 = 4;
    check_add( sli1 + ss2, __LINE__ );
    check_subtract( sli1 - ss2, __LINE__ );
    check_multiply( sli1 * ss2, __LINE__ );
    check_divide( sli1 / ss2, __LINE__ );
    sli1 = 17;
    us2 = 4;
    check_add( sli1 + us2, __LINE__ );
    check_subtract( sli1 - us2, __LINE__ );
    check_multiply( sli1 * us2, __LINE__ );
    check_divide( sli1 / us2, __LINE__ );
    sli1 = 17;
    s2 = 4;
    check_add( sli1 + s2, __LINE__ );
    check_subtract( sli1 - s2, __LINE__ );
    check_multiply( sli1 * s2, __LINE__ );
    check_divide( sli1 / s2, __LINE__ );
    sli1 = 17;
    si2 = 4;
    check_add( sli1 + si2, __LINE__ );
    check_subtract( sli1 - si2, __LINE__ );
    check_multiply( sli1 * si2, __LINE__ );
    check_divide( sli1 / si2, __LINE__ );
    sli1 = 17;
    ui2 = 4;
    check_add( sli1 + ui2, __LINE__ );
    check_subtract( sli1 - ui2, __LINE__ );
    check_multiply( sli1 * ui2, __LINE__ );
    check_divide( sli1 / ui2, __LINE__ );
    sli1 = 17;
    i2 = 4;
    check_add( sli1 + i2, __LINE__ );
    check_subtract( sli1 - i2, __LINE__ );
    check_multiply( sli1 * i2, __LINE__ );
    check_divide( sli1 / i2, __LINE__ );
    sli1 = 17;
    sli2 = 4;
    check_add( sli1 + sli2, __LINE__ );
    check_subtract( sli1 - sli2, __LINE__ );
    check_multiply( sli1 * sli2, __LINE__ );
    check_divide( sli1 / sli2, __LINE__ );
    sli1 = 17;
    uli2 = 4;
    check_add( sli1 + uli2, __LINE__ );
    check_subtract( sli1 - uli2, __LINE__ );
    check_multiply( sli1 * uli2, __LINE__ );
    check_divide( sli1 / uli2, __LINE__ );
    sli1 = 17;
    li2 = 4;
    check_add( sli1 + li2, __LINE__ );
    check_subtract( sli1 - li2, __LINE__ );
    check_multiply( sli1 * li2, __LINE__ );
    check_divide( sli1 / li2, __LINE__ );
    sli1 = 17;
    f2 = 4;
    check_add( sli1 + f2, __LINE__ );
    check_subtract( sli1 - f2, __LINE__ );
    check_multiply( sli1 * f2, __LINE__ );
    check_divide( sli1 / f2, __LINE__ );
    sli1 = 17;
    d2 = 4;
    check_add( sli1 + d2, __LINE__ );
    check_subtract( sli1 - d2, __LINE__ );
    check_multiply( sli1 * d2, __LINE__ );
    check_divide( sli1 / d2, __LINE__ );
    sli1 = 17;
    ld2 = 4;
    check_add( sli1 + ld2, __LINE__ );
    check_subtract( sli1 - ld2, __LINE__ );
    check_multiply( sli1 * ld2, __LINE__ );
    check_divide( sli1 / ld2, __LINE__ );
    uli1 = 17;
    sc2 = 4;
    check_add( uli1 + sc2, __LINE__ );
    check_subtract( uli1 - sc2, __LINE__ );
    check_multiply( uli1 * sc2, __LINE__ );
    check_divide( uli1 / sc2, __LINE__ );
    uli1 = 17;
    uc2 = 4;
    check_add( uli1 + uc2, __LINE__ );
    check_subtract( uli1 - uc2, __LINE__ );
    check_multiply( uli1 * uc2, __LINE__ );
    check_divide( uli1 / uc2, __LINE__ );
    uli1 = 17;
    c2 = 4;
    check_add( uli1 + c2, __LINE__ );
    check_subtract( uli1 - c2, __LINE__ );
    check_multiply( uli1 * c2, __LINE__ );
    check_divide( uli1 / c2, __LINE__ );
    uli1 = 17;
    ss2 = 4;
    check_add( uli1 + ss2, __LINE__ );
    check_subtract( uli1 - ss2, __LINE__ );
    check_multiply( uli1 * ss2, __LINE__ );
    check_divide( uli1 / ss2, __LINE__ );
    uli1 = 17;
    us2 = 4;
    check_add( uli1 + us2, __LINE__ );
    check_subtract( uli1 - us2, __LINE__ );
    check_multiply( uli1 * us2, __LINE__ );
    check_divide( uli1 / us2, __LINE__ );
    uli1 = 17;
    s2 = 4;
    check_add( uli1 + s2, __LINE__ );
    check_subtract( uli1 - s2, __LINE__ );
    check_multiply( uli1 * s2, __LINE__ );
    check_divide( uli1 / s2, __LINE__ );
    uli1 = 17;
    si2 = 4;
    check_add( uli1 + si2, __LINE__ );
    check_subtract( uli1 - si2, __LINE__ );
    check_multiply( uli1 * si2, __LINE__ );
    check_divide( uli1 / si2, __LINE__ );
    uli1 = 17;
    ui2 = 4;
    check_add( uli1 + ui2, __LINE__ );
    check_subtract( uli1 - ui2, __LINE__ );
    check_multiply( uli1 * ui2, __LINE__ );
    check_divide( uli1 / ui2, __LINE__ );
    uli1 = 17;
    i2 = 4;
    check_add( uli1 + i2, __LINE__ );
    check_subtract( uli1 - i2, __LINE__ );
    check_multiply( uli1 * i2, __LINE__ );
    check_divide( uli1 / i2, __LINE__ );
    uli1 = 17;
    sli2 = 4;
    check_add( uli1 + sli2, __LINE__ );
    check_subtract( uli1 - sli2, __LINE__ );
    check_multiply( uli1 * sli2, __LINE__ );
    check_divide( uli1 / sli2, __LINE__ );
    uli1 = 17;
    uli2 = 4;
    check_add( uli1 + uli2, __LINE__ );
    check_subtract( uli1 - uli2, __LINE__ );
    check_multiply( uli1 * uli2, __LINE__ );
    check_divide( uli1 / uli2, __LINE__ );
    uli1 = 17;
    li2 = 4;
    check_add( uli1 + li2, __LINE__ );
    check_subtract( uli1 - li2, __LINE__ );
    check_multiply( uli1 * li2, __LINE__ );
    check_divide( uli1 / li2, __LINE__ );
    uli1 = 17;
    f2 = 4;
    check_add( uli1 + f2, __LINE__ );
    check_subtract( uli1 - f2, __LINE__ );
    check_multiply( uli1 * f2, __LINE__ );
    check_divide( uli1 / f2, __LINE__ );
    uli1 = 17;
    d2 = 4;
    check_add( uli1 + d2, __LINE__ );
    check_subtract( uli1 - d2, __LINE__ );
    check_multiply( uli1 * d2, __LINE__ );
    check_divide( uli1 / d2, __LINE__ );
    uli1 = 17;
    ld2 = 4;
    check_add( uli1 + ld2, __LINE__ );
    check_subtract( uli1 - ld2, __LINE__ );
    check_multiply( uli1 * ld2, __LINE__ );
    check_divide( uli1 / ld2, __LINE__ );
    li1 = 17;
    sc2 = 4;
    check_add( li1 + sc2, __LINE__ );
    check_subtract( li1 - sc2, __LINE__ );
    check_multiply( li1 * sc2, __LINE__ );
    check_divide( li1 / sc2, __LINE__ );
    li1 = 17;
    uc2 = 4;
    check_add( li1 + uc2, __LINE__ );
    check_subtract( li1 - uc2, __LINE__ );
    check_multiply( li1 * uc2, __LINE__ );
    check_divide( li1 / uc2, __LINE__ );
#else
    li1 = 17;
    c2 = 4;
    check_add( li1 + c2, __LINE__ );
    check_subtract( li1 - c2, __LINE__ );
    check_multiply( li1 * c2, __LINE__ );
    check_divide( li1 / c2, __LINE__ );
    li1 = 17;
    ss2 = 4;
    check_add( li1 + ss2, __LINE__ );
    check_subtract( li1 - ss2, __LINE__ );
    check_multiply( li1 * ss2, __LINE__ );
    check_divide( li1 / ss2, __LINE__ );
    li1 = 17;
    us2 = 4;
    check_add( li1 + us2, __LINE__ );
    check_subtract( li1 - us2, __LINE__ );
    check_multiply( li1 * us2, __LINE__ );
    check_divide( li1 / us2, __LINE__ );
    li1 = 17;
    s2 = 4;
    check_add( li1 + s2, __LINE__ );
    check_subtract( li1 - s2, __LINE__ );
    check_multiply( li1 * s2, __LINE__ );
    check_divide( li1 / s2, __LINE__ );
    li1 = 17;
    si2 = 4;
    check_add( li1 + si2, __LINE__ );
    check_subtract( li1 - si2, __LINE__ );
    check_multiply( li1 * si2, __LINE__ );
    check_divide( li1 / si2, __LINE__ );
    li1 = 17;
    ui2 = 4;
    check_add( li1 + ui2, __LINE__ );
    check_subtract( li1 - ui2, __LINE__ );
    check_multiply( li1 * ui2, __LINE__ );
    check_divide( li1 / ui2, __LINE__ );
    li1 = 17;
    i2 = 4;
    check_add( li1 + i2, __LINE__ );
    check_subtract( li1 - i2, __LINE__ );
    check_multiply( li1 * i2, __LINE__ );
    check_divide( li1 / i2, __LINE__ );
    li1 = 17;
    sli2 = 4;
    check_add( li1 + sli2, __LINE__ );
    check_subtract( li1 - sli2, __LINE__ );
    check_multiply( li1 * sli2, __LINE__ );
    check_divide( li1 / sli2, __LINE__ );
    li1 = 17;
    uli2 = 4;
    check_add( li1 + uli2, __LINE__ );
    check_subtract( li1 - uli2, __LINE__ );
    check_multiply( li1 * uli2, __LINE__ );
    check_divide( li1 / uli2, __LINE__ );
    li1 = 17;
    li2 = 4;
    check_add( li1 + li2, __LINE__ );
    check_subtract( li1 - li2, __LINE__ );
    check_multiply( li1 * li2, __LINE__ );
    check_divide( li1 / li2, __LINE__ );
    li1 = 17;
    f2 = 4;
    check_add( li1 + f2, __LINE__ );
    check_subtract( li1 - f2, __LINE__ );
    check_multiply( li1 * f2, __LINE__ );
    check_divide( li1 / f2, __LINE__ );
    li1 = 17;
    d2 = 4;
    check_add( li1 + d2, __LINE__ );
    check_subtract( li1 - d2, __LINE__ );
    check_multiply( li1 * d2, __LINE__ );
    check_divide( li1 / d2, __LINE__ );
    li1 = 17;
    ld2 = 4;
    check_add( li1 + ld2, __LINE__ );
    check_subtract( li1 - ld2, __LINE__ );
    check_multiply( li1 * ld2, __LINE__ );
    check_divide( li1 / ld2, __LINE__ );
    f1 = 17;
    sc2 = 4;
    check_add( f1 + sc2, __LINE__ );
    check_subtract( f1 - sc2, __LINE__ );
    check_multiply( f1 * sc2, __LINE__ );
    check_divide( f1 / sc2, __LINE__ );
    f1 = 17;
    uc2 = 4;
    check_add( f1 + uc2, __LINE__ );
    check_subtract( f1 - uc2, __LINE__ );
    check_multiply( f1 * uc2, __LINE__ );
    check_divide( f1 / uc2, __LINE__ );
    f1 = 17;
    c2 = 4;
    check_add( f1 + c2, __LINE__ );
    check_subtract( f1 - c2, __LINE__ );
    check_multiply( f1 * c2, __LINE__ );
    check_divide( f1 / c2, __LINE__ );
    f1 = 17;
    ss2 = 4;
    check_add( f1 + ss2, __LINE__ );
    check_subtract( f1 - ss2, __LINE__ );
    check_multiply( f1 * ss2, __LINE__ );
    check_divide( f1 / ss2, __LINE__ );
    f1 = 17;
    us2 = 4;
    check_add( f1 + us2, __LINE__ );
    check_subtract( f1 - us2, __LINE__ );
    check_multiply( f1 * us2, __LINE__ );
    check_divide( f1 / us2, __LINE__ );
    f1 = 17;
    s2 = 4;
    check_add( f1 + s2, __LINE__ );
    check_subtract( f1 - s2, __LINE__ );
    check_multiply( f1 * s2, __LINE__ );
    check_divide( f1 / s2, __LINE__ );
    f1 = 17;
    si2 = 4;
    check_add( f1 + si2, __LINE__ );
    check_subtract( f1 - si2, __LINE__ );
    check_multiply( f1 * si2, __LINE__ );
    check_divide( f1 / si2, __LINE__ );
    f1 = 17;
    ui2 = 4;
    check_add( f1 + ui2, __LINE__ );
    check_subtract( f1 - ui2, __LINE__ );
    check_multiply( f1 * ui2, __LINE__ );
    check_divide( f1 / ui2, __LINE__ );
    f1 = 17;
    i2 = 4;
    check_add( f1 + i2, __LINE__ );
    check_subtract( f1 - i2, __LINE__ );
    check_multiply( f1 * i2, __LINE__ );
    check_divide( f1 / i2, __LINE__ );
    f1 = 17;
    sli2 = 4;
    check_add( f1 + sli2, __LINE__ );
    check_subtract( f1 - sli2, __LINE__ );
    check_multiply( f1 * sli2, __LINE__ );
    check_divide( f1 / sli2, __LINE__ );
    f1 = 17;
    uli2 = 4;
    check_add( f1 + uli2, __LINE__ );
    check_subtract( f1 - uli2, __LINE__ );
    check_multiply( f1 * uli2, __LINE__ );
    check_divide( f1 / uli2, __LINE__ );
    f1 = 17;
    li2 = 4;
    check_add( f1 + li2, __LINE__ );
    check_subtract( f1 - li2, __LINE__ );
    check_multiply( f1 * li2, __LINE__ );
    check_divide( f1 / li2, __LINE__ );
    f1 = 17;
    f2 = 4;
    check_add( f1 + f2, __LINE__ );
    check_subtract( f1 - f2, __LINE__ );
    check_multiply( f1 * f2, __LINE__ );
    check_divide( f1 / f2, __LINE__ );
    f1 = 17;
    d2 = 4;
    check_add( f1 + d2, __LINE__ );
    check_subtract( f1 - d2, __LINE__ );
    check_multiply( f1 * d2, __LINE__ );
    check_divide( f1 / d2, __LINE__ );
    f1 = 17;
    ld2 = 4;
    check_add( f1 + ld2, __LINE__ );
    check_subtract( f1 - ld2, __LINE__ );
    check_multiply( f1 * ld2, __LINE__ );
    check_divide( f1 / ld2, __LINE__ );
    d1 = 17;
    sc2 = 4;
    check_add( d1 + sc2, __LINE__ );
    check_subtract( d1 - sc2, __LINE__ );
    check_multiply( d1 * sc2, __LINE__ );
    check_divide( d1 / sc2, __LINE__ );
    d1 = 17;
    uc2 = 4;
    check_add( d1 + uc2, __LINE__ );
    check_subtract( d1 - uc2, __LINE__ );
    check_multiply( d1 * uc2, __LINE__ );
    check_divide( d1 / uc2, __LINE__ );
    d1 = 17;
    c2 = 4;
    check_add( d1 + c2, __LINE__ );
    check_subtract( d1 - c2, __LINE__ );
    check_multiply( d1 * c2, __LINE__ );
    check_divide( d1 / c2, __LINE__ );
    d1 = 17;
    ss2 = 4;
    check_add( d1 + ss2, __LINE__ );
    check_subtract( d1 - ss2, __LINE__ );
    check_multiply( d1 * ss2, __LINE__ );
    check_divide( d1 / ss2, __LINE__ );
    d1 = 17;
    us2 = 4;
    check_add( d1 + us2, __LINE__ );
    check_subtract( d1 - us2, __LINE__ );
    check_multiply( d1 * us2, __LINE__ );
    check_divide( d1 / us2, __LINE__ );
    d1 = 17;
    s2 = 4;
    check_add( d1 + s2, __LINE__ );
    check_subtract( d1 - s2, __LINE__ );
    check_multiply( d1 * s2, __LINE__ );
    check_divide( d1 / s2, __LINE__ );
    d1 = 17;
    si2 = 4;
    check_add( d1 + si2, __LINE__ );
    check_subtract( d1 - si2, __LINE__ );
    check_multiply( d1 * si2, __LINE__ );
    check_divide( d1 / si2, __LINE__ );
    d1 = 17;
    ui2 = 4;
    check_add( d1 + ui2, __LINE__ );
    check_subtract( d1 - ui2, __LINE__ );
    check_multiply( d1 * ui2, __LINE__ );
    check_divide( d1 / ui2, __LINE__ );
    d1 = 17;
    i2 = 4;
    check_add( d1 + i2, __LINE__ );
    check_subtract( d1 - i2, __LINE__ );
    check_multiply( d1 * i2, __LINE__ );
    check_divide( d1 / i2, __LINE__ );
    d1 = 17;
    sli2 = 4;
    check_add( d1 + sli2, __LINE__ );
    check_subtract( d1 - sli2, __LINE__ );
    check_multiply( d1 * sli2, __LINE__ );
    check_divide( d1 / sli2, __LINE__ );
    d1 = 17;
    uli2 = 4;
    check_add( d1 + uli2, __LINE__ );
    check_subtract( d1 - uli2, __LINE__ );
    check_multiply( d1 * uli2, __LINE__ );
    check_divide( d1 / uli2, __LINE__ );
    d1 = 17;
    li2 = 4;
    check_add( d1 + li2, __LINE__ );
    check_subtract( d1 - li2, __LINE__ );
    check_multiply( d1 * li2, __LINE__ );
    check_divide( d1 / li2, __LINE__ );
    d1 = 17;
    f2 = 4;
    check_add( d1 + f2, __LINE__ );
    check_subtract( d1 - f2, __LINE__ );
    check_multiply( d1 * f2, __LINE__ );
    check_divide( d1 / f2, __LINE__ );
    d1 = 17;
    d2 = 4;
    check_add( d1 + d2, __LINE__ );
    check_subtract( d1 - d2, __LINE__ );
    check_multiply( d1 * d2, __LINE__ );
    check_divide( d1 / d2, __LINE__ );
    d1 = 17;
    ld2 = 4;
    check_add( d1 + ld2, __LINE__ );
    check_subtract( d1 - ld2, __LINE__ );
    check_multiply( d1 * ld2, __LINE__ );
    check_divide( d1 / ld2, __LINE__ );
    ld1 = 17;
    sc2 = 4;
    check_add( ld1 + sc2, __LINE__ );
    check_subtract( ld1 - sc2, __LINE__ );
    check_multiply( ld1 * sc2, __LINE__ );
    check_divide( ld1 / sc2, __LINE__ );
    ld1 = 17;
    uc2 = 4;
    check_add( ld1 + uc2, __LINE__ );
    check_subtract( ld1 - uc2, __LINE__ );
    check_multiply( ld1 * uc2, __LINE__ );
    check_divide( ld1 / uc2, __LINE__ );
    ld1 = 17;
    c2 = 4;
    check_add( ld1 + c2, __LINE__ );
    check_subtract( ld1 - c2, __LINE__ );
    check_multiply( ld1 * c2, __LINE__ );
    check_divide( ld1 / c2, __LINE__ );
    ld1 = 17;
    ss2 = 4;
    check_add( ld1 + ss2, __LINE__ );
    check_subtract( ld1 - ss2, __LINE__ );
    check_multiply( ld1 * ss2, __LINE__ );
    check_divide( ld1 / ss2, __LINE__ );
    ld1 = 17;
    us2 = 4;
    check_add( ld1 + us2, __LINE__ );
    check_subtract( ld1 - us2, __LINE__ );
    check_multiply( ld1 * us2, __LINE__ );
    check_divide( ld1 / us2, __LINE__ );
    ld1 = 17;
    s2 = 4;
    check_add( ld1 + s2, __LINE__ );
    check_subtract( ld1 - s2, __LINE__ );
    check_multiply( ld1 * s2, __LINE__ );
    check_divide( ld1 / s2, __LINE__ );
    ld1 = 17;
    si2 = 4;
    check_add( ld1 + si2, __LINE__ );
    check_subtract( ld1 - si2, __LINE__ );
    check_multiply( ld1 * si2, __LINE__ );
    check_divide( ld1 / si2, __LINE__ );
    ld1 = 17;
    ui2 = 4;
    check_add( ld1 + ui2, __LINE__ );
    check_subtract( ld1 - ui2, __LINE__ );
    check_multiply( ld1 * ui2, __LINE__ );
    check_divide( ld1 / ui2, __LINE__ );
    ld1 = 17;
    i2 = 4;
    check_add( ld1 + i2, __LINE__ );
    check_subtract( ld1 - i2, __LINE__ );
    check_multiply( ld1 * i2, __LINE__ );
    check_divide( ld1 / i2, __LINE__ );
    ld1 = 17;
    sli2 = 4;
    check_add( ld1 + sli2, __LINE__ );
    check_subtract( ld1 - sli2, __LINE__ );
    check_multiply( ld1 * sli2, __LINE__ );
    check_divide( ld1 / sli2, __LINE__ );
    ld1 = 17;
    uli2 = 4;
    check_add( ld1 + uli2, __LINE__ );
    check_subtract( ld1 - uli2, __LINE__ );
    check_multiply( ld1 * uli2, __LINE__ );
    check_divide( ld1 / uli2, __LINE__ );
    ld1 = 17;
    li2 = 4;
    check_add( ld1 + li2, __LINE__ );
    check_subtract( ld1 - li2, __LINE__ );
    check_multiply( ld1 * li2, __LINE__ );
    check_divide( ld1 / li2, __LINE__ );
    ld1 = 17;
    f2 = 4;
    check_add( ld1 + f2, __LINE__ );
    check_subtract( ld1 - f2, __LINE__ );
    check_multiply( ld1 * f2, __LINE__ );
    check_divide( ld1 / f2, __LINE__ );
    ld1 = 17;
    d2 = 4;
    check_add( ld1 + d2, __LINE__ );
    check_subtract( ld1 - d2, __LINE__ );
    check_multiply( ld1 * d2, __LINE__ );
    check_divide( ld1 / d2, __LINE__ );
    ld1 = 17;
    ld2 = 4;
    check_add( ld1 + ld2, __LINE__ );
    check_subtract( ld1 - ld2, __LINE__ );
    check_multiply( ld1 * ld2, __LINE__ );
    check_divide( ld1 / ld2, __LINE__ );
#endif
#endif
    _PASS;
}
