#pmake: build medium cpu_i86 os_win
#
# cplxm.lib -- medium memory-model COMPLEX library fpc for Windows
#
processor  = 086
system     = windows
model      = mm
linkage    = static
define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
