// Resource Display Window headings

pick(   STR_BITMAP,
        "BITMAP",
        "BITMAP" )
pick(   STR_ICON,
        "ICON",
        "ICON" )
pick(   STR_CURSOR,
        "CURSOR",
        "CURSOR" )
pick(   STR_MENU,
        "MENU",
        "MENU" )
pick(   STR_NADA,
        "",
        "" )
pick(   STR_CANT_LOCK_MEM,
        "Could not lock memory",
        "Could not lock memory" )
pick(   STR_CANT_CREATE_DLG,
        "Could not create dialogue",
        "Could not create dialogue" )
pick(   STR_NO_ITEM_SELECTED,
        "No item has been selected",
        "No item has been selected" )
pick(   STR_UNABLE_TO_DISP_GRAPHIC,
        "Unable to display graphic resource\n(probable cause: lack of memory)",
        "Unable to display graphic resource\n(probable cause: lack of memory)" )

// types for local heap objects
pick(   STR_FREE,
        "FREE",
        "FREE" )
pick(   STR_MOVEABLE,
        "MOVEABLE",
        "MOVEABLE" )
pick(   STR_FIXED,
        "FIXED",
        "FIXED" )
pick(   STR_PEN,
        "PEN",
        "PEN" )
pick(   STR_BRUSH,
        "BRUSH",
        "BRUSH" )
pick(   STR_FONT,
        "FONT",
        "FONT" )
pick(   STR_PALETTE,
        "PALETTE",
        "PALETTE" )
pick(   STR_RGN,
        "RGN",
        "RGN" )
pick(   STR_DEVICE_CONTEXT,
        "DEVICE CONTEXT",
        "DEVICE CONTEXT" )
pick(   STR_DISABLED_DC,
        "DISABLED DEVICE CONTEXT",
        "DISABLED DEVICE CONTEXT" )
pick(   STR_META_DC,
        "META DEVICE CONTEXT",
        "META DEVICE CONTEXT" )
pick(   STR_METAFILE,
        "METAFILE",
        "METAFILE" )
pick(   STR_MAX,
        "MAX",
        "MAX" )
pick(   STR_UNKNOWN,
        "UNKNOWN",
        "UNKNOWN" )
pick(   STR_CLASS,
        "CLASS",
        "CLASS" )
pick(   STR_WND,
        "WND",
        "WND" )
pick(   STR_CLIP,
        "CLIP",
        "CLIP" )
pick(   STR_CBOX,
        "CBOX",
        "CBOX" )
pick(   STR_ED,
        "ED",
        "ED" )
pick(   STR_BWL,
        "BWL",
        "BWL" )
pick(   STR_OWNERDRAWN,
        "OWNERDRAWN",
        "OWNERDRAWN" )
pick(   STR_SPB,
        "SPB",
        "SPB" )
pick(   STR_CHECKPOINT,
        "CHECKPOINT",
        "CHECKPOINT" )
pick(   STR_DCE,
        "DCE",
        "DCE" )
pick(   STR_MWP,
        "MWP",
        "MWP" )
pick(   STR_PROP,
        "PROP",
        "PROP" )
pick(   STR_LBIV,
        "LBIV",
        "LBIV" )
pick(   STR_MISC,
        "MISC",
        "MISC" )
pick(   STR_ATOMS,
        "ATOMS",
        "ATOMS" )
pick(   STR_LOCKINPUTSTATE,
        "LOCKINPUTSTATE",
        "LOCKINPUTSTATE" )
pick(   STR_HOOKLIST,
        "HOOKLIST",
        "HOOKLIST" )
pick(   STR_USUDA,
        "USUDA",
        "USUDA" )
pick(   STR_HOTKEYLIST,
        "HOTKEYLIST",
        "HOTKEYLIST" )
pick(   STR_POPUPMENU,
        "POPUPMENU",
        "POPUPMENU" )
pick(   STR_HANDLETABLE,
        "HANDLETABLE",
        "HANDLETABLE" )

// save local heap file text
pick(   STR_SNAP_LCL_CREATED,
        "Snapshot of the Local Heap created:   %s\n",
        "Snapshot of the Local Heap created:   %s\n" )
pick(   STR_LCL_HEAP_OF,
        "This is the Local Heap of %s.\n",
        "This is the Local Heap of %s.\n" )
pick(   STR_LCL_SORTED_BY,
        "Items are sorted by %s.\n\n",
        "Items are sorted by %s.\n\n" )
pick(   STR_LCL_SUMMARY_HEADING,
        "                 \tCount  \tSize (in bytes)\n\n",
        "                 \tCount  \tSize (in bytes)\n\n" )
pick(   STR_LCL_FREE_OBJECTS,
        "Free Objects     \t%-5u   \t%-5u\n",
        "Free Objects     \t%-5u   \t%-5u\n" )
pick(   STR_LCL_MOVEABLE_OBJECTS,
        "Moveable Objects \t%-5u   \t%-5u\n",
        "Moveable Objects \t%-5u   \t%-5u\n" )
pick(   STR_LCL_FIXED_OBJECTS,
        "Fixed Objects    \t%-5u   \t%-5u\n",
        "Fixed Objects    \t%-5u   \t%-5u\n" )
pick(   STR_LCL_TOTAL_LINE,
        "                 \t=========================\n",
        "                 \t=========================\n" )
pick(   STR_LCL_TOTAL_OBJECTS,
        "Total            \t%-5u   \t%-5u\n",
        "Total            \t%-5u   \t%-5u\n" )
pick(   STR_UNABLE_DISP_LCL_HEAP,
        "Unable to display local heap",
        "Unable to display local heap" )
pick(   STR_LCL_HEAP_NO_MEM,
        "Unable to display local heap\n(probable cause: lack of memory)",
        "Unable to display local heap\n(probable cause: lack of memory)" )
pick(   STR_LCL_WIN_TITLE,
        "%s Local Heap",
        "%s Local Heap" )
pick(   STR_CANT_OPEN_LCL_WIN,
        "Unable to open local heap window",
        "Unable to open local heap window" )

// default file name for global and local heap saves
pick(   STR_DEF_GLOB_HEAP_FNAME,
        "hwg",
        "hwg" )
pick(   STR_DEF_LCL_HEAP_FNAME,
        "hwl",
        "hwl" )
pick(   STR_INVALID_GLOB_FNAME,
        "File name for global heap saves is invalid",
        "File name for global heap saves is invalid" )
pick(   STR_INVALID_LCL_FNAME,
        "File name for local heap saves is invalid",
        "File name for local heap saves is invalid" )
pick(   STR_INVALID_MEM_FNAME,
        "File name for memory dumps is invalid",
        "File name for memory dumps is invalid" )
pick(   STR_INSTALL_WDEBUG,
        "You must have WDEBUG.386 installed!",
        "You must have WDEBUG.386 installed!" )

// menu headings/items
pick(   STR_SORT,
        "&Sort",
        "&Sort")
pick(   STR_BY_AGE,
        "By &Age",
        "By &Age" )

pick(   STR_HAS_NO_LCL_HEAP,
        "This item has no local heap",
        "This item has no local heap" )
pick(   STR_UNABLE_2_STARTUP,
        "Unable to start up heapwalker\n(probable cause: lack of memory)",
        "Unable to start up heapwalker\n(probable cause: lack of memory)" )

// about box information
pick(   STR_ABOUT_NAME,
        "Open Watcom Heapwalker for Windows",
        "Open Watcom Heapwalker for Windows" )
pick(   STR_ABOUT_VERSION, //NOT USED
        "",
        "" )
pick(   STR_ABOUT_COPYRIGHT_YEAR,
        "1993",
        "1993" )
pick(   STR_ABOUT_TITLE,
        "About Open Watcom Heapwalker",
        "About Open Watcom Heapwalker" )
pick(   STR_UNABLE_TO_ADD,
        "Unable to do add\n(probable cause: lack of memory)",
        "Unable to do add\n(probable cause: lack of memory)" )

//sort types
pick(   STR_ADDRESS,
        "address",
        "address" )
pick(   STR_HANDLE,
        "handle",
        "handle" )
pick(   STR_LC_MODULE,
        "module",
        "module" )
pick(   STR_SIZE,
        "size",
        "size" )
pick(   STR_TYPE,
        "type",
        "type" )
pick(   STR_FLAG,
        "flag",
        "flag" )
pick(   STR_AGE,
        "age",
        "age" )

// Selector Sort Types
pick(   STR_BASE_ADDR,
        "base address",
        "base address" )
pick(   STR_SELECTOR,
        "selector",
        "selector" )
pick(   STR_LIMIT,
        "limit",
        "limit" )
pick(   STR_GRANULARITY,
        "granularity",
        "granularity" )
pick(   STR_DPL,
        "dpl",
        "dpl" )

// Items displayed
pick(   STR_ALL_HEAP_ITEMS,
        "All heap items",
        "All heap items" )
pick(   STR_ONLY_LRU_ITEMS,
        "Only LRU items",
        "Only LRU items" )
pick(   STR_ONLY_FREE_ITEMS,
        "Only free items",
        "Only free items" )
pick(   STR_SELECTOR_LIST,
        "Selector list",
        "Selector list" )

// When this string is used an items from the 'Items displayed' list (above)
// is substituted for the first %s and and item from the 'Sort Types' or
// 'Selector Sort Types' (above) is substituted for the second %s
pick(   STR_GBL_SORTED_BY,
        "%s displayed - Sorted by %s\n\n",
        "%s displayed - Sorted by %s\n\n" )
pick(   STR_GBL_HEAPINFO,
        "Global Heap Information:\n",
        "Global Heap Information:\n" )
pick(   STR_GBL_INFO_UNDERLINE,
        "========================\n\n",
        "========================\n\n" )
pick(   STR_GBL_TOT_ITEMS,
        "Total Items on Heap:  \t%-u\n",
        "Total Items on Heap:  \t%-u\n" )
pick(   STR_GBL_LRU_ITEMS,
        "Number of LRU items:  \t%-u\n",
        "Number of LRU items:  \t%-u\n" )
pick(   STR_GBL_FREE_ITEMS,
        "Number of free items: \t%-u\n\n",
        "Number of free items: \t%-u\n\n" )

pick(   STR_MEM_MAN_INFO,
        "Memory Management Information:\n",
        "Memory Management Information:\n" )
pick(   STR_MEM_MAN_UNDERLINE,
        "==============================\n",
        "==============================\n" )
pick(   STR_SIZE_LIN_ADDR_SPACE,
        "Size of Linear Address Space (in pages): \t%-lu\n",
        "Size of Linear Address Space (in pages): \t%-lu\n" )
pick(   STR_FREE_PAGES,
        "Free Pages in Linear Address Space:      \t%-lu\n",
        "Free Pages in Linear Address Space:      \t%-lu\n" )
pick(   STR_SYS_PAGE_SIZE,
        "System Page Size (in bytes):             \t%-u\n",
        "System Page Size (in bytes):             \t%-u\n" )
pick(   STR_PAGES_IN_SWAP_FILE,
        "Pages in Swap File:                      \t%-lu\n",
        "Pages in Swap File:                      \t%-lu\n" )
pick(   STR_TOT_PAGES_IN_SYSTEM,
        "Total Pages in System:                   \t%-lu\n",
        "Total Pages in System:                   \t%-lu\n" )
pick(   STR_NUM_UNLOCKED_PAGES,
        "Number of Unlocked Pages:                \t%-lu\n",
        "Number of Unlocked Pages:                \t%-lu\n" )
pick(   STR_NUM_FREE_PAGES,
        "Number of Free Pages:                    \t%-lu\n",
        "Number of Free Pages:                    \t%-lu\n" )
pick(   STR_LARGEST_FREE_MEM_BLOCK,
        "Largest Free Memory Block:               \t%-lu\n",
        "Largest Free Memory Block:               \t%-lu\n" )
pick(   STR_MAX_ALLOCATABLE_PAGES,
        "Maximum Allocatable Pages:               \t%-lu\n",
        "Maximum Allocatable Pages:               \t%-lu\n" )
pick(   STR_MAX_LOCKABLE_PAGES,
        "Maximum Lockable Pages:                  \t%-lu\n\n",
        "Maximum Lockable Pages:                  \t%-lu\n\n" )


pick(   STR_SNAP_GBL_CREATED,
        "Snapshot of the Global Heap created:   %s",
        "Snapshot of the Global Heap created:   %s" )

//strings for the local heap monitor
pick(   STR_STATIC_DATA,
        "Static Data [%u]",
        "Static Data [%u]" )
pick(   STR_STACK_ALLOCATED,
        "Stack Allocated [%u], used [%u]",
        "Stack Allocated [%u], used [%u]" )
pick(   STR_FIXED_HEAP,
        "Fixed Heap [%u]",
        "Fixed Heap [%u]" )
pick(   STR_MOVEABLE_HEAP,
        "Moveable Heap [%u]",
        "Moveable Heap [%u]" )
pick(   STR_FREE_HEAP,
        "Free Heap [%u]",
        "Free Heap [%u]" )
pick(   STR_MONITOR_UNKNOWN,
        "Unknown [%u]",
        "Unknown [%u]" )

pick(   STR_CANT_OPEN_LCL_MONITOR,
        "Unable to open local monitor window",
        "Unable to open local monitor window" )
pick(   STR_LCL_MONITOR_TITLE,
        "%s Local Heap Monitor",
        "%s Local Heap Monitor" )
pick(   STR_APP_NAME,
        "Open Watcom Heap Walker",
        "Open Watcom Heap Walker" )

pick(   STR_GBL_HEADINGS,
        "Handle  Address     Size  Owner    Flags Lock  Heap Type ",
        "Handle  Address     Size  Owner    Flags Lock  Heap Type " )
pick(   STR_SELECTOR_HEADINGS,
        " Sel.  Base      Limit     Gran. Type DPL Access Big",
        " Sel.  Base      Limit     Gran. Type DPL Access Big" )
pick(   STR_LCL_HEADINGS,
        "Offset Handle   Size Flags     Locks Type",
        "Offset Handle   Size Flags     Locks Type" )

pick(   STR_FREE_N_BYTES,
        "Free n bytes",
        "Free n bytes" )
pick(   STR_BYTES_TO_FREE,
        "Bytes to free:",
        "Bytes to free:" )
pick(   STR_ALLOC_N_BYTES,
        "Allocate n bytes",
        "Allocate n bytes" )
pick(   STR_BYTES_TO_ALLOC,
        "Bytes to allocate:",
        "Bytes to allocate:" )
pick(   STR_ALLOC_ALL_BUT_N,
        "Allocate all but n bytes",
        "Allocate all but n bytes" )
pick(   STR_BYTES_TO_LEAVE_FREE,
        "Bytes to leave free:",
        "Bytes to leave free:" )
pick(   STR_AMT_ENTERED_INVALID,
        "The amount entered in invalid",
        "The amount entered in invalid" )
pick(   STR_CANT_FREE_REQ_AMT,
        "Unable to free the requested amount",
        "Unable to free the requested amount" )
pick(   STR_CANT_ALLOC_REQ_AMT,
        "Unable to allocate the requested amount",
        "Unable to allocate the requested amount" )
pick(   STR_CANT_DISCARD_ITEM,
        "Unable to discard that item",
        "Unable to discard that item" )
pick(   STR_HDL_DISCARDED,
        "Handle %04X discarded\n%lu bytes discarded\n",
        "Handle %04X discarded\n%lu bytes discarded\n" )
pick(   STR_CANT_REPOSITION,
        "Unable to reposition\n     Handle %04X",
        "Unable to reposition\n     Handle %04X" )

// THESE 2 MESSAGES HAVE CHANGED REMEMBER TO CHANGE THE CODE
pick(   STR_HDL_IS_NOW_OLDEST,
        "Handle %04X\nis now the oldest item on the LRU list",
        "Handle %04X\nis now the oldest item on the LRU list" )
pick(   STR_HDL_IS_NOW_NEWEST,
        "Handle %04X\nis now the newest item on the LRU list",
        "Handle %04X\nis now the newest item on the LRU list" )

pick(   STR_CANT_COMPLETE_ADD,
        "Unable to complete add.\n(probable cause: lack of memory)",
        "Unable to complete add.\n(probable cause: lack of memory)" )
pick(   STR_VALUE_K,
        "%u K",
        "%u K" )
pick(   STR_INVALID_SIZE,
        "Invalid size",
        "Invalid size" )
pick(   STR_SIZE_TOO_LARGE,
        "Size is too large",
        "Size is too large" )
pick(   STR_CANT_GET_MEM_MAN_INFO,
        "Unable to get memory manager information",
        "Unable to get memory manager information" )
pick(   STR_CANT_GET_GBL_HEAP_INFO,
        "Unable to get global heap information",
        "Unable to get global heap information" )

// GLOBAL TYPES
pick(   STR_MC_UNKNOWN,
        "Unknown",
        "Unknown" )
pick(   STR_DGROUP,
        "Dgroup",
        "Dgroup" )
pick(   STR_DATA,
        "Data",
        "Data" )
pick(   STR_CODE,
        "Code",
        "Code" )
pick(   STR_TASK,
        "Task",
        "Task" )
pick(   STR_RESOURCE,
        "Resource",
        "Resource" )
pick(   STR_MC_MODULE,
        "Module",
        "Module" )
pick(   STR_MC_FREE,
        "Free",
        "Free" )
pick(   STR_INTERNAL,
        "Internal",
        "Internal" )
pick(   STR_SENTINEL,
        "Sentinel",
        "Sentinel" )
pick(   STR_BURGERMASTER,
        "Burgermaster",
        "Burgermaster" )

// RESOURCE TYPES
pick(   STR_USERDEFINED,
        "UserDefined",
        "UserDefined" )
pick(   STR_CURSOR_COMP,
        "Cursor Component",
        "Cursor Component" )
pick(   STR_MC_BITMAP,
        "Bitmap",
        "Bitmap" )
pick(   STR_ICON_COMP,
        "Icon Component",
        "Icon Component" )
pick(   STR_MC_MENU,
        "Menu",
        "Menu" )
pick(   STR_DIALOG,
        "Dialog",
        "Dialog" )
pick(   STR_STRING,
        "String",
        "String" )
pick(   STR_FONTDIR,
        "Fontdir",
        "Fontdir" )
pick(   STR_MC_FONT,
        "Font",
        "Font" )
pick(   STR_ACCELERATORS,
        "Accelerators",
        "Accelerators" )
pick(   STR_RCDATA,
        "Rcdata",
        "Rcdata" )
pick(   STR_ERRTABLE,
        "Errtable",
        "Errtable" )
pick(   STR_MC_CURSOR,
        "Cursor",
        "Cursor" )
pick(   STR_MC_ICON,
        "Icon",
        "Icon" )
pick(   STR_NAMETABLE,
        "Nametable",
        "Nametable" )

pick(   STR_LOWER_UNKNOWN,
        "unknown",
        "unknown" )
pick(   STR_CANT_CONSTRUCT_GBL_LIST,
        "Unable to construct global heap list\n(probable cause: lack of memory)",
        "Unable to construct global heap list\n(probable cause: lack of memory)" )
pick(   STR_CANT_GET_SELECTOR,
        "Unable to get a selector for handle %04X",
        "Unable to get a selector for handle %04X" )
pick(   STR_SELECTOR_FOR_HANDLE,
        "%04X is the selector for handle %04X",
        "%04X is the selector for handle %04X" )
pick(   STR_SHOW,
        "Show",
        "Show" )
pick(   STR_MONITOR_LCL_HEAP,
        "Monitor Local Heap",
        "Monitor Local Heap" )
pick(   STR_MEM_MAN_INFO_TITLE,
        "Memory Management Info",
        "Memory Management Info" )
pick(   STR_GLOB_HEAP_INFO,
        "Global Heap Info",
        "Global Heap Info" )
pick(   STR_GET_SELECTOR,
        "Get Selector",
        "Get Selector" )
pick(   STR_DISCARD,
        "Discard",
        "Discard" )

// These strings should match the strings in the display menu
pick(   STR_LRU_ITEMS,
        "LRU Items",
        "LRU Items" )
pick(   STR_ENTIRE_HEAP,
        "Entire Heap",
        "Entire Heap" )
pick(   STR_FREE_ITEMS,
        "Free Items",
        "Free Items" )
pick(   STR_SELECTOR_LIST_ITEMS,
        "Selector List",
        "Selector List" )

//This string marks the end of the list and must always be last
pick(   STR_THIS_IS_THE_LAST_STRING_IN_THE_LIST,
        "",
        "" )
