#pmake: build flat cpu_386 os_osi
#
# iostmt3r.lib -- register based multi-thread 32-bit IOSTREAM library
#
processor  = 386
system     = generic
model      = ms
convention = register
linkage    = static
mthreaded  = 1
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
