#pmake: build small cpu_i86 os_win
#
# cplxs.lib -- small memory-model COMPLEX library fpc for Windows
#
processor  = 086
system     = windows
model      = ms
linkage    = static
define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
