#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static

!include $(cpplib_dir)/runtime/plib.mif
