#pmake: build flat cpu_386 os_nt
processor  = 386
system     = winnt
model      = mf
convention = stack
linkage    = static
mthreaded  = 1
subdir     = mf_smt

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
