#pmake: build serv remote os_os2 cpu_i86 cpu_386 ser x86
host_cpu = 386
host_os  = os2

os  = os2v2
srv = ser
cpu = x86
which = SERVER
remote_link = 1

extra_objs = seros22.obj

!include $(trap_dir)/master.mif
