#pmake: build serv remote os_os2 cpu_i86 cpu_386 ser x86
host_CPU = 386
host_OS = os2

os  = os2v2
srv = ser
cpu = x86
which = SERVER
type  = remote_link

extra_objs = seros22.obj

!include $(trap_dir)/master.mif
