#pmake/25:all small stack 32bit os2 iX86 rtdll build os_os2 cpu_386
component=clib
processor=386
model=ms
subdir=ms_s
system=os2
convention=stack
!include $(rtdll_dir)\master.mif
!include ..\objs.mif
!include $(rtdll_dir)\mkdll.mif
