;*****************************************************************************
;*
;*                            Open Watcom Project
;*
;*    Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
;*
;*  ========================================================================
;*
;*    This file contains Original Code and/or Modifications of Original
;*    Code as defined in and that are subject to the Sybase Open Watcom
;*    Public License version 1.0 (the 'License'). You may not use this file
;*    except in compliance with the License. BY USING THIS FILE YOU AGREE TO
;*    ALL TERMS AND CONDITIONS OF THE LICENSE. A copy of the License is
;*    provided with the Original Code and Modifications, and is also
;*    available at www.sybase.com/developer/opensource.
;*
;*    The Original Code and all software distributed under the License are
;*    distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
;*    EXPRESS OR IMPLIED, AND SYBASE AND ALL CONTRIBUTORS HEREBY DISCLAIM
;*    ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF
;*    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR
;*    NON-INFRINGEMENT. Please see the License for the specific language
;*    governing rights and limitations under the License.
;*
;*  ========================================================================
;*
;* Description:  WHEN YOU FIGURE OUT WHAT THIS FILE DOES, PLEASE
;*               DESCRIBE IT HERE!
;*
;*****************************************************************************


;  floating point constants in tbyte format
zero    db      000H,000H,000h,000h,000h,000h,000h,000h,000h,000h
;one     db      000h,000h,000h,000h,000h,000h,000h,080h,0ffh,03fh
;log2ten db      0feh,08ah,01bh,0cdh,04bh,078h,09ah,0d4h,000h,040h
;log2e   db      0bch,0f0h,017h,05ch,029h,03bh,0aah,0b8h,0ffh,03fh
;pi      db      035h,0c2h,068h,021h,0a2h,0dah,00fh,0c9h,000h,040h
;log2    db      099h,0f7h,0cfh,0fbh,084h,09ah,020h,09ah,0fdh,03fh
;ln2     db      0ach,079h,0cfh,0d1h,0f7h,017h,072h,0b1h,0feh,03fh

