#pmake: build serv remote os_dos cpu_i86 cpu_386 net x86

tree_depth = 4

host_cpu = i86
host_os  = dos

target_cpu = x86

srv = net
which = SERVER
remote_link = 1

!include $(trap_dir)/lcl/dos/dos.mif
!include $(trap_dir)/master.mif
