#pmake:all small register 32bit calls os2 iX86 rtdll no_build os_os2 cpu_386
component=wrtlib
processor=386
model=ms
subdir=ms_r
system=os2
convention=register
!include $(rtdll)\master.mif
!include ..\objs.mif
!include $(rtdll)\mkdll.mif
