.mif : ..;..\..

EXTRA = /d_NEC_PC /zu /DCLIB_MB

TARG=windows
!ifndef FORM
EXE = exe
FORM = windows
INCLUDES =;..\..\necdos\h
!endif

extra_cdir = ..\..\necdos\c
extra_hdir = ..\..\necdos\h

!include ui.mif
