#pmake: build flat stack 32bit inline os2 iX86 rtdll os_os2 cpu_386
component  = wrtlib
processor  = 387
model      = mf
subdir     = mf_s
system     = os2
convention = stack

!include $(rtdll_dir)/master.mif
