#pmake: build medium cpu_i86 os_win
#
# strgm.lib -- medium memory-model STRING library for Windows
#
processor  = 086
system     = windows
model      = mm
linkage    = static

!include $(cpplib_dir)/string/string.mif
