#pmake: build large cpu_i86 os_win
#
# strgl.lib -- large memory-model STRING library for Windows
#
processor  = 086
system     = windows
model      = ml
linkage    = static
define_library_include = $(cpplib_dir)/string/string.mif
!include $(cpplib_dir)/mklib.mif
