#pmake: build small cpu_i86 os_osi os_os2
#
# iosts.lib -- small memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = ms
linkage    = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
