name: github-release-assets
description: 'Upload release asset file (day and month release)'
inputs:
  drelid:
    description: 'day release ID'
    required: false
    default: ''
    type: string
  mrelid:
    description: 'month release ID'
    required: false
    default: ''
    type: string
  target:
    description: 'install component to process'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - uses: ./.github/actions/artfload
    with:
      artifact: install ${{ inputs.target }}
      gitpath:  'temp'
  - name: Setup curl options
    id: curlcmd
    uses: ./.github/actions/curlcmd
  - if: env.OWTESTMODE != '1'
    run: |
      Join-Path ${{ github.workspace }} temp | Get-ChildItem -File | Foreach-Object {
        $response = ${{ steps.curlcmd.outputs.gh }} -H "Authorization: Bearer ${{ github.token }}" `
        -X POST "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ inputs.drelid }}/assets?name=$($_.Name)" `
        -H "Content-Type: application/octet-stream" `
        --data-binary `@$($_.FullName)
        if( '${{ env.OWDEBUG }}' -eq '1' ) { $response }
      }
    shell: pwsh
  - if: inputs.mrelid != '' && env.OWTESTMODE != '1'
    run: |
      Join-Path ${{ github.workspace }} temp | Get-ChildItem -File | Foreach-Object {
        $response = ${{ steps.curlcmd.outputs.gh }} -H "Authorization: Bearer ${{ github.token }}" `
        -X POST "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ inputs.mrelid }}/assets?name=$($_.Name)" `
        -H "Content-Type: application/octet-stream" `
        --data-binary `@$($_.FullName)
        if( '${{ env.OWDEBUG }}' -eq '1' ) { $response }
      }
    shell: pwsh
