name: github-upload-asset-files
description: 'Upload asset files'
inputs:
  relid:
    description: 'release ID'
    required: false
    default: ''
    type: string
  gitpath:
    description: 'source path for asset files'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    uses: ./.github/actions/curlcmd
  - run: |
      Join-Path ${{github.workspace}} ${{inputs.gitpath}} | Get-ChildItem -File | Foreach-Object {
        if( '${{env.OWTESTMODE}}' -ne '1' ) {
          $response = ${{steps.curlcmd.outputs.gh1}} `
          -X POST "${{steps.curlcmd.outputs.gh3}}/releases/${{inputs.relid}}/assets?name=$($_.Name)" `
          -H "Content-Type: application/octet-stream" `
          --data-binary `@$($_.FullName)
          if( '${{env.OWDEBUG}}' -eq '1' ) { $response }
        } else {
          "$($_.Name), $($_.FullName)"
        }
      }
    shell: pwsh
