#pmake: build compact cpu_i86 os_osi
#
# cplxc.lib -- compact memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mc
linkage    = static

define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
