#pmake: build compact cpu_i86 os_dos os_os2 os_win os_qnx
#
# cplxc.lib -- compact memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mc
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
