// the following is the font used in the status bar of the window
pick(   W_STATUSFONT,
        "Helv.8",
        "Helv.8" )

// WSTAT.C
pick(   W_STATUSNOTCREATED,
        "Could not create status line.",
        "Could not create status line." )
pick(   W_READYMSG,
        "Ready.",
        "Ready." )

// WHINTS.C
pick(   W_MENU_CLEAR,
        "Clear the menu.",
        "Clear the menu." )
pick(   W_MENU_UPDATE,
        "Update the file with this menu.",
        "Update the file with this menu." )
pick(   W_MENU_SAVE,
        "Save this menu.",
        "Save this menu." )
pick(   W_MENU_SAVEAS,
        "Save this menu to a different file.",
        "Save this menu to a different file." )
pick(   W_MENU_SAVEINTO,
        "Copy this menu into a different file.",
        "Copy this menu into a different file." )
pick(   W_MENU_EXIT,
        "Exit the menu editor.",
        "Exit the menu editor." )
pick(   W_MENU_CUT,
        "Cut the menu to the clipboard.",
        "Cut the menu to the clipboard." )
pick(   W_MENU_COPY,
        "Copy the menu to the clipbord.",
        "Copy the menu to the clipbord." )
pick(   W_MENU_PASTE,
        "Paste the menu from the clipboard.",
        "Paste the menu from the clipboard." )
pick(   W_MENU_DELETE,
        "Delete an item from the menu.",
        "Delete an item from the menu." )
pick(   W_MENU_SHOWRIBBON,
        "Show/hide the toolbar.",
        "Show/hide the toolbar." )
pick(   W_MENU_SYMBOLS,
        "Edit Symbols.",
        "Edit Symbols." )
pick(   W_MENU_LOAD_SYMBOLS,
        "Load Symbols.",
        "Load Symbols." )
pick(   W_MENU_RENAME,
        "Rename the menu resource.",
        "Rename the menu resource." )
pick(   W_MENU_MEM_FLAGS,
        "Modify the menu memory options.",
        "Modify the menu memory options." )
pick(   W_MENU_INSERTAFTER,
        "Insert new items after current item.",
        "Insert new items after current item." )
pick(   W_MENU_INSERTBEFORE,
        "Insert new items before current item.",
        "Insert new items before current item." )
pick(   W_MENU_INSERTTOGGLE,
        "Toggle insert new items before/after current item.",
        "Toggle insert new items before/after current item." )
pick(   W_MENU_INSERTSUBITEMS,
        "Toggle insert new items as subitems of popups.",
        "Toggle insert new items as subitems of popups." )
pick(   W_MENU_NEWITEM,
        "Insert a new menu item.",
        "Insert a new menu item." )
pick(   W_MENU_NEWPOPUP,
        "Insert a new menu popup.",
        "Insert a new menu popup." )
pick(   W_MENU_NEWSEPARATOR,
        "Insert a new menu separator.",
        "Insert a new menu separator." )
pick(   W_MENU_ABOUT,
        "Display program information.",
        "Display program information." )
pick(   W_MENU_HELP,
        "List Open Watcom Menu Editor help topics.",
        "List Open Watcom Menu Editor help topics." )
pick(   W_MENU_HELP_SEARCH,
        "Search for help on a specific topic.",
        "Search for help on a specific topic." )
pick(   W_MENU_HELP_ON_HELP,
        "Display information on how to use help.",
        "Display information on how to use help." )
pick(   W_MENU_FILEMENU,
        "Clear or update the menu resource.",
        "Clear or update the menu resource." )
pick(   W_MENU_EDITMENU,
        "Edit the menu and its items.",
        "Edit the menu and its items." )
pick(   W_MENU_RESMENU,
        "Manipulate menu settings.",
        "Manipulate menu settings." )
pick(   W_MENU_MENUMENU,
        "Create menu items.",
        "Create menu items." )
pick(   W_MENU_HELPMENU,
        "Display help or editor info.",
        "Display help or editor info." )

// WRIBBON.C
pick(   W_SHOWTOOLBAR,
        "Show Tool&bar",
        "Show Tool&bar" )
pick(   W_TOOLBARHIDDEN,
        "Toolbar Hidden",
        "Toolbar Hidden" )
pick(   W_HIDETOOLBAR,
        "Hide Tool&bar",
        "Hide Tool&bar" )
pick(   W_TOOLBARSHOWN,
        "Toolbar Shown",
        "Toolbar Shown" )

// WTOOLBAR.C
pick(   W_SYSMENUMOVE,
        "Move",
        "Move" )
pick(   W_SYSMENUSIZE,
        "Size",
        "Size" )
pick(   W_SYSMENUHIDE,
        "Hide",
        "Hide" )

// WSVOBJ.C
pick(   W_SAVERESINTO,
        "Save Menu Into Resource",
        "Save Menu Into Resource" )
pick(   W_SAVERESAS,
        "Save Menu Resource",
        "Save Menu Resource" )
pick(   W_SAVERESFILTER,
        "Menu Files (*.MNU)\t*.MNU\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t",
        "Menu Files (*.MNU)\t*.MNU\tResource Files (*.RES)\t*.RES\tExecutable Files (*.EXE)\t*.EXE\tDLL Libraries (*.DLL)\t*.DLL\t" )
pick(   W_RESHASNONAME,
        "This resource does not have a name.",
        "This resource does not have a name." )
pick(   W_RESDUPNAMEINFILE,
        "There is already a resource of that name in the file.",
        "There is already a resource of that name in the file." )

// WEDIT.C
pick(   W_QUERYNUKEPOPUP,
        "This change will delete all of the popup's subitems.\nChange?",
        "This change will delete all of the popup's subitems.\nChange?" )
pick(   W_CHANGEMODIFIEDMENUITEM,
        "This menu item has been modified.\nChange?",
        "This menu item has been modified.\nChange?" )

// WMAIN.C
pick(   W_MENUAPPTITLE,
        "Open Watcom Menu Editor",
        "Open Watcom Menu Editor" )
pick(   W_CHANGEMENUMEMFLAGS,
        "Changing Memory Flags",
        "Changing Memory Flags" )
pick(   W_UPDATEMODIFIEDMENU,
        "This menu resource has been modified.\nSave?",
        "This menu resource has been modified.\nSave?" )
pick(   W_RENAMINGMENU,
        "Renaming Menu",
        "Renaming Menu" )
pick(   W_MENUCLEARWARNING,
        "Clear will delete ALL menu items.\nClear?",
        "Clear will delete ALL menu items.\nClear?" )
pick(   W_MENUCLEARTITLE,
        "Clear Menu",
        "Clear Menu" )
pick(   W_MENUCLEARMSG,
        "Menu cleared",
        "Menu cleared" )
pick(   W_UPDATEMODIFIEDSYM,
        "The symbols have been modified.\nSave?",
        "The symbols have been modified.\nSave?" )
pick(   W_ABOUT_NAME,
        "Open Watcom Menu Editor for Windows",
        "Open Watcom Menu Editor for Windows" )
pick(   W_ABOUT_COPYRIGHT_YEAR,
        "2002",
        "2002" )
pick(   W_ABOUT_TITLE,
        "About Open Watcom Menu Editor",
        "About Open Watcom Menu Editor" )

// WPREV.C
pick(   W_PREVIEWMENU,
        "Preview Menu",
        "Preview Menu" )

// WNEWITEM.C
pick(   W_MENUPOPUP,
        "Popup",
        "Popup" )
pick(   W_MENUITEM,
        "Item",
        "Item" )

// W_MENU.C
pick(   W_NOMENUEX,
        "Cannot edit MENUEX resources.",
        "Cannot edit MENUEX resources." )

// WRIBBON.C
pick(   W_TIP_NEW,
        "New",
        "New" )
pick(   W_TIP_OPEN,
        "Open",
        "Open" )
pick(   W_TIP_SAVE,
        "Save",
        "Save" )
pick(   W_TIP_CLEAR,
        "Clear",
        "Clear" )
pick(   W_TIP_UPDATE,
        "Update",
        "Update" )
pick(   W_TIP_CUT,
        "Cut",
        "Cut" )
pick(   W_TIP_COPY,
        "Copy",
        "Copy" )
pick(   W_TIP_PASTE,
        "Paste",
        "Paste" )
pick(   W_TIP_DELETE,
        "Delete",
        "Delete" )
pick(   W_TIP_INSERTTOGGLE,
        "Insert After",
        "Insert After" )
pick(   W_TIP_NEWITEM,
        "Insert New Item",
        "Insert New Item" )

#include "w.msg"
