#pmake: build trap lcl os_dos dsx cpu_386 x86

host_os  = dos
host_cpu = i86

target_cpu = x86

os  = dos
srv = rsi
which = TRAP

extra_cpp_flags = -DDOS4G

!include $(trap_dir)/lcl/dos/dosx/dosx.mif
!include $(trap_dir)/master.mif
