#pmake: build medium cpu_i86 os_osi os_os2
#
# iostm.lib -- medium memory-model IOSTREAM library
#
processor  = 086
system     = generic
model      = mm
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
