#pmake: build small cpu_i86 os_win
#
# iosts.lib -- small memory-model IOSTREAM library for Windows
#
processor  = 086
system     = windows
model      = ms
linkage    = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
