#pmake/150: nobuild debug flat register 32bit calls winnt iX86 rtdll os_nt cpu_386

component  = mlib
processor  = 386
model      = mf
system     = winnt
convention = register

lib_debug = 1

!include $(rtdll_dir)/master.mif
