#pmake: build serv remote os_win cpu_i86 cpu_386 nov x86
host_cpu = i86
host_os  = win

os = win
srv = nov
cpu = x86
which = SERVER
gui = 1
remote_link = 1

extra_objs = novdos.obj
extra_flags_novdos = -zu

!include $(trap_dir)/master.mif
