#pmake: build serv remote win 16 32 nov x86

gui = 1
os = win
srv = nov
cpu = x86

extra_objs = $(remote_objs) novdos.obj
extra_flags_novdos = -zu
resource_file = serv.res

!include $(trap_dir)\serv.mif
