#pmake: build medium cpu_i86 os_win
processor  = 086
system     = windows
model      = mm
linkage    = static
subdir     = mm

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
