name: artifact-save
inputs:
  arch:
    required: false
    default: ''
    type: string
  gitpath:
    required: false
    default: ''
    type: string
  artifname:
    required: false
    default: ''
    type: string
  tools:
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - id: tarname
    run: |
      Join-Path ${{ runner.temp }} owartifact.tar.xz `
      | Join-String -OutputPrefix "path=" `
      | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
    shell: pwsh
  - uses: "./.github/actions/tarsave"
    with:
      arch: ${{ inputs.arch }}
      gitpath: ${{ inputs.gitpath }}
      tarname: ${{ steps.tarname.outputs.path }}
  - name: Get Artifact name
    id: artifact
    run: |
      -Split "${{ inputs.artifname }} ${{ inputs.tools }}" `
      | Join-String -Separator "-" -OutputPrefix "name=" `
      | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
    shell: pwsh
  - name: Upload Artifact ${{ steps.artifact.outputs.name }}
    uses: actions/upload-artifact@v3
    with:
      name: ${{ steps.artifact.outputs.name }}
      path: ${{ steps.tarname.outputs.path }}
      retention-days: 2
  - name: Delete Temporary Artifact tar file
    run: rm -f ${{ steps.tarname.outputs.path }}
    shell: bash
