name: artifact-save
description: 'Upload Artifact (tar file), first create it from git subdirectory'
inputs:
  gitpath:
    description: 'git subdirectory'
    required: true
    default: ''
    type: string
  artifact:
    description: 'artifact name, worlds separated by space, spaces are replased by dash characters (-)'
    required: false
    default: ''
    type: string
  retention_days:
    description: 'how many days artifact is preserved before deletion'
    required: false
    default: 3
    type: string
runs:
  using: composite
  steps:
  - name: Get Artifact name
    id: artifact_name
    run: |
      -Split "${{inputs.artifact}}" `
      | Join-String -Separator '-' -OutputPrefix 'id=' `
      | Out-File -FilePath ${{github.output}} -Encoding utf8 -Append
    shell: pwsh
  - if: env.OWUSETARARCHIVE == '1'
    id: tarname
    run: |
      Join-Path ${{github.workspace}} owartifact.tar.xz `
      | Join-String -OutputPrefix 'fullname=' `
      | Out-File -FilePath ${{github.output}} -Encoding utf8 -Append
    shell: pwsh
  - if: env.OWUSETARARCHIVE == '1'
    uses: ./.github/actions/tarsave
    with:
      gitpath:  ${{inputs.gitpath}}
      fullname: ${{steps.tarname.outputs.fullname}}
  - name: Get source
    id: srcpath
    run: |
      if( '${{env.OWUSETARARCHIVE}}' -eq '1' ) {
        "${{steps.tarname.outputs.fullname}}" `
        | Join-String -OutputPrefix 'path=' `
        | Out-File -FilePath ${{github.output}} -Encoding utf8 -Append
      } else {
        Join-Path ${{github.workspace}} ${{inputs.gitpath}} `
        | Join-String -OutputPrefix 'path=' `
        | Out-File -FilePath ${{github.output}} -Encoding utf8 -Append
      }
    shell: pwsh
  - if: env.OWTESTMODE != '1'
    name: Upload Artifact ${{steps.artifact_name.outputs.id}}
    uses: actions/upload-artifact@v4
    with:
      name:             ${{steps.artifact_name.outputs.id}}
      path:             ${{steps.srcpath.outputs.path}}
      retention-days:   ${{inputs.retention_days}}
      overwrite:        true
  - if: env.OWUSETARARCHIVE == '1'
    name: Delete Temporary Artifact tar file
    run: rm -f ${{steps.tarname.outputs.fullname}}
    shell: bash
