name: artifact-save
description: 'Upload Artifact (tar file), first create it from git subdirectory'
inputs:
  arch:
    description: 'run-time platform'
    required: false
    default: ''
    type: string
  gitpath:
    description: 'git subdirectory'
    required: false
    default: ''
    type: string
  artifact:
    description: 'artifact name, worlds separated by space, spaces are replased by dash characters (-)'
    required: false
    default: ''
    type: string
  tools:
    description: 'used compiler toolchain'
    required: false
    default: ''
    type: string
  retention_days:
    description: 'how many days artifact is preserved before deletion'
    required: false
    default: 3
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - id: tarname
    run: >
      Join-Path ${{ runner.temp }} owartifact.tar.xz
      | Join-String -OutputPrefix 'fullname='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - uses: "./.github/actions/tarsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  ${{ inputs.gitpath }}
      fullname: ${{ steps.tarname.outputs.fullname }}
      owdebug:  ${{ inputs.owdebug }}
  - name: Get Artifact name
    id: artifact_name
    run: >
      -Split "${{ inputs.artifact }} ${{ inputs.tools }}"
      | Join-String -Separator '-' -OutputPrefix 'id='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - name: Upload Artifact ${{ steps.artifact_name.outputs.id }}
    uses: actions/upload-artifact@v3
    with:
      name:             ${{ steps.artifact_name.outputs.id }}
      path:             ${{ steps.tarname.outputs.fullname }}
      retention-days:   ${{ inputs.retention_days }}
  - name: Delete Temporary Artifact tar file
    run: rm -f ${{ steps.tarname.outputs.fullname }}
    shell: bash
