#pmake/150: nobuild debug flat register 32bit inline os2 iX86 rtdll os_os2 cpu_386

component  = mlib
processor  = 387
model      = mf
system     = os2
convention = register

lib_debug = 1

!include $(rtdll_dir)/master.mif
