#pmake: build medium cpu_i86 os_win
#
# cplx7m.lib -- medium memory-model COMPLEX library fpi for Windows
#
processor  = 087
system     = windows
model      = mm
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
