#pmake: build flat cpu_386 os_osi
#
# plibmt3r -- 32-bit 3r PLIB multi-thread library
#
processor  = 386
system     = generic
model      = ms
convention = register
linkage    = static
mthreaded  = 1
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
