Project
    TargetGroup "DOS - 32-bit"
      Target *.exe, dw2e_, "CauseWay Executable"
      Target *.dll, dx2d_, "CauseWay DLL (register based)"
      Target *.dll, dy2d_, "CauseWay DLL (stack based)"
      Target *.exe, dr2e_, "DOS/4GW Executable"
      Target *.exe, da2e_, "DOS32/A LE Executable"
      Target *.exe, db2e_, "DOS32/A LX Executable"
      Target *.exe, dm2e_, "PMODE/W Executable"
      Target *.exp, dp2e_, "Pharlap Executable"
      Target *.exe, dt2e_, "Pharlap TNT Executable"
      Target *.exe, df2e_, "Flashtek Executable"
      Target *.exe, ds2e_, "Flashtek -- Stack based"
      Target *.lib, d_2s_, "Library"
