#pmake: nobuild debug flat cpu_386 os_nt dynamic
#
# iostmt3r.lib -- register based multi-thread 32-bit IOSTREAM library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = dynamic
mthreaded  = 1
fs_registration = yes
lib_debug = 1

!include $(cpplib_dir)/iostream/iostream.mif
