#pmake/150: build flat register 32bit calls winnt iX86 rtdll os_nt cpu_386 cpplib profile

component  = plib
processor  = 386
model      = mf
subdir     = mf_rp
system     = winnt
convention = register
profile    = 1

!include $(rtdll_dir)/master.mif
