#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp COMPLEX library
#
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static

define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
