/* UTF-8 encoding, ¥ */

pick( Busy,
        "Busy ...",
        "jBusy ..." )

pick( Not_Found,
        "Not Found",
        "jNot Found" )

pick( Search_Wrapped,
        "Search Wrapped",
        "jSearch Wrapped" )

pick( End_Of_Window,
        "End of Window Reached",
        "jEnd of Window Reached" )

pick( Top_Of_Window,
        "Top of Window Reached",
        "jTop of Window Reached" )

pick( Match_Mode,
        "Match Mode: ",
        "jMatch Mode: " )

pick( New_OK,
        "OK",
        "jOK" )

pick( New_Cancel,
        "Cancel",
        "jCancel" )
