pick( LITERAL_Busy,
	"Busy ...",
	"jBusy ..." )

pick( LITERAL_Not_Found,
	"Not Found",
	"jNot Found" )

pick( LITERAL_Search_Wrapped,
	"Search Wrapped",
	"jSearch Wrapped" )

pick( LITERAL_End_Of_Window,
	"End of Window Reached",
	"jEnd of Window Reached" )

pick( LITERAL_Top_Of_Window,
	"Top of Window Reached",
	"jTop of Window Reached" )

pick( LITERAL_Match_Mode,
	"Match Mode: ",
	"jMatch Mode: " )

pick( LITERAL_New_OK,
	"OK",
	"jOK" )

pick( LITERAL_New_Cancel,
	"Cancel",
	"jCancel" )
