#define IDR_MAINFRAME       1
#define IDR_DRAWINGTYPE     2
#define IDD_ABOUTBOX        100
#define ID_DRAW_ARROW       1000
#define ID_DRAW_LINE        1001
#define ID_DRAW_RECTANGLE   1002
#define ID_DRAW_ELLIPSE     1003
#define ID_DRAW_LINE_COLOR  1004
#define ID_DRAW_FILL_COLOR  1005
