#pmake: build flat cpu_386 os_osi
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static
mthreaded  = 1
subdir     = mf_rmt

!include $(cpplib_dir)/mrglib.mif
