name: last-build
description: 'Create OW snapshot Archive (compressed tar)'
inputs:
  arch:
    description: 'run-time platform'
    required: false
    default: ''
    type: string
  gitpath:
    description: 'git subdirectory'
    required: false
    default: ''
    type: string
  artifact:
    description: 'artifact name, worlds separated by space, spaces are replased by dash characters (-)'
    required: false
    default: ''
    type: string
  retention_days:
    description: 'how many days artifact is preserved before deletion'
    required: false
    default: 10
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
outputs:
  fullname:
    description: 'snapshot file full name'
    value: ${{ steps.tarname.outputs.fullname }}
runs:
  using: composite
  steps:
  - name: Get destination folder
    id: dstpath
    run: >
      Join-Path ${{ github.workspace }} distrib ow bin
      | Join-String -OutputPrefix 'path='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - name: Create destination folder
    run: New-Item -ErrorAction SilentlyContinue -ItemType Directory -Path ${{ steps.dstpath.outputs.path }} > $null
    shell: pwsh
  - id: tarname
    run: >
      Join-Path ${{ github.workspace }} distrib ow bin ow-snapshot.tar.xz
      | Join-String -OutputPrefix 'fullname='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - uses: "./.github/actions/tarsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  ${{ inputs.gitpath }}
      fullname: ${{ steps.tarname.outputs.fullname }}
      owdebug:  ${{ inputs.owdebug }}
