#pmake: build compact cpu_i86 os_win
#
# contc.lib -- compact memory-model CONTAINER library for Windows
#
processor  = 086
system     = windows
model      = mc
linkage    = static
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
