#pmake: build trap remote os_nt cpu_i86 cpu_386 vdm x86
host_cpu = 386
host_os  = nt

target_cpu = x86

os = nt
srv = vdm
which = TRAP
remote_link = 1

extra_objs = vdmclint.obj

!include $(trap_dir)/master.mif
