!ifdef __OS2__
_OS     = OS2
!else
_OS     = DOS
!endif
sys     = none
comp    = echo error
targ_n  = dummy
targ_e  =

target : ..\h\inlnops.h ..\h\msg.gh .SYMBOLIC
        @%null

!include ..\master.mif
