pick( SEGMENT_PARA_DEFINED,
                                "Segment parameter is defined already" ,
                                "セグメントパラメータは既に定義されています" )
pick( MODEL_PARA_DEFINED,
                                "Model parameter is defined already" ,
                                "モデルパラメータは既に定義されています" )
pick( SEGMENT_DEF_ERROR,
                                "Syntax error in segment definition" ,
                                "セグメント定義で構文エラーが起きています" )
pick( SEGDEF_AT_NOT_SUPPORTED,
                                "'AT' is not supported in segment definition" ,
                                "セグメント定義には、まだ AT はサポートされていません" )
pick( SEGDEF_CHANGED,
                                "Segment definition is changed" ,
                                "セグメント定義が変りました" )
pick( LNAME_TOO_LONG,
                                "Lname is too long" ,
                                "Lnameが長すぎます" )
pick( BLOCK_NESTING_ERROR,
                                "Block nesting error" ,
                                "ブロック・ネスト・エラー" )
pick( SEGMENT_NOT_OPENED,
                                "Ends a segment which is not opened" ,
                                "オープンされていないセグメントのendsがあります" )
pick( UNDEFINED_SEGMENT_OPTION,
                                "Segment option is undefined" ,
                                "セグメント・オプションが未定義です" )
pick( UNDEFINED_MODEL_OPTION,
                                "Model option is undefined" ,
                                "モデル・オプションが未定義です" )
pick( NO_SEGMENT_OPENED,
                                "No segment is currently opened" ,
                                "現在オープンされているセグメントはありません" )
pick( LNAME_USED_ALREADY,
                                "Lname is used already" ,
                                "Lnameは既に使用されています" )
pick( SEG_NOT_DEFINED,
                                "Segment %s is not defined" ,
                                "Segment %s is not defined" )
pick( PUBLIC_NOT_DEFINED,
                                "Public is not defined" ,
                                "パブリックが未定義です" )
pick( COLON_EXPECTED,
                                "Colon is expected" ,
                                "コロン(:)が必要です" )
pick( TOKEN_EXPECTED_AFTER_COLON,
                                "A token is expected after colon" ,
                                "コロン(:)の後にはトークンが必要です" )
pick( INVALID_QUALIFIED_TYPE,
                                "Invalid qualified type" ,
                                "無効な修飾タイプです" )
pick( QUALIFIED_TYPE_EXPECTED,
                                "Qualified type is expected" ,
                                "修飾タイプが必要です" )
pick( EXT_DEF_DIFF,
                                "External definition different from previous one" ,
                                "外部定義が前の定義と異なります" )
pick( MEMORY_NOT_FOUND,
                                "Memory model is not found in .MODEL" ,
                                ".MODELの中にメモリモデルがありません" )
pick( CANNOT_OPEN_INCLUDE_FILE,
                                "Cannot open include file %s" ,
                                "インクルード・ファイルをオープンできません %s" )
pick( NAME_USED_ALREADY,
                                "Name is used already" ,
                                "名前は既に使用されています" )
pick( LIBRARY_NAME_MISSING,
                                "Library name is missing" ,
                                "ライブラリ名がありません" )
pick( SEG_NAME_MISSING,
                                "Segment name is missing" ,
                                "セグメント名がありません" )
pick( GRP_NAME_MISSING,
                                "Group name is missing" ,
                                "グループ名がありません" )
pick( DATA_EMITTED_WITH_NO_SEGMENT,
                                "Data emitted with no segment" ,
                                "データがセグメントに属していません" )
pick( SEGLOCATION_EXPECTED,
                                "Seglocation is expected" ,
                                "セグメント・ロケーションが必要です" )
pick( INVALID_REGISTER,
                                "Invalid register" ,
                                "無効なレジスタです" )
pick( CANNOT_ADDRESS_WITH_ASSUMED_REGISTER,
                                "Cannot address with assumed register" ,
                                "ASSUMEされたレジスタでアドレスすることはできません" )
pick( INVALID_START_ADDRESS,
                                "Invalid start address" ,
                                "無効なスタートアドレスです" )
pick( LABEL_ALREADY_DEFINED,
                                "Label is already defined" ,
                                "ラベルは既に定義されています" )
pick( TOKEN_TOO_LONG,
                                "Token is too long" ,
                                "トークンが長すぎます" )
pick( EXPANDED_LINE_TOO_LONG,
                                "The line is too long after expansion" ,
                                "エクスパンジョンの後の行が長すぎます" )
pick( LABEL_EXPECTED_AFTER_COLON,
                                "A label is expected after colon" ,
                                "コロン(:)の後にはラベルが必要です" )
pick( MUST_BE_ASSOCIATED_WITH_CODE,
                                "Must be associated with code" ,
                                "コードと関係していなければなりません" )
pick( PROC_MUST_HAVE_A_NAME,
                                "Procedure must have a name" ,
                                "プロシージャには名前がなければなりません" )
pick( PROC_ALREADY_DEFINED,
                                "Procedure is already defined" ,
                                "プロシージャは既に定義されています" )
pick( LANG_MUST_BE_SPECIFIED,
                                "Language type must be specified" ,
                                "言語タイプが定義されていなければなりません" )
pick( END_OF_PROCEDURE_NOT_FOUND,
                                "End of procedure is not found" ,
                                "プロシージャの終わりが見つかりません" )
pick( LOCAL_VAR_MUST_FOLLOW_PROC,
                                "Local variable must immediately follow PROC or MACRO statement" ,
                                "ローカル変数はPROC文の直後になければなりません" )
pick( EXTRA_CHARACTER_FOUND,
                                "Extra character found" ,
                                "余分な文字があります" )
pick( CANNOT_NEST_PROCEDURES,
                                "Cannot nest procedures" ,
                                "プロシージャをネストすることはできません" )
pick( NO_PROC_IS_CURRENTLY_DEFINED,
                                "No procedure is currently defined" ,
                                "プロシージャが定義されていません" )
pick( PROC_NAME_DOES_NOT_MATCH,
                                "Procedure name does not match" ,
                                "プロシージャ名が一致しません" )
pick( VARARG_REQUIRES_C_CALLING_CONVENTION,
                                "Vararg requires C calling convention" ,
                                "varargにはCの呼出し規約が必要です" )
pick( MODEL_DECLARED_ALREADY,
                                "Model declared already" ,
                                "既に宣言されているモデルです" )
pick( MODEL_IS_NOT_DECLARED,
                                "Model is not declared" ,
                                "モデルは宣言されています" )
pick( BACKQUOTE_EXPECTED,
                                "Backquote expected" ,
                                "逆引用符(`)が必要です" )
pick( COMMENT_DELIMITER_EXPECTED,
                                "COMMENT delimiter expected" ,
                                "COMMENT区切り文字が必要です" )
pick( END_DIRECTIVE_REQUIRED,
                                "End directive required at end of file" ,
                                "ファイルの終端には、END疑似命令が必要です" )
pick( NESTING_LEVEL_TOO_DEEP,
                                "Nesting level too deep" ,
                                "ネスト・レベルが深すぎます" )
pick( SYMBOL_NOT_DEFINED,
                                "Symbol %s is not defined" ,
                                "Symbol %s is not defined" )
pick( INSERT_STUPID_WARNING_1_HERE,
                                "Insert Stupid warning #1 here" ,
                                "無意味な警告#1をここに挿入します" )
pick( INSERT_STUPID_WARNING_2_HERE,
                                "Insert Stupid warning #2 here" ,
                                "無意味な警告#2をここに挿入します" )
pick( SPACES_NOT_ALLOWED_IN_COMMAND_LINE_OPTIONS,
                                "Spaces not allowed in command line options" ,
                                "コマンドラインオプションで空白は使用できません" )
pick( MSG_ERROR,
                                "Error: " ,
                                "エラー: " )
pick( SOURCE_FILE,
                                "Source File" ,
                                "ソースファイル" )
pick( NO_FILENAME_SPECIFIED,
                                "No filename specified." ,
                                "ファイル名が指定されていません" )
pick( OUT_OF_MEMORY,
                                "Out of Memory" ,
                                "メモリ不足です" )
pick( CANNOT_OPEN_FILE,
                                "Cannot Open File - " ,
                                "ファイルをオープンできません - " )
pick( CANNOT_CLOSE_FILE,
                                "Cannot Close File - " ,
                                "ファイルをクローズできません - " )
pick( CANNOT_GET_FILE,
                                "Cannot Get Start of Source File - " ,
                                "ソースファイルのスタートが得られません - " )
pick( CANNOT_SET_FILE,
                                "Cannot Set to Start of Source File - " ,
                                "ソースファイルのスタートに設定できません - " )
pick( TOO_MANY_FILES,
                                "Command Line Contains More Than 1 File To Assemble " ,
                                "コマンドラインにアセンブルするファイルが2個以上指定されています " )
pick( MSG_INCLUDE_PATH,
                                "include path %s." ,
                                "パス %s をインクルードします\n" )
pick( MSG_UNKNOWN_OPTION,
                                "Unknown option %s. Use /? for list of options." ,
                                "%s は無効なオプションです。/?でオプションのリストを表示します\n" )
pick( MSG_READ_MORE,
                                "read more command line from %s." ,
                                "%s から追加のコマンドラインを読みます\n" )
pick( MSG_INTERNAL_ERROR,
                                "Internal error in %s(%u)" ,
                                "%s(%u) で内部エラーが起こりました\n" )
pick( OBJECT_WRITE_ERROR,
                                "OBJECT WRITE ERROR !!" ,
                                "オブジェクト書込みエラー !!\n" )
pick( NO_LOR_PHARLAP,
                                "NO LOR PHARLAP !!" ,
                                "LOR PHARLAPではありません!!\n" )
pick( PARM_REQUIRED,
                                "Parameter Required" ,
                                "パラメータが必要です" )
pick( EXPECTED_CL_SQ_BRACKET,
                                "Expecting closing square bracket" ,
                                "右鍵括弧が必要です" )
pick( EXPECTED_FILE_NAME,
                                "Expecting file name" ,
                                "ファイル名が必要です" )
pick( NO_FP_WITH_FPC_SET,
                                "Floating point instruction not allowed with /fpc" ,
                                "/fpc指定時には、浮動小数点命令は使用できません" )
pick( ERR_TOO_MANY_ERRORS,
                                "Too many errors" ,
                                "エラーが多すぎます" )
pick( BT_NOT_RECOG,
                                "Build target not recognised" ,
                                "ターゲットOSが判りません" )
pick( PUBLIC_CONSTANT_NOT_NUMERIC,
                                "Public constants should be numeric; 0 written" ,
                                "パブリックな定数は数値でなければなりません; 0を書き込みます" )
pick( SYMBOL_EXPECTED,
                                "Expecting symbol" ,
                                "シンボルが必要です" )
pick( DONT_MIX_SIM_WITH_REAL_SEGDEFS,
                                "Do not mix simplified and full segment definitions" ,
                                "簡略(simplified)セグメントと完全(full)セグメントとは、いっしょに使用できません" )
pick( CANT_ACCESS_MULTI_REG_PARMS,
                                "Parms passed in multiple registers must be accessed separately, use %s " ,
                                "複数のレジスタを使うparmは、別々にアクセスされなければなりません, %s を使用してください" )
pick( TBYTE_NOT_SUPPORTED,
                                "Ten byte variables not supported in register calling convention" ,
                                "10バイト変数はレジスタ呼出規約では、サポートされていません" )
pick( STRANGE_PARM_TYPE,
                                "Parameter type not recognised" ,
                                "パラメータ型が判りません" )
pick( FORCED,
                                "forced error:" ,
                                "強制エラー" )
pick( FORCED_NOT_ZERO,
                                "forced error: Value not equal to 0 : %d " ,
                                "強制エラー: 値が0ではありません : %d " )
pick( FORCED_EQUAL,
                                "forced error: Value equal to 0: %d " ,
                                "強制エラー: 値が0です: %d " )
pick( FORCED_DEF,
                                "forced error: symbol defined: %s" ,
                                "強制エラー: シンボルが定義されています: %s " )
pick( FORCED_NOT_DEF,
                                "forced error: symbol not defined: %s" ,
                                "強制エラー: シンボルが定義されていません: %s " )
pick( FORCED_BLANK,
                                "forced error: string blank : <%s>" ,
                                "強制エラー: 文字列が空白です: <%s>" )
pick( FORCED_NOT_BLANK,
                                "forced error: string not blank : <%s>" ,
                                "強制エラー: 文字列が空白ではありません: <%s>" )
pick( FORCED_DIF,
                                "forced error: strings not equal : <%s> : <%s>" ,
                                "強制エラー: 文字列が等しくありません: <%s> : <%s>" )
pick( FORCED_IDN,
                                "forced error: strings equal : <%s> : <%s> " ,
                                "強制エラー: 文字列が等しい: <%s> : <%s>" )
pick( NOTE_INCLUDED_BY,
                                "included by file %s(%lu)" ,
                                "ファイル %s(%lu) に含まれます" )
pick( NOTE_MACRO_CALLED_FROM,
                                "macro called from file %s(%lu)" ,
                                "ファイル %s(%lu) から呼ばれるマクロです" )
pick( SYMBOL_S_NOT_DEFINED,
                                "Symbol %s is not defined" ,
                                "シンボルが定義されていません ( %s )" ) /* fixme */
pick( EXTENDING_JUMP,
                                "Extending jump" ,
                                "範囲外へのジャンプです" ) /* fixme - jump out of range */
pick( IGNORING_DIRECTIVE,
                                "Ignoring inapplicable directive" ,
                                "不適切な擬似命令を無視します" )
pick( UNKNOWN_MANGLER,
                                "Unknown symbol class '%s'" ,
                                "未知のシンボルクラス '%s'" )
pick( CONFLICTING_MANGLER,
                                "Symbol class for '%s' already established" ,
                                "'%s' のシンボルクラスは既に確定しています" )
pick( POWER_OF_2,
                                "number must be a power of 2",
                                "数値は2のべき乗でなければなりません" )
pick( ALIGN_TOO_HIGH,
                                "alignment request greater than segment alignment",
                                "整列(ｱﾗｲﾝﾒﾝﾄ)の指定がセグメント整列より大きくなっています" )
pick( SYMBOL_PREVIOUSLY_DEFINED,
                                "'%s' is already defined",
                                "'%s' は既に定義されています" )
pick( UNCLOSED_CONDITIONALS,
                                "%u unclosed conditional directive(s) detected" ,
                                "%u 閉じていない条件擬似命令を検出しました" )
pick( WRONG_CPU_FOR_32BIT_SEGMENT,
                                "Wrong CPU type for 32-bit segment" ,
                                "Wrong CPU type for 32-bit segment")
pick( PROC_IS_NOT_CLOSED,
                                "Procedure %s is not closed" ,
                                "Procedure %s is not closed")
pick( CALL_FAR_TO_NEAR,
                                "Far call is converted to near call." ,
                                "Far call is converted to near call." )
pick( MSG_CPU_OPTION_INVALID,
                                "CPU option %s is not valid for selected CPU.\n" ,
                                "CPU option %s is not valid for selected CPU.\n" )
pick( SEGMENT_IN_GROUP,
                                "Segment is in another group already" ,
                                "Segment is in another group already" )
pick( LABEL_OUTSIDE_SEGMENT,
                                "Label is defined outside segment" ,
                                "Label is defined outside segment" )
pick( DATA_LABEL_IS_EXPECTED,
                                "Data label is expected" ,
                                "Data label is expected" )
pick( INVALID_USE_OF_LENGTH_SIZE_OPERATOR,
                                "Invalid use of LENGTH/LENGTHOF/SIZE/SIZEOF operator" ,
                                "Invalid use of LENGTH/LENGTHOF/SIZE/SIZEOF operator" )
pick( SYMBOL_TYPE_DIFF,
                                "Symbol '%s' type conflict." ,
                                "Symbol '%s' type conflict." )
pick( ARG_MUST_FOLLOW_PROC,
                                "ARG may only be used within a PROC and before the first instruction" ,
                                "ARG may only be used within a PROC and before the first instruction" )
pick( USES_MUST_FOLLOW_PROC,
                                "USES may only be used within a PROC and before the first instruction" ,
                                "USES may only be used within a PROC and before the first instruction" )
pick( ENUM_NAME_MISSING,
                                "Enum name is missing" ,
                                "Enum name is missing" )
pick( TOO_MANY_ARGS,
                                "Too many args" ,
                                "Too many args" )
pick( LOCAL_LABEL_OUTSIDE_PROC,
                                "Local labels may only be used within a PROC" ,
                                "Local labels may only be used within a PROC" )
pick( ARGUMENT_SIZE_NOT_SUPPORTED,
				"Argument size not supported" ,
				"Argument size not supported" )
pick( USES_MEANINGLESS_WITHOUT_LANGUAGE,
				"USES is meaningless without language" ,
				"USES is meaningless without language" )
