#pmake: build huge cpu_i86 os_osi
#
# cplxh.lib -- huge memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mh
linkage    = static
define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
