#pmake: build trap remote os_os2 cpu_i86 cpu_386 par x86
host_cpu = 386
host_os  = os2

os    = os2v2
srv   = par
cpu   = x86
which = TRAP
remote_link = 1

extra_objs = paros22.obj

!include ../os2v2.mif
!include $(trap_dir)/master.mif
