#pmake: build trap remote os_os2 cpu_i86 cpu_386 par x86
host_CPU = 386
host_OS = os2

os = os2v2
srv = par
cpu = x86
which = TRAP
type  = remote_link

extra_objs = paros22.obj os2noth2.obj

!include ../os2v2.mif
!include $(trap_dir)/master.mif
