#pmake: build large cpu_i86 os_win
#
# plibl -- 16-bit large memory-model PLIB for Windows
#
processor  = 086
system     = windows
model      = ml
linkage    = static
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
