#pmake: build trap remote os_nt cpu_i86 cpu_386 ser x86
host_cpu = 386
host_os = nt

os = nt
srv = ser
cpu = x86
which = TRAP
remote_link = 1

extra_objs = sernt.obj busywait.obj

!include $(trap_dir)/master.mif
