#pmake: build trap remote os_nt cpu_i86 cpu_386 ser x86
host_cpu = 386
host_os  = nt

target_cpu = x86
target_os  = nt

srv = ser
which = TRAP
remote_link = 1

extra_objs = sernt.obj busywait.obj

!include $(trap_dir)/master.mif
