#pmake:all small register 32bit calls winnt iX86 rtdll no_build os_nt cpu_386
component=wrtlib
processor=386
model=ms
subdir=ms_r
system=winnt
convention=register
!include $(rtdll)\master.mif
!include ..\objs.mif
!include $(rtdll)\mkdll.mif
