#pmake: nomodel cpu_axp os_nt
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static
mthreaded    = 1
pd_registration = yes

!include $(cpplib_dir)/runtime/runtime.mif
