#pmake: trap remote os_os2 cpu_i86 ser
host_cpu = i86
host_os  = os2

target_cpu = x86
target_os  = os2

srv = ser
which = TRAP
remote_link = 1

extra_objs = seros2.obj

!include $(trap_dir)/master.mif
