#pmake: build debug flat cpu_386 os_nt
#
# contmt3r.lib -- register based multi-thread 32-bit CONTAINER library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
mthreaded  = 1
fs_registration = yes

cpplib_release = 0

!include $(cpplib_dir)/contain/contain.mif
