#pmake/150: build flat register 32bit winnt ix86 rtdll os_nt cpu_386 profile

component  = clib
processor  = 386
model      = mf
subdir     = mf_rp
system     = winnt
convention = register
profile    = 1

!include $(rtdll_dir)/master.mif
