#pmake: build medium cpu_i86 os_osi os_os2
#
# cplx7m.lib -- medium memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = mm
linkage    = static
define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
