#pmake: build medium cpu_i86 os_dos os_os2 os_win os_qnx
#
# cplx7m.lib -- medium memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = mm
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
