#pmake: build medium cpu_i86 os_dos os_os2 os_win os_qnx
#
# strgm.lib -- medium memory-model STRING library
#
processor  = 086
system     = generic
model      = mm
linkage    = static

!include $(cpplib_dir)/string/string.mif
