#pmake: build flat cpu_386 os_dos os_win os_rdos os_linux os_nt os_os2 os_qnx os_nov
#
# iost3s.lib -- stack based 32-bit IOSTREAM library
#
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
