#pmake: os_dos cpu_i86 i86 intel
#
# WATCOM Debugger makefile for DOS
#

host_OS=dos
host_CPU=i86

ovl_dos = 1
# really_ovl_dos = 1

sysobjs =   &
    fork.obj &
    dosstl.obj &
    doschk.obj &
    doscmd.obj &
    dosfilio.obj &
    doslkup.obj &
    dosmem.obj &
    dosgrow.obj &
    dosalloc.obj &
    dostrap.obj &
    dosscrn.obj

!include ../../master.mif
