#pmake/150: build flat stack 32bit winnt ix86 rtdll os_nt cpu_386
component  = clib
processor  = 386
model      = mf
system     = winnt
convention = stack
mthreaded=1

!include $(rtdll_dir)/master.mif
