#pmake/150: build flat stack 32bit winnt ix86 rtdll os_nt cpu_386

component  = clib
processor  = 386
model      = mf
subdir     = mf_s
system     = winnt
convention = stack

!include $(rtdll_dir)/master.mif
