#pmake: all build large cpu_i86 os_os2
#
# contmt.lib -- large memory-model OS/2 multi-thread CONTAINER library
#
suffix = mtl
target_system = os2
production_lib = lib286\os2
define_library_include = $(plusplus_contain_dir)\contain.mif
define_target_include = $(plusplus_dir)\lib16$(suffix).mif
!include $(plusplus_dir)\mklib.mif
