#pmake: build flat stack 32bit inline winnt iX86 rtdll os_nt cpu_386

component  = wlib
processor  = 387
model      = mf
subdir     = mf_s
system     = winnt
convention = stack

!include $(rtdll_dir)/master.mif
