#pmake: os_qnx cpu_386 flat
#
# contmt3s.lib -- stack based multi-thread 32-bit CONTAINER library
#
processor  = 386
system     = qnx
model      = ms
convention = stack
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/contain/contain.mif
