#
# Makefile to create OS/2 version of WIC
#
# WMAKE             creates wic.exe
#
#

_OS         =   OS2V2
opts_cc     =   -oailt -s -3r
opts_lnk    =   system os2v2
cc          =   wcc386
mem_model_prefix = f         # Flat memory model

!include ..\mif\master.mif

