host_os  = win
host_cpu = i86

type = win
os   = win
sys  = windows

all : sample.exe

!include ../master.mif

#build_target = windows
#model = l
#xflags=-zW

#target : sample.exe .SYMBOLIC

#samp2 : samp2.exe  .SYMBOLIC

