#pmake: nobuild debug flat cpu_386 os_dos os_win os_rdos os_nt os_os2 os_qnx os_nov
#
# cplx3r.lib -- register based 32-bit COMPLEX library fpc
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static

lib_debug = 1

!include $(cpplib_dir)/complex/complex.mif
