#pmake: nobuild debug flat cpu_386 os_osi os_win os_rdos os_linux os_nt os_os2
#
# cplx3r.lib -- register based 32-bit COMPLEX library fpc
#
processor  = 386
system     = generic
model      = mf
convention = register
linkage    = static

cpplib_release = 0

!include $(cpplib_dir)/complex/complex.mif
