#pmake: build compact cpu_i86 os_win
#
# plibc -- 16-bit compact memory-model PLIB for Windows
#
processor  = 086
system     = windows
model      = mc
linkage    = static

!include $(cpplib_dir)/runtime/runtime.mif
