name: install
description: 'Build OW install component'
inputs:
  arch:
    description: 'run-time platform'
    required: false
    default: ''
    type: string
  bldscript:
    description: 'script to build action'
    required: false
    default: ''
    type: string
  tools:
    description: 'used compiler toolchain'
    required: false
    default: ''
    type: string
  owtools:
    description: 'OW build compiler toolchain'
    required: false
    default: ''
    type: string
  target:
    description: 'install component to process'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - uses: "./.github/actions/artfload"
    with:
      arch:         ${{ inputs.arch }}
      gitpath:      'build binbuild'
      artifact:     "build ${{ inputs.arch }}"
      tools:        ${{ inputs.tools }}
      owdebug:      ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      arch:         ${{ inputs.arch }}
      gitpath:      'bld setupgui'
      artifact:     'bld setupgui nt'
      tools:        'vs2019'
      owdebug:      ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      arch:         ${{ inputs.arch }}
      gitpath:      'bld setupgui'
      artifact:     'bld setupgui lnx'
      tools:        'gcc'
      owdebug:      ${{ inputs.owdebug }}
  # load all release binaries
  - uses: "./.github/actions/relload"
    with:
      arch:         ${{ inputs.arch }}
      gitpath:      'rel'
      tools_nt:     'vs2019'
      tools_lnx:    'gcc'
      owdebug:      ${{ inputs.owdebug }}
  - if: inputs.target == 'snapshot'
    name: Create OW snapshot
    id: owsnapshot
    uses: "./.github/actions/snapshot"
    with:
      arch:         ${{ inputs.arch }}
      gitpath:      'rel'
      owdebug:      ${{ inputs.owdebug }}
  # run build script
  - if: inputs.target != 'snapshot' && ( inputs.arch == 'lnx' || inputs.arch == 'osx' )
    name: Build Installers
    run: ${{ inputs.bldscript }} ${{ inputs.tools }}
    env:
      OWBUILD_STAGE: 'inst'
      OWTOOLS:       ${{ inputs.owtools }}
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWINSTTARGET:  ${{ inputs.target }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.target != 'snapshot' && inputs.arch == 'nt'
    name: Build Installers
    run: ${{ inputs.bldscript }} ${{ inputs.tools }}
    env:
      OWBUILD_STAGE: 'inst'
      OWTOOLS:       ${{ inputs.owtools }}
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWINSTTARGET:  ${{ inputs.target }}
      OWVERBOSE:     1
    shell: cmd
  # save all artifacts for distribution
  # full content of directory, cannot specify files
  - uses: "./.github/actions/artfsave"
    with:
      arch:         ${{ inputs.arch }}
      gitpath:      'distrib ow bin'
      artifact:     "install ${{ inputs.target }}"
      owdebug:      ${{ inputs.owdebug }}
