name: install
description: 'Build OW install component'
inputs:
  target:
    description: 'install component to process'
    required: false
    default: ''
    type: string
  suffix_nt:
    description: 'artifact name suffix (for Windows)'
    required: true
    type: string
  suffix_lnx:
    description: 'artifact name suffix (for Linux)'
    required: true
    type: string
  suffix_osx:
    description: 'artifact name suffix (for OSX)'
    required: true
    type: string
runs:
  using: composite
  steps:
  - uses: ./.github/actions/artfload
    with:
      gitpath:      'build binbuild'
      artifact:     'build lnx x64 ${{inputs.suffix_lnx}}'
  - uses: ./.github/actions/artfload
    with:
      gitpath:      'bld setupgui'
      artifact:     'bld setupgui nt x64 ${{inputs.suffix_nt}}'
  - uses: ./.github/actions/artfload
    with:
      gitpath:      'bld setupgui'
      artifact:     'bld setupgui lnx x64 ${{inputs.suffix_lnx}}'
  # load all release binaries
  - uses: ./.github/actions/relload
    with:
      suffix_nt:    ${{inputs.suffix_nt}}
      suffix_lnx:   ${{inputs.suffix_lnx}}
      suffix_osx:   ${{inputs.suffix_osx}}
  - if: inputs.target == 'snapshot'
    name: Create OW snapshot
    id: owsnapshot
    uses: ./.github/actions/snapshot
    with:
      gitpath:      'rel'
  # run build script
  - if: inputs.target != 'snapshot'
    name: Build Installers
    run: |
      if [ '${{env.OWDEBUG}}' = '1' ]; then
        env | sort
      fi
      if [ ! '${{env.OWTESTMODE}}' = '1' ]; then
        ci/buildx.sh gcc
      fi
    env:
      OWBUILD_STAGE: 'inst'
      OWTOOLS:       'GCC'
      OWROOT:        ${{github.workspace}}
      OWINSTTARGET:  ${{inputs.target}}
      OWVERBOSE:     1
    shell: bash
  # save all artifacts for distribution
  # full content of directory, cannot specify files
  - uses: ./.github/actions/artfsave
    with:
      gitpath:      'distrib ow bin'
      artifact:     install ${{inputs.target}}
