//    text      regset

#if _CPU == 8086

pick( "",     HW_D( HW_EMPTY ) )
pick( "8087", HW_D( HW_FLTS )  )
pick( "AH",   HW_D( HW_AH )    )
pick( "AL",   HW_D( HW_AL )    )
pick( "AX",   HW_D( HW_AX )    )
pick( "BH",   HW_D( HW_BH )    )
pick( "BL",   HW_D( HW_BL )    )
pick( "BP",   HW_D( HW_BP )    )
pick( "BX",   HW_D( HW_BX )    )
pick( "CH",   HW_D( HW_CH )    )
pick( "CL",   HW_D( HW_CL )    )
pick( "CS",   HW_D( HW_CS )    )
pick( "CX",   HW_D( HW_CX )    )
pick( "DH",   HW_D( HW_DH )    )
pick( "DI",   HW_D( HW_DI )    )
pick( "DL",   HW_D( HW_DL )    )
pick( "DS",   HW_D( HW_DS )    )
pick( "DX",   HW_D( HW_DX )    )
pick( "ES",   HW_D( HW_ES )    )
pick( "SI",   HW_D( HW_SI )    )
pick( "SP",   HW_D( HW_SP )    )
pick( "SS",   HW_D( HW_SS )    )

#elif   _CPU == 386

pick( "",     HW_D( HW_EMPTY ) )
pick( "8087", HW_D( HW_FLTS )  )
pick( "AH",   HW_D( HW_AH )    )
pick( "AL",   HW_D( HW_AL )    )
pick( "AX",   HW_D( HW_AX )    )
pick( "BH",   HW_D( HW_BH )    )
pick( "BL",   HW_D( HW_BL )    )
pick( "BP",   HW_D( HW_BP )    )
pick( "BX",   HW_D( HW_BX )    )
pick( "CH",   HW_D( HW_CH )    )
pick( "CL",   HW_D( HW_CL )    )
pick( "CS",   HW_D( HW_CS )    )
pick( "CX",   HW_D( HW_CX )    )
pick( "DH",   HW_D( HW_DH )    )
pick( "DI",   HW_D( HW_DI )    )
pick( "DL",   HW_D( HW_DL )    )
pick( "DS",   HW_D( HW_DS )    )
pick( "DX",   HW_D( HW_DX )    )
pick( "EAX",  HW_D( HW_EAX )   )
pick( "EBP",  HW_D( HW_BP )    )
pick( "EBX",  HW_D( HW_EBX )   )
pick( "ECX",  HW_D( HW_ECX )   )
pick( "EDI",  HW_D( HW_EDI )   )
pick( "EDX",  HW_D( HW_EDX )   )
pick( "ES",   HW_D( HW_ES )    )
pick( "ESI",  HW_D( HW_ESI )   )
pick( "ESP",  HW_D( HW_SP )    )
pick( "FS",   HW_D( HW_FS )    )
pick( "GS",   HW_D( HW_GS )    )
pick( "SI",   HW_D( HW_SI )    )
pick( "SP",   HW_D( HW_SP )    )
pick( "SS",   HW_D( HW_SS )    )

#elif   _CPU == _AXP

pick( "",      HW_D( HW_EMPTY ) )
pick( "$v0",   HW_D( HW_R0 )    )
pick( "$t0",   HW_D( HW_R1 )    )
pick( "$t1",   HW_D( HW_R2 )    )
pick( "$t2",   HW_D( HW_R3 )    )
pick( "$t3",   HW_D( HW_R4 )    )
pick( "$t4",   HW_D( HW_R5 )    )
pick( "$t5",   HW_D( HW_R6 )    )
pick( "$t6",   HW_D( HW_R7 )    )
pick( "$t7",   HW_D( HW_R8 )    )
pick( "$s0",   HW_D( HW_R9 )    )
pick( "$s1",   HW_D( HW_R10 )   )
pick( "$s2",   HW_D( HW_R11 )   )
pick( "$s3",   HW_D( HW_R12 )   )
pick( "$s4",   HW_D( HW_R13 )   )
pick( "$s5",   HW_D( HW_R14 )   )
pick( "$s6",   HW_D( HW_R15 )   )
pick( "$fp",   HW_D( HW_R15 )   )
pick( "$a0",   HW_D( HW_R16 )   )
pick( "$a1",   HW_D( HW_R17 )   )
pick( "$a2",   HW_D( HW_R18 )   )
pick( "$a3",   HW_D( HW_R19 )   )
pick( "$a4",   HW_D( HW_R20 )   )
pick( "$a5",   HW_D( HW_R21 )   )
pick( "$t8",   HW_D( HW_R22 )   )
pick( "$t9",   HW_D( HW_R23 )   )
pick( "$t10",  HW_D( HW_R24 )   )
pick( "$t11",  HW_D( HW_R25 )   )
pick( "$ra",   HW_D( HW_R26 )   )
pick( "$t12",  HW_D( HW_R27 )   )
pick( "$pv",   HW_D( HW_R27 )   )
pick( "$at",   HW_D( HW_R28 )   )
pick( "$gp",   HW_D( HW_R29 )   )
pick( "$sp",   HW_D( HW_R30 )   )
pick( "$zero", HW_D( HW_R31 )   )

#elif   _CPU == PPC

#endif
