#pmake/150: build flat register 32bit inline winnt iX86 rtdll os_nt cpu_386 profile

component  = mathlib
processor  = 387
model      = mf
subdir     = mf_rp
system     = winnt
convention = register
profile    = 1

!include $(rtdll_dir)/master.mif
