# makefile for GRAPH3S.LIB

libname =       graph3s
model =         /ms /3s /d_SUPERVGA /d__STACK
module =        $[&s
cdecl =
fard =
_386 =          386
_qnx =
asm_cmd =       386asm
asm_flags =     -NOL -EL $[&.err -O $[&.obj -I ..\inc\ -d _MODEL=_SMALL -d _386 -NO87 -TWOC

!include ..\graphics.mif
