#pmake: build compact cpu_i86 os_win
#
# cplx7c.lib -- compact memory-model COMPLEX library fpi for Windows
#
processor  = 087
system     = windows
model      = mc
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
