#pmake: build trap remote os_linux cpu_x64 tcp x86

tree_depth = 4

host_cpu = x64
host_os  = linux

target_cpu = x86

srv = tcp
which = TRAP
remote_link = 1

sys_dll = 1

inc_dirs   = -I"$(trap_dir)/lcl/linux/h"

!include $(trap_dir)/master.mif
