#pmake: serv remote os_qnx cpu_i86 cpu_386 par x86
host_cpu = 386
host_os  = qnx

os = qnx
srv = par
cpu = x86
which = SERVER
remote_link = 1

extra_objs = parqnx.obj

!include $(trap_dir)/master.mif
