#pmake: serv remote os_qnx cpu_i86 cpu_386 par x86

tree_depth = 4

host_cpu = 386
host_os  = qnx

target_cpu = x86

srv = par
which = SERVER
remote_link = 1

extra_objs = parqnx.obj

!include $(trap_dir)/lcl/qnx/qnx.mif
!include $(trap_dir)/master.mif
