#pmake: build flat cpu_386 os_osi
#
# cplx73s.lib -- stack based 32-bit COMPLEX library fpi
#
processor  = 387
system     = generic
model      = mf
convention = stack
linkage    = static
define_library_include = $(cpplib_dir)/complex/complex.mif
!include $(cpplib_dir)/mklib.mif
