#pmake: all build compact cpu_i86 os_osi
#
# plibc -- 16-bit compact memory-model PLIB
#
suffix = c
target_system = generic
target_lib = $(prefix)$(suffix).lib
production_lib = lib286
define_library_include = $(plusplus_runtime_dir)\plib.mif
define_target_include = $(plusplus_dir)\lib16$(suffix).mif
!include $(plusplus_dir)\mklib.mif
