

.extensions:
.extensions: .exe .cpp

exes =                                                                       &
GCOUNT.EXE      GETCHAR.EXE     GET.EXE         GETINBUF.EXE    GETLINE.EXE  &
IPFX.EXE        IGNORE.EXE      EATWHITE.EXE    CONISTRM.EXE    SYNC.EXE     &
PEEK.EXE        PUTBACK.EXE     READ.EXE        SEEKGPOS.EXE    SEEKGOFF.EXE &
TELLG.EXE       RSHCHBUF.EXE    RSHCHAR.EXE     RSHNUM.EXE      CONBUF.EXE   &
RSHSTRBU.EXE    DESTRUCT.EXE    RSHMAN.EXE      EQISTRM.EXE     EQSTRMBU.EXE &
GETINSTR.EXE

all : $(exes) .symbolic

.cpp.exe :
    wcl $[@
