#pmake: all build flat cpu_386 os_os2
host_CPU = 386
fs_prefix = os2
suffix = mt3r
subdir = 3rmt
target_lib = $(prefix)$(suffix).lib
production_lib = lib386
define_library_include = $(plusplus_cpplib_dir)\plib.mif
!include $(plusplus_dir)\mrglib.mif
