#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp STRING library
#
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static

!include $(cpplib_dir)/string/string.mif
