/****************************************************************************
*
*                            Open Watcom Project
*
*    Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
*
*  ========================================================================
*
*    This file contains Original Code and/or Modifications of Original
*    Code as defined in and that are subject to the Sybase Open Watcom
*    Public License version 1.0 (the 'License'). You may not use this file
*    except in compliance with the License. BY USING THIS FILE YOU AGREE TO
*    ALL TERMS AND CONDITIONS OF THE LICENSE. A copy of the License is
*    provided with the Original Code and Modifications, and is also
*    available at www.sybase.com/developer/opensource.
*
*    The Original Code and all software distributed under the License are
*    distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
*    EXPRESS OR IMPLIED, AND SYBASE AND ALL CONTRIBUTORS HEREBY DISCLAIM
*    ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF
*    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR
*    NON-INFRINGEMENT. Please see the License for the specific language
*    governing rights and limitations under the License.
*
*  ========================================================================
*
* Description:  Register names for SPARC CPUs.
*
****************************************************************************/


regpick( f0, "%f0" )
regpick( f1, "%f1" )
regpick( f2, "%f2" )
regpick( f3, "%f3" )
regpick( f4, "%f4" )
regpick( f5, "%f5" )
regpick( f6, "%f6" )
regpick( f7, "%f7" )
regpick( f8, "%f8" )
regpick( f9, "%f9" )
regpick( f10, "%f10" )
regpick( f11, "%f11" )
regpick( f12, "%f12" )
regpick( f13, "%f13" )
regpick( f14, "%f14" )
regpick( f15, "%f15" )
regpick( f16, "%f16" )
regpick( f17, "%f17" )
regpick( f18, "%f18" )
regpick( f19, "%f19" )
regpick( f20, "%f20" )
regpick( f21, "%f21" )
regpick( f22, "%f22" )
regpick( f23, "%f23" )
regpick( f24, "%f24" )
regpick( f25, "%f25" )
regpick( f26, "%f26" )
regpick( f27, "%f27" )
regpick( f28, "%f28" )
regpick( f29, "%f29" )
regpick( f30, "%f30" )
regpick( f31, "%f31" )
regpick( r0, "%r0" )
regpick( r1, "%r1" )
regpick( r2, "%r2" )
regpick( r3, "%r3" )
regpick( r4, "%r4" )
regpick( r5, "%r5" )
regpick( r6, "%r6" )
regpick( r7, "%r7" )
regpick( r8, "%r8" )
regpick( r9, "%r9" )
regpick( r10, "%r10" )
regpick( r11, "%r11" )
regpick( r12, "%r12" )
regpick( r13, "%r13" )
regpick( r14, "%r14" )
regpick( r15, "%r15" )
regpick( r16, "%r16" )
regpick( r17, "%r17" )
regpick( r18, "%r18" )
regpick( r19, "%r19" )
regpick( r20, "%r20" )
regpick( r21, "%r21" )
regpick( r22, "%r22" )
regpick( r23, "%r23" )
regpick( r24, "%r24" )
regpick( r25, "%r25" )
regpick( r26, "%r26" )
regpick( r27, "%r27" )
regpick( r28, "%r28" )
regpick( r29, "%r29" )
regpick( r30, "%r30" )
regpick( r31, "%r31" )
regpick( g0, "%g0" )
regpick( g1, "%g1" )
regpick( g2, "%g2" )
regpick( g3, "%g3" )
regpick( g4, "%g4" )
regpick( g5, "%g5" )
regpick( g6, "%g6" )
regpick( g7, "%g7" )
regpick( o0, "%o0" )
regpick( o1, "%o1" )
regpick( o2, "%o2" )
regpick( o3, "%o3" )
regpick( o4, "%o4" )
regpick( o5, "%o5" )
regpick( o6, "%o6" )
regpick( o7, "%o7" )
regpick( l0, "%l0" )
regpick( l1, "%l1" )
regpick( l2, "%l2" )
regpick( l3, "%l3" )
regpick( l4, "%l4" )
regpick( l5, "%l5" )
regpick( l6, "%l6" )
regpick( l7, "%l7" )
regpick( i0, "%i0" )
regpick( i1, "%i1" )
regpick( i2, "%i2" )
regpick( i3, "%i3" )
regpick( i4, "%i4" )
regpick( i5, "%i5" )
regpick( i6, "%i6" )
regpick( i7, "%i7" )
regpick( fp, "%fp" )
regpick( sp, "%sp" )
regpick( c0, "%c0" )
regpick( c1, "%c1" )
regpick( c2, "%c2" )
regpick( c3, "%c3" )
regpick( c4, "%c4" )
regpick( c5, "%c5" )
regpick( c6, "%c6" )
regpick( c7, "%c7" )
regpick( c8, "%c8" )
regpick( c9, "%c9" )
regpick( c10, "%c10" )
regpick( c11, "%c11" )
regpick( c12, "%c12" )
regpick( c13, "%c13" )
regpick( c14, "%c14" )
regpick( c15, "%c15" )
regpick( c16, "%c16" )
regpick( c17, "%c17" )
regpick( c18, "%c18" )
regpick( c19, "%c19" )
regpick( c20, "%c20" )
regpick( c21, "%c21" )
regpick( c22, "%c22" )
regpick( c23, "%c23" )
regpick( c24, "%c24" )
regpick( c25, "%c25" )
regpick( c26, "%c26" )
regpick( c27, "%c27" )
regpick( c28, "%c28" )
regpick( c29, "%c29" )
regpick( c30, "%c30" )
regpick( c31, "%c31" )
// no asr0 for some reason
regpick( asr1, "asr1" )
regpick( asr2, "asr2" )
regpick( asr3, "asr3" )
regpick( asr4, "asr4" )
regpick( asr5, "asr5" )
regpick( asr6, "asr6" )
regpick( asr7, "asr7" )
regpick( asr8, "asr8" )
regpick( asr9, "asr9" )
regpick( asr10, "asr10" )
regpick( asr11, "asr11" )
regpick( asr12, "asr12" )
regpick( asr13, "asr13" )
regpick( asr14, "asr14" )
regpick( asr15, "asr15" )
regpick( asr16, "asr16" )
regpick( asr17, "asr17" )
regpick( asr18, "asr18" )
regpick( asr19, "asr19" )
regpick( asr20, "asr20" )
regpick( asr21, "asr21" )
regpick( asr22, "asr22" )
regpick( asr23, "asr23" )
regpick( asr24, "asr24" )
regpick( asr25, "asr25" )
regpick( asr26, "asr26" )
regpick( asr27, "asr27" )
regpick( asr28, "asr28" )
regpick( asr29, "asr29" )
regpick( asr30, "asr30" )
regpick( asr31, "asr31" )
regpick( fsr, "fsr" )
regpick( fq, "fq" )
regpick( csr, "csr" )
regpick( cq, "cq" )
