#
# Makefile to create OSI version of WIC
#
# WMAKE             creates wic.exe
#
#

_OS         =   OSI
opts_cc     =   -oailt -s -3r
opts_lnk    =   system osi
cc          =   wcc386
mem_model_prefix = f         # Flat memory model

!include ..\mif\master.mif

