#pmake: build serv remote os_win cpu_i86 cpu_386 tcp x86

tree_depth = 4

host_cpu = i86
host_os  = win

target_cpu = x86

srv = tcp
which = SERVER
gui = 1
remote_link = 1

extra_linker = lib winsock.lib

!include $(trap_dir)/master.mif
