#pmake: build serv remote os_os2 cpu_i86 cpu_386 par x86
host_cpu = 386
host_os  = os2

target_cpu = x86

os  = os2v2
srv = par
which = SERVER
remote_link = 1

extra_objs = paros22.obj

!include ../os2v2.mif
!include $(trap_dir)/master.mif
