#pmake: build flat cpu_386 os_osi
processor  = 386
system     = generic
model      = ms
convention = register
linkage    = static
mthreaded  = 1
subdir     = ms_rmt

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
