#pmake: nomodel cpu_axp os_nt
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
pd_registration = yes
suffix = mt
target_system = ntaxp
production_lib = libaxp
define_library_include = $(plusplus_runtime_dir)\plib.mif
define_target_include = $(plusplus_dir)\libaxp$(suffix).mif
text = -hd
!include $(plusplus_dir)\mklib.mif
