pick(   APPWIZ_CFG_MISSING,
        "The configuration file '%s' could not be found.",
        "The configuration file '%s' could not be found." )
pick(   APPWIZ_INVALID_PROJTYPES,
        "The Application Wizard could not read the list of project types.",
        "The Application Wizard could not read the list of project types." )
pick(   APPWIZ_MKDIR_FAILED,
        "Creation of the project directory has failed.",
        "Creation of the project directory has failed." )
pick(   APPWIZ_NO_PROJDIR,
        "Please enter a project directory.",
        "Please enter a project directory." )
pick(   APPWIZ_NO_PROJNAME,
        "Please enter a project name.",
        "Please enter a project name." )
pick(   APPWIZ_TEMPLATE_MISSING,
        "The template file '%s' could not be found.",
        "The template file '%s' could not be found." )

