#pmake: build large cpu_i86 os_dos os_os2 os_win os_qnx
#
# contl.lib -- large memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = ml
linkage    = static

!include $(cpplib_dir)/contain/contain.mif
