#pmake: build large cpu_i86 os_osi os_os2
#
# contl.lib -- large memory-model CONTAINER library
#
processor  = 086
system     = generic
model      = ml
linkage    = static
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
