#pmake: build large cpu_i86 os_os2
processor  = 286
system     = os2
model      = ml
convention =
linkage    = static
mthreaded  = 1
subdir     = ml_mt
define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
