#pmake/150: build flat stack 32bit calls os2 iX86 rtdll os_os2 cpu_386 cpplib

component  = cpplib
processor  = 386
model      = mf
subdir     = mf_s
system     = os2
convention = stack

!include $(rtdll_dir)/master.mif
