#pmake/150: build flat stack 32bit os2 ix86 rtdll os_os2 cpu_386

component  = clib
processor  = 386
model      = mf
subdir     = mf_s
system     = os2
convention = stack

!include $(rtdll_dir)/master.mif
