#pmake: build flat cpu_386 os_osi os_dos os_linux
#
# plib3s -- 32-bit 3s PLIB
#
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
