#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp CONTAINER library
#
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static

!include $(cpplib_dir)/contain/contain.mif
