#pmake: build serv remote os_nt cpu_386 par
host_CPU = 386
host_OS = nt

gui = 1
os = nt
srv = par
cpu = x86
which = SERVER
type  = remote_link

extra_objs = parnt.obj

!include $(trap_dir)/master.mif
