#pmake: debug flat cpu_386 os_os2
#
# iost3r.lib -- register based 32-bit IOSTREAM library
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
cpplib_release  = 0
fs_registration = yes

!include $(cpplib_dir)/iostream/iostream.mif
