#pmake: nobuild debug flat cpu_386 os_os2
#
# iost3r.lib -- register based 32-bit IOSTREAM library
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
fs_registration = yes

cpplib_release  = 0

!include $(cpplib_dir)/iostream/iostream.mif
