name: boot-ow
description: 'Process boot build steps by previous version of Open Watcom compiler'
inputs:
  arch:
    description: ''
    required: false
    default: ''
    type: string
  pscript:
    description: ''
    required: false
    default: ''
    type: string
  owdebug:
    description: ''
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: inputs.arch == 'lnx'
    name: Bootstrap OW
    run: ${{ inputs.pscript }}
    env:
      OWTOOLS:       'WATCOM'
      OWBUILD_STAGE: 'boot'
      OWROOT:        ${{ github.workspace }}
      WATCOM:        ${{ github.workspace }}/ci/ow
      INCLUDE:       ${{ github.workspace }}/ci/ow/lh
      WATCOM_PATH:   ${{ github.workspace }}/ci/ow/binl
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.arch == 'nt'
    name: Bootstrap OW
    run: ${{ inputs.pscript }}
    env:
      OWTOOLS:       'WATCOM'
      OWBUILD_STAGE: 'boot'
      OWROOT:        ${{ github.workspace }}
      WATCOM:        ${{ github.workspace }}\ci\ow
      INCLUDE:       ${{ github.workspace }}\ci\ow\h;${{ github.workspace }}\ci\ow\h\nt
      WATCOM_PATH:   ${{ github.workspace }}\ci\ow\binnt
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: cmd
