#pmake: build small cpu_i86 os_osi os_os2
#
# strgs.lib -- small memory-model STRING library
#
processor  = 086
system     = generic
model      = ms
linkage    = static

!include $(cpplib_dir)/string/string.mif
