#pmake: build flat cpu_386 os_nt
#
# iost3r.lib -- register based 32-bit IOSTREAM library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
fs_registration = yes

!include $(cpplib_dir)/iostream/iostream.mif
