#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp IOSTREAM library
#
processor    = axp
system       = winnt
model        =
convention   =
linkage      = static
define_library_include = $(cpplib_dir)/iostream/iostream.mif
!include $(cpplib_dir)/mklib.mif
