#pmake: all build flat cpu_386 os_nt
host_CPU = 386
fs_prefix = nt
suffix = 3r
subdir = 3r
production_lib = lib386
define_library_include = $(plusplus_cpplib_dir)\plib.mif
!include $(plusplus_dir)\mrglib.mif
