#pmake: build large cpu_i86 os_os2
#
# contmt.lib -- large memory-model OS/2 multi-thread CONTAINER library
#
processor  = 286
system     = os2
model      = ml
convention =
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/contain/contain.mif
