

.extensions:
.extensions: .exe .cpp

exes =                                                                       &
BAD.EXE         EOF.EXE         CLEAR.EXE       FAIL.EXE        FILL.EXE     &
PRECISIO.EXE    FLAGS.EXE       GOOD.EXE        OPEXAM.EXE      OPVOID.EXE   &
RDBUF.EXE       RDSTATE.EXE     WIDTH.EXE       SETF.EXE        UNSETF.EXE   &
EXCEPT.EXE      TIE.EXE         IWORD.EXE       PWORD.EXE       INIT.EXE     &
CONSTRBU.EXE   BITALLOC.EXE

all : $(exes) .symbolic

.cpp.exe :
    wcl $[@ -xs
