#pmake: os_qnx cpu_386 flat
#
# plibmt3r -- 32-bit 3r PLIB multi-thread library
#
processor  = 386
system     = qnx
model      = ms
convention = register
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/runtime/plib.mif
