// NB the maximum allowable string length is 128 bytes

pick(   STR_APP_NAME,
        "Open Watcom Zoom",
        "Open Watcom ズーム" )
pick(   STR_ABOUT_VER,
        "",     //NOT USED
        "" )
pick(   STR_ABOUT_YEAR,
        "1994",
        "1994" )
pick(   STR_ABOUT_TITLE,
        "About Open Watcom Zoom",
        "Open Watcom ズームのバージョン情報" )
pick(   STR_UNABLE_TO_AUTOREFRESH,
        "Unable to do autorefresh.  No system timer available",
        "自動更新が行えません.  使用可能なシステム タイマーがありません" )
pick(   STR_INTERV_NOT_NUMERIC,
        "The Interval field must contain a numeric value",
        "間隔は数値で指定しなければなりません" )
pick(   STR_ABOUT_NAME,
        "Open Watcom Zoom for Windows" STR_BITNEES,
        "Open Watcom ズームのWindows版" STR_BITNEES )
pick(   STR_INTERV_IS_ZERO,
        "The refresh interval must be greater than zero.",
        "更新間隔は 0 より大きい値です." )
