// NB the maximum allowable string length is 128 bytes

pick( STR_APP_NAME,
	"WATCOM Zoom",
	"WATCOM ズーム" )
pick( STR_ABOUT_VER,
	"",	//NOT USED
	"" )
pick( STR_ABOUT_YEAR,
	"1994",
	"1994" )
pick( STR_ABOUT_TITLE,
	"About WATCOM Zoom",
	"WATCOM ズームのバージョン情報" )
pick( STR_UNABLE_TO_AUTOREFRESH,
	"Unable to do autorefresh.  No system timer available",
	"自動更新が行えません.  使用可能なシステム タイマーがありません" )
pick( STR_INTERV_NOT_NUMERIC,
	"The Interval field must contain a numeric value",
	"間隔は数値で指定しなければなりません" )
pick( STR_ABOUT_NAME_NT,
	"WATCOM Zoom for Windows NT",
	"WATCOM ズームのWindows NT版" )
pick( STR_ABOUT_NAME,
	"WATCOM Zoom for Windows",
	"WATCOM ズームのWindows版" )
pick( STR_INTERV_IS_ZERO,
	"The refresh interval must be greater than zero.",
	"更新間隔は 0 より大きい値です." )

#include "about.msg"
