#pmake: build debug flat cpu_386 os_nt
#
# plib3r -- 32-bit 3r MT PLIB, PLBX
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
mthreaded  = 1
fs_registration = yes

cpplib_release = 0

!include $(cpplib_dir)/runtime/plib.mif
