#pmake: build os_os2 cpu_386
#
# Open Watcom Debugger makefile for OS/2 Presentation Manager
#

host_os  = os2
host_cpu = 386

sys_windowed = 1

syshdir  =

sysobjs =            &
        autoenv.obj  &
        os22ini.obj  &
        os2chk.obj   &
        os2cmd.obj   &
        os22flio.obj &
        pmscrn2.obj

!include ../../master.mif
