#pmake: build flat cpu_386 os_nt
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = static
fs_registration = yes
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
