#pmake: os_qnx cpu_386 flat
#
# iostmt3r.lib -- register based multi-thread 32-bit IOSTREAM library
#
processor  = 386
system     = qnx
model      = ms
convention = register
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/iostream/iostream.mif
