#pmake: build large cpu_i86 os_os2
#
# plibmtl -- 16-bit large memory-model PLIB multi-thread OS/2
#
processor  = 286
system     = os2
model      = ml
convention =
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/runtime/plib.mif
