name: release-load-all
description: 'Load all artifact for OW Release'
inputs:
  tools_nt:
    description: 'used compiler toolchain (for Windows)'
    required: false
    default: ''
    type: string
  tools_lnx:
    description: 'used compiler toolchain (for Linux)'
    required: false
    default: ''
    type: string
  tools_osx:
    description: 'used compiler toolchain (for OSX)'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel nt x64 ${{ inputs.tools_nt }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel lnx x64 ${{ inputs.tools_lnx }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel lnx a64 ${{ inputs.tools_lnx }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel bino64'
      artifact: "rel osx x64 ${{ inputs.tools_osx }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel armo64'
      artifact: "rel osx a64 ${{ inputs.tools_osx }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel docdos ${{ inputs.tools_nt }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel docchm ${{ inputs.tools_nt }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel docnt ${{ inputs.tools_nt }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel docos2 ${{ inputs.tools_nt }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel docpdf ${{ inputs.tools_nt }}"
      owdebug:  ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:   'lnx'
      gitpath:  'rel'
      artifact: "rel docwin ${{ inputs.tools_nt }}"
      owdebug:  ${{ inputs.owdebug }}
