#pmake: build serv remote os_dos cpu_i86 cpu_386 par x86
host_cpu = i86
host_os  = dos

target_cpu = x86

os = dos
srv = par
which = SERVER
remote_link = 1

extra_objs = pardos.obj

!include $(trap_dir)/master.mif
