type = win
os = pm
build_target = os2_pm
sys=os2v2 pm
compiler = comp386
model=f
extra_lib=os2386.lib
extra_option = option undefsok
sysinclude=$(watcom_dir)\os220_h;

target : sample.exe .SYMBOLIC
    @%null

!include ..\makefile
