#pmake: build huge cpu_i86 os_osi
#
# cplxh.lib -- huge memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mh
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
