#pmake: build huge cpu_i86 os_dos os_os2 os_win os_qnx
#
# cplxh.lib -- huge memory-model COMPLEX library fpc
#
processor  = 086
system     = generic
model      = mh
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
