#pmake: all build large cpu_i86 os_osi
#
# plibl -- 16-bit large memory-model PLIB
#
suffix = l
target_system = generic
target_lib = $(prefix)$(suffix).lib
production_lib = lib286
define_library_include = $(plusplus_runtime_dir)\plib.mif
define_target_include = $(plusplus_dir)\lib16$(suffix).mif
!include $(plusplus_dir)\mklib.mif
