# makefile for GRAPHS.LIB

libname =       graphs
model =         /ms /d_NEC_PC
module =        $[&
cdecl =         _loadds
fard =
_386 =
_qnx =
asm_cmd =       masm
asm_flags =     -t -ml -i..\inc -d_MODEL=_SMALL;
_NEC_PC =       1

!include ..\graphics.mif
