#pmake: build compact cpu_i86 os_win
#
# iostc.lib -- compact memory-model IOSTREAM library for Windows
#
processor  = 086
system     = windows
model      = mc
linkage    = static

!include $(cpplib_dir)/iostream/iostream.mif
