#pmake: nomodel cpu_axp os_nt
#
# iost -- 32-bit axp STRING library
#
suffix = nt
target_system = ntaxp
production_lib = libaxp
uncompressed=1
define_library_include = $(plusplus_string_dir)\string.mif
define_deps_include = $(plusplus_string_dir)\deps.mif
define_target_include = $(plusplus_dir)\libaxp$(suffix).mif
!include $(plusplus_dir)\mklib.mif
