#pmake: build small cpu_i86 os_win
#
# cplx7s.lib -- small memory-model COMPLEX library fpi for Windows
#
processor  = 087
system     = windows
model      = ms
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
