#pmake: build serv remote os_nt cpu_i86 cpu_386 ser x86
host_CPU = 386
host_OS = nt

os = nt
srv = ser
cpu = x86
which = SERVER
type  = remote_link

extra_objs = sernt.obj busywait.obj

!include $(trap_dir)/master.mif
