// wrsvexe.c
pick(   WR_NOCONV1632,
        "Conversion between 16 and 32 bit resources are not supported.",
        "Conversion between 16 and 32 bit resources are not supported." )
pick(   WR_NOTWIN16,
        "Resource was not originally a 16 bit Windows executable!",
        "Resource was not originally a 16 bit Windows executable!" )
pick(   WR_NOTWINNT,
        "Resource was not originally a 32 bit Windows NT executable!",
        "Resource was not originally a 32 bit Windows NT executable!" )

//wrmsg.c
pick(   WR_ERRMSG,
        "Error Message",
        "Error Message" )

// rcerrprt.c
pick(   WR_WRCMSG,
        "Open Watcom Resource Compiler Message",
        "Open Watcom Resource Compiler Message" )

// wrdata.c
pick(   WR_RESTOOLARGE,
        "Resource is too large to edit.",
        "Resource is too large to edit." )

//wrimg.c
pick(   WR_PRJNOBMP,
        "This project has no bitmap resources.",
        "This project has no bitmap resources." )
pick(   WR_PRJMORETHANONE,
        "This project has more than one resource.",
        "This project has more than one resource." )
pick(   WR_PRJNOCUR,
        "This project has no cursor group resources.",
        "This project has no cursor group resources." )
pick(   WR_PRJNOICON,
        "This project has no icon group resources.",
        "This project has no icon group resources." )

// wrselft
pick(   WR_INVALIDSELECTION,
        "That is not a valid selection",
        "That is not a valid selection" )

// wrselimg
pick(   WR_EMPTY,
        "<<empty>>",
        "<<empty>>" )
pick(   WR_PRJNOIMAGES,
        "This project contains no images.",
        "This project contains no images." )

// wrmain.c
pick(   WR_BADFILETYPE,
        "Unsupported file type.",
        "Unsupported file type." )
pick(   WR_NOCREATESCRIPT,
        "Cannot create resource script.",
        "Cannot create resource script." )
pick(   WR_BADSAVETYPE,
        "Invalid save file type.",
        "Invalid save file type." )
pick(   WR_REPLACERES,
        "A resource with this name already exists.\nReplace?",
        "A resource with this name already exists.\nReplace?" )
pick(   WR_REPLACESTR,
        "String block %d already exists.\nReplace old strings?",
        "String block %d already exists.\nReplace old strings?" )
pick(   WR_COPYRESINTO,
        "Copy Resource Into",
        "Copy Resource Into" )
pick(   WR_NOLOAD32IN16,
        "Cannot load 32 bit resources with the 16 version of this application.",
        "Cannot load 32 bit resources with the 16 version of this application." )
pick(   WR_NOSAVE32IN16,
        "Cannot save 32 bit resources with the 16 version of this application.",
        "Cannot save 32 bit resources with the 16 version of this application." )

//wrrdw16.c
pick(   WR_BADEXE,
        "This is an invalid executable.",
        "This is an invalid executable." )

// wrrdres.c
pick(   WR_INVALIDFILE,
        "Invalid file type detected.",
        "Invalid file type detected." )
pick(   WR_BADFILEWWIN16,
        "Incorrect file type.\nThis is a WATCOM WIN16 resource file.",
        "Incorrect file type.\nThis is a WATCOM WIN16 resource file." )
pick(   WR_BADFILEWWINNT,
        "Incorrect file type.\nThis is a WATCOM WINNT resource file.",
        "Incorrect file type.\nThis is a WATCOM WINNT resource file." )
pick(   WR_BADFILEMWIN16,
        "Incorrect file type.\nThis is a Microsoft WIN16 resource file.",
        "Incorrect file type.\nThis is a Microsoft WIN16 resource file." )
pick(   WR_BADFILEMWINNT,
        "Incorrect file type.\nThis is a Microsoft WINNT resource file.",
        "Incorrect file type.\nThis is a Microsoft WINNT resource file." )
pick(   WR_DUPRESDISCARD,
        "WARNING: A duplicate resource name was discarded!",
        "WARNING: A duplicate resource name was discarded!" )

// wrrdwnt.c
pick(   WR_EXENORES,
        "This executable has no resources.",
        "This executable has no resources." )
pick(   WR_BADIDDISCARDTYPE,
        "WARNING: Bad id_name. Type discarded.",
        "WARNING: Bad id_name. Type discarded." )
pick(   WR_BADRVADISCARDTYPE,
        "WARNING: Bad entry_rva. Type discarded.",
        "WARNING: Bad entry_rva. Type discarded." )
pick(   WR_BADIDDISCARDNAME,
        "WARNING: Bad id_name. Name discarded.",
        "WARNING: Bad id_name. Name discarded." )
pick(   WR_BADLANGDISCARDNAME,
        "WARNING: Bad LangId entry_rva. Name discarded.",
        "WARNING: Bad LangId entry_rva. Name discarded." )
pick(   WR_INVALIDNTEXE,
        "This is not a valid Windows NT executable file.",
        "This is not a valid Windows NT executable file." )

// wrrnames.c
pick(   WR_ALLSTRINGS,
        "All Strings",
        "All Strings" )
pick(   WR_STRINGIDS,
        "Strings %d - %d",
        "Strings %d - %d" )

// wrhash.c
pick(   WR_BADSYMBOL,
        "That was an illegal symbol name.",
        "That was an illegal symbol name." )
pick(   WR_EDITSYMBOLSTITLE,
        "Edit Symbols",
        "Edit Symbols" )
pick(   WR_DISCARDCHANGESMSG,
        "Discard Changes?",
        "Discard Changes?" )
pick(   WR_ADDSYMBOLTITLE,
        "Add Symbol",
        "Add Symbol" )
pick(   WR_MODIFYSYMBOLTITLE,
        "Change Symbol",
        "Change Symbol" )
pick(   WR_QUERYUNIQUEMSG,
        "Another symbol is using this value.\nAdd symbol anyway?",
        "Another symbol is using this value.\nAdd symbol anyway?" )
pick(   WR_FORCEADDQUERYMSG,
        "This symbol already exists.\nModify this symbol?",
        "This symbol already exists.\nModify this symbol?" )
pick(   WR_FILEOPENFAILED,
        "Could not open file %s.\n%s",
        "Could not open file %s.\n%s" )
pick(   WR_FILECLOSEFAILED,
        "Could not close file %s.\n%s",
        "Could not close file %s.\n%s" )

// wrsvres.c
pick(   WR_DUPRESFOUND,
        "A duplicate resource of type %s named %s was detected.",
        "A duplicate resource of type %s named %s was detected." )

// wrtmpfil.c
pick(   WR_BACKUPFAILED,
        "Could not backup file %s to %s.\n%s",
        "Could not backup file %s to %s.\n%s" )
