#pmake: build os_nt cpu_386
#
# WATCOM Debugger makefile for NT (real GUI version)
#

host_OS=nt
host_CPU=386

sys_windowed = 1

sysobjs =   &
    autoenv.obj &
    ntinit.obj &
    ntguiscn.obj &
    ntfilio.obj &
    ntfinfo.obj &
    ntcmd.obj &
    winchk.obj &
    winlkup.obj

!include ../../master.mif
