/* UTF-8 encoding, ¥ */

pick( MSG_EXCEPT_0
        , ""
        , ""
)
pick( MSG_EXCEPT_1
        , "divide overflow"
        , "除算オーバーフロー"
)
pick( MSG_EXCEPT_2
        , "non-maskable interrupt"
        , "マスク不可能割込み(ﾉﾝﾏｽｶﾌﾞﾙ割込み,NMI)"
)
pick( MSG_EXCEPT_3
        , "integer overflow"
        , "整数オーバーフロー"
)
pick( MSG_EXCEPT_4
        , "bounds check"
        , "境界検査"
)
pick( MSG_EXCEPT_5
        , "invalid opcode"
        , "無効なオペコード"
)
pick( MSG_EXCEPT_6
        , "coprocessor not available"
        , "コプロセッサはありません"
)
pick( MSG_EXCEPT_7
        , "double fault"
        , "二重フォールト"
)
pick( MSG_EXCEPT_8
        , "coprocessor segment overrun"
        , "コプロセッサ・セグメント・オーバーラン"
)
pick( MSG_EXCEPT_9
        , "invalid TSS"
        , "無効なTSS"
)
pick( MSG_EXCEPT_10
        , "segment not present"
        , "セグメントが(メモリ上に)ありません"
)
pick( MSG_EXCEPT_11
        , "stack exception"
        , "スタック例外"
)
pick( MSG_EXCEPT_12
        , "general protection fault"
        , "一般保護フォールト"
)
pick( MSG_EXCEPT_13
        , "page fault"
        , "ページ・フォールト"
)
pick( MSG_EXCEPT_14
        , "coprocessor error"
        , "コプロセッサ・エラー"
)
