#pmake: build small cpu_i86 os_osi os_os2
processor  = 086
system     = generic
model      = ms
linkage    = static
subdir     = ms
define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
