

.extensions:
.extensions: .exe .cpp

exes = abs.exe   acos.exe acosh.exe arg.exe  asin.exe asinh.exe atan.exe &
       atanh.exe conj.exe cos.exe   cosh.exe exp.exe  imag.exe  log.exe  &
       log10.exe norm.exe polar.exe pow.exe  real.exe sin.exe   sinh.exe &
       sqrt.exe  tan.exe  tanh.exe

all : $(exes) .symbolic

.cpp.exe :
    wcl $[@
