#pmake: build small cpu_i86 os_win
#
# conts.lib -- small memory-model CONTAINER library for Windows
#
processor  = 086
system     = windows
model      = ms
linkage    = static
define_library_include = $(cpplib_dir)/contain/contain.mif
!include $(cpplib_dir)/mklib.mif
