#pmake: build small cpu_i86 os_win
#
# conts.lib -- small memory-model CONTAINER library for Windows
#
processor  = 086
system     = windows
model      = ms
linkage    = static

!include $(cpplib_dir)/contain/contain.mif
