#pmake: build medium cpu_i86 os_dos os_os2 os_win os_qnx
#
# plibm -- 16-bit medium memory-model PLIB
#
processor  = 086
system     = generic
model      = mm
linkage    = static

!include $(cpplib_dir)/runtime/runtime.mif
