#pmake: build medium cpu_i86 os_osi os_os2
#
# plibm -- 16-bit medium memory-model PLIB
#
processor  = 086
system     = generic
model      = mm
linkage    = static
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
