

.extensions:
.extensions: .exe .cpp

exes =constr.exe condef.exe   opequal.exe  opincre.exe char.exe  conchar.exe &
      poslen.exe poschara.exe poscharb.exe length.exe  match.exe index.exe   &
      lower.exe  upper.exe    alloc.exe    cstr.exe    valid.exe concstr.exe

all : $(exes) .symbolic

.cpp.exe :
    wcl $[@
