pick( UNKNOWN_ERROR,	"Unknown\n" ),
pick( OUT_OF_MEMORY, 	"Out of memory\n" ),
pick( PARSE_ERROR,	"Parse error\n" ),
pick( FILE_READ_ERR,	"Attempt to read from a file failed\n" ),
pick( FILE_WRITE_ERR,	"Attempt to write to file '%s' failed\n" ),
pick( FILE_OPEN_ERR,	"Attempt to open '%s' failed\n" ),
pick( FILE_RM_ERR,	"Attempt to delete '%s' failed\n" ),
pick( FILE_REN_ERR,	"Attempt to rename '%s' to %s' failed\n" ),
pick( FILE_FORMAT_ERR,	"Improper file format\n" ),
pick( CLI_BAD_CMD_OPT,	"Unknown option '%s' specified\n" ),
pick( CLI_MULTI_INPUTS,	"More than one input file specified\n" ),
pick( CLI_NO_INPUT_FILE,"No input file specified\n" ),
pick( UNKNOWN_TYPE,	"Unknown type '%s' in function/subroutine '%s'\n" ),
pick( CHANGED_PROTOTYPE,"Prototype for '%s' has changed\n" ),
pick( CLI_MISSING_OPTION, "Option '%s' cannot be used without option '%s'\n" ),
pick( UNKNOWN_DATA_TYPE, "Variable '%s' has unknown type '%s'\n" ),
pick( SCANNER_ERROR,	 "Scanner Error\n" ),
pick( ERR_DYNAMIC_ARRAY, "Variable '%s' is a dynamic array\n" ),
pick( ERR_MULTI_DIM_ARRAY, "Variable '%s' is a multidimensional array\n" ),
pick( ERR_INDEX_DEFN,	"Variable '%s' contains an array element definition\n" ),
pick( ERR_MULTI_DIM_PARM,"Parameter '%s' in function '%s' is a multidimensional array\n" ),
pick( ERR_INDEX_DEF_PARM,"Parameter '%s' in function '%s' contains an array element definition\n" )
