#pmake/150: build flat register 32bit calls os2 iX86 rtdll os_os2 cpu_386

component  = mathlib
processor  = 386
model      = mf
subdir     = mf_r
system     = os2
convention = register

!include $(rtdll_dir)/master.mif
