#pmake: build medium cpu_i86 os_osi os_os2
processor  = 086
system     = generic
model      = mm
linkage    = static
subdir     = mm
define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
