#pmake: os_qnx cpu_386 flat
processor  = 386
system     = qnx
model      = ms
convention = register
linkage    = static
mthreaded  = 1
subdir     = ms_rmt
define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
