#pmake: build os_nt cpu_386
#
# WATCOM Debugger makefile for NT (character mode)
#

host_OS=nt
host_CPU=386

sysobjs =   &
    autoenv.obj &
    ntinit.obj &
    ntscrn.obj &
    ntfilio.obj &
    ntfinfo.obj &
    ntcmd.obj &
    winchk.obj &
    winlkup.obj

!include ../../master.mif
