#pmake: build flat cpu_386 os_nt dynamic profile
#
# strgmt3r.lib -- register based multi-thread 32-bit STRING library
#
processor  = 386
system     = winnt
model      = mf
convention = register
linkage    = dynamic
mthreaded  = 1
fs_registration = yes
profile = 1

!include $(cpplib_dir)/string/string.mif
