name: dosbox-instalation
description: 'Install DOSBOX run-time if necessary'
runs:
  using: composite
  steps:
  - if: runner.os == 'Linux'
    name: Install DOSBOX
    run: |
      for i in {1..3}
      do
        sudo apt update --fix-missing
        sudo apt-get install -y dosbox
        if [ $? = 0 ]; then
          break
        fi
      done
    shell: bash
  - if: runner.os == 'macOS'
    name: Install DOSBOX-X
    run: |
      # this install version defined by ci/dosbox-x.rb
      brew tap --force homebrew/core
      sudo cp -v ci/dosbox-x.rb $(brew --repository homebrew/core)/Formula/d/dosbox-x.rb
      brew install dosbox-x
    env:
      HOMEBREW_NO_INSTALL_FROM_API: 1
      HOMEBREW_NO_AUTO_UPDATE:      1
    shell: bash
