name: dosbox-instalation
description: 'Install DOSBOX run-time if necessary'
runs:
  using: composite
  steps:
  - if: runner.os == 'Linux'
    name: Install DOSBOX
    run: |
      for i in {1..3}
      do
        sudo apt update --fix-missing
        sudo apt-get install -y dosbox
        if [ $? = 0 ]; then
          break
        fi
      done
    shell: bash
  - if: runner.os == 'macOS'
    name: Install DOSBOX-X/DOSBOX
    run: |
      brew install dosbox-x
      brew install --cask dosbox
    shell: bash
