name: dosbox-instalation
description: 'Install DOSBOX run-time if necessary'
runs:
  using: composite
  steps:
  - if: runner.os == 'Linux'
    name: Install DOSBOX
    run: |
      for i in {1..3}
      do
        sudo apt update --fix-missing
        sudo apt-get install -y dosbox
        if [ $? = 0 ]; then
          break
        fi
      done
    shell: bash
  - if: runner.os == 'macOS'
    name: Install DOSBox-X (v2025.12.01)
    run: |
      brew tap-new local/custom --no-git
      cp ci/dosbox-x.rb "$(brew --repository local/custom)/Formula/dosbox-x.rb"
      brew install local/custom/dosbox-x
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_REQUIRE_TAP_TRUST: 1
      HOMEBREW_NO_ENV_HINTS: 1
    shell: bash
