pick( ERR_DUMMY,       "Dummy msg",    // do not delete
                       "Dummy msg" )

pick( INF_PAUSE,       "(Press return to continue)",
                       "(Press return to continue)" )

pick( INF_USE_START,   " ", " " )

pick( INF_USE_USE,     "Usage: wgml srcfile [{-|/}Newoptions] [ ( option [option ...]]",
                       "Usage: wgml srcfile [{-|/}Newoptions] [ ( option [option ...]]" )

pick( INF_USE_SRC,     "srcfile has to come first.",
                       "srcfile has to come first." )

pick( INF_USE_OP,      "Newoptions:",
                       "Newoptions:" )

pick( INF_USE_OPQ,     "-q\tQuiet, don't show product info.",
                       "-q\tQuiet, don't show product info." )

pick( INF_USE_OPR,     "-r [filename] [from [to]]",
                       "-r [filename] [from [to]]" )

pick( INF_USE_OPR1,    "\tResearch produce additional output,",
                       "\tResearch produce additional output," )

pick( INF_USE_OPR2,    "\tfilename and / or lineno range can limit the output,",
                       "\tfilename and / or lineno range can limit the output," )

pick( INF_USE_OPR3,    "\tdefault is srcfile with full line range.",
                       "\tdefault is srcfile with full line range." )

pick( INF_USE_OPR4,    "\tShow substituted lines:",
                       "\tShow substituted lines:" )

pick( INF_USE_OPSUB,   "\t>V>line with variables substituted<V<",
                       "\t>V>line with variables substituted<V<" )

pick( INF_USE_OPRES,   "\t)T)resulting text line after macro / tag processing(T(",
                       "\t)T)resulting text line after macro / tag processing(T(" )

pick( INF_USE_BL1,     " ", " " )

pick( INF_USE_OA,      "Old WGML 4.0 options start with a (",
                       "Old WGML 4.0 options start with a (" )

pick( INF_USE_OB,      "\tall tokens after ( are treated as options",
                       "\tall tokens after ( are treated as options" )

pick( INF_USE_OC,      "\toptions may be abbreviated to the UPPERcase part",
                       "\toptions may be abbreviated to the UPPERcase part" )
pick( INF_USE_BL2,     " ", " " )

pick( INF_USE_OP_ALTEXT, "ALTEXTension xxx    alternate extension",
                         "ALTEXTension xxx    alternate extension" )
pick( INF_USE_OP_BIND,   "Bind  odd [even]    bind margin(s)",
                         "Bind  odd [even]    bind margin(s)" )
pick( INF_USE_OP_CPINCH, "CPInch nn           character per inch",
                         "CPInch nn           character per inch" )
pick( INF_USE_OP_DELIM,  "DELim c             GML tag start character",
                         "DELim c             GML tag start character" )
pick( INF_USE_OP_DESCRI, "DESCription   x y z Comment in the option file",
                         "DESCription   x y z Comment in the option file" )
pick( INF_USE_OP_DEVICE, "DEVice xx           output device",
                         "DEVice xx           output device" )
pick( INF_USE_OP_DUPLEX, "DUPlex              set &sysduplex ON",
                         "DUPlex              set &sysduplex ON" )
pick( INF_USE_OP_FILE,   "FILE filename       include command (options) file",
                         "FILE filename       include command (options) file" )
pick( INF_USE_OP_FONT,   "FONT n name att space height",
                         "FONT n name att space height" )
pick( INF_USE_OP_FONTFA, "FONTFAMILY          undocumented",
                         "FONTFAMILY          undocumented" )
pick( INF_USE_OP_FORMAT, "FORMat STANDARD     only format supported",
                         "FORMat STANDARD     only format supported" )
pick( INF_USE_OP_FROM,   "FROM nn             first page to print",
                         "FROM nn             first page to print" )
pick( INF_USE_OP_INCLIS, "INCList             display include filenames",
                         "INCList             display include filenames" )
pick( INF_USE_OP_INDEX,  "INDex               produce an index",
                         "INDex               produce an index" )
pick( INF_USE_OP_LAYOUT, "LAYout filename     include layout file",
                         "LAYout filename     include layout file" )
pick( INF_USE_OP_LINEMO, "LINEmode            is standard",
                         "LINEmode            is standard" )
pick( INF_USE_OP_LLENGT, "LLength length      initial value for line length",
                         "LLength length      initial value for line length" )
pick( INF_USE_OP_LOGFIL, "LOGfile             undocumented",
                         "LOGfile             undocumented" )
pick( INF_USE_OP_LPINCH, "LPInch nn           initial lines per inch",
                         "LPInch nn           initial lines per inch" )
pick( INF_USE_OP_MAILME, "MAILMERGE           not implemented",
                         "MAILMERGE           not implemented" )
pick( INF_USE_OP_NODUPL, "NODUPlex            set &sysduplex OFF",
                         "NODUPlex            set &sysduplex OFF" )
pick( INF_USE_OP_NOINCL, "NOINCList           don't display included filenames",
                         "NOINCList           don't display included filenames" )
pick( INF_USE_OP_NOINDE, "NOINDex             don't create an index",
                         "NOINDex             don't create an index" )
pick( INF_USE_OP_NOPAUS, "NOPause             ignored",
                         "NOPause             ignored" )
pick( INF_USE_OP_NOQUIE, "NOQuiet             set &sysquiet OFF",
                         "NOQuiet             set &sysquiet OFF" )
pick( INF_USE_OP_NOSCRI, "NOSCRipt            ignored",
                         "NOSCRipt            ignored" )
pick( INF_USE_OP_NOSTAT, "NOSTATistics        don't display statistics at end",
                         "NOSTATistics        don't display statistics at end" )
pick( INF_USE_OP_NOWAIT, "NOWAIT              ignored",
                         "NOWAIT              ignored" )
pick( INF_USE_OP_NOWARN, "NOWARNing           suppress warning messages",
                         "NOWARNing           suppress warning messages" )
pick( INF_USE_OP_OUTPUT, "OUTput filename     output goes to this file",
                         "OUTput filename     output goes to this file" )
pick( INF_USE_OP_PASSES, "PASSes n            number of passes",
                         "PASSes n            number of passes" )
pick( INF_USE_OP_PAUSE,  "PAUSE               ignored",
                         "PAUSE               ignored" )
pick( INF_USE_OP_PROCES, "PROCess             ignored",
                         "PROCess             ignored" )
pick( INF_USE_OP_QUIET,  "QUIET               set &sysquiet ON",
                         "QUIET               set &sysquiet ON" )
pick( INF_USE_OP_RESETS, "RESETScreen         ignored",
                         "RESETScreen         ignored" )
pick( INF_USE_OP_SCRIPT, "SCRipt              always set",
                         "SCRipt              always set" )
pick( INF_USE_OP_SETSYM, "SETsymbol sym value set global variable sym to value",
                         "SETsymbol sym value set global variable sym to value" )
pick( INF_USE_OP_STATIS, "STATistics          display statistic at end",
                         "STATistics          display statistic at end" )
pick( INF_USE_OP_TERSE,  "TERSE               ignored",
                         "TERSE               ignored" )
pick( INF_USE_OP_TO,     "TO nn               last pagenumber to print",
                         "TO nn               last pagenumber to print" )
pick( INF_USE_OP_VALUES, "VALUESET            not implemented",
                         "VALUESET            not implemented" )
pick( INF_USE_OP_VERBOS, "VERBose             not implemented",
                         "VERBose             not implemented" )
pick( INF_USE_OP_WAIT,   "WAIT                not implemented",
                         "WAIT                not implemented" )
pick( INF_USE_OP_WARNIN, "WARNing             display warning messages",
                         "WARNing             display warning messages" )
pick( INF_USE_OP_WSCRIP, "WSCRipt             always set",
                         "WSCRipt             always set" )

pick( INF_USE_BL3,     " ", " " )

pick( INF_USE_OPTFILE, "Options can be put into an option file via ( file myopt.opt",
                       "Options can be put into an option file via ( file myopt.opt" )
pick( INF_USE_OPTFIL2, "Every line has a single option: ( option parm(s)",
                       "Every line has a single option: ( option parm(s)" )

pick( INF_USE_BL4,     " ", " " )

pick( INF_USE_ENVVAR,  "Set environment variables before calling WGML:",
                       "Set environment variables before calling WGML:" )
pick( INF_USE_GMLINC,  "\tGMLINC for include directories for included files",
                       "\tGMLINC for include directories for included files" )
pick( INF_USE_GMLLIB,  "\tGMLLIB for directories with device information files (*.cop)",
                       "\tGMLLIB for directories with device information files (*.cop)" )
pick( INF_USE_BEF_END, "Sample call: WGML mydoc.gml -r ( device ps pass 2 incl",
                       "Sample call: WGML mydoc.gml -r ( device ps pass 2 incl" )

pick( INF_USE_END,     " ", " " )

/* usage msgs start with INF_USE_START and continue thru INF_USE_END */

