#
# Makefile to create OS/2 version of WIC
#
# WMAKE             creates do2a.exp, a debugging version of wdisasm
#
#

_OS         =   PLS
opts_cc     =   -oailt -s -3r -bt=dos
opts_lnk    =   system pharlap option offset=64k
cc          =   wcc386
mem_model_prefix = f         # Flat memory model

!include ..\mif\master.mif

