// - the change font menu item and hint text

guipick(	Change_XFont_,
		"Change &Font ...",
		"jChange &Font ..." )

guipick(	Change_Font_for_this_window,
		"Change Font for this window",
		"jChange Font for this window" )

// title of a floating toolbar in a character mode application

guipick(	Floating_Toolbar,
		"Floating Toolbar",
		"jFloating Toolbar" )
// - the "Fix Tool Bar" font menu item and hint text

guipick(	XFix_Tool_Bar,
		"&Fix Tool Bar",
		"j&Fix Tool Bar" )

guipick(	Make_Tool_Bar_Fixed,
		"Make Tool Bar Fixed",
		"jMake Tool Bar Fixed" )

// - error messages (internal problems)

guipick(	Pen_Failed,
		"Could Not Create Required Pen",
		"jCould Not Create Required Pen" )

guipick(	Open_Failed,
		"Could Not Open Window",
		"jCould Not Open Window" )

// - these are the strings on the file browser dialog (in character mode apps)

guipick(	File_Name_Colon,
		"File Name:",
		"jFile Name:" )

guipick(	Directories_Colon,
		"Directories:",
		"jDirectories:" )

guipick(	OK,
		"OK",
		"OK" )

guipick(	Cancel,
		"Cancel",
                "ƒLƒƒƒ“ƒZƒ‹" )

guipick(	List_Files_of_Type_Colon,
		"List Files of Type:",
		"jList Files of Type:" )

guipick(	Drives_Colon,
		"Drives:",
		"jDrives:" )

guipick(	File_Exists_Replace,
		"\nThis file already exists.\n\nReplace existing file?\n",
		"j\nThis file already exists.\n\nReplace existing file?\n" )

guipick(	FDlg_Save_Text,
		"Save",
		"jSave" )

guipick(	FDlg_Open_Text,
		"Open",
		"jOpen" )

// - these are the strings on the system menu (for character mode apps)

guipick(	Restore,
		"Restore",
		"jRestore" )

guipick(	Move,
		"Move",
		"jMove" )

guipick(	Size,
		"Size",
		"jSize" )

guipick(	Minimize,
		"Minimize",
		"jMinimize" )

guipick(	Maximize,
		"Maximize",
		"jMaximize" )

guipick(	Close,
		"Close",
		"jClose" )

// these are menu items from the system menu of an MDI child window

guipick(	NexXt,
		"Nex&t",
		"jNex&t" )

guipick(	XClose,
		"&Close",
		"j&Close" )

// these are elements of the Window menu for character mode apps

guipick(	XCascade,
		"&Cascade",
		"j&Cascade" )

guipick(	Tile_XHorz,
		"Tile &Horizontally",
		"jTile &Horizontally" )

guipick(	Tile_XVert,
		"Tile &Vertically",
		"jTile &Vertically" )

guipick(	XArrange_Icons,
		"&Arrange Icons",
		"j&Arrange Icons" )

guipick(	XMore_Windows,
		"&More Windows ...",
		"j&More Windows ..." )

guipick(	Cascade_Hint,
		"Arrange all windows in a cascaded fashion",
		"jArrange all windows in a cascaded fashion" )

guipick(	Tile_Horz_Hint,
		"Arrange all windows in a horizontally tiled fashion",
		"jArrange all windows in a horizontally tiled fashion" )

guipick(	Tile_Vert_Hint,
		"Arrange all windows in a vertically tiled fashion",
		"jArrange all windows in a vertically tiled fashion" )

guipick(	Arrange_Icons_Hint,
		"Arrange all icons in rows",
		"jArrange all icons in rows" )

guipick(	More_Windows_Hint,
		"Show a list of all windows",
		"jShow a list of all windows" )

guipick(	Window_Name_Hint,
		"Go to Window ",
		"jGo to Window " )

guipick(	Select_Window,
		"Select Window",
		"jSelect Window" )

// - this is a menu item on a floating toolbar window in a character mode app

guipick(	XFix_Toolbar,
		"&Fix Toolbar",
		"j&Fix Toolbar" )

guipick(	Fix_Toolbar_Hint,
		"Make toolbar buttons into menus",
		"jMake toolbar buttons into menus" )

// - These are strings for character mode message boxes

guipick(	XAbort,
		"&Abort",
		"j&Abort" )

guipick(	XIgnore,
		"&Ignore",
		"j&Ignore" )

guipick(	XNo,
		"&No",
		"j&No" )

guipick(	XRetry,
		"&Retry",
		"j&Retry" )

guipick(	XYes,
		"&Yes",
		"j&Yes" )

guipick(	Stop_Bang,
		"Stop!",
		"jStop!" )

guipick(	Exclamation,
		"!",
		"!" )


// - these are elements of the get colour dialog for character mode apps

guipick(	Colour,
		"Colour",
		"jColour" )

guipick(	Black,
		"Black",
		"jBlack" )

guipick(	Blue,
		"Blue",
		"jBlue" )

guipick(	Green,
		"Green",
		"jGreen" )

guipick(	Cyan,
		"Cyan",
		"jCyan" )

guipick(	Red,
		"Red",
		"jRed" )

guipick(	Magenta,
		"Magenta",
		"jMagenta" )

guipick(	Brown,
		"Brown",
		"jBrown" )

guipick(	White,
		"White",
		"jWhite" )

guipick(	Grey,
		"Grey",
		"jGrey" )

guipick(	BrightBlue,
		"Bright Blue",
		"jBright Blue" )

guipick(	BrightGreen,
		"Bright Green",
		"jBright Green" )

guipick(	BrightCyan,
		"Bright Cyan",
		"jBright Cyan" )

guipick(	BrightRed,
		"Bright Red",
		"jBright Red" )

guipick(	BrightMagenta,
		"Bright Magenta",
		"jBright Magenta" )

guipick(	BrightYellow,
		"Bright Yellow",
		"jBright Yellow" )

guipick(	BrightWhite,
		"Bright White",
		"jBright White" )

guipick(	Table_of_Contents,
		"table of contents",
		"jtable of contents" )
		

// - DO NOT TRANSLATE anything from here on down.

guipick(	ApplIcon,
		"ApplIcon",
		"jApplIcon" )
		

guipick(	Empty,
		"",
		"" )


guipick(	Blank,
		" ",
		" " )

guipick(	Windows_Dialog_Font,
		"Helv.8",
		"‚l‚r –¾’©.10" )

guipick(	OS2_Dialog_Font,
		"System Proportional.10",
		"" )
		
//Note:	This is a special msg that marks the end of GUI msgs
//	and it MUST be the last message in this file!!

guipick(	Internal_Last_Message,
		"Last",
		"Last" )
