#pmake: os_nt cpu_axp axp
#
# WATCOM Debugger makefile for NT (character mode)
#

host_cpu=axp
host_os=nt

sysobjs =   &
    autoenv.obj &
    ntinit.obj &
    ntscrn.obj &
    ntfilio.obj &
    ntfinfo.obj &
    ntcmd.obj &
    winchk.obj &
    winlkup.obj

!include ../../master.mif
