pick( ALIAS_VALUE_MUST_BE_INT,
	"The value field must contain an integer",
	"The value field must contain an integer" )
pick( ALIAS_NO_SPACES_ALLOWED,
	"The current text field must not contain spaces",
	"The current text field must not contain spaces" )
pick( ALIAS_NO_DUPLICATES_ALLOWED,
	"The alias \"%s\" has aready been assigned to id %08lX.  Please choose a unique alias.",
	"The alias \"%s\" has aready been assigned to id %08lX.  Please choose a unique alias." )


