pick( MWND_DISP_BYTES,
	"Data displayed as bytes",
	"Data displayed as bytes" )
pick( MWND_DISP_WORDS,
	"Data displayed as words",
	"Data displayed as words" )
pick( MWND_DISP_DWORDS,
	"Data displayed as dwords",
	"Data displayed as dwords" )
pick( MWND_DISP_CODE_16,
	"Data displayed as 16 bit code",
	"Data displayed as 16 bit code" )
pick( MWND_DISP_CODE_32,
	"Data displayed as 32 bit code",
	"Data displayed as 32 bit code" )
pick( MWND_MEM_DMP_CREATED,
	"Memory dump created:   %s\n%n",
	"Memory dump created:   %s\n%n" )
pick( MWND_DPMI_ITEM,
	"This is a DPMI item\n\n",
	"This is a DPMI item\n\n" )
pick( MWND_SELECTOR,
	"Selector:    \t%04X\n%n",
	"Selector:    \t%04X\n%n" )
pick( MWND_BASE,
	"Base:        \t%08lX\n%n",
	"Base:        \t%08lX\n%n" )
pick( MWND_LIMIT,
	"Limit:       \t%08lX\n%n",
	"Limit:       \t%08lX\n%n" )
pick( MWND_TYPE_DATA,
	"Type         \tdata\n%n",
	"Type         \tdata\n%n" )
pick( MWND_TYPE_CODE,
	"Type         \tcode\n%n",
	"Type         \tcode\n%n" )
pick( MWND_GRANULARITY_PAGE,
	"Granularity: \tpage\n%n",
	"Granularity: \tpage\n%n" )
pick( MWND_GRANULARITY_BYTE,
	"Granularity: \tbyte\n%n",
	"Granularity: \tbyte\n%n" )
pick( MWND_ACCESS,
	"Access:      \t%s\n\n%n",
	"Access:      \t%s\n\n%n" )
pick( MWND_BLOCK_ADDR,
	"\nBlock Address:   \t%08lX\n%n",
	"\nBlock Address:   \t%08lX\n%n" )
pick( MWND_BLOCK_HDL,
	"Block Handle:    \t%04X\n%n",
	"Block Handle:    \t%04X\n%n" )
pick( MWND_BLOCK_SIZE,
	"Block Size:      \t%04lX\n%n",
	"Block Size:      \t%04lX\n%n" )
pick( MWND_LOCK_CNT,
	"Lock Count:      \t%04X\n%n",
	"Lock Count:      \t%04X\n%n" )
pick( MWND_PAGE_LOCK_CNT,
	"Page Lock Count: \t%04X\n\n%n",
	"Page Lock Count: \t%04X\n\n%n" )
pick( MWND_ENTER_NUMERIC_VALUE,
	"You must enter a numeric value.\n(Prefix hex values with 0x)",
	"You must enter a numeric value.\n(Prefix hex values with 0x)" )
pick( MWND_OFFSET_TOO_BIG,
	"The offset is beyond the end of the object.\nPlease choose a smaller offset.",
	"The offset is beyond the end of the object.\nPlease choose a smaller offset." )
pick( MWND_OFFSET_TOO_SMALL,
	"The offset is before the beginning of the object.\nPlease choose a larger offset.",
	"The offset is before the beginning of the object.\nPlease choose a larger offset." )
pick( MWND_DATA,
	"data",
	"data" )
pick( MWND_CODE,
	"code",
	"code" )
pick( MWND_PAGE,
	"page",
	"page" )
pick( MWND_BYTE,
	"byte",
	"byte" )
pick( MWND_MEM_DISP_FOR_SEL_X,
	"Memory Display for selector %04X",
	"Memory Display for selector %04X" )
pick( MWND_MEM_DISP_FOR_HDL_X,
	"Memory Display for handle %04X",
	"Memory Display for handle %04X" )
pick( MWND_CANT_DISP_MEM_WND,
	"Unable to display memory display window\n(probable cause: lack of memory)",
	"Unable to display memory display window\n(probable cause: lack of memory)" )
