#pmake: build trap remote os_os2 cpu_i86 cpu_386 vdm x86

tree_depth = 4

host_cpu = 386
host_os  = os2

target_cpu = x86

srv   = vdm
which = TRAP
remote_link = 1

extra_cflags = -d2

!include $(trap_dir)/master.mif
