#pmake: build trap remote os_os2 cpu_i86 cpu_386 vdm x86
host_CPU = 386
host_OS = os2

os  = os2v2
srv = vdm
cpu = x86
which = TRAP
type  = remote_link

extra_cflags = -d2
extra_objs = vdmcli2.obj

!include $(trap_dir)/master.mif
