#pmake: build trap remote os_os2 cpu_i86 cpu_386 vdm x86
host_cpu = 386
host_os  = os2

os    = os2v2
srv   = vdm
cpu   = x86
which = TRAP
remote_link = 1

extra_cflags = -d2
extra_objs = vdmcli2.obj

!include $(trap_dir)/master.mif
