#pmake: os_qnx cpu_386 flat
#
# plibmt3s -- 32-bit 3s PLIB multi-thread
#
processor  = 386
system     = qnx
model      = ms
convention = stack
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/runtime/plib.mif
