pick( MSG_NO_TIME_STAMP,	"no time-stamp for (%s) -- will use current time",
				"(%s)のタイム・スタンプがありません -- 現在の時間を使用します" )
pick( MSG_NO_DATE,		"no date specified for 'd' option",
				"'d'オプションで日付けが指定されていません" )
pick( MSG_NO_FILE,		"no file specified for 'f' option",
				"'f'オプションでファイルが指定されていません" )
pick( MSG_NO_TIME,		"no time specified for 't' option",
				"'t'オプションで時間が指定されていません" )
pick( MSG_UNKNOWN_OPTION,	"unknown option: %s",
				"無効なオプション: %s" )
pick( MSG_CANT_TOUCH,		"unable to touch (%s): %Z",
				"(%s)をタッチできません: %Z" )
pick( MSG_READ_ONLY,		"unable to touch (%s): %Z (file is read-only)",
				"(%s)をタッチできません: %Z(ファイルがリード・オンリです)" )
pick( MSG_ERR_CLOSE,		"system error closing (%s): %Z",
				"(%s)クローズ・システム・エラー: %Z" )
pick( MSG_NO_MATCH,		"no matching files found for (%s)",
				"(%s)と一致するファイルがありません" )
pick( MSG_CANT_CREATE,		"unable to create file (%s): %Z",
				"(%s)ファイルを作成できません: %Z" )
pick( MSG_CANT_TOUCH_FILE,	"unable to touch file (%s): %Z",
				"(%s)ファイルにタッチできません: %Z" )
pick( MSG_INV_TIME,		"invalid character ('%s') in time",
				"時間で無効な文字('%s')があります" )
pick( MSG_INV_HOUR,		"invalid hour specified in time",
				"時間で無効な時数を指定しました" )
pick( MSG_INV_MINUTE,		"invalid minute specified in time",
				"時間で無効な分数を指定しました" )
pick( MSG_INV_SECOND,		"invalid second specified in time",
				"時間で無効な秒数を指定しました" )
pick( MSG_INV_DATE,		"invalid character ('%s') in date",
				"日付で無効な文字('%s')があります" )
pick( MSG_INV_YEAR,		"invalid year specified in date",
				"日付で無効な年を指定しました" )
pick( MSG_INV_MONTH,		"invalid month specified in date",
				"日付で無効な月を指定しました" )
pick( MSG_INV_DAY,		"invalid day specified in date",
				"日付で無効な日を指定しました" )
pick( MSG_SYS_ERR_0,		"Error 0",
				"エラー 0" )
pick( MSG_SYS_ERR_1,		"No such file or directory",
				"指定されたファイル又はディレクトリがありません" )
pick( MSG_SYS_ERR_2,		"Argument list too big",
				"引数リストが大きすぎます" )
pick( MSG_SYS_ERR_3,		"Exec format error",
				"実行フォーマット・エラー" )
pick( MSG_SYS_ERR_4,		"Bad file number",
				"ファイル番号が間違っています" )
pick( MSG_SYS_ERR_5,		"Not enough memory",
				"メモリが足りません" )
pick( MSG_SYS_ERR_6,		"Permission denied",
				"パーミッション拒否されました" )
pick( MSG_SYS_ERR_7,		"File exists",
				"ファイルが存在しています" )
pick( MSG_SYS_ERR_8,		"Cross-device link",
				"デバイスを変更しました" )
pick( MSG_SYS_ERR_9,		"Invalid argument",
				"無効な引数です" )
pick( MSG_SYS_ERR_10,		"File table overflow",
				"ファイル・テーブルがオーバフローしました" )
pick( MSG_SYS_ERR_11,		"Too many open files",
				"オープン・ファイルが多すぎます" )
pick( MSG_SYS_ERR_12,		"No space left on device",
				"デバイスにスペースがありません" )
pick( MSG_SYS_ERR_13,		"Argument too large",
				"引数が大きすぎます" )
pick( MSG_SYS_ERR_14,		"Result too large",
				"結果が大きすぎます" )
pick( MSG_SYS_ERR_15,		"Resource deadlock would occur",
				"リソースのデッドロックが発生します" )
pick( MSG_USAGE_DATE_FORM,	"where: <date> is of the form \"%s\"",
				"場所:  <日付> は\"%s\"フォームにあります" )
pick( MSG_USAGE_TIME_FORM,	"       <time> is of the form \"%s\"",
				"       <時間> は\"%s\"フォームにあります" )
pick( MSG_USAGE_AM_PM_0,	"       (<time> may be followed by either 'a' or 'p'",
				"       (<時間> は'a'か'p'の後に続きます" )
pick( MSG_USAGE_AM_PM_1,	"        indicating A.M. or P.M. respectively)",
				"        A.M.かP.M.をそれぞれ示します)" )
