type = win
os = w386
build_target = windows
sys = win386
compiler = comp386
model = f
xflags=-zw

target : sample.exe .SYMBOLIC
    @%null

samp2 : samp2.exe  .SYMBOLIC
    @%null

!include ../makefile
