#pmake: os_linux cpu_mps mips
#
# Open Watcom Debugger makefile for MIPS Linux
#

host_os  = linux
host_cpu = mps

syshdir =

sysobjs = &
    linuxcmd.obj &
    linuxio.obj &
    lnxinit.obj &
    lnxscrn.obj &
    lnxlkup.obj &
    lnxchk.obj

!include ../../master.mif
