#pmake: build large cpu_i86 os_win
processor  = 086
system     = windows
model      = ml
linkage    = static
subdir     = ml

define_library_include = $(cpplib_dir)/pliblibs.mif
!include $(cpplib_dir)/mrglib.mif
