#pmake: build compact cpu_i86 os_win
#
# plibc -- 16-bit compact memory-model PLIB for Windows
#
processor  = 086
system     = windows
model      = mc
linkage    = static
define_library_include = $(cpplib_dir)/runtime/plib.mif
!include $(cpplib_dir)/mklib.mif
