#pmake: build small cpu_i86 os_dos os_os2 os_win os_qnx
#
# cplx7s.lib -- small memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = ms
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
