#pmake: build small cpu_i86 os_osi
#
# cplx7s.lib -- small memory-model COMPLEX library fpi
#
processor  = 087
system     = generic
model      = ms
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
