#pmake: build os_dos cpu_386 386 intel
#
# Open Watcom Debugger makefile for dsx
#

host_os  = dos
host_cpu = 386

syshdir = ../h;../../dos/h

sysobjs =   &
    dsxfork.obj &
    dsxstart.obj &
    dsxchk.obj &
    dsxcmd.obj &
    dsxfilio.obj &
    dsxscrn.obj &
    dsxlkup.obj &
    dsxhdlr.obj &
    dsxmem.obj


!include ../../master.mif
