// the following is the font used in the status bar of the window
pick(   WDE_STATUSFONT,
        "Helv.8",
        "Helv.8" )

// this is a default font used for the edit window
pick(   WDE_EDITWINDOWFONT,
        "Helv.8",
        "Helv.8" )

// this is a default font used for the base object
pick(   WDE_BASEOBJECTFONT,
        "Helv.8",
        "Helv.8" )

// WDEMSGBX.C
pick(   WDE_MSGBOXTITLE,
        "Open Watcom Dialog Editor",
        "Open Watcom Dialog Editor" )

// WRESTAT.C
pick(   WDE_NOCREATESTATUS,
        "Could not create status line.",
        "Could not create status line." )
pick(   WDE_READYMSG,
        "Ready",
        "Ready" )

// WREHINTS.C
pick(   WDE_HINT_NEW_RES,
        "Create a new resource.",
        "Create a new resource." )
pick(   WDE_HINT_OPEN_RES,
        "Open a file.",
        "Open a file." )
pick(   WDE_HINT_SAVE_RES,
        "Save this file.",
        "Save this file." )
pick(   WDE_HINT_SAVEAS_RES,
        "Save this file to a different file.",
        "Save this file to a different file." )
pick(   WDE_HINT_MS_CUSTOM,
        "Load a Microsoft custom control.",
        "Load a Microsoft custom control." )
pick(   WDE_HINT_BOR_CUSTOM,
        "Load a Borland custom control library.",
        "Load a Borland custom control library." )
pick(   WDE_HINT_LOADLIB,
        "Load a Windows DLL.",
        "Load a Windows DLL." )
pick(   WDE_HINT_SELCUST1,
        "Select custom control one.",
        "Select custom control one." )
pick(   WDE_HINT_SELCUST2,
        "Select custom control two.",
        "Select custom control two." )
pick(   WDE_HINT_LOAD_SYMBOLS,
        "Load symbols from a file.",
        "Load symbols from a file." )
pick(   WDE_HINT_VIEW_SYMBOLS,
        "Edit symbols.",
        "Edit symbols." )
pick(   WDE_HINT_WRITE_SYMBOLS,
        "Write symbols to a file.",
        "Write symbols to a file." )
pick(   WDE_HINT_EXIT,
        "Exit the Open Watcom Dialog Editor.",
        "Exit the Open Watcom Dialog Editor." )
pick(   WDE_HINT_SAME_WIDTH,
        "Change the width of selected objects.",
        "Change the width of selected objects." )
pick(   WDE_HINT_SAME_HEIGHT,
        "Change the height of selected objects.",
        "Change the height of selected objects." )
pick(   WDE_HINT_SAME_SIZE,
        "Change the size of selected objects.",
        "Change the size of selected objects." )
pick(   WDE_HINT_SPACE_HORZ,
        "Move selected objects so that they are spaced evenly in the horizontal direction.",
        "Move selected objects so that they are spaced evenly in the horizontal direction." )
pick(   WDE_HINT_SPACE_VERT,
        "Move selected objects so that they are spaced evenly in the vertical direction.",
        "Move selected objects so that they are spaced evenly in the vertical direciton." )
pick(   WDE_HINT_SIZETOTEXT,
        "Size the selected control to its text.",
        "Size the selected control to its text." )
pick(   WDE_HINT_GOTO_OBJECT,
        "Scroll the current object into view.",
        "Scroll the current object into view." )
pick(   WDE_HINT_DEFINEOBJECT,
        "Modify object attributes.",
        "Modify object attributes." )
pick(   WDE_HINT_GEN_DEFINEOBJECT,
        "Advanced modify object attributes.",
        "Advanced modify object attributes." )
pick(   WDE_HINT_OPTIONS,
        "Set program options.",
        "Set program options." )
pick(   WDE_HINT_SELECT_DIALOG,
        "Select dialog(s) from a resource.",
        "Select dialog(s) from a resource." )
pick(   WDE_HINT_REMOVE_DIALOG,
        "Remove dialog(s) from a resource.",
        "Remove dialog(s) from a resource." )
pick(   WDE_HINT_DIALOG_RESTORE,
        "Revert dialog to state after last save operation.",
        "Revert dialog to state after last save operation." )
pick(   WDE_HINT_DIALOG_NEW,
        "Create a new dialog.",
        "Create a new dialog." )
pick(   WDE_HINT_DIALOG_SAVE,
        "Save this dialog.",
        "Save this dialog." )
pick(   WDE_HINT_DIALOG_SAVEAS,
        "Save this dialog to a different file.",
        "Save this dialog to a different file." )
pick(   WDE_HINT_DIALOG_SAVEINTO,
        "Copy this dialog into a different file.",
        "Copy this dialog into a different file." )
pick(   WDE_HINT_TEST_MODE,
        "Test the current dialog.",
        "Test the current dialog." )
pick(   WDE_HINT_SET_ORDER,
        "Order the controls in the current dialog.",
        "Order the controls in the current dialog." )
pick(   WDE_HINT_SET_TABS,
        "Set tab stops in the current dialog.",
        "Set tab stops in the current dialog." )
pick(   WDE_HINT_SET_GROUPS,
        "Set groups in the current dialog.",
        "Set groups in the current dialog." )
pick(   WDE_HINT_SELECT_MODE,
        "Use pointer to select objects.",
        "Use pointer to select objects." )
pick(   WDE_HINT_DIALOG_TOOL,
        "Use pointer to create a dialog.",
        "Use pointer to create a dialog." )
pick(   WDE_HINT_PBUTTON_TOOL,
        "Use pointer to create a push button.",
        "Use pointer to create a push button." )
pick(   WDE_HINT_CBUTTON_TOOL,
        "Use pointer to create a check box.",
        "Use pointer to create a check box." )
pick(   WDE_HINT_RBUTTON_TOOL,
        "Use pointer to create a radio button.",
        "Use pointer to create a radio button." )
pick(   WDE_HINT_GBUTTON_TOOL,
        "Use pointer to create a group box.",
        "Use pointer to create a group box." )
pick(   WDE_HINT_FRAME_TOOL,
        "Use pointer to create a frame.",
        "Use pointer to create a frame." )
pick(   WDE_HINT_TEXT_TOOL,
        "Use pointer to create text.",
        "Use pointer to create text." )
pick(   WDE_HINT_ICON_TOOL,
        "Use pointer to create an icon.",
        "Use pointer to create an icon." )
pick(   WDE_HINT_EDIT_TOOL,
        "Use pointer to create an edit box.",
        "Use pointer to create an edit box." )
pick(   WDE_HINT_LISTBOX_TOOL,
        "Use pointer to create a list box.",
        "Use pointer to create a list box." )
pick(   WDE_HINT_COMBOBOX_TOOL,
        "Use pointer to create a combo box.",
        "Use pointer to create a combo box." )
pick(   WDE_HINT_HSCROLL_TOOL,
        "Use pointer to create a horizontal scroll bar.",
        "Use pointer to create a horizontal scroll bar." )
pick(   WDE_HINT_VSCROLL_TOOL,
        "Use pointer to create a vertical scroll bar.",
        "Use pointer to create a vertical scroll bar." )
pick(   WDE_HINT_SIZEBOX_TOOL,
        "Use pointer to create a size box.",
        "Use pointer to create a size box." )
pick(   WDE_HINT_STATUSBAR_TOOL,
        "Use pointer to create a status bar.",
        "Use pointer to create a status bar." )
pick(   WDE_HINT_LISTVIEW_TOOL,
        "Use pointer to create a list view.",
        "Use pointer to create a list view." )
pick(   WDE_HINT_TREEVIEW_TOOL,
        "Use pointer to create a tree view.",
        "Use pointer to create a tree view." )
pick(   WDE_HINT_TABCNTL_TOOL,
        "Use pointer to create a tab control.",
        "Use pointer to create a tab control." )
pick(   WDE_HINT_ANIMATE_TOOL,
        "Use pointer to create an animation control.",
        "Use pointer to create an animation control." )
pick(   WDE_HINT_UPDOWN_TOOL,
        "Use pointer to create an up/down control.",
        "Use pointer to create an up/down control." )
pick(   WDE_HINT_TRACKBAR_TOOL,
        "Use pointer to create a trackbar.",
        "Use pointer to create a trackbar." )
pick(   WDE_HINT_PROGRESS_TOOL,
        "Use pointer to create a progress bar.",
        "Use pointer to create a progress bar." )
pick(   WDE_HINT_HOTKEY_TOOL,
        "Use pointer to create a hot key control.",
        "Use pointer to create a hot key control." )
pick(   WDE_HINT_HEADER_TOOL,
        "Use pointer to create a header control.",
        "Use pointer to create a header control." )
pick(   WDE_HINT_CUSTOM1_TOOL,
        "Use pointer to create custom control one.",
        "Use pointer to create custom control one." )
pick(   WDE_HINT_CUSTOM2_TOOL,
        "Use pointer to create custom control two.",
        "Use pointer to create custom control two." )
pick(   WDE_HINT_STICKY_TOOLS,
        "Toggle select mode after create.",
        "Toggle select mode after create." )
pick(   WDE_HINT_SHOW_TOOLS,
        "Show/hide the toolbox.",
        "Show/hide the toolbox." )
pick(   WDE_HINT_SHOW_RIBBON,
        "Show/hide the toolbar.",
        "Show/hide the toolbar." )
pick(   WDE_HINT_MDI_CASCADE,
        "Cascade resource windows.",
        "Cascade resource windows." )
pick(   WDE_HINT_MDI_TILEH,
        "Tile resource windows horizontally.",
        "Tile resource windows horizontally." )
pick(   WDE_HINT_MDI_TILEV,
        "Tile resource windows vertically.",
        "Tile resource windows vertically." )
pick(   WDE_HINT_MDI_ARRANGE,
        "Arrange resource icons.",
        "Arrange resource icons." )
pick(   WDE_HINT_ABOUT,
        "Display program information.",
        "Display program information." )
pick(   WDE_HINT_HELP,
        "List Open Watcom Dialog Editor help topics.",
        "List Open Watcom Dialog Editor help topics." )
pick(   WDE_HINT_HELP_SEARCH,
        "Search for help on a specific topic.",
        "Search for help on a specific topic." )
pick(   WDE_HINT_HELP_ON_HELP,
        "Display information on how to use help.",
        "Display information on how to use help." )
pick(   WDE_HINT_DELETEOBJECT,
        "Delete selected object(s).",
        "Delete selected object(s)." )
pick(   WDE_HINT_CUTOBJECT,
        "Cut selected object(s) to clipboard.",
        "Cut selected object(s) to clipboard." )
pick(   WDE_HINT_PASTEOBJECT,
        "Paste object(s) from clipboard.",
        "Paste object(s) from clipboard." )
pick(   WDE_HINT_COPYOBJECT,
        "Copy selected object(s) to clipboard.",
        "Copy selected object(s) to clipboard." )
pick(   WDE_HINT_FMLEFT,
        "Align the left sides of selected objects.",
        "Align the left sides of selected objects." )
pick(   WDE_HINT_FMHCENTRE,
        "Align the horizontal centres of selected objects.",
        "Align the horizontal centres of selected objects." )
pick(   WDE_HINT_FMRIGHT,
        "Align the right sides of selected objects.",
        "Align the right sides of selected objects." )
pick(   WDE_HINT_FMTOP,
        "Align the tops of the selected objects.",
        "Align the tops of the selected objects." )
pick(   WDE_HINT_FMVCENTRE,
        "Align the vertical centres of the selected objects.",
        "Align the vertical centres of the selected objects." )
pick(   WDE_HINT_FMBOTTOM,
        "Align the bottoms of the selected objects.",
        "Align the bottoms of the selected objects." )
pick(   WDE_HINT_DDE_CLEAR,
        "Clear the resource of all the displayed objects.",
        "Clear the resource of all the displayed objects." )
pick(   WDE_HINT_DDE_UPDATE_PRJ,
        "Update the file with this dialog.",
        "Update the file with this dialog." )
pick(   WDE_HINT_FILEMENU,
        "Create or open a new file.",
        "Create or open a new file." )
pick(   WDE_HINT_LOADCUSTMENU,
        "Load custom controls.",
        "Load custom controls." )
pick(   WDE_HINT_EDITSYMMENU,
        "Load, edit, or write symbols.",
        "Load, edit, or write symbols." )
pick(   WDE_HINT_EDITMENU,
        "Modify, align, or select objects.",
        "Modify, align, or select objects." )
pick(   WDE_HINT_ALIGNMENU,
        "Align selected objects.",
        "Align selected objects." )
pick(   WDE_HINT_SIZEMENU,
        "Size selected objects.",
        "Size selected objects." )
pick(   WDE_HINT_SPACEMENU,
        "Move selected objects so that they are spaced evenly.",
        "Move selected objects so that they are spaced evenly." )
pick(   WDE_HINT_DIALOGMENU,
        "Test, revert, or save dialogs.",
        "Test, revert, or save dialogs." )
pick(   WDE_HINT_CONTROLMENU,
        "Select objects to create.",
        "Select objects to create." )
pick(   WDE_HINT_COMMCONTROLMENU,
        "Select common control objects to create.",
        "Select common control objects to create." )
pick(   WDE_HINT_WINDOWMENU,
        "Manipulate windows.",
        "Manipulate windows." )
pick(   WDE_HINT_HELPMENU,
        "Display help.",
        "Display help." )
pick(   WDE_HINT_DDEFILEMENU,
        "Clear or update a new file.",
        "Clear or update a new file." )
pick(   WDE_HINT_MDIMSG,
        "Switch to Resource #%d.",
        "Switch to Resource #%d." )

// WDETOOLB.C
pick(   WDE_SYSMENUMOVE,
        "Move",
        "Move" )
pick(   WDE_SYSMENUSIZE,
        "Size",
        "Size" )
pick(   WDE_SYSMENUHIDE,
        "Hide",
        "Hide" )

// WDERIBBN.C
pick(   WDE_SHOWTOOLBAR,
        "Show Tool&bar",
        "Show Tool&bar" )
pick(   WDE_HIDETOOLBAR,
        "Hide Tool&bar",
        "Hide Tool&bar" )

// WDECTOOL.C
pick(   WDE_TOOLBOXCAPTION,
        "Tools",
        "Tools" )
pick(   WDE_CREATINGTOOLBOX,
        "Creating Toolbox...",
        "Creating Toolbox..." )
pick(   WDE_HIDETOOLBOX,
        "Hide &Toolbox",
        "Hide &Toolbox" )
pick(   WDE_SHOWTOOLBOX,
        "Show &Toolbox",
        "Show &Toolbox" )

// WDETEST.C
pick(   WDE_TESTMODE,
        "Test Mode",
        "Test Mode" )
pick(   WDE_TESTITEM,
        "Item %02.2d",
        "Item %02.2d" )

// WDEALIGN.C
pick(   WDE_OBJECTCANTBESIZED,
        "One of the objects can't be sized",
        "One of the objects can't be sized" )
pick(   WDE_ALLMUSTHAVESAMEPARENT,
        "All objects must have same parent",
        "All objects must have same parent" )
pick(   WDE_OBJECTCANTBEMOVED,
        "One of the objects can't be moved",
        "One of the objects can't be moved" )

// WDEOPTS.C
pick(   WDE_DISPLAYOPTIONS,
        "Display Options",
        "Display Options" )

// WDEDDE.C
pick(   WDE_DDEDEATHMSG,
        "The Dialog Editor is being terminated and \nwas unable to inform the Resource Editor.\nThis may cause the Resource Editor to reject\nany more attempts to edit any resources.\n",
        "The Dialog Editor is being terminated and \nwas unable to inform the Resource Editor.\nThis may cause the Resource Editor to reject\nany more attempts to edit any resources.\n" )

// WDEMAIN.C
pick(   WDE_APPTITLE,
        "Open Watcom Dialog Editor",
        "Open Watcom Dialog Editor" )
pick(   WDE_NOMULTIPLEINSTANCES,
        "Cannot run multiple instances of the Open Watcom Dialog Editor.",
        "Cannot run multiple instances of the Open Watcom Dialog Editor." )
pick(   WDE_INITFAILED,
        "Initialization Failed!",
        "Initialization Failed!" )
pick(   WDE_DDEINITFAILED,
        "DDE Initialization Failed!",
        "DDE Initialization Failed!" )
pick(   WDE_EXCEPTIONDURINGABNORMALEXIT,
        "Exception during abnormal termination",
        "Exception during abnormal termination" )
pick(   WDE_NOREGISTERMAINCLASS,
        "WdeInit: Couldn't register Main window class!",
        "WdeInit: Couldn't register Main window class!" )
pick(   WDE_NOREGISTEREDITCLASS,
        "WdeInit: WdeRegisterEditClass failed!",
        "WdeInit: WdeRegisterEditClass failed!" )
pick(   WDE_NOREGISTERRESCLASS,
        "WdeInit: WdeRegisterResClass failed!",
        "WdeInit: WdeRegisterResClass failed!" )
pick(   WDE_NOREGISTERTAGCLASS,
        "WdeInit: WdeRegisterTagClass failed!",
        "WdeInit: WdeRegisterTagClass failed!" )
pick(   WDE_NOINITCONTROLOBJECTS,
        "Could not initialize control objects!",
        "Could not initialize control objects!" )
pick(   WDE_LOADACCELFAILED,
        "Could not load accelerator table!",
        "Could not load accelerator table!" )
pick(   WDE_NOCREATEMAINWINDOW,
        "Could not create main window!",
        "Could not create main window!" )
pick(   WDE_NOCREATEINFOWINDOW,
        "Could not create Info window!",
        "Could not create Info window!" )
pick(   WDE_NOCREATESTATUSLINE,
        "Could not create status line!",
        "Could not create status line!" )
pick(   WDE_NOINITMENUS,
        "Could not initalize menus!",
        "Could not initalize menus!" )
pick(   WDE_NOINITHINTS,
        "Could not initalize hints!",
        "Could not initalize hints!" )
pick(   WDE_NOCREATETOOLBOX,
        "Could not create tools toolbox!",
        "Could not create tools toolbox!" )
pick(   WDE_NOCREATEMDICLIENT,
        "Could not create MDI Client window!",
        "Could not create MDI Client window!" )
pick(   WDE_ONLYONEINSTANCE,
        "Only one instance allowed.",
        "Only one instance allowed." )
pick(   WDE_PASTINGNOTVALID,
        "Pasting is not valid now!",
        "Pasting is not valid now!" )
pick(   WDE_SETFAILED,
        "Current custom control not set.",
        "Current custom control not set." )
pick(   WDE_INPUTFILENOTFOUND,
        "Input file not found.",
        "Input file not found." )
pick(   WDE_ABOUT_NAME,
        "Open Watcom Dialog Editor for Windows",
        "Open Watcom Dialog Editor for Windows" )
pick(   WDE_ABOUT_COPYRIGHT_YEAR,
        "1984",
        "1984" )
pick(   WDE_ABOUT_TITLE,
        "About Open Watcom Dialog Editor",
        "About Open Watcom Dialog Editor" )

// WDEFUTIL.C
pick(   WDE_DEFININGCONTROL,
        "Defining Control",
        "Defining Control" )

// WDEINFO.C
pick(   WDE_INFOCAPTIONTEXT,
        "&Caption:",
        "&Caption:" )
pick(   WDE_INFODLGNAMETEXT,
        "&Dlg Name:",
        "&Dlg Name:" )
pick(   WDE_INFOTEXTTEXT,
        "&Text:",
        "&Text:" )
pick(   WDE_INFOIDTEXT,
        "&ID:",
        "&ID:" )

// WDEFDIAG.C
pick(   WDE_DEFAULTDIALOGCAPTION,
        "Dialog",
        "Dialog" )
pick(   WDE_DEFAULTDIALOGFONT,
        "Helv.8",
        "Helv.8" )
pick(   WDE_DEFDIALOGNAME,
        "DIALOG_%d",
        "DIALOG_%d" )
pick(   WDE_DEFININGDIALOG,
        "Defining Dialog",
        "Defining Dialog" )
pick(   WDE_DIALOGFULL,
        "No more controls can fit in this dialog.",
        "No more controls can fit in this dialog." )
pick(   WDE_UNDEFINEDCLASS,
        "This dialog uses an undefined class. ",
        "This dialog uses an undefined class. " )

// WDEGETFN.C
pick(   WDE_ERRORSELECTINGFILE,
        "An error occurred selecting the file.",
        "An error occurred selecting the file." )
pick(   WDE_GETFNCOMBOTITLE,
        "List Files of &Type",
        "List Files of &Type" )

// WDEDEFIN.C
pick(   WDE_GENERICDEFINE,
        "Advanced Define",
        "Advanced Define" )
pick(   WDE_GENERICNAME,
        "&Name:",
        "&Name:" )
pick(   WDE_GENERICTEXT,
        "&Text:",
        "&Text:" )

// WDESDLG.C
pick(   WDE_REMOVEDIALOGS,
        "Remove Dialog(s)",
        "Remove Dialog(s)" )
pick(   WDE_DIALOGNOTOPENED,
        "Dialog not opened.",
        "Dialog not opened." )

// WDECLEAR.C
pick(   WDE_CLEARMSG,
        "Clear will DELETE ALL objects.\nClear?",
        "Clear will DELETE ALL objects.\nClear?" )
pick(   WDE_CLEARTITLE,
        "Clear Resource",
        "Clear Resource" )

// WDEEDIT.C
pick(   WDE_EDITREGISTERCLASSFAILED,
        "WdeRegisterEditClass: RegisterClass failed!",
        "WdeRegisterEditClass: RegisterClass failed!" )

// WDERES.C
pick(   WDE_UNTITLEDPROJECT,
        "untitled",
        "untitled" )
pick(   WDE_OPENPROJECT,
        "Open File",
        "Open File" )
pick(   WDE_SAVEPROJECT,
        "Save File",
        "Save File" )
pick(   WDE_OPENFILTER,
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t"
        "Executable Files (*.EXE)\t*.EXE\t"
        "DLL Libraries (*.DLL)\t*.DLL\t",
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t"
        "Executable Files (*.EXE)\t*.EXE\t"
        "DLL Libraries (*.DLL)\t*.DLL\t" )
pick(   WDE_SAVEFILTER,
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t",
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t" )
pick(   WDE_SAVEFILTEREXE,
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t"
        "Executable Files (*.EXE)\t*.EXE\t",
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t"
        "Executable Files (*.EXE)\t*.EXE\t" )
pick(   WDE_SAVEFILTERDLL,
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t"
        "DLL Libraries (*.DLL)\t*.DLL\t",
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t"
        "DLL Libraries (*.DLL)\t*.DLL\t" )
pick(   WDE_SAVEFILTERALL,
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t"
        "Executable Files (*.EXE)\t*.EXE\t"
        "DLL Libraries (*.DLL)\t*.DLL\t",
        "Dialog Script (*.DLG)\t*.DLG\t"
        "Resource Script (*.RC)\t*.RC\t"
        "Resource Files (*.RES)\t*.RES\t"
        "Executable Files (*.EXE)\t*.EXE\t"
        "DLL Libraries (*.DLL)\t*.DLL\t" )
pick(   WDE_SYMFILTER,
        "Header Files (*.h)\t*.h\t"
        "All Files (*.*)\t*.*\t",
        "Header Files (*.h)\t*.h\t"
        "All Files (*.*)\t*.*\t" )
pick(   WDE_REGISTEREDITFAILED,
        "WdeRegisterEditClass: RegisterClass failed!",
        "WdeRegisterEditClass: RegisterClass failed!" )
pick(   WDE_PRJHASNODIALOGS,
        "This file has no dialogs.",
        "This file has no dialogs." )
pick(   WDE_RESOURCESNOTLOADED,
        "Resources not loaded.",
        "Resources not loaded." )
pick(   WDE_UPDATEMODIFIEDPRJ,
        "This file has been modified.\nUpdate?",
        "This file has been modified.\nUpdate?" )
pick(   WDE_SAVEMODIFIEDPRJ,
        "This file has been modified.\nSave?",
        "This file has been modified.\nSave?" )
pick(   WDE_SAVEMODIFIEDSYM,
        "The symbols for this file have been modified.\nSave symbols?",
        "The symbols for this file have been modified.\nSave symbols?" )
pick(   WDE_SAVEFAILED,
        "Save failed!",
        "Save failed!" )

// WDESYM.C
pick(   WDE_LOADSYMTITLE,
        "Load Symbol Header File",
        "Load Symbol Header File" )
pick(   WDE_WRITESYMTITLE,
        "Write Symbol Header File",
        "Write Symbol Header File" )
pick(   WDE_LOADINGSYMBOLS,
        "Loading Symbols...",
        "Loading Symbols..." )
pick(   WDE_NOLOADHEADERFILE,
        "Unable to open header file.",
        "Unable to open header file." )
pick(   WDE_WRITINGSYMBOLS,
        "Writing Symbols...",
        "Writing Symbols..." )
pick(   WDE_ERRORCLOSINGFILE,
        "Error closing file!",
        "Error closing file!" )
pick(   WDE_NOMODIFYSYMBOLTABLE,
        "Could not modify symbol table",
        "Could not modify symbol table" )
pick(   WDE_SYMBOLEXISTS,
        "Symbol already exists.",
        "Symbol already exists." )
pick(   WDE_SYMBOLNOTFOUND,
        "Symbol not found.",
        "Symbol not found." )
pick(   WDE_NOOPENSYMFILE,
        "Symbol could not be opened.",
        "Symbol could not be opened." )

// WDESVOBJ.C
pick(   WDE_SAVEDLGINTOTITLE,
        "Save Dialog Into Resource",
        "Save Dialog Into Resource" )
pick(   WDE_SAVEDLGTITLE,
        "Save Dialog",
        "Save Dialog" )
pick(   WDE_SAVEDLGASTITLE,
        "Save Dialog As",
        "Save Dialog As" )
pick(   WDE_DUPRESNAMEINFILE,
        "There is already a resource of that name in the file.",
        "There is already a resource of that name in the file." )

// WDEHASH.C
pick(   WDE_NOSYMBOL,
        "(no symbol)",
        "(no symbol)" )
pick(   WDE_SYMBOLSNOTADDED,
        "Could not add all symbols! Low memory?",
        "Could not add all symbols! Low memory?" )
pick(   WDE_NOSYMBOLMSG,
        "No Symbols",
        "No Symbols" )

// WDEFCUST.C
pick(   WDE_DEFININGCUSTOM,
        "Defining Custom Control",
        "Defining Custom Control" )
pick(   WDE_CANTFINDCUSTOM,
        "No custom control fits this class & style.",
        "No custom control fits this class & style." )
pick(   WDE_NOCUSTOMFORCLASS,
        "There are no custom controls of this class.",
        "There are no custom controls of this class." )

// WDECUST.C
pick(   WDE_OPENCUSTTITLE,
        "Open Custom Library",
        "Open Custom Library" )
pick(   WDE_OPENCUSTFILTER,
        "DLL Libraries (*.DLL)\t*.DLL\tAll Files (*.*)\t*.*\t",
        "DLL Libraries (*.DLL)\t*.DLL\tAll Files (*.*)\t*.*\t" )
pick(   WDE_NOCUSTLOADED,
        "No Custom Controls have been loaded.",
        "No Custom Controls have been loaded." )
pick(   WDE_LIBRARYLOADED,
        "Library loaded.",
        "Library loaded." )
pick(   WDE_MSWARNINGTEXT,
        "Caution!!\nThe editor cannot determine if this is indeed a DLL containing a Microsoft Custom Control. If it isn't, a system crash is likely.\nContinue?",
        "Caution!!\nThe editor cannot determine if this is indeed a DLL containing a Microsoft Custom Control. If it isn't, a system crash is likely.\nContinue?" )
pick(   WDE_MSWARNINGTITLE,
        "Load Microsoft Custom Control",
        "Load Microsoft Custom Control" )
pick(   WDE_BORWARNINGTEXT,
        "This is not a Borland Custom Control Library!\nAttempt to load as a Microsoft Custom Control DLL?",
        "This is not a Borland Custom Control Library!\nAttempt to load as a Microsoft Custom Control DLL?" )
pick(   WDE_BORWARNINGTITLE,
        "Load Borland Custom Controls",
        "Load Borland Custom Controls" )
pick(   WDE_BADPROCEDUREORDINAL,
        "Bad procedure ordinal.",
        "Bad procedure ordinal." )
pick(   WDE_CANTFINDINFOPROC,
        "The Info procedure cannot be found.",
        "The Info procedure cannot be found." )
pick(   WDE_CANTFINDSTYLEPROC,
        "The Style procedure cannot be found.",
        "The Style procedure cannot be found." )
pick(   WDE_CANTFINDFLAGSPROC,
        "The Flags procedure cannot be found.",
        "The Flags procedure cannot be found." )
pick(   WDE_UNICUSTNOTSUPPORTED,
        "UNICODE not supported.",
        "UNICODE not supported." )

// WDECUST.C
pick(   WDE_BADCTL3D,
        "You are using an older version of CTL3D.DLL.\nUse the version provided in %WATCOM%\\BINW.",
        "You are using an older version of CTL3D.DLL.\nUse the version provided in %WATCOM%\\BINW." )

// WDERIBBN.C
pick(   WDE_TIP_NEW,
        "New",
        "New" )
pick(   WDE_TIP_OPEN,
        "Open",
        "Open" )
pick(   WDE_TIP_SAVE,
        "Save",
        "Save" )
pick(   WDE_TIP_CUT,
        "Cut",
        "Cut" )
pick(   WDE_TIP_COPY,
        "Copy",
        "Copy" )
pick(   WDE_TIP_PASTE,
        "Paste",
        "Paste" )
pick(   WDE_TIP_SIZETOTEXT,
        "Size to Text",
        "Size to Text" )
pick(   WDE_TIP_TEST_MODE,
        "Test Mode",
        "Test Mode" )
pick(   WDE_TIP_SET_ORDER,
        "Set Order",
        "Set Order" )
pick(   WDE_TIP_SET_TABS,
        "Set Tabs",
        "Set Tabs" )
pick(   WDE_TIP_SET_GROUPS,
        "Set Groups",
        "Set Groups" )

