/*
 *  winver.h    Win32 version information functions
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */
 
#ifndef VER_H
#define VER_H

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#include <verrsrc.h>

/* The rest of the file should be ignored when resources are being compiled. */
#ifndef RC_INVOKED
#ifdef __cplusplus
extern "C" {
#endif

/* Functions in VERSION.DLL */
BOOL APIENTRY   GetFileVersionInfoA( LPCSTR, DWORD, DWORD, LPVOID );
DWORD APIENTRY  GetFileVersionInfoSizeA( LPCSTR, LPDWORD );
DWORD APIENTRY  GetFileVersionInfoSizeExW( DWORD, LPCWSTR, LPDWORD );
DWORD APIENTRY  GetFileVersionInfoSizeW( LPCWSTR, LPDWORD );
BOOL APIENTRY   GetFileVersionInfoExW( DWORD, LPCWSTR, DWORD, DWORD, LPVOID );
BOOL APIENTRY   GetFileVersionInfoW( LPCWSTR, DWORD, DWORD, LPVOID );
DWORD APIENTRY  VerFindFileA( DWORD, LPSTR, LPSTR, LPSTR, LPSTR, PUINT, LPSTR, PUINT );
DWORD APIENTRY  VerFileFileW( DWORD, LPWSTR, LPWSTR, LPWSTR, LPWSTR, PUINT, LPWSTR, PUINT );
DWORD APIENTRY  VerInstallFileA( DWORD, LPSTR, LPSTR, LPSTR, LPSTR, LPSTR, LPSTR, PUINT );
DWORD APIENTRY  VerInstallFileW( DWORD, LPWSTR, LPWSTR, LPWSTR, LPWSTR, LPWSTR, LPWSTR, PUINT );
DWORD APIENTRY  VerLanguageNameA( DWORD, LPSTR, DWORD );
DWORD APIENTRY  VerLanguageNameW( DWORD, LPWSTR, DWORD );
BOOL APIENTRY   VerQueryValueA( const LPVOID, LPSTR, LPVOID *, PUINT );
BOOL APIENTRY   VerQueryValueW( const LPVOID, LPWSTR, LPVOID *, PUINT );

/* Map generic function names to the appropriate ANSI or Unicode version. */
#ifdef UNICODE
    #define GetFileVersionInfo          GetFileVersionInfoW
    #define GetFileVersionInfoEx        GetFileVersionInfoExW
    #define GetFileVersionInfoSize      GetFileVersionInfoSizeW
    #define GetFileVersionInfoSizeEx    GetFileVersionInfoSizeExW
    #define VerFindFile                 VerFindFileW
    #define VerInstallFile              VerInstallFileW
    #define VerLanguageName             VerLanguageNameW
    #define VerQueryValue               VerQueryValueW
#else
    #define GetFileVersionInfo          GetFileVersionInfoA
    #define GetFileVersionInfoSize      GetFileVersionInfoSizeA
    #define VerFindFile                 VerFindFileA
    #define VerInstallFile              VerInstallFileA
    #define VerLanguageName             VerLanguageNameA
    #define VerQueryValue               VerQueryValueA
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif /* RC_INVOKED */

#endif /* VER_H */
