/*
 *  wsipx.h     Windows Sockets IPX/SPX definitions
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _WSIPX_
#define _WSIPX_

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* IPX/SPX protocol families */
#define NSPROTO_IPX     1000
#define NSPROTO_SPX     1256
#define NSPROTO_SPXII   1257

/* IPX/SPX socket address */
typedef struct sockaddr_ipx {
    short           sa_family;
    char            sa_netnum[4];
    char            sa_nodenum[6];
    unsigned short  sa_socket;
} SOCKADDR_IPX;
typedef SOCKADDR_IPX    *PSOCKADDR_IPX;
typedef SOCKADDR_IPX    *LPSOCKADDR_IPX;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* _WSIPX_ */
