type=ui
os=nlm
build_target=nlm
sys=nlm
compiler=comp386
model=f
ext=nlm
extra_option=,caseexact,stack=10k,quiet

target : sample.nlm .SYMBOLIC
    @%null

samp2 : samp2.nlm  .SYMBOLIC
    @%null

!include ../makefile

