#pmake: all build large cpu_i86 os_os2
#
# strgmtl.lib -- large memory-model multi-thread STRING library
#
suffix = mtl
target_system = os2
production_lib = lib286\os2
define_library_include = $(plusplus_string_dir)\string.mif
define_deps_include = $(plusplus_string_dir)\deps.mif
define_target_include = $(plusplus_dir)\lib16$(suffix).mif
!include $(plusplus_dir)\mklib.mif
