#pmake: build flat cpu_386 os_rdos
#
# plib3rmt -- register based 32-bit multi-threaded PLIB, PLBX
#
processor  = 386
system     = rdos
model      = mf
convention = register
linkage    = static
mthreaded  = 1

!include $(cpplib_dir)/runtime/runtime.mif
