#pmake: os_os2 cpu_i86
#
# Open Watcom Debugger makefile for OS/2 PM
#

host_os  = os2
host_cpu = i86

sys_windowed = 1

syshdir  =

#add '16' suffix to avoid conflicts
tail_gui_os2 = w16

!include ../../master.mif
