#pmake: os_os2 cpu_i86
#
# Open Watcom Debugger makefile for OS/2 PM
#

host_OS  = os2
host_CPU = i86

sys_windowed = 1

syshdir  =

#add '16' suffix to avoid conflicts
tail_gui_os2 = w16

sysobjs =            &
        os2init.obj  &
        os2lkup.obj  &
        os2chk.obj   &
        os2cmd.obj   &
        os2filio.obj &
        pmscrn.obj

!include ../../master.mif
