#pmake: build flat cpu_386 os_dos os_win os_rdos os_nt os_os2 os_qnx os_nov
#
# cplx73s.lib -- stack based 32-bit COMPLEX library fpi
#
processor  = 387
system     = generic
model      = ms
convention = stack
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
