#pmake: build flat cpu_386 os_osi
#
# cplx73s.lib -- stack based 32-bit COMPLEX library fpi
#
processor  = 387
system     = generic
model      = ms
convention = stack
linkage    = static

!include $(cpplib_dir)/complex/complex.mif
