#pmake: build compact cpu_i86 os_win
#
# strgc.lib -- compact memory-model STRING library for Windows
#
processor  = 086
system     = windows
model      = mc
linkage    = static
define_library_include = $(cpplib_dir)/string/string.mif
!include $(cpplib_dir)/mklib.mif
