#pmake: 386 os2

host_os    = nt
host_cpu   = 386
target_cpu = 386

comp386   = $(cc_dir)\nt386\wcc386d.exe
bootstrap = 1
o_dir = $(cg_dir)\intel\386\r2
i_dir = $(cg_dir)\intel\386\h;$(cg_dir)\intel\h;$(cg_dir)\h

!include ../master.mif
