

.extensions:
.extensions: .exe .cpp

exes = incre.exe    decre.exe assign.exe minus.exe real.exe imag.exe &
       construc.exe div.exe   plus.exe   multi.exe

all : $(exes) .symbolic

.cpp.exe :
    wcl $[@
