#pmake: build flat cpu_386 os_osi
processor  = 386
system     = generic
model      = mf
convention = stack
linkage    = static
mthreaded  = 1
subdir     = mf_smt
define_library_include = $(cpplib_dir)/plib.mif
!include $(cpplib_dir)/mrglib.mif
