#pmake: build serv remote os_win cpu_i86 cpu_386 par x86

tree_depth = 4

host_cpu = i86
host_os  = win

target_cpu = x86

srv = par
which = SERVER
gui = 1
remote_link = 1

extra_objs = pardos.obj

!include $(trap_dir)/master.mif
