#pmake: build serv remote os_win cpu_i86 cpu_386 par x86
host_CPU = i86
host_OS = win

gui = 1
os = win
srv = par
cpu = x86
which = SERVER
type  = remote_link

extra_objs = pardos.obj

!include $(trap_dir)/master.mif
