.686
.xmm2
.model small

.code

    addpd       xmm1,cs:0aH[bx+di]
    addpd       xmm1,cs:0aH[ebx+eax*2]
    addpd       xmm1,DGROUP:L$1
    addpd       xmm1,xmm7
    addsd       xmm1,cs:0aH[bx+di]
    addsd       xmm1,cs:0aH[ebx+eax*2]
    addsd       xmm1,DGROUP:L$1
    addsd       xmm1,xmm7
    andnpd      xmm1,cs:0aH[bx+di]
    andnpd      xmm1,cs:0aH[ebx+eax*2]
    andnpd      xmm1,DGROUP:L$1
    andnpd      xmm1,xmm7
    andpd       xmm1,cs:0aH[bx+di]
    andpd       xmm1,cs:0aH[ebx+eax*2]
    andpd       xmm1,DGROUP:L$1
    andpd       xmm1,xmm7
    clflush     cs:0aH[bx+di]
    clflush     cs:0aH[ebx+eax*2]
    clflush     DGROUP:L$1
    cmppd       xmm1,cs:0aH[bx+di],0
    cmppd       xmm1,cs:0aH[ebx+eax*2],0
    cmppd       xmm1,DGROUP:L$1,0
    cmppd       xmm1,xmm6,0
    cmpsd       xmm1,cs:0aH[bx+di],0
    cmpsd       xmm1,cs:0aH[ebx+eax*2],0
    cmpsd       xmm1,DGROUP:L$1,0
    cmpsd       xmm1,xmm6,0
    cmppd       xmm1,cs:0aH[bx+di],2
    cmppd       xmm1,cs:0aH[ebx+eax*2],2
    cmppd       xmm1,DGROUP:L$1,2
    cmppd       xmm1,xmm6,2
    cmpsd       xmm1,cs:0aH[bx+di],2
    cmpsd       xmm1,cs:0aH[ebx+eax*2],2
    cmpsd       xmm1,DGROUP:L$1,2
    cmpsd       xmm1,xmm6,2
    cmppd       xmm1,cs:0aH[bx+di],1
    cmppd       xmm1,cs:0aH[ebx+eax*2],1
    cmppd       xmm1,DGROUP:L$1,1
    cmppd       xmm1,xmm6,1
    cmpsd       xmm1,cs:0aH[bx+di],1
    cmpsd       xmm1,cs:0aH[ebx+eax*2],1
    cmpsd       xmm1,DGROUP:L$1,1
    cmpsd       xmm1,xmm6,1
    cmppd       xmm1,cs:0aH[bx+di],4
    cmppd       xmm1,cs:0aH[ebx+eax*2],4
    cmppd       xmm1,DGROUP:L$1,4
    cmppd       xmm1,xmm6,4
    cmpsd       xmm1,cs:0aH[bx+di],4
    cmpsd       xmm1,cs:0aH[ebx+eax*2],4
    cmpsd       xmm1,DGROUP:L$1,4
    cmpsd       xmm1,xmm6,4
    cmppd       xmm1,cs:0aH[bx+di],6
    cmppd       xmm1,cs:0aH[ebx+eax*2],6
    cmppd       xmm1,DGROUP:L$1,6
    cmppd       xmm1,xmm6,6
    cmpsd       xmm1,cs:0aH[bx+di],6
    cmpsd       xmm1,cs:0aH[ebx+eax*2],6
    cmpsd       xmm1,DGROUP:L$1,6
    cmpsd       xmm1,xmm6,6
    cmppd       xmm1,cs:0aH[bx+di],5
    cmppd       xmm1,cs:0aH[ebx+eax*2],5
    cmppd       xmm1,DGROUP:L$1,5
    cmppd       xmm1,xmm6,5
    cmpsd       xmm1,cs:0aH[bx+di],5
    cmpsd       xmm1,cs:0aH[ebx+eax*2],5
    cmpsd       xmm1,DGROUP:L$1,5
    cmpsd       xmm1,xmm6,5
    cmppd       xmm1,cs:0aH[bx+di],7
    cmppd       xmm1,cs:0aH[ebx+eax*2],7
    cmppd       xmm1,DGROUP:L$1,7
    cmppd       xmm1,xmm6,7
    cmpsd       xmm1,cs:0aH[bx+di],7
    cmpsd       xmm1,cs:0aH[ebx+eax*2],7
    cmpsd       xmm1,DGROUP:L$1,7
    cmpsd       xmm1,xmm6,7
    cmppd       xmm1,cs:0aH[bx+di],0ffH
    cmppd       xmm1,cs:0aH[ebx+eax*2],0ffH
    cmppd       xmm1,DGROUP:L$1,0ffH
    cmppd       xmm1,xmm7,0ffH
    cmpsd       xmm1,cs:0aH[bx+di],0ffH
    cmpsd       xmm1,cs:0aH[ebx+eax*2],0ffH
    cmpsd       xmm1,DGROUP:L$1,0ffH
    cmpsd       xmm1,xmm7,0ffH
    cmppd       xmm1,cs:0aH[bx+di],3
    cmppd       xmm1,cs:0aH[ebx+eax*2],3
    cmppd       xmm1,DGROUP:L$1,3
    cmppd       xmm1,xmm6,3
    cmpsd       xmm1,cs:0aH[bx+di],3
    cmpsd       xmm1,cs:0aH[ebx+eax*2],3
    cmpsd       xmm1,DGROUP:L$1,3
    cmpsd       xmm1,xmm6,3
    comisd      xmm1,cs:0aH[bx+di]
    comisd      xmm1,cs:0aH[ebx+eax*2]
    comisd      xmm1,DGROUP:L$1
    comisd      xmm1,xmm7
    cvtdq2pd    xmm1,cs:0aH[bx+di]
    cvtdq2pd    xmm1,cs:0aH[ebx+eax*2]
    cvtdq2pd    xmm1,DGROUP:L$1
    cvtdq2pd    xmm1,xmm7
    cvtdq2ps    xmm1,cs:0aH[bx+di]
    cvtdq2ps    xmm1,cs:0aH[ebx+eax*2]
    cvtdq2ps    xmm1,DGROUP:L$1
    cvtdq2ps    xmm1,xmm7
    cvtpd2dq    xmm1,cs:0aH[bx+di]
    cvtpd2dq    xmm1,cs:0aH[ebx+eax*2]
    cvtpd2dq    xmm1,DGROUP:L$1
    cvtpd2dq    xmm1,xmm7
    cvtpd2pi    mm1,cs:0aH[bx+di]
    cvtpd2pi    mm1,cs:0aH[ebx+eax*2]
    cvtpd2pi    mm1,DGROUP:L$1
    cvtpd2pi    mm1,xmm7
    cvtpd2ps    xmm1,cs:0aH[bx+di]
    cvtpd2ps    xmm1,cs:0aH[ebx+eax*2]
    cvtpd2ps    xmm1,DGROUP:L$1
    cvtpd2ps    xmm1,xmm7
    cvtpi2pd    xmm1,cs:0aH[bx+di]
    cvtpi2pd    xmm1,cs:0aH[ebx+eax*2]
    cvtpi2pd    xmm1,mm7
    cvtpi2pd    xmm1,DGROUP:L$1
    cvtps2dq    xmm1,cs:0aH[bx+di]
    cvtps2dq    xmm1,cs:0aH[ebx+eax*2]
    cvtps2dq    xmm1,DGROUP:L$1
    cvtps2dq    xmm1,xmm7
    cvtps2pd    xmm1,cs:0aH[bx+di]
    cvtps2pd    xmm1,cs:0aH[ebx+eax*2]
    cvtps2pd    xmm1,DGROUP:L$1
    cvtps2pd    xmm1,xmm7
    cvtsd2si    ebx,cs:0aH[bx+di]
    cvtsd2si    ebx,cs:0aH[ebx+eax*2]
    cvtsd2si    ebx,DGROUP:L$1
    cvtsd2si    ebx,xmm7
    cvtsd2ss    xmm1,cs:0aH[bx+di]
    cvtsd2ss    xmm1,cs:0aH[ebx+eax*2]
    cvtsd2ss    xmm1,DGROUP:L$1
    cvtsd2ss    xmm1,xmm7
    cvtsi2sd    xmm5,cs:0aH[bx+di]
    cvtsi2sd    xmm5,cs:0aH[ebx+eax*2]
    cvtsi2sd    xmm5,ecx
    cvtsi2sd    xmm5,DGROUP:L$1
    cvtss2sd    xmm1,cs:0aH[bx+di]
    cvtss2sd    xmm1,cs:0aH[ebx+eax*2]
    cvtss2sd    xmm1,DGROUP:L$1
    cvtss2sd    xmm1,xmm7
    cvttpd2dq   xmm1,cs:0aH[bx+di]
    cvttpd2dq   xmm1,cs:0aH[ebx+eax*2]
    cvttpd2dq   xmm1,DGROUP:L$1
    cvttpd2dq   xmm1,xmm7
    cvttpd2pi   mm1,cs:0aH[bx+di]
    cvttpd2pi   mm1,cs:0aH[ebx+eax*2]
    cvttpd2pi   mm1,DGROUP:L$1
    cvttpd2pi   mm1,xmm7
    cvttps2dq   xmm1,cs:0aH[bx+di]
    cvttps2dq   xmm1,cs:0aH[ebx+eax*2]
    cvttps2dq   xmm1,DGROUP:L$1
    cvttps2dq   xmm1,xmm7
    cvttsd2si   ebx,cs:0aH[bx+di]
    cvttsd2si   ebx,cs:0aH[ebx+eax*2]
    cvttsd2si   ebx,DGROUP:L$1
    cvttsd2si   ebx,xmm7
    divpd       xmm1,cs:0aH[bx+di]
    divpd       xmm1,cs:0aH[ebx+eax*2]
    divpd       xmm1,DGROUP:L$1
    divpd       xmm1,xmm7
    divsd       xmm1,cs:0aH[bx+di]
    divsd       xmm1,cs:0aH[ebx+eax*2]
    divsd       xmm1,DGROUP:L$1
    divsd       xmm1,xmm7
    lfence      
    maskmovdqu  xmm1,xmm5
    maxpd       xmm1,cs:0aH[bx+di]
    maxpd       xmm1,cs:0aH[ebx+eax*2]
    maxpd       xmm1,DGROUP:L$1
    maxpd       xmm1,xmm7
    maxsd       xmm1,cs:0aH[bx+di]
    maxsd       xmm1,cs:0aH[ebx+eax*2]
    maxsd       xmm1,DGROUP:L$1
    maxsd       xmm1,xmm7
    mfence      
    minpd       xmm1,cs:0aH[bx+di]
    minpd       xmm1,cs:0aH[ebx+eax*2]
    minpd       xmm1,DGROUP:L$1
    minpd       xmm1,xmm7
    minsd       xmm1,cs:0aH[bx+di]
    minsd       xmm1,cs:0aH[ebx+eax*2]
    minsd       xmm1,DGROUP:L$1
    minsd       xmm1,xmm7
    movapd      cs:0aH[bx+di],xmm7
    movapd      cs:0aH[ebx+eax*2],xmm7
    movapd      DGROUP:L$1,xmm7
    movapd      xmm1,cs:0aH[bx+di]
    movapd      xmm1,cs:0aH[ebx+eax*2]
    movapd      xmm1,DGROUP:L$1
    movapd      xmm1,xmm7
    movd        cs:0aH[bx+di],xmm1
    movd        cs:0aH[ebx+eax*2],xmm1
    movd        ebx,xmm3
    movd        DGROUP:L$1,xmm1
    movd        xmm1,cs:0aH[bx+di]
    movd        xmm1,cs:0aH[ebx+eax*2]
    movd        xmm1,DGROUP:L$1
    movd        xmm7,ebx
    movdq2q     mm7,xmm1
    movdqa      cs:0aH[bx+di],xmm1
    movdqa      cs:0aH[ebx+eax*2],xmm1
    movdqa      DGROUP:L$1,xmm1
    movdqa      xmm1,cs:0aH[bx+di]
    movdqa      xmm1,cs:0aH[ebx+eax*2]
    movdqa      xmm1,DGROUP:L$1
    movdqa      xmm1,xmm7
    movdqu      cs:0aH[bx+di],xmm3
    movdqu      cs:0aH[ebx+eax*2],xmm3
    movdqu      DGROUP:L$1,xmm3
    movdqu      xmm1,cs:0aH[bx+di]
    movdqu      xmm1,cs:0aH[ebx+eax*2]
    movdqu      xmm1,DGROUP:L$1
    movdqu      xmm1,xmm7
    movhpd      cs:0aH[bx+di],xmm3
    movhpd      cs:0aH[ebx+eax*2],xmm3
    movhpd      DGROUP:L$1,xmm3
    movhpd      xmm1,cs:0aH[bx+di]
    movhpd      xmm1,cs:0aH[ebx+eax*2]
    movhpd      xmm1,DGROUP:L$1
    movlpd      cs:0aH[bx+di],xmm7
    movlpd      cs:0aH[ebx+eax*2],xmm7
    movlpd      DGROUP:L$1,xmm7
    movlpd      xmm1,cs:0aH[bx+di]
    movlpd      xmm1,cs:0aH[ebx+eax*2]
    movlpd      xmm1,DGROUP:L$1
    movmskpd    ebx,xmm1
    movntdq     cs:0aH[bx+di],xmm1
    movntdq     cs:0aH[ebx+eax*2],xmm1
    movntdq     DGROUP:L$1,xmm1
    movnti      cs:0aH[bx+di],ebx
    movnti      cs:0aH[ebx+eax*2],ebx
    movnti      DGROUP:L$2,ebx
    movntpd     cs:0aH[bx+di],xmm1
    movntpd     cs:0aH[ebx+eax*2],xmm1
    movntpd     DGROUP:L$1,xmm1
    movq        cs:0aH[bx+di],xmm1
    movq        cs:0aH[ebx+eax*2],xmm1
    movq        DGROUP:L$1,xmm1
    movq        xmm1,cs:0aH[bx+di]
    movq        xmm1,cs:0aH[ebx+eax*2]
    movq        xmm1,DGROUP:L$1
    movq        xmm1,xmm7
    movq2dq     xmm1,mm7
    movsd       cs:0aH[bx+di],xmm1
    movsd       cs:0aH[ebx+eax*2],xmm1
    movsd       DGROUP:L$1,xmm1
    movsd       xmm1,cs:0aH[bx+di]
    movsd       xmm1,cs:0aH[ebx+eax*2]
    movsd       xmm1,DGROUP:L$1
    movsd       xmm1,xmm7
    movupd      cs:0aH[bx+di],xmm1
    movupd      cs:0aH[ebx+eax*2],xmm1
    movupd      DGROUP:L$1,xmm1
    movupd      xmm1,cs:0aH[bx+di]
    movupd      xmm1,cs:0aH[ebx+eax*2]
    movupd      xmm1,DGROUP:L$1
    movupd      xmm1,xmm7
    mulpd       xmm1,cs:0aH[bx+di]
    mulpd       xmm1,cs:0aH[ebx+eax*2]
    mulpd       xmm1,DGROUP:L$1
    mulpd       xmm1,xmm7
    mulsd       xmm1,cs:0aH[bx+di]
    mulsd       xmm1,cs:0aH[ebx+eax*2]
    mulsd       xmm1,DGROUP:L$1
    mulsd       xmm1,xmm7
    orpd        xmm1,cs:0aH[bx+di]
    orpd        xmm1,cs:0aH[ebx+eax*2]
    orpd        xmm1,DGROUP:L$1
    orpd        xmm1,xmm7
    packssdw    xmm1,cs:0aH[bx+di]
    packssdw    xmm1,cs:0aH[ebx+eax*2]
    packssdw    xmm1,DGROUP:L$1
    packssdw    xmm1,xmm7
    packsswb    xmm1,cs:0aH[bx+di]
    packsswb    xmm1,cs:0aH[ebx+eax*2]
    packsswb    xmm1,DGROUP:L$1
    packsswb    xmm1,xmm7
    packuswb    xmm1,cs:0aH[bx+di]
    packuswb    xmm1,cs:0aH[ebx+eax*2]
    packuswb    xmm1,DGROUP:L$1
    packuswb    xmm1,xmm7
    paddb       xmm1,cs:0aH[bx+di]
    paddb       xmm1,cs:0aH[ebx+eax*2]
    paddb       xmm1,DGROUP:L$1
    paddb       xmm1,xmm7
    paddd       xmm1,cs:0aH[bx+di]
    paddd       xmm1,cs:0aH[ebx+eax*2]
    paddd       xmm1,DGROUP:L$1
    paddd       xmm1,xmm7
    paddq       xmm1,cs:0aH[bx+di]
    paddq       xmm1,cs:0aH[ebx+eax*2]
    paddq       xmm1,DGROUP:L$1
    paddq       xmm1,xmm7
    paddsb      xmm1,cs:0aH[bx+di]
    paddsb      xmm1,cs:0aH[ebx+eax*2]
    paddsb      xmm1,DGROUP:L$1
    paddsb      xmm1,xmm7
    paddsw      xmm1,cs:0aH[bx+di]
    paddsw      xmm1,cs:0aH[ebx+eax*2]
    paddsw      xmm1,DGROUP:L$1
    paddsw      xmm1,xmm7
    paddusb     xmm1,cs:0aH[bx+di]
    paddusb     xmm1,cs:0aH[ebx+eax*2]
    paddusb     xmm1,DGROUP:L$1
    paddusb     xmm1,xmm7
    paddusw     xmm1,cs:0aH[bx+di]
    paddusw     xmm1,cs:0aH[ebx+eax*2]
    paddusw     xmm1,DGROUP:L$1
    paddusw     xmm1,xmm7
    paddw       xmm1,cs:0aH[bx+di]
    paddw       xmm1,cs:0aH[ebx+eax*2]
    paddw       xmm1,DGROUP:L$1
    paddw       xmm1,xmm7
    pand        xmm1,cs:0aH[bx+di]
    pand        xmm1,cs:0aH[ebx+eax*2]
    pand        xmm1,DGROUP:L$1
    pand        xmm1,xmm7
    pandn       xmm1,cs:0aH[bx+di]
    pandn       xmm1,cs:0aH[ebx+eax*2]
    pandn       xmm1,DGROUP:L$1
    pandn       xmm1,xmm7
    pause       
    pavgb       xmm1,cs:0aH[bx+di]
    pavgb       xmm1,cs:0aH[ebx+eax*2]
    pavgb       xmm1,DGROUP:L$1
    pavgb       xmm1,xmm7
    pavgw       xmm1,cs:0aH[bx+di]
    pavgw       xmm1,cs:0aH[ebx+eax*2]
    pavgw       xmm1,DGROUP:L$1
    pavgw       xmm1,xmm7
    pcmpeqb     xmm1,cs:0aH[bx+di]
    pcmpeqb     xmm1,cs:0aH[ebx+eax*2]
    pcmpeqb     xmm1,DGROUP:L$1
    pcmpeqb     xmm1,xmm7
    pcmpeqd     xmm1,cs:0aH[bx+di]
    pcmpeqd     xmm1,cs:0aH[ebx+eax*2]
    pcmpeqd     xmm1,DGROUP:L$1
    pcmpeqd     xmm1,xmm7
    pcmpeqw     xmm1,cs:0aH[bx+di]
    pcmpeqw     xmm1,cs:0aH[ebx+eax*2]
    pcmpeqw     xmm1,DGROUP:L$1
    pcmpeqw     xmm1,xmm7
    pcmpgtb     xmm1,cs:0aH[bx+di]
    pcmpgtb     xmm1,cs:0aH[ebx+eax*2]
    pcmpgtb     xmm1,DGROUP:L$1
    pcmpgtb     xmm1,xmm7
    pcmpgtd     xmm1,cs:0aH[bx+di]
    pcmpgtd     xmm1,cs:0aH[ebx+eax*2]
    pcmpgtd     xmm1,DGROUP:L$1
    pcmpgtd     xmm1,xmm7
    pcmpgtw     xmm1,cs:0aH[bx+di]
    pcmpgtw     xmm1,cs:0aH[ebx+eax*2]
    pcmpgtw     xmm1,DGROUP:L$1
    pcmpgtw     xmm1,xmm7
    pmaddwd     xmm1,cs:0aH[bx+di]
    pmaddwd     xmm1,cs:0aH[ebx+eax*2]
    pmaddwd     xmm1,DGROUP:L$1
    pmaddwd     xmm1,xmm7
    pmaxsw      xmm1,cs:0aH[bx+di]
    pmaxsw      xmm1,cs:0aH[ebx+eax*2]
    pmaxsw      xmm1,DGROUP:L$1
    pmaxsw      xmm1,xmm7
    pmaxub      xmm1,cs:0aH[bx+di]
    pmaxub      xmm1,cs:0aH[ebx+eax*2]
    pmaxub      xmm1,DGROUP:L$1
    pmaxub      xmm1,xmm7
    pminsw      xmm1,cs:0aH[bx+di]
    pminsw      xmm1,cs:0aH[ebx+eax*2]
    pminsw      xmm1,DGROUP:L$1
    pminsw      xmm1,xmm7
    pminub      xmm1,cs:0aH[bx+di]
    pminub      xmm1,cs:0aH[ebx+eax*2]
    pminub      xmm1,DGROUP:L$1
    pminub      xmm1,xmm7
    pmovmskb    ebx,xmm7
    pmulhuw     xmm1,DGROUP:L$1
    pmulhuw     xmm1,xmm6
    pmulhw      xmm1,cs:0aH[bx+di]
    pmulhw      xmm1,cs:0aH[ebx+eax*2]
    pmulhw      xmm1,DGROUP:L$1
    pmulhw      xmm1,xmm7
    pmullw      xmm1,cs:0aH[bx+di]
    pmullw      xmm1,cs:0aH[ebx+eax*2]
    pmullw      xmm1,DGROUP:L$1
    pmullw      xmm1,xmm7
    pmuludq     xmm1,cs:0aH[bx+di]
    pmuludq     xmm1,cs:0aH[ebx+eax*2]
    pmuludq     xmm1,DGROUP:L$1
    pmuludq     xmm1,xmm7
    por         xmm1,cs:0aH[bx+di]
    por         xmm1,cs:0aH[ebx+eax*2]
    por         xmm1,DGROUP:L$1
    por         xmm1,xmm7
    psadbw      xmm1,cs:0aH[bx+di]
    psadbw      xmm1,cs:0aH[ebx+eax*2]
    psadbw      xmm1,DGROUP:L$1
    psadbw      xmm1,xmm7
    pshufd      xmm1,cs:0aH[bx+di],0ffH
    pshufd      xmm1,cs:0aH[ebx+eax*2],0ffH
    pshufd      xmm1,DGROUP:L$1,0ffH
    pshufd      xmm1,xmm7,0ffH
    pshufhw     xmm1,cs:0aH[bx+di],0ffH
    pshufhw     xmm1,cs:0aH[ebx+eax*2],0ffH
    pshufhw     xmm1,DGROUP:L$1,0ffH
    pshufhw     xmm1,xmm7,0ffH
    pshuflw     xmm1,cs:0aH[bx+di],0ffH
    pshuflw     xmm1,cs:0aH[ebx+eax*2],0ffH
    pshuflw     xmm1,DGROUP:L$1,0ffH
    pshuflw     xmm1,xmm7,0ffH
    pslld       xmm1,0ffH
    pslld       xmm1,cs:0aH[bx+di]
    pslld       xmm1,cs:0aH[ebx+eax*2]
    pslld       xmm1,DGROUP:L$1
    pslld       xmm1,xmm7
    pslldq      xmm1,0ffH
    psllq       xmm1,0ffH
    psllq       xmm1,cs:0aH[bx+di]
    psllq       xmm1,cs:0aH[ebx+eax*2]
    psllq       xmm1,DGROUP:L$1
    psllq       xmm1,xmm7
    psllw       xmm1,0ffH
    psllw       xmm1,cs:0aH[bx+di]
    psllw       xmm1,cs:0aH[ebx+eax*2]
    psllw       xmm1,DGROUP:L$1
    psllw       xmm1,xmm7
    psrad       xmm1,0ffH
    psrad       xmm1,cs:0aH[bx+di]
    psrad       xmm1,cs:0aH[ebx+eax*2]
    psrad       xmm1,DGROUP:L$1
    psrad       xmm1,xmm7
    psraw       xmm1,0ffH
    psrld       xmm1,0ffH
    psrld       xmm1,cs:0aH[bx+di]
    psrld       xmm1,cs:0aH[ebx+eax*2]
    psrld       xmm1,DGROUP:L$1
    psrld       xmm1,xmm7
    psrldq      xmm1,0ffH
    psrlq       xmm1,0ffH
    psrlq       xmm1,cs:0aH[bx+di]
    psrlq       xmm1,cs:0aH[ebx+eax*2]
    psrlq       xmm1,DGROUP:L$1
    psrlq       xmm1,xmm7
    psrlw       xmm1,0ffH
    psrlw       xmm1,cs:0aH[bx+di]
    psrlw       xmm1,cs:0aH[ebx+eax*2]
    psrlw       xmm1,DGROUP:L$1
    psrlw       xmm1,xmm7
    psubb       mm1,cs:0aH[bx+di]
    psubb       mm1,cs:0aH[ebx+eax*2]
    psubb       mm1,mm7
    psubb       mm1,DGROUP:L$1
    psubb       xmm1,cs:0aH[bx+di]
    psubb       xmm1,cs:0aH[ebx+eax*2]
    psubb       xmm1,DGROUP:L$1
    psubb       xmm1,xmm7
    psubd       mm1,cs:0aH[bx+di]
    psubd       mm1,cs:0aH[ebx+eax*2]
    psubd       mm1,mm7
    psubd       mm1,DGROUP:L$1
    psubd       xmm1,cs:0aH[bx+di]
    psubd       xmm1,cs:0aH[ebx+eax*2]
    psubd       xmm1,DGROUP:L$1
    psubd       xmm1,xmm7
    psubq       mm1,cs:0aH[bx+di]
    psubq       mm1,cs:0aH[ebx+eax*2]
    psubq       mm1,mm7
    psubq       mm1,DGROUP:L$1
    psubq       xmm1,cs:0aH[bx+di]
    psubq       xmm1,cs:0aH[ebx+eax*2]
    psubq       xmm1,DGROUP:L$1
    psubq       xmm1,xmm7
    psubsb      mm1,cs:0aH[bx+di]
    psubsb      mm1,cs:0aH[ebx+eax*2]
    psubsb      mm1,mm7
    psubsb      mm1,DGROUP:L$1
    psubsb      xmm1,cs:0aH[bx+di]
    psubsb      xmm1,cs:0aH[ebx+eax*2]
    psubsb      xmm1,DGROUP:L$1
    psubsb      xmm1,xmm7
    psubsw      mm1,cs:0aH[bx+di]
    psubsw      mm1,cs:0aH[ebx+eax*2]
    psubsw      mm1,mm7
    psubsw      mm1,DGROUP:L$1
    psubsw      xmm1,cs:0aH[bx+di]
    psubsw      xmm1,cs:0aH[ebx+eax*2]
    psubsw      xmm1,DGROUP:L$1
    psubsw      xmm1,xmm7
    psubusb     mm1,cs:0aH[bx+di]
    psubusb     mm1,cs:0aH[ebx+eax*2]
    psubusb     mm1,mm7
    psubusb     mm1,DGROUP:L$1
    psubusb     xmm1,cs:0aH[bx+di]
    psubusb     xmm1,cs:0aH[ebx+eax*2]
    psubusb     xmm1,DGROUP:L$1
    psubusb     xmm1,xmm7
    psubusw     mm1,cs:0aH[bx+di]
    psubusw     mm1,cs:0aH[ebx+eax*2]
    psubusw     mm1,mm7
    psubusw     mm1,DGROUP:L$1
    psubusw     xmm1,cs:0aH[bx+di]
    psubusw     xmm1,cs:0aH[ebx+eax*2]
    psubusw     xmm1,DGROUP:L$1
    psubusw     xmm1,xmm7
    psubw       mm1,cs:0aH[bx+di]
    psubw       mm1,cs:0aH[ebx+eax*2]
    psubw       mm1,mm7
    psubw       mm1,DGROUP:L$1
    psubw       xmm1,cs:0aH[bx+di]
    psubw       xmm1,cs:0aH[ebx+eax*2]
    psubw       xmm1,DGROUP:L$1
    psubw       xmm1,xmm7
    punpckhbw   xmm1,cs:0aH[bx+di]
    punpckhbw   xmm1,cs:0aH[ebx+eax*2]
    punpckhbw   xmm1,DGROUP:L$1
    punpckhbw   xmm1,xmm7
    punpckhdq   xmm1,cs:0aH[bx+di]
    punpckhdq   xmm1,cs:0aH[ebx+eax*2]
    punpckhdq   xmm1,DGROUP:L$1
    punpckhdq   xmm1,xmm7
    punpckhqdq  xmm1,cs:0aH[bx+di]
    punpckhqdq  xmm1,cs:0aH[ebx+eax*2]
    punpckhqdq  xmm1,DGROUP:L$1
    punpckhqdq  xmm1,xmm7
    punpckhwd   xmm1,cs:0aH[bx+di]
    punpckhwd   xmm1,cs:0aH[ebx+eax*2]
    punpckhwd   xmm1,DGROUP:L$1
    punpckhwd   xmm1,xmm7
    punpcklbw   xmm1,cs:0aH[bx+di]
    punpcklbw   xmm1,cs:0aH[ebx+eax*2]
    punpcklbw   xmm1,DGROUP:L$1
    punpcklbw   xmm1,xmm7
    punpckldq   xmm1,cs:0aH[bx+di]
    punpckldq   xmm1,cs:0aH[ebx+eax*2]
    punpckldq   xmm1,DGROUP:L$1
    punpckldq   xmm1,xmm7
    punpcklqdq  xmm1,cs:0aH[bx+di]
    punpcklqdq  xmm1,cs:0aH[ebx+eax*2]
    punpcklqdq  xmm1,DGROUP:L$1
    punpcklqdq  xmm1,xmm7
    punpcklwd   xmm1,cs:0aH[bx+di]
    punpcklwd   xmm1,cs:0aH[ebx+eax*2]
    punpcklwd   xmm1,DGROUP:L$1
    punpcklwd   xmm1,xmm7
    pxor        xmm1,cs:0aH[bx+di]
    pxor        xmm1,cs:0aH[ebx+eax*2]
    pxor        xmm1,DGROUP:L$1
    pxor        xmm1,xmm7
    shufpd      xmm1,cs:0aH[bx+di],0ffH
    shufpd      xmm1,cs:0aH[ebx+eax*2],0ffH
    shufpd      xmm1,DGROUP:L$1,0ffH
    shufpd      xmm1,xmm7,0ffH
    sqrtpd      xmm1,cs:0aH[bx+di]
    sqrtpd      xmm1,cs:0aH[ebx+eax*2]
    sqrtpd      xmm1,DGROUP:L$1
    sqrtpd      xmm1,xmm7
    sqrtsd      xmm1,cs:0aH[bx+di]
    sqrtsd      xmm1,cs:0aH[ebx+eax*2]
    sqrtsd      xmm1,DGROUP:L$1
    sqrtsd      xmm1,xmm7
    subpd       xmm1,cs:0aH[bx+di]
    subpd       xmm1,cs:0aH[ebx+eax*2]
    subpd       xmm1,DGROUP:L$1
    subpd       xmm1,xmm7
    subsd       xmm1,cs:0aH[bx+di]
    subsd       xmm1,cs:0aH[ebx+eax*2]
    subsd       xmm1,DGROUP:L$1
    subsd       xmm1,xmm7
    ucomisd     xmm1,cs:0aH[bx+di]
    ucomisd     xmm1,cs:0aH[ebx+eax*2]
    ucomisd     xmm1,DGROUP:L$1
    ucomisd     xmm1,xmm7
    unpckhpd    xmm1,cs:0aH[bx+di]
    unpckhpd    xmm1,cs:0aH[ebx+eax*2]
    unpckhpd    xmm1,DGROUP:L$1
    unpckhpd    xmm1,xmm7
    unpcklpd    xmm1,cs:0aH[bx+di]
    unpcklpd    xmm1,cs:0aH[ebx+eax*2]
    unpcklpd    xmm1,DGROUP:L$1
    unpcklpd    xmm1,xmm7
    xorpd       xmm1,cs:0aH[bx+di]
    xorpd       xmm1,cs:0aH[ebx+eax*2]
    xorpd       xmm1,DGROUP:L$1
    xorpd       xmm1,xmm7

.data

L$1 dq 0
L$2 dd 0

end
