#pmake: build large cpu_i86 os_os2
#
# strgmtl.lib -- large memory-model multi-thread STRING library
#
processor  = 286
system     = os2
model      = ml
convention =
linkage    = static
mthreaded  = 1
define_library_include = $(cpplib_dir)/string/string.mif
!include $(cpplib_dir)/mklib.mif
