#ifndef ___IALIAS_H_INCLUDED
#define ___IALIAS_H_INCLUDED

#pragma include_alias( "ArrayOb.h", "arrayob.h" )
#pragma include_alias( "nihclIO.h", "nihclio.h" )
#pragma include_alias( "Assoc.h", "assoc.h" )
#pragma include_alias( "AssocInt.h", "assocint.h" )
#pragma include_alias( "Bag.h", "bag.h" )
#pragma include_alias( "Integer.h", "integer.h" )
#pragma include_alias( "Iterator.h", "iterator.h" )
#pragma include_alias( "BitBoard.h", "bitboard.h" )
#pragma include_alias( "Bitset.h", "bitset.h" )
#pragma include_alias( "Object.h", "object.h" )
#pragma include_alias( "String.ho", "string.ho" )
#pragma include_alias( "Dictionary.h", "dictiona.h" )
#pragma include_alias( "OrderedCltn.h", "orderedc.h" )
#pragma include_alias( "IdentSet.h", "identset.h" )
#pragma include_alias( "OIO.h", "oio.h" )
#pragma include_alias( "OIOnih.h", "oionih.h" )
#pragma include_alias( "OIOfd.h", "oiofd.h" )
#pragma include_alias( "OIOstream.h", "oiostrea.h" )
#pragma include_alias( "OIOTbl.h", "oiotbl.h" )
#pragma include_alias( "Collection.h", "collecti.h" )
#pragma include_alias( "Date.h", "date.h" )
#pragma include_alias( "LookupKey.h", "lookupke.h" )
#pragma include_alias( "Float.h", "float.h" )
#pragma include_alias( "Fraction.h", "fraction.h" )
#pragma include_alias( "Heap.h", "heap.h" )
#pragma include_alias( "IdentDict.h", "identdict.h" )
#pragma include_alias( "SeqCltn.h", "seqcltn.h" )
#pragma include_alias( "Set.h", "set.h" )
#pragma include_alias( "SortedCltn.h", "sortedcl.h" )
#pragma include_alias( "KeySortCltn.h", "keysortc.h" )
#pragma include_alias( "Link.h", "link.h" )
#pragma include_alias( "LinkOb.h", "linkob.h" )
#pragma include_alias( "LinkedList.h", "linkedli.h" )
#pragma include_alias( "Point.h", "point.h" )
#pragma include_alias( "Random.h", "random.h" )
#pragma include_alias( "Range.h", "range.h" )
#pragma include_alias( "Rectangle.h", "rectangl.h" )
#pragma include_alias( "SharedQueue.h", "sharedqu.h" )
#pragma include_alias( "Stack.h", "stack.h" )
#pragma include_alias( "Semaphore.h", "semaphor.h" )
#pragma include_alias( "Time.ho", "time.ho" )

#endif