#pmake: build serv remote os_linux cpu_386 par
host_cpu = 386
host_os = linux

os = linux
srv = par
cpu = x86
which = SERVER
remote_link = 1

extra_objs = parlinux.obj

!include $(trap_dir)/lcl/linux/trap.mif
!include $(trap_dir)/master.mif

