#pmake: build serv remote os_linux cpu_386 par
host_CPU = 386
host_OS = linux

os = linux
srv = par
cpu = x86
which = SERVER
type  = remote_link

extra_objs = parlinux.obj

!include $(trap_dir)/lcl/linux/trap.mif
!include $(trap_dir)/master.mif

