#pmake: build lcl os_dos cpu_i86 trap x86

host_os  = dos
host_cpu = i86

os      = dos
srv     = lcl
cpu     = x86
which = TRAP

!include $(trap_dir)/lcl/dos/dosr/dosr.mif
!include $(trap_dir)/master.mif
