#pmake: build lcl os_dos cpu_i86 trap x86

host_os  = dos
host_cpu = i86

target_cpu = x86
target_os  = dos

srv   = lcl
which = TRAP

!include $(trap_dir)/lcl/dos/dosr/dosr.mif
!include $(trap_dir)/master.mif
