# makefile for GRAPH3R.LIB

libname =       graph3s
model =         /ms /3s /d_SUPERVGA /bt=QNX /d__STACK
module =        $[&s
module =        $[&
cdecl =
fard =
_386 =          386
_qnx =          q
asm_cmd =       386asm
asm_flags =     -NOL -EL $[&.err -O $[&.obj -I ..\inc\ -d _QNX -d _MODEL=_SMALL -d _386 -NO87 -TWOC

!include ..\graphics.mif
