/****************************************************************************
*
*                            Open Watcom Project
*
* Copyright (c) 2004-2025 The Open Watcom Contributors. All Rights Reserved.
*
*  ========================================================================
*
*    This file contains Original Code and/or Modifications of Original
*    Code as defined in and that are subject to the Sybase Open Watcom
*    Public License version 1.0 (the 'License'). You may not use this file
*    except in compliance with the License. BY USING THIS FILE YOU AGREE TO
*    ALL TERMS AND CONDITIONS OF THE LICENSE. A copy of the License is
*    provided with the Original Code and Modifications, and is also
*    available at www.sybase.com/developer/opensource.
*
*    The Original Code and all software distributed under the License are
*    distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
*    EXPRESS OR IMPLIED, AND SYBASE AND ALL CONTRIBUTORS HEREBY DISCLAIM
*    ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF
*    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR
*    NON-INFRINGEMENT. Please see the License for the specific language
*    governing rights and limitations under the License.
*
*  ========================================================================
*
* Description: WGML implement :FIGCAP tag for LAYOUT processing
*
****************************************************************************/


#include "wgml.h"

#include "clibext.h"


/***************************************************************************/
/*   :FIGCAP attributes                                                    */
/***************************************************************************/
static const lay_att    figcap_att[] = {
    e_pre_lines, e_font, e_figcap_string, e_string_font, e_delim
};


/*********************************************************************************/
/*Define the characteristics of the figure caption entity.                       */
/*                                                                               */
/*:FIGCAP                                                                        */
/*        pre_lines = 1                                                          */
/*        font = 0                                                               */
/*        figcap_string = "Figure "                                              */
/*        string_font = 0                                                        */
/*        delim = '.'                                                            */
/*                                                                               */
/*pre_lines This attribute accepts vertical space units. A zero value means that */
/*no lines are skipped. If the skip value is a line unit, it is multiplied       */
/*by the current line spacing (see "Vertical Space Unit" on page 77 for          */
/*more information). The resulting number of lines are skipped                   */
/*before the figure caption. If the document entity starts a new page,           */
/*the specified number of lines are still skipped. The pre-lines value           */
/*is not merged with the previous document entity's post-skip value.             */
/*                                                                               */
/*font This attribute accepts a non-negative integer number. If a font           */
/*number is used for which no font has been defined, WATCOM                      */
/*Script/GML will use font zero. The font numbers from zero to three             */
/*correspond directly to the highlighting levels specified by the                */
/*highlighting phrase GML tags. The font attribute defines the font of           */
/*the figure caption text. The font value is linked to the pre_lines             */
/*attribute (see "Font Linkage" on page 77).                                     */
/*                                                                               */
/*figcap_string This attribute accepts a character string. The specified string  */
/*is the first part of the figure caption generated by WATCOM Script/GML.        */
/*                                                                               */
/*string_font This attribute accepts a non-negative integer number. If a font    */
/*number is used for which no font has been defined, WATCOM                      */
/*Script/GML will use font zero. The font numbers from zero to three             */
/*correspond directly to the highlighting levels specified by the                */
/*highlighting phrase GML tags. The string_font attribute defines the            */
/*font of the the figure caption string defined from the text specified          */
/*by the figcap_string attribute to the figure caption delimiter                 */
/*inclusive.                                                                     */
/*                                                                               */
/*delim This attribute accepts a quoted character value. The delimiter value     */
/*specifies the character which is inserted after the number of the              */
/*figure. If a character other than a blank space is specified, that             */
/*character followed by a blank space will be inserted. If a blank               */
/*space is specified, only that blank space will be inserted.                    */
/*********************************************************************************/


/***************************************************************************/
/*  lay_figcap                                                             */
/***************************************************************************/

void    lay_figcap( const gmltag * entry )
{
    char                *p;
    condcode            cc;
    int                 cvterr;
    int                 k;
    lay_att             curr;
    att_name_type       attr_name;
    att_val_type        attr_val;
    struct {
        unsigned    pre_lines       :1;
        unsigned    font            :1;
        unsigned    figcap_string   :1;
        unsigned    string_font     :1;
        unsigned    delim           :1;
    } AttrFlags;

    p = g_scandata.s;
    cvterr = false;

    memset( &AttrFlags, 0, sizeof( AttrFlags ) );   // clear all attribute flags
    if( ProcFlags.lay_xxx != entry->u.layid ) {
        ProcFlags.lay_xxx = entry->u.layid;
    }
    while( (cc = lay_attr_and_value( &attr_name, &attr_val )) == CC_pos ) {   // get att with value
        cvterr = -1;
        for( k = 0; k < TABLE_SIZE( figcap_att ); k++ ) {
            curr = figcap_att[k];
            if( strcmp( lay_att_names[curr], attr_name.attname.l ) == 0 ) {
                p = attr_val.tok.s;
                switch( curr ) {
                case e_pre_lines:
                    if( AttrFlags.pre_lines ) {
                        xx_line_err_exit_ci( ERR_ATT_DUP, attr_name.tok.s,
                            attr_val.tok.s - attr_name.tok.s + attr_val.tok.l);
                        /* never return */
                    }
                    cvterr = i_space_unit( p, &attr_val,
                                           &layout_work.figcap.pre_lines );
                    AttrFlags.pre_lines = true;
                    break;
                case e_font:
                    if( AttrFlags.font ) {
                        xx_line_err_exit_ci( ERR_ATT_DUP, attr_name.tok.s,
                            attr_val.tok.s - attr_name.tok.s + attr_val.tok.l);
                        /* never return */
                    }
                    cvterr = i_font_number( p, &attr_val, &layout_work.figcap.font );
                    AttrFlags.font = true;
                    break;
                case e_figcap_string:
                    if( AttrFlags.figcap_string ) {
                        xx_line_err_exit_ci( ERR_ATT_DUP, attr_name.tok.s,
                            attr_val.tok.s - attr_name.tok.s + attr_val.tok.l);
                        /* never return */
                    }
                    cvterr = i_xx_string( p, &attr_val, layout_work.figcap.string );
                    AttrFlags.figcap_string = true;
                    break;
                case e_string_font:
                    if( AttrFlags.string_font ) {
                        xx_line_err_exit_ci( ERR_ATT_DUP, attr_name.tok.s,
                            attr_val.tok.s - attr_name.tok.s + attr_val.tok.l);
                        /* never return */
                    }
                    cvterr = i_font_number( p, &attr_val, &layout_work.figcap.string_font );
                    AttrFlags.string_font = true;
                    break;
                case e_delim:
                    if( AttrFlags.delim ) {
                        xx_line_err_exit_ci( ERR_ATT_DUP, attr_name.tok.s,
                            attr_val.tok.s - attr_name.tok.s + attr_val.tok.l);
                        /* never return */
                    }
                    cvterr = i_char( p, &attr_val, &layout_work.figcap.delim );
                    AttrFlags.delim = true;
                    break;
                default:
                    internal_err_exit( __FILE__, __LINE__ );
                    /* never return */
                }
                if( cvterr ) {          // there was an error
                    xx_err_exit( ERR_ATT_VAL_INV );
                    /* never return */
                }
                break;                  // break out of for loop
            }
        }
        if( cvterr < 0 ) {
            xx_err_exit( ERR_ATT_NAME_INV );
            /* never return */
        }
    }
    g_scandata.s = g_scandata.e;
    return;
}



/***************************************************************************/
/*   :FIGCAP    output figure caption attribute values                     */
/***************************************************************************/
void    put_lay_figcap( FILE *fp, layout_data * lay )
{
    int                 k;
    lay_att             curr;

    fprintf( fp, ":FIGCAP\n" );

    for( k = 0; k < TABLE_SIZE( figcap_att ); k++ ) {
        curr = figcap_att[k];
        switch( curr ) {
        case e_pre_lines:
            o_space_unit( fp, curr, &lay->figcap.pre_lines );
            break;
        case e_font:
            o_font_number( fp, curr, &lay->figcap.font );
            break;
        case e_figcap_string:
            o_xx_string( fp, curr, lay->figcap.string );
            break;
        case e_string_font:
            o_font_number( fp, curr, &lay->figcap.string_font );
            break;
        case e_delim:
            o_char( fp, curr, &lay->figcap.delim );
            break;
        default:
            internal_err_exit( __FILE__, __LINE__ );
            /* never return */
        }
    }
}
