#pmake: nobuild debug flat cpu_386 os_os2
#
# plib3r -- 32-bit 3r PLIB, PLBX
#
processor  = 386
system     = os2
model      = mf
convention = register
linkage    = static
fs_registration = yes

cpplib_release  = 0

!include $(cpplib_dir)/runtime/runtime.mif
